import { expect, it, vi } from "vitest";
import { randomUUID } from "node:crypto";
import { amendmentService, type AmendmentRepository, type AmendmentTransaction } from "../../src/modules/amendments/service";
import { type Amendment } from "../../src/modules/amendments/domain";
import { plan, source, now } from "../planning-fixtures";
const baseline = { ...plan, state: "committed" as const, committedAt: now, commitments: plan.commitments.map(c => ({ ...c, snapshot: source.context })) }; const actor = { userId: "owner" };
const input = (extra = {}) => ({ mutationId: randomUUID(), expectedVersion: baseline.version, reason: "Protect recovery time", provisionalCapacityMinutes: 600, reserveMinutes: 180, commitments: baseline.commitments.map(({ actionId, budgetMinutes }) => ({ actionId, budgetMinutes })), ...extra });
function setup(value: typeof baseline | null = baseline, live = [source], history: Amendment[] = []) {
  const tx: AmendmentTransaction = { timezone: vi.fn(async () => "Europe/London"), findForUpdate: vi.fn(async () => value), history: vi.fn(async () => history), lockSources: vi.fn(async () => live), append: vi.fn(async v => v) };
  const repository: AmendmentRepository = { read: vi.fn(), get: vi.fn(), executeOwned: vi.fn(async (_a,_id,_hash,apply) => apply(tx)) };
  return { tx, repository, service: amendmentService(repository, () => now) };
}
it("budget changes carry complete frozen context even absent/terminal sources without estimate writes", async () => { const { tx, service } = setup(baseline, []); const result = await service.confirm(actor, plan.id, input({ commitments: [{ actionId: source.actionId, budgetMinutes: 90 }] })); expect(result.commitments[0]).toEqual({ id: baseline.commitments[0].id, actionId: source.actionId, budgetMinutes: 90, source: source.source, snapshot: source.context }); expect(tx.lockSources).toHaveBeenCalledWith([]); expect(baseline.commitments[0].budgetMinutes).toBe(180); expect(source.context.action.estimateMinutes).toBe(120); });
it("fresh eligible addition captures current snapshot and identity; only additions lock sources", async () => { const addition = { ...source, actionId: randomUUID(), context: { ...source.context, action: { ...source.context.action, title: "New urgent issue" } } }; const { tx, service } = setup(baseline, [addition]); const result = await service.confirm(actor, plan.id, input({ commitments: [...input().commitments, { actionId: addition.actionId, budgetMinutes: 60, source: addition.source }] })); expect(tx.lockSources).toHaveBeenCalledWith([addition.actionId]); expect(result.commitments.find(c => c.actionId === addition.actionId)?.snapshot).toEqual(addition.context); expect(result.commitments.find(c => c.actionId === addition.actionId)?.snapshot).not.toBe(addition.context); });
it.each(["unavailable", "changed", "terminal"])("new additions reject %s sources atomically", async kind => { const id = randomUUID(); const added = { ...source, actionId: id, eligible: kind !== "terminal", source: { ...source.source, actionVersion: kind === "changed" ? 2 : 1 } }; const { tx, service } = setup(baseline, kind === "unavailable" ? [] : [added]); await expect(service.confirm(actor, plan.id, input({ commitments: [{ actionId: id, budgetMinutes: 60, source: source.source }] }))).rejects.toMatchObject({ code: kind === "unavailable" ? "NOT_FOUND" : "CONFLICT" }); expect(tx.append).not.toHaveBeenCalled(); });
it.each([null, { ...baseline, ownerId: "foreign" }])("foreign/missing plans never reveal history or lock sources", async value => { const { tx, service } = setup(value); await expect(service.confirm(actor, plan.id, input())).rejects.toMatchObject({ code: "NOT_FOUND" }); expect(tx.history).not.toHaveBeenCalled(); });
it("stale and past requests never append or merge", async () => { for (const value of [{ ...baseline, version: 3 }, { ...baseline, weekStartDate: "2026-09-21" }]) { const { tx, service } = setup(value); await expect(service.confirm(actor, plan.id, input())).rejects.toMatchObject({ code: "CONFLICT" }); expect(tx.append).not.toHaveBeenCalled(); } });
it.each(["NO_CHANGE", "OVER_CAPACITY"])("%s is rejected before append", async kind => { const { service, tx } = setup(); await expect(service.confirm(actor, plan.id, input({ provisionalCapacityMinutes: kind === "NO_CHANGE" ? 720 : 200 }))).rejects.toMatchObject({ details: { kind } }); expect(tx.append).not.toHaveBeenCalled(); });
it("zero-capacity/all-dropped appends an empty complete snapshot", async () => { const { service } = setup(); expect(await service.confirm(actor, plan.id, input({ provisionalCapacityMinutes: 0, reserveMinutes: 0, commitments: [] }))).toMatchObject({ commitments: [], provisionalCapacityMinutes: 0, sequenceNumber: 1, version: 3 }); });
it("second amendment starts from latest full snapshot; prior snapshot remains unchanged", async () => { const { service } = setup(); const first = await service.confirm(actor, plan.id, input({ commitments: [] })); const { service: next } = setup({ ...baseline, version: 3 }, [], [first]); const saved = JSON.stringify(first); const second = await next.confirm(actor, plan.id, input({ expectedVersion: 3, reserveMinutes: 120, commitments: [] })); expect(second).toMatchObject({ sequenceNumber: 2, version: 4, commitments: [] }); expect(JSON.stringify(first)).toBe(saved); });
it("receipt replay precedes current date/version/ownership/source checks", async () => { const { service, repository, tx } = setup(); const original = await service.confirm(actor, plan.id, input()); vi.mocked(repository.executeOwned).mockResolvedValue(original); vi.mocked(tx.findForUpdate).mockClear(); expect(await service.confirm(actor, plan.id, input())).toEqual(original); expect(tx.findForUpdate).not.toHaveBeenCalled(); });
it("hash canonicalizes ordering and binds reason/budgets/version/plan; strict validation before receipt", async () => { const { service, repository } = setup(); vi.mocked(repository.executeOwned).mockResolvedValue({} as Amendment); const v = input({ commitments: [...input().commitments, { actionId: randomUUID(), budgetMinutes: 60, source: source.source }] }); await service.confirm(actor, plan.id, v); await service.confirm(actor, plan.id, { ...v, commitments: [...v.commitments].reverse() }); expect(vi.mocked(repository.executeOwned).mock.calls[0][2]).toBe(vi.mocked(repository.executeOwned).mock.calls[1][2]); for (const changed of [{ reason: "Different reason" }, { expectedVersion: 4 }, { reserveMinutes: 120 }]) await service.confirm(actor, plan.id, { ...v, ...changed }); expect(new Set(vi.mocked(repository.executeOwned).mock.calls.map(c => c[2])).size).toBe(4); const count = vi.mocked(repository.executeOwned).mock.calls.length; await expect(service.confirm(actor, plan.id, { ...v, ownerId: "foreign" })).rejects.toMatchObject({ code: "VALIDATION" }); expect(repository.executeOwned).toHaveBeenCalledTimes(count); });
