import { expect, it, vi } from "vitest";
import { hoursService, focusAvailabilityService, type HoursRepository } from "../../src/modules/availability/service";
import type { FocusableHoursSchedule } from "../../src/modules/availability/domain";
import { ApplicationError } from "../../src/domain/errors";
const a={userId:"a"},b={userId:"b"}; const clock=()=>"2026-10-02T12:00:00Z";
function fixture() {
  const rows=new Map<string,FocusableHoursSchedule>(); const receipts=new Map<string,{hash:string,result:FocusableHoursSchedule}>();
  const repository: HoursRepository={ async read(actor,id) { const schedule=rows.get(actor.userId)??null; if(id && schedule?.id!==id) throw new ApplicationError("NOT_FOUND","These Focusable Hours are unavailable."); return {schedule,timezone:"Europe/London"}; },async execute(actor,mutationId,hash,apply) { const key=`${actor.userId}:${mutationId}`,receipt=receipts.get(key); if(receipt) { if(receipt.hash!==hash) throw new ApplicationError("CONFLICT","Different command.",{kind:"MUTATION_ID"}); return structuredClone(receipt.result); } const result=apply(rows.get(actor.userId)??null); rows.set(actor.userId,structuredClone(result));receipts.set(key,{hash,result:structuredClone(result)});return result; } };
  return {service:hoursService(repository,clock),rows,receipts};
}
const create=(mutationId=crypto.randomUUID())=>({mutationId,scheduleId:null,expectedVersion:0,windows:[{weekday:1,startMinute:540,endMinute:720}]});
it("read has no default/write; save creates/increments aggregate and permits deliberate clearing", async()=>{ const f=fixture();expect(await f.service.settings(a)).toEqual({schedule:null,timezone:"Europe/London"});expect(f.receipts.size).toBe(0);const first=await f.service.save(a,create());expect(first.version).toBe(1);const next=await f.service.save(a,{mutationId:crypto.randomUUID(),scheduleId:first.id,expectedVersion:1,windows:[]});expect(next).toMatchObject({version:2,windows:[],createdAt:first.createdAt}); });
it("stale state keeps current settings and creates no success receipt",async()=>{ const f=fixture(),command=create(),first=await f.service.save(a,command); await expect(f.service.save(a,create())).rejects.toMatchObject({code:"CONFLICT",details:{kind:"HOURS_VERSION",current:first}});expect(f.rows.get(a.userId)).toEqual(first);expect(f.receipts.size).toBe(1); });
it("identical successful retry replays original even after newer save; changed payload rejects",async()=>{ const f=fixture(),command=create(),first=await f.service.save(a,command);await f.service.save(a,{mutationId:crypto.randomUUID(),scheduleId:first.id,expectedVersion:1,windows:[]});expect(await f.service.save(a,command)).toEqual(first);await expect(f.service.save(a,{...command,windows:[]})).rejects.toMatchObject({code:"CONFLICT",details:{kind:"MUTATION_ID"}}); });
it("mutation namespace is owner scoped and foreign/missing reads/writes indistinguishable",async()=>{ const f=fixture(),command=create(),first=await f.service.save(a,command);expect((await f.service.save(b,command)).id).not.toBe(first.id);for(const id of [first.id,crypto.randomUUID()]) {await expect(f.service.settings(b,id)).rejects.toMatchObject({code:"NOT_FOUND"});await expect(f.service.save(b,{mutationId:crypto.randomUUID(),scheduleId:id,expectedVersion:1,windows:[]})).rejects.toMatchObject({code:"NOT_FOUND"});}expect(f.rows.get(a.userId)).toEqual(first); });
it("invalid input rejects before persistence",async()=>{ const f=fixture();await expect(f.service.save(a,{...create(),ownerId:b.userId})).rejects.toMatchObject({code:"VALIDATION"});expect(f.receipts.size).toBe(0); });
it("owned derived read uses current Calendar timezone, no provider refresh/write or receipt",async()=>{ const f=fixture(),first=await f.service.save(a,create());const calendar={workspace:vi.fn(async()=>({configured:true,connection:null,availability:{weekStartDate:"2026-09-28",timezone:"America/New_York",status:"fresh" as const,intervals:[],totalBusyMinutes:0,days:[],fetchedAt:clock(),error:null}}))};const service=focusAvailabilityService(f.service,calendar,()=>Date.parse(clock()));const before=structuredClone([...f.rows]);const result=await service.read(a,"2026-09-28");expect(result.availability.focusable[0].start).toBe("2026-09-28T13:00:00Z");expect(calendar.workspace).toHaveBeenCalledWith(a,"2026-09-28");expect([...f.rows]).toEqual(before);expect(f.receipts.size).toBe(1);await expect(service.read(b,"2026-09-28",first.id)).rejects.toMatchObject({code:"NOT_FOUND"});expect(calendar.workspace).toHaveBeenCalledTimes(1); });
