import { beforeEach, expect, it } from "vitest";
import { randomUUID } from "node:crypto";
import { calendarService } from "../../src/modules/calendar/service";
import { ProviderFailure } from "../../src/modules/calendar/provider";
import { calendarCipher, calendarClock, calendarGrant, fakeCalendar, memoryCalendarRepository } from "../calendar-fixtures";
const a = { userId: randomUUID() }, b = { userId: randomUUID() }; let memory: ReturnType<typeof memoryCalendarRepository>, provider: ReturnType<typeof fakeCalendar>, service: ReturnType<typeof calendarService>; let now: Date;
beforeEach(() => { memory = memoryCalendarRepository(); provider = fakeCalendar(); now = new Date(calendarClock); service = calendarService(memory.repository, provider, calendarCipher(), () => now); });
async function connect(actor = a) { const auth = await service.start(actor); const state = new URL(auth.url).searchParams.get("state")!; expect(await service.callback(actor, { state, code: "fixture-code", denied: false })).toBe("success"); const value = (await service.workspace(actor)).connection!; return { value, state }; }
async function configured() { const { value } = await connect(); const listed = await service.refreshCalendars(a, value.id); return service.select(a, value.id, { expectedVersion: listed.version, calendarIds: ["personal", "work"] }); }
const week = { weekStartDate: "2026-09-28" };
it("starts owner-bound random state with encrypted PKCE and no automatic Calendar consent", async () => { expect((await service.workspace(a)).connection).toBeNull(); expect(provider.authorization).not.toHaveBeenCalled(); const first = await service.start(a), second = await service.start(a); expect(first.url).not.toBe(second.url); const flow = memory.flows.get(a.userId)!; expect(JSON.stringify(flow)).not.toContain("fixture-unit-verifier"); expect(flow.stateHash).not.toContain(new URL(second.url).searchParams.get("state")); });
it.each(["missing", "invalid", "expired", "foreign"])("%s callback state cannot exchange or persist a connection", async kind => { const { url } = await service.start(a); const state = new URL(url).searchParams.get("state"); if (kind === "expired") now = new Date(calendarClock.getTime() + 601000); expect(await service.callback(kind === "foreign" ? b : a, { state: kind === "missing" ? null : kind === "invalid" ? "tampered" : state, code: "fixture-code", denied: false })).toBe("failed"); expect(provider.exchange).not.toHaveBeenCalled(); expect(memory.connections.size).toBe(0); });
it("successful callback retries exchange once and repair exactly one owned connection", async () => { const { value, state } = await connect(); expect(await service.callback(a, { state, code: "fixture-code", denied: false })).toBe("success"); expect(provider.exchange).toHaveBeenCalledTimes(1); const next = await connect(); expect(next.value.id).toBe(value.id); expect(memory.connections.size).toBe(1); expect(next.value.version).toBe(2); expect(memory.connections.get(a.userId)?.providerAccountId).not.toBe(a.userId); });
it.each(["missing-scopes", "missing-offline"])("%s grant never becomes connected", async kind => { provider.exchange.mockResolvedValueOnce({ ...calendarGrant(), ...(kind === "missing-scopes" ? { scopes: [] } : { refreshToken: null }) }); const { url } = await service.start(a); expect(await service.callback(a, { state: new URL(url).searchParams.get("state"), code: "fixture-code", denied: false })).toBe("failed"); expect(memory.connections.size).toBe(0); });
it("denial and interrupted exchange consume the flow and preserve a prior connection", async () => { const { value } = await connect(); const before = structuredClone(memory.connections.get(a.userId)); const { url } = await service.start(a); const state = new URL(url).searchParams.get("state"); expect(await service.callback(a, { state, code: null, denied: true })).toBe("cancelled"); expect(memory.connections.get(a.userId)).toEqual(before); expect((await service.workspace(a)).connection?.id).toBe(value.id); provider.exchange.mockRejectedValueOnce(new Error("untrusted raw provider error")); const second = await service.start(a); const input = { state: new URL(second.url).searchParams.get("state"), code: "fixture-code", denied: false }; expect(await service.callback(a, input)).toBe("failed"); expect(await service.callback(a, input)).toBe("failed"); expect(provider.exchange).toHaveBeenCalledTimes(2); });
it("no secrets, scopes or provider identity leak through DTOs", async () => { await configured(); const text = JSON.stringify(await service.workspace(a)); for (const marker of ["fixture-unit-access", "fixture-unit-refresh", "fixture-unit-verifier", "encryptedCredentials", "google-identity-different-from-app-user", "ownerId"]) expect(text).not.toContain(marker); const stored = memory.connections.get(a.userId)!; expect(stored.encryptedCredentials).not.toContain("fixture-unit-refresh"); expect(stored.accessExpiresAt).toEqual(new Date(calendarGrant().expiresAt)); });
it("listing leaves primary/other calendars unselected; explicit selection alone persists", async () => { const { value } = await connect(); const listed = await service.refreshCalendars(a, value.id); expect(listed.selectedCalendarIds).toEqual([]); const selected = await service.select(a, value.id, { expectedVersion: listed.version, calendarIds: ["work"] }); expect(selected.selectedCalendarIds).toEqual(["work"]); expect((await service.workspace(a)).connection).toEqual(selected); });
it("selection version conflict retains saved choices; exact lost-ack retry is a no-op", async () => { const value = await configured(); const command = { expectedVersion: value.version, calendarIds: ["work"] }; const selected = await service.select(a, value.id, command); expect(await service.select(a, value.id, command)).toEqual(selected); await expect(service.select(a, value.id, { expectedVersion: value.version, calendarIds: [] })).rejects.toMatchObject({ code: "CONFLICT", details: { kind: "CALENDAR_VERSION" } }); });
it("unavailable selections remain explicit and require review without substitution", async () => { const value = await configured(); await service.refreshAvailability(a, value.id, week); provider.listCalendars.mockResolvedValueOnce([{ id: "work", summary: "Work", primary: true, timezone: "Europe/London", accessRole: "owner" }]); const listed = await service.refreshCalendars(a, value.id); expect(listed.selectedCalendarIds).toEqual(["personal", "work"]); expect(listed.listError).toBe("selection_review"); const previousCalls = provider.queryBusyIntervals.mock.calls.length; const advisory = await service.refreshAvailability(a, value.id, week); expect(advisory.status).toBe("stale"); expect(advisory.error).toBe("selection_review"); expect(provider.queryBusyIntervals).toHaveBeenCalledTimes(previousCalls); await expect(service.select(a, value.id, { expectedVersion: listed.version, calendarIds: ["personal"] })).rejects.toMatchObject({ code: "VALIDATION" }); const selected = await service.select(a, value.id, { expectedVersion: listed.version, calendarIds: ["work"] }); expect(selected.listError).toBeNull(); expect((await service.workspace(a)).availability?.fetchedAt).toBeNull(); });
it("selection replacement, empty selection and different account invalidate old availability", async () => { const value = await configured(); await service.refreshAvailability(a, value.id, week); expect(memory.caches.size).toBe(1); await service.select(a, value.id, { expectedVersion: value.version, calendarIds: [] }); expect(memory.caches.size).toBe(0); expect((await service.workspace(a)).availability?.status).toBe("not_configured"); await configured(); provider.exchange.mockResolvedValueOnce({ ...calendarGrant(), accountId: "another-google-account" }); const next = await connect(); expect(next.value.selectedCalendarIds).toEqual([]); expect(next.value.calendars).toEqual([]); });
it("same-account reconnect safely retains selection and omitted refresh credential", async () => { const value = await configured(); provider.exchange.mockResolvedValueOnce({ ...calendarGrant(), refreshToken: null }); const next = await connect(); expect(next.value.id).toBe(value.id); expect(next.value.selectedCalendarIds).toEqual(value.selectedCalendarIds); await service.refreshCalendars(a, value.id); await service.refreshAvailability(a, value.id, week); expect(provider.queryBusyIntervals).toHaveBeenCalled(); });
it("cannot reuse old refresh credential when provider subject is missing or different", async () => { await configured(); for (const accountId of [null, "other-account"]) { provider.exchange.mockResolvedValueOnce({ ...calendarGrant(), accountId, refreshToken: null }); const { url } = await service.start(a); expect(await service.callback(a, { state: new URL(url).searchParams.get("state"), code: "fixture-code", denied: false })).toBe("failed"); } });
it("exact local range and union return busy minutes only; no capacity/recommendation output", async () => { const value = await configured(); const result = await service.refreshAvailability(a, value.id, week); expect(result.status).toBe("fresh"); expect(result.totalBusyMinutes).toBe(180); expect(result.days[0].busyMinutes).toBe(180); expect(provider.queryBusyIntervals.mock.calls[0][2]).toMatchObject({ start: "2026-09-27T23:00:00Z", end: "2026-10-04T23:00:00Z" }); expect(Object.keys(result)).not.toContain("capacityMinutes"); expect(result.fetchedAt).toBe(calendarClock.toISOString()); });
it.each(["unavailable", "incomplete"] as const)("%s leaves complete prior intervals and timestamp intact and persistently stale", async kind => { const value = await configured(); const good = await service.refreshAvailability(a, value.id, week); provider.queryBusyIntervals.mockRejectedValueOnce(new ProviderFailure(kind)); const bad = await service.refreshAvailability(a, value.id, week); expect(bad.status).toBe("stale"); expect(bad.error).toBe(kind); expect(bad.intervals).toEqual(good.intervals); expect(bad.fetchedAt).toBe(good.fetchedAt); expect((await service.workspace(a)).availability).toEqual(bad); });
it.each(["unavailable", "incomplete"] as const)("%s with no snapshot cannot appear as zero busy/free time", async kind => { const value = await configured(); provider.queryBusyIntervals.mockRejectedValueOnce(new ProviderFailure(kind)); const result = await service.refreshAvailability(a, value.id, week); expect(result.status).toBe("unavailable"); expect(result.totalBusyMinutes).toBeNull(); expect(result.intervals).toBeNull(); expect(result.error).toBe(kind); });
it("clock expiry makes cached timing stale; successful empty refresh is explicitly complete", async () => { const value = await configured(); await service.refreshAvailability(a, value.id, week); now = new Date(calendarClock.getTime() + 15 * 60000); expect((await service.workspace(a)).availability?.status).toBe("stale"); provider.queryBusyIntervals.mockResolvedValueOnce([]); const next = await service.refreshAvailability(a, value.id, week); expect(next.status).toBe("fresh"); expect(next.totalBusyMinutes).toBe(0); expect(next.intervals).toEqual([]); });
it("expired access refreshes once, preserves omitted refresh and re-encrypts credentials", async () => { const value = await configured(); const before = memory.connections.get(a.userId)!.encryptedCredentials; now = new Date(calendarGrant().expiresAt); await service.refreshAvailability(a, value.id, week); expect(provider.refresh).toHaveBeenCalledWith("fixture-unit-refresh"); expect(memory.connections.get(a.userId)!.encryptedCredentials).not.toBe(before); expect((await service.workspace(a)).connection?.version).toBe(value.version); });
it("revoked refresh marks reconnection required and stops future refresh attempts", async () => { const value = await configured(); const good = await service.refreshAvailability(a, value.id, week); now = new Date(calendarGrant().expiresAt); provider.refresh.mockRejectedValueOnce(new ProviderFailure("reauthorization_required")); const result = await service.refreshAvailability(a, value.id, week); expect(result.status).toBe("stale"); expect(result.intervals).toEqual(good.intervals); expect((await service.workspace(a)).connection?.state).toBe("reauthorization_required"); await service.refreshAvailability(a, value.id, week); expect(provider.refresh).toHaveBeenCalledTimes(1); });
it("revoked access tries one refresh and retry, never an unbounded loop", async () => { const value = await configured(); provider.queryBusyIntervals.mockRejectedValue(new ProviderFailure("reauthorization_required")); await service.refreshAvailability(a, value.id, week); expect(provider.refresh).toHaveBeenCalledTimes(1); expect(provider.queryBusyIntervals).toHaveBeenCalledTimes(2); expect((await service.workspace(a)).connection?.state).toBe("reauthorization_required"); });
it("disconnect removes secrets/config/cache/pending flow despite revocation failure; retries cannot reconnect", async () => { const value = await configured(); await service.refreshAvailability(a, value.id, week); const pending = await service.start(a); provider.revoke.mockRejectedValueOnce(new Error("untrusted provider error")); const result = await service.disconnect(a, value.id); expect(result.revocationConfirmed).toBe(false); const row = memory.connections.get(a.userId)!; expect(row.encryptedCredentials).toBeNull(); expect(row.grantedScopes).toEqual([]); expect(row.selectedCalendarIds).toEqual([]); expect(memory.caches.size).toBe(0); expect(memory.flows.size).toBe(0); expect(provider.revoke).toHaveBeenCalledWith("fixture-unit-refresh"); expect(await service.callback(a, { state: new URL(pending.url).searchParams.get("state"), code: "fixture-code", denied: false })).toBe("failed"); expect((await service.disconnect(a, value.id)).connection).toEqual(result.connection); });
it("foreign and missing connection IDs are indistinguishable across all reads and writes", async () => { const value = await configured(); const operations = (id: string) => [() => service.workspace(b, undefined, id), () => service.refreshCalendars(b, id), () => service.select(b, id, { expectedVersion: 1, calendarIds: [] }), () => service.refreshAvailability(b, id, week), () => service.disconnect(b, id)]; for (const id of [value.id, randomUUID()]) for (const operation of operations(id)) await expect(operation()).rejects.toMatchObject({ code: "NOT_FOUND", message: "This Calendar connection is unavailable." }); expect((await service.workspace(b)).connection).toBeNull(); expect(provider.revoke).not.toHaveBeenCalled(); });

it("JSONB key ordering and identical list refresh never invalidate a selection draft", async () => { const value = await configured(); const row = memory.connections.get(a.userId)!; row.calendars = row.calendars.map(c => ({ accessRole: c.accessRole, timezone: c.timezone, primary: c.primary, summary: c.summary, id: c.id })); const refreshed = await service.refreshCalendars(a, value.id); expect(refreshed.version).toBe(value.version); expect((await service.select(a, value.id, { expectedVersion: value.version, calendarIds: ["work"] })).selectedCalendarIds).toEqual(["work"]); });
it("reconnect cannot reuse a known revoked refresh credential even for the same subject", async () => { const value = await configured(); now = new Date(calendarGrant().expiresAt); provider.refresh.mockRejectedValueOnce(new ProviderFailure("reauthorization_required")); await service.refreshAvailability(a, value.id, week); provider.exchange.mockResolvedValueOnce({ ...calendarGrant(), refreshToken: null }); const { url } = await service.start(a); expect(await service.callback(a, { state: new URL(url).searchParams.get("state"), code: "fixture-code", denied: false })).toBe("failed"); expect((await service.workspace(a)).connection?.state).toBe("reauthorization_required"); });
