import { it, expect } from 'vitest';
import OpenAI from 'openai';
import Anthropic from '@anthropic-ai/sdk';
import { openAICoach } from '../../src/providers/openai/coaching';
import { anthropicCoach, anthropicWireSchema } from '../../src/providers/anthropic/coaching';
import {safeProviderFailure} from '../../src/providers/ai-errors';
import { structuredSchema } from '../../src/modules/coaching/provider';
import { buildContext } from '../../src/modules/coaching/context';
import { contextFixture, suggestions } from '../coaching-fixture';
const context=buildContext(contextFixture()),output={recommendations:suggestions(context)};
const openResponse=(body:unknown=output,status='completed')=>({id:'resp_fixture',object:'response',created_at:1791010000,status,output:[{id:'msg_fixture',type:'message',role:'assistant',status:'completed',content:[{type:'output_text',text:JSON.stringify(body),annotations:[]}]}],usage:{input_tokens:100,output_tokens:60,total_tokens:160,input_tokens_details:{cached_tokens:10},output_tokens_details:{reasoning_tokens:0}}});
const claudeResponse=(body:unknown=output)=>({id:'msg_fixture',type:'message',role:'assistant',model:'fixture-claude',content:[{type:'text',text:JSON.stringify(body)}],stop_reason:'end_turn',stop_sequence:null,usage:{input_tokens:100,output_tokens:60,cache_read_input_tokens:10,cache_creation_input_tokens:0}});
it('OpenAI official SDK calls Responses with strict schema, no tools/history and store:false',async()=>{let sent:Record<string,unknown>={},path='';const client=new OpenAI({apiKey:'synthetic-secret',maxRetries:0,logLevel:'off',fetch:async(input,init)=>{const request=new Request(input,init);path=new URL(request.url).pathname;sent=await request.json();return Response.json(openResponse());}});const result=await openAICoach(client,'fixture-openai').generateCoaching(context,structuredSchema,new AbortController().signal);expect(path).toBe('/v1/responses');expect(sent).toMatchObject({model:'fixture-openai',store:false,max_output_tokens:4096,text:{format:{type:'json_schema',strict:true,schema:structuredSchema}}});expect(sent).not.toHaveProperty('tools');expect(sent).not.toHaveProperty('previous_response_id');expect(result).toEqual({output,usage:{inputTokens:100,outputTokens:60,cachedInputTokens:10}});expect(JSON.stringify(sent)).not.toContain('synthetic-secret');});
it('Anthropic official SDK calls Messages with output_config JSON schema and no tools',async()=>{let sent:Record<string,unknown>={},path='';const client=new Anthropic({apiKey:'synthetic-secret',maxRetries:0,logLevel:'off',fetch:async(input,init)=>{const request=new Request(input,init);path=new URL(request.url).pathname;sent=await request.json();return Response.json(claudeResponse());}});const result=await anthropicCoach(client,'fixture-claude').generateCoaching(context,structuredSchema,new AbortController().signal);expect(path).toBe('/v1/messages');expect(sent).toMatchObject({model:'fixture-claude',max_tokens:4096,output_config:{format:{type:'json_schema',schema:structuredSchema}}});expect(sent).not.toHaveProperty('tools');expect(result).toEqual({output,usage:{inputTokens:100,outputTokens:60,cachedInputTokens:10}});});
it.each([401,403,429,404,500])('both adapters redact secret-bearing HTTP %i errors',async status=>{const fetcher:typeof fetch=async()=>Response.json({error:{type:'api_error',message:'secret-provider-token PRIVATE-CONTEXT'}},{status});for(const provider of [openAICoach(new OpenAI({apiKey:'dummy',logLevel:'off',maxRetries:0,fetch:fetcher}),'fixture-openai'),anthropicCoach(new Anthropic({apiKey:'dummy',logLevel:'off',maxRetries:0,fetch:fetcher}),'fixture-claude')]){try{await provider.generateCoaching(context,structuredSchema,new AbortController().signal);throw new Error('Expected failure');}catch(error){expect((error as Error).message).toBe('Coaching could not be generated.');expect(String(error)).not.toMatch(/secret-provider-token|PRIVATE/);}}});
it('refusal, truncated and malformed outputs never become domain commands',async()=>{for(const error of [new OpenAI.APIConnectionTimeoutError(),new OpenAI.APIUserAbortError(),new Anthropic.APIConnectionTimeoutError(),new Anthropic.APIUserAbortError()])expect(safeProviderFailure(error).kind).toBe('timeout');for(const payload of [{...openResponse(),output:[{type:'message',content:[{type:'refusal',refusal:'Cannot do that'}]}]},openResponse(output,'incomplete'),{...openResponse(),output:[{type:'message',content:[{type:'output_text',text:'{invalid'}]}]}]){const provider=openAICoach(new OpenAI({apiKey:'dummy',logLevel:'off',fetch:async()=>Response.json(payload)}),'fixture-openai');await expect(provider.generateCoaching(context,structuredSchema,new AbortController().signal)).rejects.toMatchObject({kind:expect.any(String),usage:{inputTokens:100,outputTokens:60,cachedInputTokens:10}});}for(const payload of [{...claudeResponse(),stop_reason:'refusal'},{...claudeResponse(),stop_reason:'max_tokens'},{...claudeResponse(),content:[{type:'text',text:'not json'}]}]){const provider=anthropicCoach(new Anthropic({apiKey:'dummy',logLevel:'off',fetch:async()=>Response.json(payload)}),'fixture-claude');await expect(provider.generateCoaching(context,structuredSchema,new AbortController().signal)).rejects.toMatchObject({kind:expect.any(String),usage:{inputTokens:100,outputTokens:60,cachedInputTokens:10}});}});

it('Review uses the same narrow semantic instructions, schema and frozen packet in both official SDK adapters',async()=>{
 const {reviewSystemPrompt,reviewStructuredSchema}=await import('../../src/modules/coaching/provider');
 const {reviewInsightFixture}=await import('../review-insight-fixture');
 const packet=buildContext(reviewInsightFixture('gap_reflection'));
 const body={insights:[]},requests:Record<string,unknown>[]=[];
 const capture=(response:unknown):typeof fetch=>async(input,init)=>{requests.push(await new Request(input,init).json());return Response.json(response);};
 const providers=[openAICoach(new OpenAI({apiKey:'synthetic',maxRetries:0,fetch:capture(openResponse(body))}),'fixture-openai'),anthropicCoach(new Anthropic({apiKey:'synthetic',maxRetries:0,fetch:capture(claudeResponse(body))}),'fixture-claude')];
 for(const provider of providers)expect((await provider.generateCoaching(packet,reviewStructuredSchema,new AbortController().signal)).output).toEqual(body);
 expect(requests[0].instructions).toBe(reviewSystemPrompt);expect(requests[1].system).toBe(reviewSystemPrompt);
 expect(requests[0].input).toBe(JSON.stringify(packet));expect(requests[1].messages).toEqual([{role:'user',content:JSON.stringify(packet)}]);
 expect(requests[0]).toMatchObject({text:{format:{schema:reviewStructuredSchema}}});expect(requests[1]).toMatchObject({output_config:{format:{schema:anthropicWireSchema(reviewStructuredSchema)}}});
});

it('Anthropic compatibility removes only unsupported Review maxItems while application cap and Calendar schema stay unchanged',async()=>{const {reviewStructuredSchema}=await import('../../src/modules/coaching/provider');const original=structuredClone(reviewStructuredSchema),wire=anthropicWireSchema(reviewStructuredSchema) as typeof reviewStructuredSchema;expect(wire).not.toHaveProperty('properties.insights.maxItems');expect(reviewStructuredSchema).toEqual(original);expect(original).toHaveProperty('properties.insights.maxItems',2);expect(anthropicWireSchema(structuredSchema)).toEqual(structuredSchema);});
