import { expect,it,vi } from "vitest";
import { randomUUID } from "node:crypto";
import { focusService,type FocusRepository } from "../../src/modules/focus/service";
import { focusContext,focusNow,focusSession } from "../focus-fixtures";
import type { FocusSession } from "../../src/modules/focus/domain";
const actor={userId:"a"};
function fixture(){const c=focusContext(),existing=focusSession({timeBlockId:c.block.id});let active:FocusSession|null=null;const insert=vi.fn(async(v:FocusSession)=>v),end=vi.fn(async(v:FocusSession)=>v);const repo:FocusRepository={workspace:vi.fn(),get:vi.fn(async()=>({...existing,ownerId:"a"})),execute:vi.fn(async(_a,_id,_h,apply)=>apply({context:async()=>c,active:async()=>active,session:async()=>({...existing,ownerId:"a"}),insert,end}))};return {c,existing,repo,insert,end,setActive:(v:FocusSession|null)=>{active=v;},s:focusService(repo,()=>focusNow)};}
const input=()=>({mutationId:randomUUID(),expectedBlockVersion:1,acknowledgeRemoved:false});
it("start uses authoritative injected clock and immutable block context without mutations",async()=>{const f=fixture(),before=structuredClone(f.c),s=await f.s.start(actor,f.c.block.id,input());expect(s).toMatchObject({startedAt:focusNow,endedAt:null,version:1});expect(f.c).toEqual(before);expect(f.insert).toHaveBeenCalledOnce();});
it("active conflict exposes only this owner's current session and never silently ends it",async()=>{const f=fixture();f.setActive(f.existing);await expect(f.s.start(actor,f.c.block.id,input())).rejects.toMatchObject({details:{kind:"ACTIVE_SESSION",current:f.existing}});expect(f.insert).not.toHaveBeenCalled();expect(f.end).not.toHaveBeenCalled();});
it("removed context checked in final transaction",async()=>{const f=fixture();f.c.effective.commitments=[];await expect(f.s.start(actor,f.c.block.id,input())).rejects.toMatchObject({details:{kind:"REMOVED_COMMITMENT"}});await expect(f.s.start(actor,f.c.block.id,{...input(),acknowledgeRemoved:true})).resolves.toMatchObject({timeBlockId:f.c.block.id});});
it("end with nonpositive clock never writes, notes validated before receipts",async()=>{const f=fixture();await expect(f.s.end(actor,f.existing.id,{mutationId:randomUUID(),expectedVersion:1,outcome:"partial",endNote:"x"})).rejects.toMatchObject({details:{kind:"CLOCK_ORDER"}});expect(f.end).not.toHaveBeenCalled();await expect(f.s.start(actor,f.c.block.id,{...input(),startedAt:focusNow})).rejects.toMatchObject({code:"VALIDATION"});});
it("end captures exact server clock, normalizes note, preserves all other aggregates",async()=>{const f=fixture(),later="2026-10-06T09:45:00.321Z",s=focusService(f.repo,()=>later),before=structuredClone(f.c);const result=await s.end(actor,f.existing.id,{mutationId:randomUUID(),expectedVersion:1,outcome:"completed",endNote:"  Finished slice; tests remain.  "});expect(result).toMatchObject({endedAt:later,outcome:"completed",endNote:"Finished slice; tests remain."});expect(f.c).toEqual(before);});
it("hash binds start/end kind, resource, version and normalized outcome",async()=>{const f=fixture(),cmd=input();await f.s.start(actor,f.c.block.id,cmd);const first=vi.mocked(f.repo.execute).mock.calls[0][2];await f.s.start(actor,f.c.block.id,{...cmd,acknowledgeRemoved:true});expect(vi.mocked(f.repo.execute).mock.calls[1][2]).not.toBe(first);});
