import {expect,it,vi} from "vitest";
import {randomUUID} from "node:crypto";
import {reviewService,type ReviewRepository} from "../../src/modules/reviews/service";
import type {DailyReflection} from "../../src/modules/reviews/domain";
import {focusSession} from "../focus-fixtures";
const a={userId:"a"},now="2026-10-06T18:00:00.123Z";
const command=(extra:object={})=>({mutationId:randomUUID(),localDate:"2026-10-06",reflectionId:null,expectedVersion:0,note:" A useful day. ",...extra});
function fixture(){let current:DailyReflection|null=null,active:ReturnType<typeof focusSession>|null=null;const insert=vi.fn(async(v:DailyReflection)=>{current=v;return v;}),update=vi.fn(async(v:DailyReflection)=>{current=v;return v;});const repo:ReviewRepository={day:vi.fn(),get:vi.fn(async()=>current?{...current,ownerId:"a"}:null),execute:vi.fn(async(_a,_id,_h,apply)=>apply({timezone:"Europe/London",byDate:async()=>current,get:async()=>current?{...current,ownerId:"a"}:null,active:async()=>active,insert,update}))};return {repo,insert,update,s:reviewService(repo,()=>now),setActive:(v:typeof active)=>active=v};}
it("create uses server IDs/timestamps; repeated explicit saves increment draft version",async()=>{const f=fixture(),one=await f.s.save(a,command()),two=await f.s.save(a,command({reflectionId:one.id,expectedVersion:1,note:"Another thought"}));expect(one).toMatchObject({note:"A useful day.",version:1,createdAt:now,updatedAt:now,finalizedAt:null});expect(two).toMatchObject({id:one.id,version:2,note:"Another thought"});expect(f.insert).toHaveBeenCalledOnce();expect(f.update).toHaveBeenCalledOnce();});
it("stale save retains the original note, cannot overwrite or create a second draft",async()=>{const f=fixture(),one=await f.s.save(a,command());await expect(f.s.save(a,command({note:"stale"}))).rejects.toMatchObject({details:{kind:"REFLECTION_VERSION",current:one}});expect(f.update).not.toHaveBeenCalled();});
it("finish requires saved non-empty note and uses authoritative timestamp/version",async()=>{const f=fixture(),one=await f.s.save(a,command({note:""}));await expect(f.s.finalize(a,one.id,{mutationId:randomUUID(),expectedVersion:1})).rejects.toMatchObject({code:"VALIDATION"});const two=await f.s.save(a,command({reflectionId:one.id,expectedVersion:1})),final=await f.s.finalize(a,one.id,{mutationId:randomUUID(),expectedVersion:2});expect(final).toMatchObject({status:"finalized",finalizedAt:now,updatedAt:now,version:3,note:two.note});await expect(f.s.save(a,command({reflectionId:one.id,expectedVersion:3}))).rejects.toMatchObject({details:{kind:"REFLECTION_FINALIZED"}});});
it("current-day active session rejects atomically; crossed midnight past day may finish",async()=>{const f=fixture();f.setActive(focusSession({startedAt:"2026-10-05T22:50Z"}));const today=await f.s.save(a,command());await expect(f.s.finalize(a,today.id,{mutationId:randomUUID(),expectedVersion:1})).rejects.toMatchObject({details:{kind:"ACTIVE_EXECUTION"}});expect(f.update).not.toHaveBeenCalled();const old=fixture();old.setActive(focusSession({startedAt:"2026-10-05T22:50Z"}));const past=await old.s.save(a,command({localDate:"2026-10-05"}));await expect(old.s.finalize(a,past.id,{mutationId:randomUUID(),expectedVersion:1})).resolves.toMatchObject({status:"finalized"});});
it("future create rejects without insert; date is immutable; backwards clock rejects",async()=>{const f=fixture();await expect(f.s.save(a,command({localDate:"2026-10-07"}))).rejects.toMatchObject({details:{kind:"FUTURE_REFLECTION"}});expect(f.insert).not.toHaveBeenCalled();const one=await f.s.save(a,command());await expect(f.s.save(a,command({reflectionId:one.id,expectedVersion:1,localDate:"2026-10-05"}))).rejects.toMatchObject({details:{kind:"REFLECTION_DATE"}});await expect(reviewService(f.repo,()=>"2026-10-06T17:00Z").finalize(a,one.id,{mutationId:randomUUID(),expectedVersion:1})).rejects.toMatchObject({details:{kind:"CLOCK_ORDER"}});});
it("foreign IDs return same safe error for get/save/finalize",async()=>{const f=fixture(),one=await f.s.save(a,command());await expect(f.s.get({userId:"b"},one.id)).rejects.toMatchObject({code:"NOT_FOUND"});await expect(f.s.save({userId:"b"},command({reflectionId:one.id,expectedVersion:1}))).rejects.toMatchObject({code:"NOT_FOUND"});await expect(f.s.finalize({userId:"b"},one.id,{mutationId:randomUUID(),expectedVersion:1})).rejects.toMatchObject({code:"NOT_FOUND"});});
it("hash binds command kind/date/identity/version/normalized note; invalid inputs never reach receipts",async()=>{const f=fixture(),cmd=command(),one=await f.s.save(a,cmd),first=vi.mocked(f.repo.execute).mock.calls[0][2];await f.s.save(a,{...cmd,note:"A useful day."}).catch(()=>{});expect(vi.mocked(f.repo.execute).mock.calls[1][2]).toBe(first);await f.s.finalize(a,one.id,{mutationId:cmd.mutationId,expectedVersion:1});expect(vi.mocked(f.repo.execute).mock.calls[2][2]).not.toBe(first);const calls=vi.mocked(f.repo.execute).mock.calls.length;await expect(f.s.save(a,{...cmd,ownerId:"b"})).rejects.toMatchObject({code:"VALIDATION"});expect(vi.mocked(f.repo.execute)).toHaveBeenCalledTimes(calls);});
