import { expect,it,vi } from "vitest";
import { randomUUID } from "node:crypto";
import { schedulingService, type SchedulingRepository } from "../../src/modules/scheduling/service";
import { context,placement,now,block } from "../scheduling-fixtures";
import type { TimeBlock } from "../../src/modules/scheduling/domain";
function fixture(){const c=context();const insert=vi.fn(async(v:TimeBlock)=>v),replace=vi.fn(async(v:TimeBlock)=>v);const repo:SchedulingRepository={read:vi.fn(async()=>c),get:vi.fn(async()=>({...block(),ownerId:"a"})),execute:vi.fn(async(_a,_id,_hash,apply)=>apply({context:async()=>c,block:async()=>c.blocks[0]?{...c.blocks[0],ownerId:"a"}:null,insert,replace}))};return {c,insert,replace,repo,s:schedulingService(repo,()=>now)};}
const actor={userId:"a"};
async function command(f:ReturnType<typeof fixture>){const r=await f.s.preview(actor,f.c.plan.id,placement);return {...placement,mutationId:randomUUID(),expectedPlanVersion:r.planVersion,reviewKey:r.reviewKey,acknowledgeOutsideHours:false,acknowledgeBusy:false};}
it("preview is a read only proposal, create freezes commitment context",async()=>{const f=fixture(),input=await command(f);expect(f.repo.execute).not.toHaveBeenCalled();const b=await f.s.create(actor,f.c.plan.id,input);expect(b.snapshot).toEqual(f.c.effective.commitments[0].snapshot);f.c.effective.commitments[0].snapshot.action.title="Changed";expect(b.snapshot.action.title).not.toBe("Changed");expect(f.insert).toHaveBeenCalledOnce();});
it("outside hours are advisory and remain visible in preview without a required acknowledgement",async()=>{const f=fixture();f.c.hours=null;const review=await f.s.preview(actor,f.c.plan.id,placement);expect(review.outsideHours).toBe(true);const input=await command(f);await expect(f.s.create(actor,f.c.plan.id,input)).resolves.toMatchObject({state:"planned"});expect(f.insert).toHaveBeenCalledTimes(1);});
it("server requires separate busy acknowledgement and permits intentional busy placement",async()=>{const f=fixture();f.c.calendar.intervals=[block()];const input=await command(f);await expect(f.s.create(actor,f.c.plan.id,input)).rejects.toMatchObject({details:{kind:"GOOGLE_BUSY"}});await expect(f.s.create(actor,f.c.plan.id,{...input,acknowledgeBusy:true})).resolves.toMatchObject({state:"planned"});});
for(const change of ["hours","calendar","membership","blocks"] as const)it(`review token rejects changed ${change} with retained client input`,async()=>{const f=fixture(),input=await command(f);if(change==="hours")f.c.hours!.version++;if(change==="calendar")f.c.calendar.fetchedAt="2026-10-02T11:59Z";if(change==="membership")f.c.effective.commitments[0].budgetMinutes=120;if(change==="blocks")f.c.blocks=[block({start:"2026-10-07T09:00Z",end:"2026-10-07T10:00Z"})];await expect(f.s.create(actor,f.c.plan.id,input)).rejects.toMatchObject({details:{kind:"REVIEW_CHANGED"}});expect(f.insert).not.toHaveBeenCalled();});
it("effective version is checked inside final transaction",async()=>{const f=fixture(),input=await command(f);f.c.plan.version++;await expect(f.s.create(actor,f.c.plan.id,input)).rejects.toMatchObject({details:{kind:"EFFECTIVE_VERSION"}});});
it("removed future commitment allows intentional cancel while labels/identity survive",async()=>{const f=fixture(),b=block();f.c.blocks=[b];f.c.effective.commitments=[];const saved=await f.s.cancel(actor,b.id,{mutationId:randomUUID(),expectedVersion:1});expect(saved).toEqual({...b,state:"cancelled",version:2,cancelledAt:now,updatedAt:now});expect(f.replace).toHaveBeenCalledWith(saved,1);});
it("foreign/missing and past mutations never reach writes",async()=>{const f=fixture();await expect(f.s.cancel(actor,randomUUID(),{mutationId:randomUUID(),expectedVersion:1})).rejects.toMatchObject({code:"NOT_FOUND"});f.c.blocks=[block({start:now,end:"2026-10-02T13:00Z"})];await expect(f.s.cancel(actor,f.c.blocks[0].id,{mutationId:randomUUID(),expectedVersion:1})).rejects.toMatchObject({details:{kind:"STARTED"}});expect(f.replace).not.toHaveBeenCalled();});
it("strict input before persistence rejects owner/version identity and unsupported lifecycle",async()=>{const f=fixture(),input=await command(f);for(const extra of [{ownerId:"b"},{state:"completed"},{expectedPlanVersion:0},{startTime:"09:00:01"}])await expect(f.s.create(actor,f.c.plan.id,{...input,...extra})).rejects.toMatchObject({code:"VALIDATION"});expect(f.repo.execute).not.toHaveBeenCalled();});
