import {expect,it,vi} from "vitest";
import {randomUUID} from "node:crypto";
import {weeklyReviewService,type WeeklyReviewRepository,type WeeklyReviewTransaction} from "../../src/modules/weekly-reviews/service";
import {plan,source} from "../planning-fixtures";
import type {WeeklyReview} from "../../src/modules/weekly-reviews/domain";
const p={...plan,state:"committed" as const,committedAt:plan.updatedAt,commitments:plan.commitments.map(c=>({...c,snapshot:source.context}))};
const review:WeeklyReview={id:randomUUID(),planId:p.id,status:"draft",note:"A useful next decision",version:1,createdAt:"2026-10-05T09:00Z",updatedAt:"2026-10-05T09:00Z",finalizedAt:null,decisions:[{commitmentId:p.commitments[0].id,actionId:source.actionId,kind:"drop",proposedBudgetMinutes:null,source:source.source}]};
function harness(){const tx:WeeklyReviewTransaction={timezone:"Europe/London",get:vi.fn(async()=>structuredClone(review)),byPlan:vi.fn(async()=>null),plan:vi.fn(async()=>p),history:vi.fn(async()=>[]),sources:vi.fn(async()=>[source]),archive:vi.fn(async()=>{}),insert:vi.fn(async v=>v),update:vi.fn(async v=>v)};const repository={execute:vi.fn(async(_a,_id,_hash,apply)=>apply(tx)),workspace:vi.fn(),get:vi.fn(),carries:vi.fn()} as WeeklyReviewRepository;return {tx,repository,service:weeklyReviewService(repository,()=>"2026-10-05T10:00:00.000Z")};}
it("finalization uses existing archive effect once only after validation and explicit confirmation",async()=>{const h=harness();await expect(h.service.finalize({userId:"A"},review.id,{mutationId:randomUUID(),expectedVersion:1,confirmArchive:false})).rejects.toThrow(/Confirm archival/);expect(h.tx.archive).not.toHaveBeenCalled();const result=await h.service.finalize({userId:"A"},review.id,{mutationId:randomUUID(),expectedVersion:1,confirmArchive:true});expect(h.tx.archive).toHaveBeenCalledOnce();expect(result).toMatchObject({status:"finalized",version:2,finalizedAt:"2026-10-05T10:00:00.000Z",decisions:review.decisions});});
it("stale source prevents all effects and final update",async()=>{const h=harness();vi.mocked(h.tx.sources).mockResolvedValue([{...source,eligible:false}]);await expect(h.service.finalize({userId:"A"},review.id,{mutationId:randomUUID(),expectedVersion:1,confirmArchive:true})).rejects.toThrow(/changed/);expect(h.tx.archive).not.toHaveBeenCalled();expect(h.tx.update).not.toHaveBeenCalled();});
it("strict invalid Carry is rejected before receipt; changed semantic body hashes differently",async()=>{const h=harness();const cmd={mutationId:randomUUID(),planId:p.id,reviewId:null,expectedVersion:0,note:"",decisions:[]};await h.service.save({userId:"A"},cmd);await h.service.save({userId:"A"},{...cmd,note:"Different"});expect(vi.mocked(h.repository.execute).mock.calls[0][2]).not.toBe(vi.mocked(h.repository.execute).mock.calls[1][2]);await expect(h.service.save({userId:"A"},{...cmd,decisions:[{...review.decisions[0],kind:"carry",proposedBudgetMinutes:0}]})).rejects.toThrow();expect(h.repository.execute).toHaveBeenCalledTimes(2);});
it("matching committed receipt is returned before lifecycle, source and archive checks",async()=>{const h=harness(),final={...review,status:"finalized" as const,version:2,finalizedAt:"2026-10-05T10:00Z"};vi.mocked(h.repository.execute).mockResolvedValue(final);expect(await h.service.finalize({userId:"A"},review.id,{mutationId:randomUUID(),expectedVersion:1,confirmArchive:true})).toEqual(final);expect(h.tx.archive).not.toHaveBeenCalled();expect(h.tx.get).not.toHaveBeenCalled();});
