import { afterAll, beforeAll, beforeEach, expect, it } from "vitest";
import { randomUUID } from "node:crypto";
import { eq, inArray } from "drizzle-orm";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { connectDatabase } from "../../src/db/connect";
import { focusSession, timeBlock, commitmentIdentity, weeklyPlanAmendment, amendmentCommitment, action, goal, milestone, mutationReceipt, user, weeklyCommitment, weeklyPlan } from "../../src/db/schema";
import { goalRepository } from "../../src/modules/goals/repository";
import { goalService } from "../../src/modules/goals/service";
import { milestoneRepository } from "../../src/modules/milestones/repository";
import { milestoneService } from "../../src/modules/milestones/service";
import { actionRepository } from "../../src/modules/actions/repository";
import { actionService } from "../../src/modules/actions/service";
import { planRepository } from "../../src/modules/planning/repository";
import { planService } from "../../src/modules/planning/service";
import type { WeeklyPlan } from "../../src/modules/planning/domain";
import { amendmentRepository } from "../../src/modules/amendments/repository";
import { amendmentService } from "../../src/modules/amendments/service";
import { effectivePlan, type Amendment } from "../../src/modules/amendments/domain";
import { ApplicationError } from "../../src/domain/errors";
import { provisionLocalUser } from "../../scripts/local-user";
import { requireTestDatabaseURL } from "../../scripts/test-database";
const { db, pool } = connectDatabase(requireTestDatabaseURL().url);
const goals = goalService(goalRepository(db)), milestones = milestoneService(milestoneRepository(db)), actions = actionService(actionRepository(db));
const repository = planRepository(db); const clock = () => "2026-10-02T12:00:00.000Z"; const service = planService(repository, clock);
const a = { userId: "" }, b = { userId: "" };
const create = (extra = {}) => ({ mutationId: randomUUID(), weekStartDate: "2026-09-28", provisionalCapacityMinutes: 720, reserveMinutes: 180, ...extra });
const transition = (expectedVersion = 2) => ({ mutationId: randomUUID(), expectedVersion });
beforeAll(async () => { await migrate(db, { migrationsFolder: "src/db/migrations" }); for (const [suffix, actor] of [["A", a], ["B", b]] as const) actor.userId = (await provisionLocalUser(db, { email: process.env[`TEST_USER_${suffix}_EMAIL`], password: process.env[`TEST_USER_${suffix}_PASSWORD`], name: `Engineer ${suffix}`, timezone: "Europe/London" })).id; });
beforeEach(async () => { const owners = [a.userId, b.userId]; await db.delete(mutationReceipt).where(inArray(mutationReceipt.ownerId, owners)); await db.delete(amendmentCommitment).where(inArray(amendmentCommitment.ownerId, owners)); await db.delete(weeklyPlanAmendment).where(inArray(weeklyPlanAmendment.ownerId, owners)); await db.delete(focusSession).where(inArray(focusSession.ownerId, owners)); await db.delete(timeBlock).where(inArray(timeBlock.ownerId, owners)); await db.delete(commitmentIdentity).where(inArray(commitmentIdentity.ownerId, owners)); await db.delete(weeklyCommitment).where(inArray(weeklyCommitment.ownerId, owners)); await db.delete(weeklyPlan).where(inArray(weeklyPlan.ownerId, owners)); await db.delete(action).where(inArray(action.ownerId, owners)); await db.delete(milestone).where(inArray(milestone.ownerId, owners)); await db.delete(goal).where(inArray(goal.ownerId, owners)); await db.update(user).set({ timezone: "Europe/London" }).where(inArray(user.id, owners)); });
afterAll(() => pool.end());
async function fixture(actor = a) {
  const parent = await goals.createGoal(actor, { mutationId: randomUUID(), title: "Useful One Better", outcome: "I plan small meaningful weeks." });
  const first = await milestones.createMilestone(actor, parent.id, { mutationId: randomUUID(), title: "Planning loop usable", successCondition: "Plan one real week." });
  const second = await milestones.createMilestone(actor, parent.id, { mutationId: randomUUID(), title: "Second active context", successCondition: "Keep reassignment explicit." });
  const plain = await actions.createAction(actor, parent.id, { mutationId: randomUUID(), title: "Build capacity editor", doneWhen: "Capacity saves", estimateMinutes: 120 });
  const linked = await actions.createAction(actor, parent.id, { mutationId: randomUUID(), title: "Implement planning persistence", milestoneId: first.id, estimateMinutes: 240, doneWhen: "Restart keeps baseline" });
  const third = await actions.createAction(actor, parent.id, { mutationId: randomUUID(), title: "Test planning flow", milestoneId: second.id, estimateMinutes: 45 });
  const candidates = await service.candidates(actor);
  const selections = [plain, linked, third].map((v, i) => ({ actionId: v.id, source: candidates.find((c) => c.actionId === v.id)!.source, budgetMinutes: [180, 120, 90][i] }));
  return { parent, first, second, plain, linked, third, selections };
}
const save = (plan: WeeklyPlan, commitments: Awaited<ReturnType<typeof fixture>>["selections"], extra = {}) => ({ mutationId: randomUUID(), expectedVersion: plan.version, provisionalCapacityMinutes: plan.provisionalCapacityMinutes, reserveMinutes: plan.reserveMinutes, commitments, ...extra });
const error = async (promise: Promise<unknown>) => { try { await promise; throw new Error("Expected rejection"); } catch (value) { expect(value).toBeInstanceOf(ApplicationError); const e = value as ApplicationError; return { code: e.code, message: e.message, details: e.details }; } };
async function oneWinner(calls: Promise<Amendment>[]) { const results = await Promise.allSettled(calls); expect(results.filter((r) => r.status === "fulfilled")).toHaveLength(1); expect(results.filter((r) => r.status === "rejected")).toHaveLength(1); const failure = results.find((r) => r.status === "rejected") as PromiseRejectedResult; expect(failure.reason).toMatchObject({ code: "CONFLICT" }); return (results.find((r) => r.status === "fulfilled") as PromiseFulfilledResult<Amendment>).value; }

const amendmentsRepo = amendmentRepository(db); const amends = amendmentService(amendmentsRepo, clock);
async function baseline(weekStartDate = "2026-09-28") { const f = await fixture(); const created = await service.create(a, create({ weekStartDate })); const saved = await service.save(a, created.id, save(created, f.selections)); return { ...f, value: await service.commit(a, saved.id, transition(saved.version)) }; }
const amend = (value: WeeklyPlan, extra = {}) => ({ mutationId: randomUUID(), expectedVersion: value.version, reason: "Production support reduced capacity", provisionalCapacityMinutes: 600, reserveMinutes: 120, commitments: value.commitments.map(({ actionId, budgetMinutes }) => ({ actionId, budgetMinutes })), ...extra });
const content = ({ version: _version, ...value }: WeeklyPlan) => { void _version; return value; };
it("baseline-only effective read reproduces original commitment and current amendability", async () => { const { value } = await baseline(); expect(await amends.history(a, value.id)).toMatchObject({ baseline: value, effective: effectivePlan(value, []), amendments: [], canAmend: true }); });
it("two full snapshots leave all baseline content/rows and first amendment unchanged; latest is effective", async () => {
  const { value } = await baseline(); const rows = await db.select().from(weeklyCommitment); const first = await amends.confirm(a, value.id, amend(value)); const firstRows = await db.select().from(amendmentCommitment);
  const latest = (await amends.history(a, value.id)).baseline; const second = await amends.confirm(a, value.id, amend(latest, { reserveMinutes: 180 }));
  const history = await amends.history(a, value.id); expect(history.amendments).toEqual([first, second]); expect(history.effective).toEqual(effectivePlan(value, [first, second])); expect(history.baseline.version).toBe(value.version + 2); expect(content(history.baseline)).toEqual(content(value)); expect(await db.select().from(weeklyCommitment)).toEqual(rows); expect(await amends.get(a, first.id)).toEqual(first); expect((await db.select().from(amendmentCommitment)).filter(c => c.amendmentId === first.id)).toEqual(firstRows);
});
it("budget/source edits preserve frozen context, guards, identity, estimate and live rows independently", async () => {
  const f = await baseline(); await actions.updateAction(a, f.plain.id, { mutationId: randomUUID(), expectedVersion: 1, title: "Live source renamed", doneWhen: "Different", estimateMinutes: 95, milestoneId: f.first.id }); const liveRows = await db.select().from(action);
  const first = await amends.confirm(a, f.value.id, amend(f.value, { commitments: f.value.commitments.map(c => ({ actionId: c.actionId, budgetMinutes: c.actionId === f.plain.id ? 150 : c.budgetMinutes })) }));
  expect(first.commitments.find(c => c.actionId === f.plain.id)).toEqual({ id: f.value.commitments.find(c => c.actionId === f.plain.id)!.id, actionId: f.plain.id, budgetMinutes: 150, source: f.selections[0].source, snapshot: f.value.commitments.find(c => c.actionId === f.plain.id)!.snapshot }); expect(await db.select().from(action)).toEqual(liveRows);
});
it.each(["action-complete", "action-archive", "milestone-complete", "milestone-archive", "goal-archive"])("carried commitments remain valid beneath %s", async change => {
  const f = await baseline(); if (change === "action-complete") await actions.completeAction(a, f.linked.id, transition(1)); if (change === "action-archive") await actions.archiveAction(a, f.linked.id, transition(1)); if (change === "milestone-complete") await milestones.completeMilestone(a, f.first.id, { ...transition(1), evidence: "Done" }); if (change === "milestone-archive") await milestones.archiveMilestone(a, f.first.id, transition(1)); if (change === "goal-archive") await goals.archiveGoal(a, f.parent.id, transition(1));
  const result = await amends.confirm(a, f.value.id, amend(f.value)); expect(result.commitments).toEqual(effectivePlan(f.value, []).commitments); expect(content((await service.get(a, f.value.id)).plan)).toEqual(content(f.value));
});
it("drop then re-add is a fresh eligible capture with new identity and current context", async () => {
  const f = await baseline(); const kept = f.value.commitments.filter(c => c.actionId !== f.plain.id).map(({ actionId, budgetMinutes }) => ({ actionId, budgetMinutes })); const first = await amends.confirm(a, f.value.id, amend(f.value, { commitments: kept }));
  await actions.updateAction(a, f.plain.id, { ...transition(1), title: "Fresh definition", estimateMinutes: 45, doneWhen: "Fresh condition", milestoneId: null }); const candidate = (await service.candidates(a)).find(c => c.actionId === f.plain.id)!;
  const second = await amends.confirm(a, f.value.id, amend({ ...f.value, version: first.version }, { commitments: [...kept, { actionId: f.plain.id, budgetMinutes: 60, source: candidate.source }] }));
  const newCommit = second.commitments.find(c => c.actionId === f.plain.id)!; expect(newCommit.snapshot).toEqual(candidate.context); expect(newCommit.id).not.toBe(f.value.commitments.find(c => c.actionId === f.plain.id)!.id); expect(await amends.get(a, first.id)).toEqual(first); expect(first.commitments.some(c => c.actionId === f.plain.id)).toBe(false);
});
it("new eligible Action has fresh snapshot; changed guards reject and rollback before fresh review", async () => {
  const f = await baseline(); const added = await actions.createAction(a, f.parent.id, { mutationId: randomUUID(), title: "Urgent support", estimateMinutes: 45 }); const old = (await service.candidates(a)).find(c => c.actionId === added.id)!;
  await actions.updateAction(a, added.id, { ...transition(1), title: "Reviewed urgent support", estimateMinutes: 30, doneWhen: null, milestoneId: f.first.id });
  const command = amend(f.value, { commitments: [...amend(f.value).commitments, { actionId: added.id, budgetMinutes: 45, source: old.source }] }); await expect(amends.confirm(a, f.value.id, command)).rejects.toMatchObject({ details: { kind: "SOURCES" } }); expect((await amends.history(a, f.value.id)).amendments).toEqual([]);
  const fresh = (await service.candidates(a)).find(c => c.actionId === added.id)!; const result = await amends.confirm(a, f.value.id, { ...command, commitments: [...amend(f.value).commitments, { actionId: added.id, budgetMinutes: 45, source: fresh.source }] }); expect(result.commitments.find(c => c.actionId === added.id)?.snapshot).toEqual(fresh.context);
});
it.each(["action-complete", "action-archive", "milestone-complete", "milestone-archive", "goal-archive"])("new addition rejects %s after editor opens", async change => {
  const f = await baseline(); const added = await actions.createAction(a, f.parent.id, { mutationId: randomUUID(), title: "New linked work", milestoneId: f.first.id }); const candidate = (await service.candidates(a)).find(c => c.actionId === added.id)!;
  if (change === "action-complete") await actions.completeAction(a, added.id, transition(1)); if (change === "action-archive") await actions.archiveAction(a, added.id, transition(1)); if (change === "milestone-complete") await milestones.completeMilestone(a, f.first.id, transition(1)); if (change === "milestone-archive") await milestones.archiveMilestone(a, f.first.id, transition(1)); if (change === "goal-archive") await goals.archiveGoal(a, f.parent.id, transition(1));
  await expect(amends.confirm(a, f.value.id, amend(f.value, { commitments: [{ actionId: added.id, budgetMinutes: 45, source: candidate.source }] }))).rejects.toMatchObject({ code: "CONFLICT", details: { kind: "SOURCES" } }); expect((await amends.history(a, f.value.id)).amendments).toEqual([]);
});
it.each([0, 600])("capacity %s permits deliberate all-dropped snapshot without altering baseline", async capacity => { const { value } = await baseline(); const result = await amends.confirm(a, value.id, amend(value, { provisionalCapacityMinutes: capacity, reserveMinutes: 0, commitments: [] })); expect(result.commitments).toEqual([]); expect(result.provisionalCapacityMinutes).toBe(capacity); expect(content((await service.get(a, value.id)).plan)).toEqual(content(value)); });
it.each(["NO_CHANGE", "OVER_CAPACITY"])("%s writes neither history, version nor receipt", async kind => { const { value } = await baseline(); const receipts = await db.select().from(mutationReceipt); await expect(amends.confirm(a, value.id, amend(value, { provisionalCapacityMinutes: kind === "NO_CHANGE" ? 720 : 300, reserveMinutes: kind === "NO_CHANGE" ? 180 : 120 }))).rejects.toMatchObject({ details: { kind } }); expect((await service.get(a, value.id)).plan).toEqual(value); expect(await db.select().from(weeklyPlanAmendment)).toEqual([]); expect(await db.select().from(mutationReceipt)).toEqual(receipts); });
it("invalid reason/capacity/budget/duplicate/no source/historical text rejected without any writes", async () => {
  const { value } = await baseline(); const receipts = await db.select().from(mutationReceipt);
  for (const extra of [{ reason: " " }, { reason: "x".repeat(501) }, { provisionalCapacityMinutes: 0 }, { reserveMinutes: 600 }, { ownerId: b.userId }, { commitments: [...amend(value).commitments, ...amend(value).commitments] }, { commitments: [{ actionId: randomUUID(), budgetMinutes: 10 }] }, { commitments: [{ ...amend(value).commitments[0], snapshot: {} }] }, { commitments: [{ ...amend(value).commitments[0], source: value.commitments[0].source }] }]) await expect(amends.confirm(a, value.id, amend(value, extra))).rejects.toMatchObject({ code: "VALIDATION" });
  expect(await db.select().from(mutationReceipt)).toEqual(receipts); expect((await service.get(a, value.id)).plan).toEqual(value);
});
it("same successful command replays original amendment after later amendment, source terminal changes and finished week", async () => {
  const f = await baseline(); const command = amend(f.value); const first = await amends.confirm(a, f.value.id, command); await amends.confirm(a, f.value.id, amend({ ...f.value, version: first.version }, { reserveMinutes: 180 })); await goals.archiveGoal(a, f.parent.id, transition(1)); const later = amendmentService(amendmentsRepo, () => "2026-10-12T12:00:00Z"); expect(await later.confirm(a, f.value.id, command)).toEqual(first); expect((await later.history(a, f.value.id)).amendments).toHaveLength(2); expect(await amends.get(a, first.id)).toEqual(first);
});
it("changed payload, other plan, existing command kind cannot reuse receipt ID", async () => { const { value } = await baseline(); const command = amend(value); await amends.confirm(a, value.id, command); for (const extra of [{ reason: "Different reason" }, { reserveMinutes: 180 }, { expectedVersion: 9 }]) await expect(amends.confirm(a, value.id, { ...command, ...extra })).rejects.toMatchObject({ details: { kind: "MUTATION_ID" } }); await expect(amends.confirm(a, randomUUID(), command)).rejects.toMatchObject({ details: { kind: "MUTATION_ID" } }); await expect(service.commit(a, value.id, { mutationId: command.mutationId, expectedVersion: value.version })).rejects.toMatchObject({ details: { kind: "MUTATION_ID" } }); });
it("concurrent different confirmations have one winner, one typed conflict and one linear sequence", async () => { const { value } = await baseline(); const winner = await oneWinner([amends.confirm(a, value.id, amend(value)), amends.confirm(a, value.id, amend(value, { reserveMinutes: 180 }))]); const history = await amends.history(a, value.id); expect(history.amendments).toEqual([winner]); expect(history.baseline.version).toBe(value.version + 1); expect(winner.sequenceNumber).toBe(1); });
it("concurrent identical confirmations replay one original snapshot and one sequence", async () => { const { value } = await baseline(); const command = amend(value); const [first, second] = await Promise.all([amends.confirm(a, value.id, command), amends.confirm(a, value.id, command)]); expect(second).toEqual(first); expect((await amends.history(a, value.id)).amendments).toEqual([first]); });
it("injected failure after full snapshot write rolls back metadata, rows, version and receipt", async () => { const { value } = await baseline(); const receipts = await db.select().from(mutationReceipt); const failing = amendmentService({ ...amendmentsRepo, executeOwned: (actor, key, hash, apply) => amendmentsRepo.executeOwned(actor, key, hash, tx => apply({ ...tx, append: async (v, version) => { await tx.append(v, version); throw new ApplicationError("VALIDATION", "Injected after snapshot insert"); } })) }, clock); await expect(failing.confirm(a, value.id, amend(value))).rejects.toMatchObject({ code: "VALIDATION" }); expect((await service.get(a, value.id)).plan).toEqual(value); expect(await db.select().from(weeklyPlanAmendment)).toEqual([]); expect(await db.select().from(amendmentCommitment)).toEqual([]); expect(await db.select().from(mutationReceipt)).toEqual(receipts); });
it.each(["2026-09-28", "2026-10-05"])("current/future %s allowed; later finished week blocked using current User zone", async week => { const { value } = await baseline(week); expect((await amends.history(a, value.id)).canAmend).toBe(true); const later = amendmentService(amendmentsRepo, () => "2026-10-12T12:00:00Z"); expect((await later.history(a, value.id)).canAmend).toBe(false); await expect(later.confirm(a, value.id, amend(value))).rejects.toMatchObject({ details: { kind: "READ_ONLY_WEEK" } }); expect((await amends.history(a, value.id)).amendments).toEqual([]); });
it("current User timezone controls finished boundary without changing pinned historical timezone", async () => { const { value } = await baseline(); const boundary = amendmentService(amendmentsRepo, () => "2026-10-04T23:30:00Z"); expect((await boundary.history(a, value.id)).canAmend).toBe(false); await db.update(user).set({ timezone: "America/Los_Angeles" }).where(eq(user.id, a.userId)); expect((await boundary.history(a, value.id)).canAmend).toBe(true); expect((await boundary.confirm(a, value.id, amend(value))).sequenceNumber).toBe(1); expect((await boundary.history(a, value.id)).baseline.timezone).toBe("Europe/London"); });
it("foreign/missing plan/history/amendment IDs are indistinguishable; foreign Action cannot be added", async () => { const { value } = await baseline(); const first = await amends.confirm(a, value.id, amend(value)); expect(await error(amends.history(b, value.id))).toEqual(await error(amends.history(b, randomUUID()))); expect(await error(amends.get(b, first.id))).toEqual(await error(amends.get(b, randomUUID()))); expect(await error(amends.confirm(b, value.id, amend(value)))).toEqual(await error(amends.confirm(b, randomUUID(), amend(value)))); const foreign = await fixture(b); const command = amend({ ...value, version: first.version }, { commitments: [{ actionId: foreign.plain.id, budgetMinutes: 45, source: foreign.selections[0].source }] }); expect(await error(amends.confirm(a, value.id, command))).toEqual(await error(amends.confirm(a, value.id, { ...command, mutationId: randomUUID(), commitments: [{ ...command.commitments[0], actionId: randomUUID() }] }))); expect((await amends.history(a, value.id)).amendments).toEqual([first]); });
it("receipt namespace is owner scoped and cannot influence another owner's sequence", async () => { const left = await baseline(); const foreign = await fixture(b); const created = await service.create(b, create()); const saved = await service.save(b, created.id, save(created, foreign.selections)); const right = await service.commit(b, saved.id, transition(saved.version)); const key = randomUUID(); const first = await amends.confirm(a, left.value.id, amend(left.value, { mutationId: key })); const second = await amends.confirm(b, right.id, amend(right, { mutationId: key })); expect(first.id).not.toBe(second.id); expect(first.sequenceNumber).toBe(1); expect(second.sequenceNumber).toBe(1); });
it("migration constraints enforce sequence, ownership, membership, snapshot shape and budgets", async () => { const { value } = await baseline(); const result = await amends.confirm(a, value.id, amend(value)); const [row] = await db.select().from(weeklyPlanAmendment); const [child] = await db.select().from(amendmentCommitment);
  for (const extra of [{}, { sequenceNumber: 0 }, { sequenceNumber: 2, ownerId: b.userId }, { sequenceNumber: 2, reason: " " }, { sequenceNumber: 2, provisionalCapacityMinutes: 0 }, { sequenceNumber: 2, version: 0 }]) await expect(db.insert(weeklyPlanAmendment).values({ ...row, id: randomUUID(), ...extra })).rejects.toThrow();
  for (const extra of [{}, { actionId: randomUUID() }, { ownerId: b.userId }, { budgetMinutes: 0 }, { snapshot: {} }, { snapshot: { action: {}, goal: {}, milestone: null } }]) await expect(db.insert(amendmentCommitment).values({ ...child, id: randomUUID(), ...extra } as typeof amendmentCommitment.$inferInsert)).rejects.toThrow(); expect(await amends.get(a, result.id)).toEqual(result);
});
it("no amendment API in repository exposes update/delete; original draft and commit rules stay positive/nonempty", async () => { expect(Object.keys(amendmentsRepo).sort()).toEqual(["executeOwned", "get", "read"]); await expect(service.create(a, create({ provisionalCapacityMinutes: 0, reserveMinutes: 0 }))).rejects.toMatchObject({ code: "VALIDATION" }); const empty = await service.create(a, create()); await expect(service.commit(a, empty.id, transition(1))).rejects.toMatchObject({ details: { kind: "EMPTY" } }); });
