import { afterAll, beforeAll, beforeEach, expect, it } from "vitest";
import { randomUUID } from "node:crypto";
import { eq, inArray } from "drizzle-orm";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { connectDatabase } from "../../src/db/connect";
import { calendarAvailabilityCache, calendarConnection, calendarOAuthFlow } from "../../src/db/schema";
import { calendarRepository } from "../../src/modules/calendar/repository";
import { calendarService } from "../../src/modules/calendar/service";
import { ProviderFailure } from "../../src/modules/calendar/provider";
import { goalRepository } from "../../src/modules/goals/repository";
import { goalService } from "../../src/modules/goals/service";
import { milestoneRepository } from "../../src/modules/milestones/repository";
import { milestoneService } from "../../src/modules/milestones/service";
import { actionRepository } from "../../src/modules/actions/repository";
import { actionService } from "../../src/modules/actions/service";
import { planRepository } from "../../src/modules/planning/repository";
import { planService } from "../../src/modules/planning/service";
import { amendmentRepository } from "../../src/modules/amendments/repository";
import { amendmentService } from "../../src/modules/amendments/service";
import { provisionLocalUser } from "../../scripts/local-user";
import { requireTestDatabaseURL } from "../../scripts/test-database";
import { calendarCipher, calendarClock, calendarGrant, fakeCalendar } from "../calendar-fixtures";
const { db, pool } = connectDatabase(requireTestDatabaseURL().url), a = { userId: "" }, b = { userId: "" }; const repository = calendarRepository(db, pool);
let provider: ReturnType<typeof fakeCalendar>, service: ReturnType<typeof calendarService>;
const week = { weekStartDate: "2026-09-28" };
beforeAll(async () => { await migrate(db, { migrationsFolder: "src/db/migrations" }); for (const [suffix, actor] of [["A", a], ["B", b]] as const) actor.userId = (await provisionLocalUser(db, { email: process.env[`TEST_USER_${suffix}_EMAIL`], password: process.env[`TEST_USER_${suffix}_PASSWORD`], name: `Engineer ${suffix}`, timezone: "Europe/London" })).id; });
async function cleanup() { const ids = [a.userId, b.userId]; await db.delete(calendarAvailabilityCache).where(inArray(calendarAvailabilityCache.ownerId, ids)); await db.delete(calendarOAuthFlow).where(inArray(calendarOAuthFlow.ownerId, ids)); await db.delete(calendarConnection).where(inArray(calendarConnection.ownerId, ids)); }
beforeEach(async () => { await cleanup(); provider = fakeCalendar(); service = calendarService(repository, provider, calendarCipher(), () => new Date(calendarClock)); }); afterAll(async () => { await cleanup(); await pool.end(); });
async function connect(actor = a) { const auth = await service.start(actor); const input = { state: new URL(auth.url).searchParams.get("state"), code: "fixture-db-code", denied: false }; expect(await service.callback(actor, input)).toBe("success"); return { connection: (await service.workspace(actor)).connection!, input }; }
async function configured() { const { connection } = await connect(); const listed = await service.refreshCalendars(a, connection.id); return service.select(a, connection.id, { expectedVersion: listed.version, calendarIds: ["work", "personal"] }); }
it("stores one owned connection with ciphertext credentials, encrypted PKCE, scope/expiry/subject metadata", async () => {
  const auth = await service.start(a); const [flow] = await db.select().from(calendarOAuthFlow); const state = new URL(auth.url).searchParams.get("state")!;
  expect(JSON.stringify(flow)).not.toContain(state); expect(JSON.stringify(flow)).not.toContain("fixture-unit-verifier");
  expect(await service.callback(a, { state, code: "fixture-db-code", denied: false })).toBe("success");
  const [row] = await db.select().from(calendarConnection); expect(row.ownerId).toBe(a.userId); expect(row.providerAccountId).toBe(calendarGrant().accountId); expect(row.providerAccountId).not.toBe(a.userId); expect(row.grantedScopes).toEqual(calendarGrant().scopes);
  const storedText = JSON.stringify(await pool.query("SELECT row_to_json(c) AS data FROM google_calendar_connection c")); for (const marker of ["fixture-unit-access", "fixture-unit-refresh", "fixture-db-code", "fixture-unit-verifier"]) expect(storedText).not.toContain(marker);
  expect(JSON.parse(calendarCipher().decrypt(row.encryptedCredentials!, `google:${a.userId}:${row.id}`))).toEqual(calendarGrant()); const consumed = (await db.select().from(calendarOAuthFlow))[0]; expect(consumed.encryptedVerifier).toBeNull(); expect(consumed.result).toBe("success");
});
it("same callback concurrent retries exchange once and return one owned active connection", async () => { const auth = await service.start(a); const input = { state: new URL(auth.url).searchParams.get("state"), code: "fixture-db-code", denied: false }; expect(await Promise.all([service.callback(a, input), service.callback(a, input)])).toEqual(["success", "success"]); expect(provider.exchange).toHaveBeenCalledTimes(1); expect(await db.select().from(calendarConnection)).toHaveLength(1); });
it("reconnect repairs same identity and preserves selection; account switch clears it", async () => { const first = await configured(); const next = await connect(); expect(next.connection.id).toBe(first.id); expect(next.connection.selectedCalendarIds).toEqual(first.selectedCalendarIds); provider.exchange.mockResolvedValueOnce({ ...calendarGrant(), accountId: "different-subject" }); const switched = await connect(); expect(switched.connection.id).toBe(first.id); expect(switched.connection.selectedCalendarIds).toEqual([]); expect(await db.select().from(calendarConnection)).toHaveLength(1); });
it("persists explicit primary-free selection and availability through a new repository/service instance", async () => { const { connection } = await connect(); const listed = await service.refreshCalendars(a, connection.id); expect(listed.selectedCalendarIds).toEqual([]); const selected = await service.select(a, connection.id, { expectedVersion: listed.version, calendarIds: ["personal"] }); const result = await service.refreshAvailability(a, connection.id, week); const restarted = calendarService(calendarRepository(db, pool), provider, calendarCipher(), () => new Date(calendarClock)); expect((await restarted.workspace(a)).connection).toEqual(selected); expect((await restarted.workspace(a)).availability).toEqual(result); });
it("competing different selections from one version have exactly one winner", async () => { const value = await configured(); const results = await Promise.allSettled([service.select(a, value.id, { expectedVersion: value.version, calendarIds: ["work"] }), service.select(a, value.id, { expectedVersion: value.version, calendarIds: ["personal"] })]); expect(results.filter(v => v.status === "fulfilled")).toHaveLength(1); const rejected = results.find(v => v.status === "rejected"); expect(rejected && rejected.status === "rejected" && rejected.reason).toMatchObject({ code: "CONFLICT", details: { kind: "CALENDAR_VERSION" } }); });
it("repeated identical selection is a no-op; new selection invalidates every old cache", async () => { const value = await configured(); await service.refreshAvailability(a, value.id, week); const command = { expectedVersion: value.version, calendarIds: ["work"] }; const selected = await service.select(a, value.id, command); expect(await service.select(a, value.id, command)).toEqual(selected); expect(await db.select().from(calendarAvailabilityCache)).toEqual([]); expect((await service.workspace(a)).availability?.totalBusyMinutes).toBeNull(); });
it.each(["incomplete", "unavailable"] as const)("%s preserves complete snapshot and fetch time across rereads", async kind => { const value = await configured(); const good = await service.refreshAvailability(a, value.id, week); provider.queryBusyIntervals.mockRejectedValueOnce(new ProviderFailure(kind)); const failed = await service.refreshAvailability(a, value.id, week); expect(failed.status).toBe("stale"); expect(failed.fetchedAt).toBe(good.fetchedAt); expect(failed.intervals).toEqual(good.intervals); expect((await service.workspace(a)).availability).toEqual(failed); });
it("revoked refresh transitions into attention state without deleting prior complete timing", async () => { const value = await configured(); await service.refreshAvailability(a, value.id, week); provider.refresh.mockRejectedValueOnce(new ProviderFailure("reauthorization_required")); const later = calendarService(repository, provider, calendarCipher(), () => new Date(calendarGrant().expiresAt)); const stale = await later.refreshAvailability(a, value.id, week); expect(stale.status).toBe("stale"); expect((await later.workspace(a)).connection?.state).toBe("reauthorization_required"); await later.refreshAvailability(a, value.id, week); expect(provider.refresh).toHaveBeenCalledTimes(1); });
it("disconnect erases all secrets, pending flow, selection and cache despite revocation failure; repeat safe", async () => { const value = await configured(); await service.refreshAvailability(a, value.id, week); await service.start(a); provider.revoke.mockRejectedValueOnce(new Error("fixture-provider-unavailable")); const result = await service.disconnect(a, value.id); expect(result.revocationConfirmed).toBe(false); const [row] = await db.select().from(calendarConnection); expect(row.state).toBe("disconnected"); expect(row.encryptedCredentials).toBeNull(); expect(row.accessExpiresAt).toBeNull(); expect(row.grantedScopes).toEqual([]); expect(row.calendars).toEqual([]); expect(row.selectedCalendarIds).toEqual([]); expect(await db.select().from(calendarAvailabilityCache)).toEqual([]); expect(await db.select().from(calendarOAuthFlow)).toEqual([]); expect((await service.disconnect(a, value.id)).connection).toEqual(result.connection); });
it("owner lock prevents an in-flight refresh from restoring cache after disconnect", async () => { const value = await configured(); let release!: () => void; let started!: () => void; const ready = new Promise<void>(resolve => { started = resolve; }); provider.queryBusyIntervals.mockImplementationOnce(async () => { started(); await new Promise<void>(resolve => { release = resolve; }); return []; }); const refresh = service.refreshAvailability(a, value.id, week); await ready; const disconnected = service.disconnect(a, value.id); release(); await refresh; await disconnected; expect(await db.select().from(calendarAvailabilityCache)).toEqual([]); expect((await service.workspace(a)).connection?.state).toBe("disconnected"); });
it("selection waits for old in-flight query and removes its obsolete snapshot", async () => { const value = await configured(); let release!: () => void; let started!: () => void; const ready = new Promise<void>(resolve => { started = resolve; }); provider.queryBusyIntervals.mockImplementationOnce(async () => { started(); await new Promise<void>(resolve => { release = resolve; }); return []; }); const refresh = service.refreshAvailability(a, value.id, week); await ready; const selection = service.select(a, value.id, { expectedVersion: value.version, calendarIds: ["work"] }); release(); await refresh; await selection; expect(await db.select().from(calendarAvailabilityCache)).toEqual([]); expect((await service.workspace(a)).connection?.selectedCalendarIds).toEqual(["work"]); });
it("foreign and missing IDs are indistinguishable and never use another owner's credentials", async () => { const value = await configured(); const calls = provider.listCalendars.mock.calls.length; for (const id of [value.id, randomUUID()]) for (const work of [() => service.workspace(b, undefined, id), () => service.refreshCalendars(b, id), () => service.select(b, id, { expectedVersion: 1, calendarIds: [] }), () => service.refreshAvailability(b, id, week), () => service.disconnect(b, id)]) await expect(work()).rejects.toMatchObject({ code: "NOT_FOUND", message: "This Calendar connection is unavailable." }); expect(provider.listCalendars).toHaveBeenCalledTimes(calls); expect(provider.revoke).not.toHaveBeenCalled(); expect((await service.workspace(b)).connection).toBeNull(); });
it("migration constraints enforce owned cache, single connection, lifecycle and selection bound", async () => { const value = await configured(); await service.refreshAvailability(a, value.id, week); const [row] = await db.select().from(calendarConnection), [cache] = await db.select().from(calendarAvailabilityCache);
  await expect(db.insert(calendarConnection).values({ ...row, id: randomUUID() })).rejects.toThrow(); await expect(db.update(calendarConnection).set({ state: "disconnected" }).where(eq(calendarConnection.id, value.id))).rejects.toThrow(); await expect(db.update(calendarConnection).set({ selectedCalendarIds: Array.from({ length: 51 }, (_, i) => String(i)) }).where(eq(calendarConnection.id, value.id))).rejects.toThrow(); await expect(db.insert(calendarAvailabilityCache).values({ ...cache, ownerId: b.userId, weekStartDate: "2026-10-05" })).rejects.toThrow(); });
it("failed atomic OAuth completion rolls back connection metadata and cache removal", async () => { const value = await configured(); await service.refreshAvailability(a, value.id, week); const beforeRows = await db.select().from(calendarConnection), beforeCache = await db.select().from(calendarAvailabilityCache); await service.start(a); const [flow] = await db.select().from(calendarOAuthFlow); await expect(repository.locked(a.userId, async store => store.complete({ ...beforeRows[0], version: 99 }, { ...flow, encryptedVerifier: null, result: null }))).rejects.toMatchObject({ code: "DATABASE_UNAVAILABLE" }); expect(await db.select().from(calendarConnection)).toEqual(beforeRows); expect(await db.select().from(calendarAvailabilityCache)).toEqual(beforeCache); });
it("all Calendar operations leave Goals/Milestones/Actions/Drafts/baselines/Amendments and receipts byte-for-byte unchanged", async () => {
  const goals = goalService(goalRepository(db)), milestones = milestoneService(milestoneRepository(db)), actions = actionService(actionRepository(db)), plans = planService(planRepository(db), () => calendarClock.toISOString()), amendments = amendmentService(amendmentRepository(db), () => calendarClock.toISOString());
  const goal = await goals.createGoal(a, { mutationId: randomUUID(), title: "Calendar facts inform my manual decision", outcome: "I deliberately protect breathing room." }); const milestone = await milestones.createMilestone(a, goal.id, { mutationId: randomUUID(), title: "Useful planning", successCondition: "The manual plan stays intact." }); const action = await actions.createAction(a, goal.id, { mutationId: randomUUID(), title: "Build a useful loop", milestoneId: milestone.id, estimateMinutes: 240 });
  const draft = await plans.create(a, { mutationId: randomUUID(), weekStartDate: "2026-10-05", provisionalCapacityMinutes: 720, reserveMinutes: 180 }); const selected = (await plans.candidates(a)).find(v => v.actionId === action.id)!; const saved = await plans.save(a, draft.id, { mutationId: randomUUID(), expectedVersion: draft.version, provisionalCapacityMinutes: 720, reserveMinutes: 180, commitments: [{ actionId: action.id, source: selected.source, budgetMinutes: 390 }] }); const baseline = await plans.commit(a, saved.id, { mutationId: randomUUID(), expectedVersion: saved.version }); await amendments.confirm(a, baseline.id, { mutationId: randomUUID(), expectedVersion: baseline.version, provisionalCapacityMinutes: 600, reserveMinutes: 120, reason: "Protect room deliberately", commitments: [{ actionId: action.id, budgetMinutes: 390 }] }); await plans.create(a, { mutationId: randomUUID(), weekStartDate: "2026-10-12", provisionalCapacityMinutes: 720, reserveMinutes: 180 });
  const snapshot = async () => { const values: Record<string, unknown> = {}; for (const table of ["goal", "milestone", "action", "weekly_plan", "weekly_commitment", "weekly_plan_amendment", "amendment_commitment", "mutation_receipt"]) values[table] = (await pool.query(`SELECT row_to_json(t) AS data FROM ${table} t WHERE owner_id=$1 ORDER BY row_to_json(t)::text`, [a.userId])).rows; return JSON.stringify(values); };
  const before = await snapshot(); const value = await configured(); await service.refreshAvailability(a, value.id, week); provider.queryBusyIntervals.mockRejectedValueOnce(new ProviderFailure("incomplete")); await service.refreshAvailability(a, value.id, week); await service.refreshCalendars(a, value.id); const fresh = (await service.workspace(a)).connection!; await service.select(a, value.id, { expectedVersion: fresh.version, calendarIds: ["work"] }); await connect(); await service.disconnect(a, value.id); expect(await snapshot()).toBe(before);
});
