import {beforeAll,beforeEach,afterAll,afterEach,it,expect} from 'vitest';
import {randomUUID,randomBytes} from 'node:crypto';
import {migrate} from 'drizzle-orm/node-postgres/migrator';
import {connectDatabase} from '../../src/db/connect';
import {requireTestDatabaseURL} from '../../scripts/test-database';
import {provisionLocalUser} from '../../scripts/local-user';
import {chatGPTRepository} from '../../src/modules/chatgpt/repository';
import {chatGPTService} from '../../src/modules/chatgpt/service';
import {credentialCipher} from '../../src/modules/calendar/encryption';
import {chatGPTOAuth} from '../../src/providers/chatgpt/oauth';
import {startChatGPTFixture} from '../chatgpt-provider-fixture';
const database=connectDatabase(requireTestDatabaseURL().url),{db,pool}=database,cipher=credentialCipher({qa:randomBytes(32).toString('base64')},'qa');
let fixture:Awaited<ReturnType<typeof startChatGPTFixture>>,actor={userId:''},other={userId:''},now='2026-10-03T09:00:00Z';const clock=()=>now;
const repository=chatGPTRepository(db,pool),service=()=>chatGPTService({repository,cipher,oauth:chatGPTOAuth({testOrigin:fixture.origin,clock}),host:async()=> 'urn:uuid:stable-fixture-host',redirectUri:'http://127.0.0.1:3100/auth/chatgpt/callback',clock});
beforeAll(async()=>{await migrate(db,{migrationsFolder:'src/db/migrations'});fixture=await startChatGPTFixture(clock);});beforeEach(async()=>{now='2026-10-03T09:00:00Z';await fixture.control({mode:'useful',clientId:'oaiapp_fixture',subject:'chatgpt-subject'});actor={userId:(await provisionLocalUser(db,{email:`chatgpt-${randomUUID()}@example.test`,password:'Disposable-ChatGPT-Tests!',name:'ChatGPT test',timezone:'Europe/London'})).id};other={userId:(await provisionLocalUser(db,{email:`chatgpt-other-${randomUUID()}@example.test`,password:'Disposable-ChatGPT-Tests!',name:'Other',timezone:'Europe/London'})).id};});
afterEach(async()=>{for(const table of ['chatgpt_oauth_flow','chatgpt_connection'])await pool.query(`DELETE FROM ${table} WHERE owner_id=ANY($1)`,[[actor.userId,other.userId]]);await pool.query('DELETE FROM app_user WHERE id=ANY($1)',[[actor.userId,other.userId]]);});afterAll(async()=>{await fixture.close();await pool.end();});
async function begin(id:string|null=null){const a=await service().start(actor,{connectionId:id});const u=await fixture.authorize(a.url);return {url:new URL(a.url),input:{state:u.searchParams.get('state'),code:u.searchParams.get('code'),clientId:u.searchParams.get('client_id'),denied:false}};}
async function connected(mode='useful'){await fixture.control({mode});const a=await begin();expect(await service().callback(actor,a.input)).toBe(mode==='no_permission'?'permission_disabled':'success');return (await service().workspace(actor)).connections.find(c=>c.active)!;}
async function enabled(mode='useful'){let c=await connected(mode);c=await service().refreshModels(actor,c.id);return service().update(actor,c.id,{expectedVersion:c.version,selectedModel:'fixture-openai',useForCoaching:true});}
it('state/PKCE/nonce encrypted, wrong/foreign state cannot consume; callback one-time only',async()=>{const a=await begin(),row=(await pool.query('SELECT * FROM chatgpt_oauth_flow WHERE owner_id=$1',[actor.userId])).rows[0];expect(JSON.stringify(row)).not.toContain(a.input.state);expect(JSON.stringify(row)).not.toContain(a.url.searchParams.get('nonce'));expect(await service().callback(other,a.input)).toBe('failed');expect(await service().callback(actor,{...a.input,state:'wrong'})).toBe('failed');expect(await service().callback(actor,a.input)).toBe('success');expect(await service().callback(actor,a.input)).toBe('failed');expect((await pool.query('SELECT encrypted_attempt,consumed_at FROM chatgpt_oauth_flow WHERE owner_id=$1',[actor.userId])).rows[0]).toMatchObject({encrypted_attempt:null});});
it('expired, denied and incomplete registration callbacks never exchange',async()=>{const count=(await fixture.control()).exchangeCount;let a=await begin();now='2026-10-03T09:11:00Z';expect(await service().callback(actor,a.input)).toBe('failed');a=await begin();expect(await service().callback(actor,{...a.input,denied:true})).toBe('cancelled');a=await begin();expect(await service().callback(actor,{...a.input,clientId:null})).toBe('failed');expect((await fixture.control()).exchangeCount).toBe(count);});
it('issued client ID is durable before failed exchange and reused; mismatched client/subject reconnect rejected',async()=>{await fixture.control({mode:'wrong_nonce'});const a=await begin();expect(await service().callback(actor,a.input)).toBe('failed');let c=(await service().workspace(actor)).connections[0];expect(c).toMatchObject({clientId:'oaiapp_fixture',subject:null,status:'pending'});await fixture.control({mode:'useful'});let b=await begin(c.id);expect(b.url.searchParams.get('client_id')).toBe('oaiapp_fixture');expect(b.url.searchParams.has('agent_name_hint')).toBe(false);expect(await service().callback(actor,{...b.input,clientId:'oaiapp_unexpected'})).toBe('failed');b=await begin(c.id);expect(await service().callback(actor,b.input)).toBe('success');c=(await service().workspace(actor)).connections[0];await fixture.control({subject:'different-subject'});b=await begin(c.id);expect(await service().callback(actor,b.input)).toBe('failed');expect((await service().workspace(actor)).connections[0].subject).toBe('chatgpt-subject');});
it('identity without plan usage is connected, cannot discover/use models or invoke inference',async()=>{const c=await connected('no_permission'),count=(await fixture.control()).responseCount;expect(c.status).toBe('connected');await expect(service().refreshModels(actor,c.id)).rejects.toMatchObject({kind:'authentication'});await expect(service().update(actor,c.id,{expectedVersion:c.version,useForCoaching:true})).rejects.toMatchObject({code:'CONFLICT'});expect((await fixture.control()).responseCount).toBe(count);});
it('encrypted credentials survive another repository; DTO never exposes token/nonce/expiry ciphertext',async()=>{const c=await enabled();const row=(await pool.query('SELECT * FROM chatgpt_connection WHERE id=$1',[c.id])).rows[0];expect(row.encrypted_credentials).toMatch(/^v1.qa./);expect(JSON.stringify(row)).not.toContain('access-fixture-secret');expect(JSON.stringify(c)).not.toContain('encryptedCredentials');expect(cipher.decrypt(row.encrypted_credentials,`chatgpt:${actor.userId}:${c.id}:credentials`)).toContain('access-fixture-secret');expect(()=>cipher.decrypt(row.encrypted_credentials,`chatgpt:${other.userId}:${c.id}:credentials`)).toThrow();const another=connectDatabase(requireTestDatabaseURL().url);try{expect((await chatGPTRepository(another.db,another.pool).read(actor.userId,s=>s.get(c.id)))?.selectedModel).toBe('fixture-openai');}finally{await another.pool.end();}});
it('catalog display names, explicit model selection and no fabricated model accepted',async()=>{const c=await connected();await expect(service().update(actor,c.id,{expectedVersion:c.version,selectedModel:'invented'})).rejects.toMatchObject({code:'VALIDATION'});const m=await service().refreshModels(actor,c.id);expect(m.models.map(v=>v.slug)).toEqual(['fixture-openai','fixture-alternate']);expect(m.selectedModel).toBeNull();const saved=await service().update(actor,c.id,{expectedVersion:m.version,selectedModel:'fixture-alternate'});expect(saved.selectedModel).toBe('fixture-alternate');expect(saved.useForCoaching).toBe(false);});
it('foreign registrations cannot be read, reconnected, updated, used, or disconnected',async()=>{const c=await enabled();expect((await service().workspace(other)).connections).toEqual([]);for(const operation of [()=>service().start(other,{connectionId:c.id}),()=>service().refreshModels(other,c.id),()=>service().update(other,c.id,{expectedVersion:c.version,selectedModel:'fixture-openai'}),()=>service().credential(other,c.id,'fixture-openai'),()=>service().disconnect(other,c.id,{expectedVersion:c.version})])await expect(operation()).rejects.toMatchObject({code:'NOT_FOUND'});});
it('same email across registrations/workspaces retains distinct subject/client rows and one active registration',async()=>{const first=await connected();await fixture.control({clientId:'oaiapp_second'});const second=await connected();const all=(await service().workspace(actor)).connections;expect(all).toHaveLength(2);expect(first.email).toBe(second.email);expect(first.id).not.toBe(second.id);expect(all.filter(c=>c.active)).toHaveLength(1);expect(all.find(c=>c.id===first.id)?.status).toBe('connected');});
it('expired token refreshes once across independent PostgreSQL services; rotating replacement and model survive',async()=>{const c=await enabled('short_expiry'),before=(await fixture.control()).refreshCount;await fixture.control({mode:'useful'});const another=connectDatabase(requireTestDatabaseURL().url);try{const service2=chatGPTService({repository:chatGPTRepository(another.db,another.pool),cipher,oauth:chatGPTOAuth({testOrigin:fixture.origin,clock}),host:async()=> 'host',redirectUri:'http://127.0.0.1:3100/auth/chatgpt/callback',clock});await Promise.all([service().credential(actor,c.id,'fixture-openai'),service2.credential(actor,c.id,'fixture-openai'),service().credential(actor,c.id,'fixture-openai')]);expect((await fixture.control()).refreshCount).toBe(before+1);const row=(await pool.query('SELECT encrypted_credentials FROM chatgpt_connection WHERE id=$1',[c.id])).rows[0];const tokens=JSON.parse(cipher.decrypt(row.encrypted_credentials,`chatgpt:${actor.userId}:${c.id}:credentials`));expect(tokens.refreshToken).toMatch(/^refresh-fixture-/);expect(Date.parse(tokens.expiresAt)).toBeGreaterThan(Date.parse(now));expect((await service().workspace(actor)).connections[0].selectedModel).toBe('fixture-openai');}finally{await another.pool.end();}});
it('terminal refresh clears dead credentials once, requires reconnect and never retries the dead token',async()=>{const c=await enabled(),before=(await fixture.control()).refreshCount;now='2026-10-03T10:01:00Z';await fixture.control({mode:'refresh_terminal'});await expect(service().credential(actor,c.id,'fixture-openai')).rejects.toMatchObject({kind:'terminal_refresh'});await expect(service().credential(actor,c.id,'fixture-openai')).rejects.toMatchObject({kind:'authentication'});expect((await fixture.control()).refreshCount).toBe(before+1);expect((await service().workspace(actor)).connections[0]).toMatchObject({status:'needs_sign_in',useForCoaching:true});expect((await pool.query('SELECT encrypted_credentials FROM chatgpt_connection WHERE id=$1',[c.id])).rows[0].encrypted_credentials).toBeNull();});
it('temporary refresh failure keeps credentials and connection usable for recovery',async()=>{const c=await enabled(),before=(await pool.query('SELECT encrypted_credentials FROM chatgpt_connection WHERE id=$1',[c.id])).rows[0];now='2026-10-03T10:01:00Z';await fixture.control({mode:'refresh_temporary'});await expect(service().credential(actor,c.id,'fixture-openai')).rejects.toMatchObject({kind:'temporary'});expect((await pool.query('SELECT encrypted_credentials FROM chatgpt_connection WHERE id=$1',[c.id])).rows[0]).toEqual(before);await fixture.control({mode:'useful'});expect(await service().credential(actor,c.id,'fixture-openai')).toBe('access-fixture-secret');});
it('disconnect clears tokens before remote revoke; failure is explicit; reconnect reuses registration and model',async()=>{let c=await enabled();await fixture.control({mode:'revoke_failure'});c=await service().disconnect(actor,c.id,{expectedVersion:c.version});expect(c).toMatchObject({status:'disconnected',revocationConfirmed:false,selectedModel:'fixture-openai',useForCoaching:false});await expect(service().credential(actor,c.id,'fixture-openai')).rejects.toMatchObject({kind:'authentication'});await fixture.control({mode:'useful'});const b=await begin(c.id);expect(b.url.searchParams.get('client_id')).toBe(c.clientId);expect(await service().callback(actor,b.input)).toBe('success');expect((await service().workspace(actor)).connections[0]).toMatchObject({id:c.id,selectedModel:'fixture-openai',models:[],status:'connected'});});
it('disconnect invalidates an outstanding authorization transaction',async()=>{const c=await enabled(),b=await begin(c.id);await service().disconnect(actor,c.id,{expectedVersion:c.version});expect(await service().callback(actor,b.input)).toBe('failed');});
