import {afterAll,afterEach,beforeAll,beforeEach,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {migrate} from 'drizzle-orm/node-postgres/migrator';
import {connectDatabase} from '../../src/db/connect';
import {cycleRepository} from '../../src/modules/focus-cycles/repository';
import {cycleService} from '../../src/modules/focus-cycles/service';
import {goalRepository} from '../../src/modules/goals/repository';
import {goalService} from '../../src/modules/goals/service';
import {provisionLocalUser} from '../../scripts/local-user';
import {requireTestDatabaseURL} from '../../scripts/test-database';
import {weeklyFixture} from '../weekly-review-fixture';
const database=connectDatabase(requireTestDatabaseURL().url),{db,pool}=database;
let actor={userId:''},other={userId:''},now='2026-10-03T09:00:00.000Z';const cycles=cycleService(cycleRepository(db),()=>now),goals=goalService(goalRepository(db),()=>now);
const command=(overrides={})=>({mutationId:randomUUID(),title:'Oct–Nov: make room for useful work',intent:'A bounded horizon',startDate:'2026-10-01',endDate:'2026-11-30',goals:[],...overrides});
const version=(n:number)=>({mutationId:randomUUID(),expectedVersion:n});
async function makeGoal(a=actor){return goals.createGoal(a,{mutationId:randomUUID(),title:'A useful outcome',outcome:'Usable every week'});}
async function draft(){const g=await makeGoal();return cycles.create(actor,command({goals:[{goalId:g.id,goalVersion:g.version}]}));}
beforeAll(async()=>{await migrate(db,{migrationsFolder:'src/db/migrations'});});
beforeEach(async()=>{now='2026-10-03T09:00:00.000Z';actor={userId:(await provisionLocalUser(db,{email:`cycles-${randomUUID()}@example.test`,password:'Disposable-Cycle-Tests!',name:'Cycle tests',timezone:'Europe/London'})).id};other={userId:(await provisionLocalUser(db,{email:`cycles-${randomUUID()}@example.test`,password:'Disposable-Cycle-Tests!',name:'Other cycle tests',timezone:'Europe/London'})).id};});
afterEach(async()=>{for(const table of ['focus_cycle_goal','focus_cycle','weekly_review_decision','weekly_review','daily_reflection','focus_session','time_block','amendment_commitment','weekly_plan_amendment','commitment_identity','weekly_commitment','weekly_plan','action','milestone','goal','mutation_receipt'])await pool.query(`DELETE FROM ${table} WHERE owner_id=ANY($1)`,[[actor.userId,other.userId]]);await pool.query("DELETE FROM app_user WHERE id=ANY($1)",[[actor.userId,other.userId]]);});afterAll(()=>pool.end());
it('migration is repeatable; empty workspace and Draft metadata persist without leaking owner',async()=>{await migrate(db,{migrationsFolder:'src/db/migrations'});expect((await cycles.workspace(actor)).current).toBeNull();const c=await cycles.create(actor,command());expect(c).toMatchObject({status:'draft',version:1,intent:'A bounded horizon'});expect(c).not.toHaveProperty('ownerId');expect((await cycles.workspace(actor)).cycles).toEqual([c]);});
it('select, activate, remove a Goal and finish preserve Goal lifecycle/versions',async()=>{const c=await draft(),g=c.goals[0],before=await goals.getGoal(actor,g.goalId),active=await cycles.transition(actor,c.id,'activate',version(1));expect((await cycles.workspace(actor)).current?.id).toBe(c.id);const edited=await cycles.update(actor,c.id,{...command({goals:[]}),expectedVersion:2});expect(edited.goals).toEqual([]);expect(await goals.getGoal(actor,g.goalId)).toEqual(before);const final=await cycles.transition(actor,c.id,'finish',version(3));expect(final.status).toBe('finished');expect(active.status).toBe('active');expect((await cycles.workspace(actor)).current).toBeNull();});
it('concurrent Active cycles have one winner, including shared Goal membership',async()=>{const c=await draft(),d=await cycles.create(actor,command({goals:c.goals.map(g=>({goalId:g.goalId,goalVersion:g.goalVersion}))}));const results=await Promise.allSettled([cycles.transition(actor,c.id,'activate',version(1)),cycles.transition(actor,d.id,'activate',version(1))]);expect(results.filter(r=>r.status==='fulfilled')).toHaveLength(1);expect((await cycles.workspace(actor)).cycles.filter(c=>c.status==='active')).toHaveLength(1);});
it('concurrent updates use explicit aggregate version, one winner',async()=>{const c=await draft();const r=await Promise.allSettled(['first','second'].map(title=>cycles.update(actor,c.id,{...command({title,goals:c.goals.map(g=>({goalId:g.goalId,goalVersion:g.goalVersion}))}),expectedVersion:1})));expect(r.filter(v=>v.status==='fulfilled')).toHaveLength(1);expect((await cycles.workspace(actor)).cycles[0].version).toBe(2);});
it('duplicate create and lifecycle retries return exact original snapshots after finish/archive and new connection',async()=>{const g=await makeGoal(),input=command({goals:[{goalId:g.id,goalVersion:1}]}),created=await Promise.all(Array.from({length:5},()=>cycles.create(actor,input)));expect(created).toEqual(Array(5).fill(created[0]));const c=created[0],activate=version(1),a=await cycles.transition(actor,c.id,'activate',activate),finish=version(2),f=await cycles.transition(actor,c.id,'finish',finish);await cycles.transition(actor,c.id,'archive',version(3));const newDB=connectDatabase(requireTestDatabaseURL().url);try{const service=cycleService(cycleRepository(newDB.db),()=>now);expect(await service.create(actor,input)).toEqual(c);expect(await service.transition(actor,c.id,'activate',activate)).toEqual(a);expect(await service.transition(actor,c.id,'finish',finish)).toEqual(f);}finally{await newDB.pool.end();}await expect(cycles.create(actor,{...input,title:'changed'})).rejects.toMatchObject({details:{kind:'MUTATION_ID'}});});
it('ownership and strict payload prevent foreign membership and foreign/missing cycles equally',async()=>{const c=await draft(),foreign=await makeGoal(other);await expect(cycles.create(actor,command({goals:[{goalId:foreign.id,goalVersion:1}]}))).rejects.toMatchObject({code:'NOT_FOUND'});for(const id of [c.id,randomUUID()])await expect(cycles.transition(other,id,'archive',version(1))).rejects.toMatchObject({code:'NOT_FOUND',message:'This Focus Cycle is unavailable.'});expect((await cycles.workspace(other)).cycles).toEqual([]);await expect(cycles.create(actor,command({ownerId:other.userId}))).rejects.toMatchObject({code:'VALIDATION'});});
it('edited/archived Goal selections reject atomically; no successful receipt or partial membership',async()=>{const g=await makeGoal(),c=await cycles.create(actor,command());await goals.updateGoal(actor,g.id,{mutationId:randomUUID(),expectedVersion:1,title:'New',outcome:'New outcome'});const bad={...command({goals:[{goalId:g.id,goalVersion:1}]}),expectedVersion:1};await expect(cycles.update(actor,c.id,bad)).rejects.toMatchObject({details:{kind:'CYCLE_GOAL'}});expect((await cycles.workspace(actor)).cycles[0]).toEqual(c);expect((await pool.query('SELECT * FROM mutation_receipt WHERE mutation_id=$1',[bad.mutationId])).rows).toEqual([]);await goals.archiveGoal(actor,g.id,version(2));await expect(cycles.update(actor,c.id,{...bad,mutationId:randomUUID(),goals:[{goalId:g.id,goalVersion:3}]})).rejects.toMatchObject({details:{kind:'CYCLE_GOAL'}});});
it('archiving a Goal keeps membership context separate until explicitly removed',async()=>{const c=await draft();await cycles.transition(actor,c.id,'activate',version(1));await goals.archiveGoal(actor,c.goals[0].goalId,version(1));const v=await cycles.workspace(actor);expect(v.current?.goals[0].archivedAt).not.toBeNull();expect(v.current?.status).toBe('active');await cycles.update(actor,c.id,{...command(),expectedVersion:2});expect((await cycles.workspace(actor)).current?.goals).toEqual([]);});
it('finished Goal context stays frozen while live Goal titles change; archive retains it',async()=>{const c=await draft();await cycles.transition(actor,c.id,'activate',version(1));const f=await cycles.transition(actor,c.id,'finish',version(2));await goals.updateGoal(actor,c.goals[0].goalId,{mutationId:randomUUID(),expectedVersion:1,title:'A changed Goal',outcome:'New outcome'});expect((await cycles.workspace(actor)).cycles[0].goals).toEqual(f.goals);const archived=await cycles.transition(actor,c.id,'archive',version(3));expect(archived.goals).toEqual(f.goals);await expect(cycles.update(actor,c.id,{...command(),expectedVersion:4})).rejects.toMatchObject({details:{kind:'CYCLE_TERMINAL'}});await expect(pool.query("UPDATE focus_cycle SET title='Tampered',version=version+1 WHERE id=$1",[c.id])).rejects.toThrow();await expect(pool.query("UPDATE focus_cycle_goal SET snapshot=snapshot || '{\"title\":\"Tampered\"}' WHERE cycle_id=$1",[c.id])).rejects.toThrow();});
it('inclusive dates use owned timezone, expiration is read-only projection, explicit finish remains possible',async()=>{const c=await draft();await cycles.transition(actor,c.id,'activate',version(1));now='2026-11-30T23:59:00.000Z';expect((await cycles.workspace(actor)).current?.id).toBe(c.id);now='2026-12-01T00:00:00.000Z';expect((await cycles.workspace(actor)).current).toBeNull();expect((await cycles.workspace(actor)).cycles[0].status).toBe('active');await expect(cycles.transition(actor,(await cycles.create(actor,command())).id,'activate',version(1))).rejects.toMatchObject({code:'CONFLICT'});await cycles.transition(actor,c.id,'finish',version(2));expect((await goals.getGoal(actor,c.goals[0].goalId)).archivedAt).toBeNull();});
it('cannot activate empty, future or past Draft; Active date edits must cover today',async()=>{const empty=await cycles.create(actor,command());await expect(cycles.transition(actor,empty.id,'activate',version(1))).rejects.toMatchObject({code:'CONFLICT'});const c=await draft();now='2026-09-30T12:00Z';await expect(cycles.transition(actor,c.id,'activate',version(1))).rejects.toMatchObject({code:'CONFLICT'});now='2026-10-03T09:00Z';await cycles.transition(actor,c.id,'activate',version(1));await expect(cycles.update(actor,c.id,{...command({endDate:'2026-10-02'}),expectedVersion:2})).rejects.toMatchObject({details:{kind:'CYCLE_DATES'}});});
it('changing Focus Cycle membership cannot mutate immutable planning, blocks, execution or reflections',async()=>{const f=await weeklyFixture(db,actor);now=f.clock();const before:Record<string,unknown>={};const tables=['goal','milestone','action','weekly_plan','weekly_commitment','weekly_plan_amendment','amendment_commitment','time_block','focus_session','daily_reflection'];for(const t of tables)before[t]=(await pool.query(`SELECT row_to_json(t) FROM ${t} t WHERE owner_id=$1 ORDER BY row_to_json(t)::text`,[actor.userId])).rows;let c=await cycles.create(actor,command({goals:[{goalId:f.goal.id,goalVersion:1}]}));c=await cycles.transition(actor,c.id,'activate',version(1));c=await cycles.update(actor,c.id,{...command(),expectedVersion:c.version});await cycles.transition(actor,c.id,'finish',version(c.version));for(const t of tables)expect((await pool.query(`SELECT row_to_json(t) FROM ${t} t WHERE owner_id=$1 ORDER BY row_to_json(t)::text`,[actor.userId])).rows).toEqual(before[t]);});

it('database ownership references and one-Active index defend direct writes',async()=>{const c=await draft(),active=await cycles.transition(actor,c.id,'activate',version(1)),d=await cycles.create(actor,command({goals:c.goals.map(g=>({goalId:g.goalId,goalVersion:g.goalVersion}))}));await expect(pool.query("UPDATE focus_cycle SET status='active',activated_at=updated_at,version=2 WHERE id=$1",[d.id])).rejects.toThrow();const foreign=await makeGoal(other);await expect(pool.query('INSERT INTO focus_cycle_goal(owner_id,cycle_id,goal_id,snapshot) VALUES ($1,$2,$3,$4)',[actor.userId,d.id,foreign.id,JSON.stringify({goalId:foreign.id,goalVersion:1,title:foreign.title,outcome:foreign.outcome,archivedAt:null})])).rejects.toThrow();expect((await cycles.workspace(actor)).current?.id).toBe(active.id);});
it('current horizon uses User local date across timezone boundaries without rewriting authored dates',async()=>{now='2026-09-30T09:00:00.000Z';await pool.query("UPDATE app_user SET timezone='America/Los_Angeles' WHERE id=$1",[actor.userId]);const c=await draft();now='2026-10-01T00:30:00.000Z';expect((await cycles.workspace(actor)).today).toBe('2026-09-30');await expect(cycles.transition(actor,c.id,'activate',version(1))).rejects.toMatchObject({code:'CONFLICT'});now='2026-10-01T08:00:00.000Z';await cycles.transition(actor,c.id,'activate',version(1));await pool.query("UPDATE app_user SET timezone='Asia/Tokyo' WHERE id=$1",[actor.userId]);const v=await cycles.workspace(actor);expect(v.current?.startDate).toBe('2026-10-01');expect(v.timezone).toBe('Asia/Tokyo');});
