import {beforeAll,beforeEach,afterAll,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {eq,inArray} from 'drizzle-orm';
import {migrate} from 'drizzle-orm/node-postgres/migrator';
import {connectDatabase} from '../../src/db/connect';
import {user,goal,action,weeklyPlan,weeklyCommitment,weeklyPlanAmendment,amendmentCommitment,commitmentIdentity,timeBlock,focusSession,mutationReceipt,focusableHours,dailyReflection,weeklyReview,weeklyReviewDecision} from '../../src/db/schema';
import {requireTestDatabaseURL} from '../../scripts/test-database';
import {calendarTaskService} from '../../src/modules/calendar-tasks/service';
import {planService} from '../../src/modules/planning/service';
import {planRepository} from '../../src/modules/planning/repository';
import {unfinishedWeekTasks} from '../../src/modules/planning/unfinished';
import {readHabitProgress} from '../../src/modules/reviews/habit-repository';
const {db,pool}=connectDatabase(requireTestDatabaseURL().url),a={userId:randomUUID()},b={userId:randomUUID()};
let now='2027-12-27T08:00:00Z';const clock=()=>now,plans=planService(planRepository(db),clock),tasks=calendarTaskService(db,clock);
beforeAll(async()=>{await migrate(db,{migrationsFolder:'src/db/migrations'});for(const actor of [a,b])await db.insert(user).values({id:actor.userId,name:'Living week QA',email:`living-${actor.userId}@example.test`,timezone:'Europe/London'});});
beforeEach(async()=>{now='2027-12-27T08:00:00Z';for(const table of [weeklyReviewDecision,weeklyReview,dailyReflection,focusSession,timeBlock,amendmentCommitment,weeklyPlanAmendment,weeklyCommitment,commitmentIdentity,weeklyPlan,action,goal,mutationReceipt,focusableHours])await db.delete(table).where(inArray(table.ownerId,[a.userId,b.userId]));});
afterAll(()=>pool.end());
it('unfinished suggestions use the latest living list and live eligibility, respect explicit Defer, and never write a new week',async()=>{
 const previous=await plans.firstTask(a,{mutationId:randomUUID(),weekStartDate:'2027-12-27',title:'Reading',budgetMinutes:60}),c=previous.commitments[0];
 const edited=await tasks.change(a,previous.id,{kind:'budget',mutationId:randomUUID(),expectedVersion:2,commitmentId:c.id,delta:-30});
 const added=await tasks.change(a,previous.id,{kind:'add',mutationId:randomUUID(),expectedVersion:edited.version,title:'Write something',budgetMinutes:120});
 const candidates=await plans.candidates(a);
 expect(await unfinishedWeekTasks(db,a,'2028-01-03',candidates)).toEqual(expect.arrayContaining([expect.objectContaining({actionId:c.actionId,budgetMinutes:30}),expect.objectContaining({budgetMinutes:120})]));
 expect((await plans.workspace(a,'2028-01-03')).view).toBeNull();
 expect(await unfinishedWeekTasks(db,b,'2028-01-03',candidates)).toEqual([]);
 const reviewId=randomUUID();now='2028-01-03T08:00:00Z';await db.insert(weeklyReview).values({id:reviewId,ownerId:a.userId,planId:previous.id,status:'draft',note:'PRIVATE weekly text',version:1,createdAt:new Date(now),updatedAt:new Date(now),finalizedAt:null});
 await db.insert(weeklyReviewDecision).values({ownerId:a.userId,planId:previous.id,reviewId,commitmentId:c.id,actionId:c.actionId,kind:'defer',proposedBudgetMinutes:null,source:c.source});
 await db.update(weeklyReview).set({status:'finalized',version:2,finalizedAt:new Date(now)}).where(eq(weeklyReview.id,reviewId));
 const suggestions=await unfinishedWeekTasks(db,a,'2028-01-03',await plans.candidates(a));expect(suggestions).toHaveLength(1);expect(JSON.stringify(suggestions)).not.toContain('PRIVATE');
 const chosen=suggestions[0],input={mutationId:randomUUID(),weekStartDate:'2028-01-03',commitments:[chosen]};
 const next=await plans.quickCommit(a,input);expect(next.provisionalCapacityMinutes).toBe(160);expect(next.reserveMinutes).toBe(40);expect(next.commitments[0].actionId).toBe(chosen.actionId);expect(await plans.quickCommit(a,input)).toEqual(next);
 const second=added.commitments.find(v=>v.actionId===chosen.actionId)!;
 await db.update(action).set({state:'completed',completedAt:new Date(now),updatedAt:new Date(now),version:2}).where(eq(action.id,second.actionId));
 expect(await unfinishedWeekTasks(db,a,'2028-01-03',await plans.candidates(a))).toEqual([]);
});
it('habit reading stays owner-scoped and contains dates only, with no draft/future note leakage',async()=>{
 now='2028-01-03T08:00:00Z';const p=await plans.firstTask(a,{mutationId:randomUUID(),weekStartDate:'2028-01-03',title:'Focus',budgetMinutes:60}),c=p.commitments[0],blockId=randomUUID();
 await db.insert(timeBlock).values({id:blockId,ownerId:a.userId,planId:p.id,commitmentId:c.id,start:new Date('2028-01-03T06:00Z'),end:new Date('2028-01-03T07:00Z'),state:'planned',version:1,snapshot:c.snapshot!,createdAt:new Date('2028-01-03T05:00Z'),updatedAt:new Date('2028-01-03T05:00Z')});
 await db.insert(focusSession).values({id:randomUUID(),ownerId:a.userId,timeBlockId:blockId,startedAt:new Date('2028-01-03T06:00Z'),endedAt:new Date('2028-01-03T06:30Z'),outcome:'partial',endNote:'PRIVATE session',version:2,createdAt:new Date('2028-01-03T06:00Z'),updatedAt:new Date('2028-01-03T06:30Z')});
 for(const [date,status] of [['2028-01-02','finalized'],['2028-01-01','draft']] as const)await db.insert(dailyReflection).values({id:randomUUID(),ownerId:a.userId,localDate:date,status,note:'PRIVATE reflection',version:status==='finalized'?2:1,createdAt:new Date('2028-01-02T20:00Z'),updatedAt:new Date('2028-01-02T20:00Z'),finalizedAt:status==='finalized'?new Date('2028-01-02T20:00Z'):null});
 const result=await db.transaction(tx=>readHabitProgress(tx,a,'Europe/London',now));expect(result.current).toBe(2);expect(JSON.stringify(result)).not.toContain('PRIVATE');
 const other=await db.transaction(tx=>readHabitProgress(tx,b,'Europe/London',now));expect(other.current).toBe(0);
});
