import { afterAll,beforeAll,beforeEach,expect,it } from "vitest";
import { randomUUID } from "node:crypto";
import { eq,inArray } from "drizzle-orm";
import { readFile } from "node:fs/promises";
import { migrate } from "drizzle-orm/node-postgres/migrator";
import { connectDatabase } from "../../src/db/connect";
import { weeklyReviewDecision, weeklyReview, dailyReflection, focusSession, timeBlock,commitmentIdentity,weeklyPlan,weeklyCommitment,weeklyPlanAmendment,amendmentCommitment,action,goal,milestone,mutationReceipt,user,focusableHours,calendarAvailabilityCache,calendarOAuthFlow,calendarConnection } from "../../src/db/schema";
import { goalService } from "../../src/modules/goals/service";
import { goalRepository } from "../../src/modules/goals/repository";
import { actionService } from "../../src/modules/actions/service";
import { actionRepository } from "../../src/modules/actions/repository";
import { planService } from "../../src/modules/planning/service";
import { planRepository } from "../../src/modules/planning/repository";
import { amendmentService } from "../../src/modules/amendments/service";
import { amendmentRepository } from "../../src/modules/amendments/repository";
import {readCalendarProjection} from '../../src/modules/scheduling/calendar-reader';
import { schedulingService } from "../../src/modules/scheduling/service";
import { schedulingRepository } from "../../src/modules/scheduling/repository";
import { hoursService } from "../../src/modules/availability/service";
import { hoursRepository } from "../../src/modules/availability/repository";
import { calendarService } from "../../src/modules/calendar/service";
import { calendarRepository } from "../../src/modules/calendar/repository";
import { calendarCipher,fakeCalendar,calendarClock } from "../calendar-fixtures";
import { provisionLocalUser } from "../../scripts/local-user";
import { requireTestDatabaseURL } from "../../scripts/test-database";
import type { Actor } from "../../src/domain/actor";
import type { Placement,TimeBlock } from "../../src/modules/scheduling/domain";
const {db,pool}=connectDatabase(requireTestDatabaseURL().url),a={userId:""},b={userId:""},clock=()=>"2026-10-02T12:00:00.000Z";
const goals=goalService(goalRepository(db)),actions=actionService(actionRepository(db)),plans=planService(planRepository(db),clock),amends=amendmentService(amendmentRepository(db),clock),repo=schedulingRepository(db,()=>new Date(clock())),service=schedulingService(repo,clock);
beforeAll(async()=>{await migrate(db,{migrationsFolder:"src/db/migrations"});for(const [suffix,actor] of [["A",a],["B",b]] as const)actor.userId=(await provisionLocalUser(db,{email:process.env[`TEST_USER_${suffix}_EMAIL`],password:process.env[`TEST_USER_${suffix}_PASSWORD`],name:`Engineer ${suffix}`,timezone:"Europe/London"})).id;});
async function clean(){const owners=[a.userId,b.userId];for(const table of [weeklyReviewDecision,weeklyReview,dailyReflection,focusSession,timeBlock,commitmentIdentity,mutationReceipt,amendmentCommitment,weeklyPlanAmendment,weeklyCommitment,weeklyPlan,action,milestone,goal,focusableHours,calendarAvailabilityCache,calendarOAuthFlow,calendarConnection])await db.delete(table).where(inArray(table.ownerId,owners));await db.update(user).set({timezone:"Europe/London"}).where(inArray(user.id,owners));}
beforeEach(clean);afterAll(async()=>{await clean();await pool.end();});
async function fixture(actor:Actor=a,week="2026-10-05",withHours=true) {
  const g=await goals.createGoal(actor,{mutationId:randomUUID(),title:"A calmer useful week",outcome:"Protect meaningful work."});
  const act=await actions.createAction(actor,g.id,{mutationId:randomUUID(),title:"Build weekly planning UI",estimateMinutes:240,doneWhen:"The weekly flow is usable."});
  const source=(await plans.candidates(actor)).find(c=>c.actionId===act.id)!;
  let plan=await plans.create(actor,{mutationId:randomUUID(),weekStartDate:week,provisionalCapacityMinutes:720,reserveMinutes:180});
  plan=await plans.save(actor,plan.id,{mutationId:randomUUID(),expectedVersion:1,provisionalCapacityMinutes:720,reserveMinutes:180,commitments:[{actionId:act.id,source:source.source,budgetMinutes:180}]});
  const draft=plan;plan=await plans.commit(actor,plan.id,{mutationId:randomUUID(),expectedVersion:2});
  if(withHours)await hoursService(hoursRepository(db),clock).save(actor,{mutationId:randomUUID(),scheduleId:null,expectedVersion:0,windows:Array.from({length:5},(_,i)=>({weekday:i+1,startMinute:540,endMinute:1020}))});
  const placement={commitmentId:plan.commitments[0].id,date:week,startTime:"10:00",endTime:"11:30"};return {g,act,plan,draft,placement};
}
async function command(f:Awaited<ReturnType<typeof fixture>>,changes:Partial<Placement>={},actor:Actor=a){const placement={...f.placement,...changes},r=await service.preview(actor,f.plan.id,placement);return {...placement,mutationId:randomUUID(),expectedPlanVersion:r.planVersion,reviewKey:r.reviewKey,acknowledgeOutsideHours:false,acknowledgeBusy:false};}
async function create(f:Awaited<ReturnType<typeof fixture>>,changes:Partial<Placement>={}){return service.create(a,f.plan.id,await command(f,changes));}
async function editInput(f:Awaited<ReturnType<typeof fixture>>,block:TimeBlock,changes:Partial<Placement>={}){const {blockId:_id,...input}=await command(f,{blockId:block.id,expectedVersion:block.version,...changes});void _id;return input;}
async function amend(f:Awaited<ReturnType<typeof fixture>>,budgets:number[]){const h=await amends.history(a,f.plan.id);return amends.confirm(a,f.plan.id,{mutationId:randomUUID(),expectedVersion:h.baseline.version,provisionalCapacityMinutes:720,reserveMinutes:180,reason:"Reality changed deliberately",commitments:budgets.map(budgetMinutes=>({actionId:f.act.id,budgetMinutes,...(h.effective.commitments.some(c=>c.actionId===f.act.id)?{}:{source:f.plan.commitments[0].source})}))});}
async function winner(calls:Promise<TimeBlock>[]){const r=await Promise.allSettled(calls);expect(r.filter(v=>v.status==="fulfilled")).toHaveLength(1);const failed=r.find(v=>v.status==="rejected") as PromiseRejectedResult;expect(failed.reason).toMatchObject({code:"CONFLICT"});return (r.find(v=>v.status==="fulfilled") as PromiseFulfilledResult<TimeBlock>).value;}
async function planningRows(){const result:Record<string,unknown>={};for(const table of ["goal","action","weekly_plan","weekly_commitment","weekly_plan_amendment","amendment_commitment","focusable_hours"])result[table]=(await pool.query(`SELECT row_to_json(t) FROM ${table} t WHERE owner_id=$1 ORDER BY row_to_json(t)::text`,[a.userId])).rows;return result;}
it("migration reconstructs owned logical identity and block constraints; repeated migration is safe",async()=>{await migrate(db,{migrationsFolder:"src/db/migrations"});const f=await fixture(),first=await create(f),[row]=await db.select().from(timeBlock);expect(row.start.toISOString()).toBe("2026-10-05T09:00:00.000Z");expect(first.commitmentId).toBe(f.plan.commitments[0].id);for(const changes of [{ownerId:b.userId},{planId:randomUUID()},{commitmentId:randomUUID()},{version:0},{end:row.start},{state:"completed"},{state:"cancelled"},{updatedAt:new Date(0)}])await expect(db.insert(timeBlock).values({...row,id:randomUUID(),...changes} as typeof timeBlock.$inferInsert)).rejects.toThrow();});
it("create/edit/cancel preserve every planning/source/settings row and fresh connection reads persisted instants",async()=>{const f=await fixture(),before=await planningRows(),first=await create(f),input=await editInput(f,first,{startTime:"12:00",endTime:"13:30"}),edited=await service.edit(a,first.id,input);await service.cancel(a,first.id,{mutationId:randomUUID(),expectedVersion:2});expect(await planningRows()).toEqual(before);expect(await db.select().from(timeBlock)).toHaveLength(1);const other=connectDatabase(requireTestDatabaseURL().url);try{expect(await schedulingService(schedulingRepository(other.db),clock).get(a,first.id)).toMatchObject({state:"cancelled",version:3,start:edited.start,snapshot:first.snapshot});}finally{await other.pool.end();}});
for(const [startTime,endTime] of [["10:00","11:30"],["11:00","12:00"]])it(`concurrent ${startTime}-${endTime} overlap has exactly one winner and one success receipt`,async()=>{const f=await fixture(),x=await command(f),y=await command(f,{startTime,endTime});await winner([service.create(a,f.plan.id,x),service.create(a,f.plan.id,y)]);expect(await db.select().from(timeBlock)).toHaveLength(1);expect((await pool.query("SELECT 1 FROM mutation_receipt WHERE owner_id=$1 AND result ? 'commitmentId'",[a.userId])).rowCount).toBe(1);});
it("adjacency and cancelled space are reusable without rewriting history",async()=>{const f=await fixture(),first=await create(f);await create(f,{startTime:"11:30",endTime:"12:00"});await service.cancel(a,first.id,{mutationId:randomUUID(),expectedVersion:1});await create(f);expect((await service.view(a,f.plan.id)).commitments[0].scheduledMinutes).toBe(120);expect(await db.select().from(timeBlock)).toHaveLength(3);});
it("two concurrent edits of one version have one winner",async()=>{const f=await fixture(),first=await create(f),x=await editInput(f,first,{startTime:"12:00",endTime:"13:30"}),y=await editInput(f,first,{startTime:"14:00",endTime:"15:30"});const saved=await winner([service.edit(a,first.id,x),service.edit(a,first.id,y)]);expect(saved.version).toBe(2);expect(await service.get(a,first.id)).toEqual(saved);});
it("edit versus cancellation has one winner; cancellation never deletes the row",async()=>{const f=await fixture(),first=await create(f);await winner([service.edit(a,first.id,await editInput(f,first,{startTime:"12:00",endTime:"13:30"})),service.cancel(a,first.id,{mutationId:randomUUID(),expectedVersion:1})]);expect((await service.get(a,first.id)).version).toBe(2);expect(await db.select().from(timeBlock)).toHaveLength(1);});
it("concurrent edits of different blocks cannot converge on an overlapping interval",async()=>{const f=await fixture(),x=await create(f),y=await create(f,{startTime:"12:00",endTime:"13:30"});await winner([service.edit(a,x.id,await editInput(f,x,{startTime:"14:00",endTime:"15:30"})),service.edit(a,y.id,await editInput(f,y,{startTime:"15:00",endTime:"16:00"}))]);});
it("create/edit/cancel original receipts replay after later states and duplicate concurrent creates insert once",async()=>{const f=await fixture(),input=await command(f);const [first,retry]=await Promise.all([service.create(a,f.plan.id,input),service.create(a,f.plan.id,input)]);expect(retry).toEqual(first);const edit=await editInput(f,first,{startTime:"12:00",endTime:"13:30"}),edited=await service.edit(a,first.id,edit),cancel={mutationId:randomUUID(),expectedVersion:2},cancelled=await service.cancel(a,first.id,cancel);expect(await service.create(a,f.plan.id,input)).toEqual(first);expect(await service.edit(a,first.id,edit)).toEqual(edited);expect(await service.cancel(a,first.id,cancel)).toEqual(cancelled);await expect(service.create(a,f.plan.id,{...input,endTime:"11:45"})).rejects.toMatchObject({details:{kind:"MUTATION_ID"}});expect(await db.select().from(timeBlock)).toHaveLength(1);});
it("stable carry/budget change leaves blocks byte identical; drop preserves review/cancel; readd cannot steal them",async()=>{const f=await fixture(),first=await create(f);await amend(f,[120]);let view=await service.view(a,f.plan.id);expect(view.commitments[0]).toMatchObject({id:first.commitmentId,budgetMinutes:120,scheduledMinutes:90});expect(await service.get(a,first.id)).toEqual(first);await amend(f,[]);view=await service.view(a,f.plan.id);expect(view.blocks[0]).toMatchObject({reviewRequired:true,canEdit:false,canCancel:true});await amend(f,[180]);view=await service.view(a,f.plan.id);expect(view.commitments[0].id).not.toBe(first.commitmentId);expect(view.commitments[0].scheduledMinutes).toBe(0);expect(view.blocks[0].reviewRequired).toBe(true);await service.cancel(a,first.id,{mutationId:randomUUID(),expectedVersion:1});expect((await service.get(a,first.id)).snapshot).toEqual(first.snapshot);});
it("frozen source context survives renamed, completed and archived source",async()=>{const f=await fixture(),first=await create(f);await actions.updateAction(a,f.act.id,{mutationId:randomUUID(),expectedVersion:1,title:"Changed live work",estimateMinutes:10,doneWhen:"New",milestoneId:null});await actions.completeAction(a,f.act.id,{mutationId:randomUUID(),expectedVersion:2});await goals.archiveGoal(a,f.g.id,{mutationId:randomUUID(),expectedVersion:1});await amend(f,[120]);expect(await service.get(a,first.id)).toEqual(first);await create(f,{startTime:"12:00",endTime:"13:00"});expect((await service.view(a,f.plan.id)).blocks.every(v=>v.snapshot.action.title==="Build weekly planning UI")).toBe(true);});
it("hard overlap is owner wide across differently pinned Plan timezones",async()=>{const f=await fixture();await service.create(a,f.plan.id,{...await command(f,{startTime:"00:30",endTime:"01:30"}),acknowledgeOutsideHours:true});await db.update(user).set({timezone:"America/Los_Angeles"}).where(eq(user.id,a.userId));const act=await actions.createAction(a,f.g.id,{mutationId:randomUUID(),title:"Another commitment"});const p=await plans.create(a,{mutationId:randomUUID(),weekStartDate:"2026-09-28",provisionalCapacityMinutes:120,reserveMinutes:0});const candidate=(await plans.candidates(a)).find(c=>c.actionId===act.id)!;const saved=await plans.save(a,p.id,{mutationId:randomUUID(),expectedVersion:1,provisionalCapacityMinutes:120,reserveMinutes:0,commitments:[{actionId:act.id,budgetMinutes:120,source:candidate.source}]});const committed=await plans.commit(a,p.id,{mutationId:randomUUID(),expectedVersion:saved.version});await expect(service.preview(a,p.id,{commitmentId:committed.commitments[0].id,date:"2026-10-04",startTime:"16:30",endTime:"17:00"})).rejects.toMatchObject({details:{kind:"LOCAL_OVERLAP"}});});
it("owner B cannot inspect, derive, create, reschedule or cancel foreign data; missing indistinguishable",async()=>{const f=await fixture(),first=await create(f),input=await editInput(f,first);for(const id of [first.id,randomUUID()]){await expect(service.get(b,id)).rejects.toMatchObject({code:"NOT_FOUND",message:"This time block is unavailable."});await expect(service.edit(b,id,input)).rejects.toMatchObject({code:"NOT_FOUND"});await expect(service.cancel(b,id,{mutationId:randomUUID(),expectedVersion:1})).rejects.toMatchObject({code:"NOT_FOUND"});}for(const id of [f.plan.id,randomUUID()]){await expect(service.view(b,id)).rejects.toMatchObject({code:"NOT_FOUND"});await expect(service.create(b,id,await command(f,{startTime:"12:00",endTime:"13:00"}))).rejects.toMatchObject({code:"NOT_FOUND"});}expect(await service.get(a,first.id)).toEqual(first);const own=await fixture(b),sameId=randomUUID();await service.create(a,f.plan.id,{...await command(f,{startTime:"12:00",endTime:"13:00"}),mutationId:sameId});await service.create(b,own.plan.id,{...await command(own,{},b),mutationId:sameId});expect((await service.view(b,own.plan.id)).blocks).toHaveLength(1);});
it("draft, finished and exact-start history cannot be written; receipts still replay",async()=>{const f=await fixture(),input=await command(f),first=await service.create(a,f.plan.id,input);const later=schedulingService(repo,()=>first.start);await expect(later.cancel(a,first.id,{mutationId:randomUUID(),expectedVersion:1})).rejects.toMatchObject({details:{kind:"STARTED"}});const historical=schedulingService(repo,()=>"2026-10-12T12:00Z");await expect(historical.cancel(a,first.id,{mutationId:randomUUID(),expectedVersion:1})).rejects.toMatchObject({details:{kind:"READ_ONLY_WEEK"}});expect(await historical.create(a,f.plan.id,input)).toEqual(first);const draft=await plans.create(a,{mutationId:randomUUID(),weekStartDate:"2026-10-12",provisionalCapacityMinutes:120,reserveMinutes:0});expect((await service.view(a,draft.id)).canSchedule).toBe(false);await expect(service.create(a,draft.id,{...input,mutationId:randomUUID()})).rejects.toMatchObject({details:{kind:"READ_ONLY_WEEK"}});});
it("outside hours require acknowledgement; underscheduling and overscheduling preserve budget/estimate",async()=>{const f=await fixture(),before=await planningRows(),input=await command(f,{startTime:"07:00",endTime:"11:00"});await expect(service.create(a,f.plan.id,input)).rejects.toMatchObject({details:{kind:"OUTSIDE_HOURS"}});await service.create(a,f.plan.id,{...input,acknowledgeOutsideHours:true});expect((await service.view(a,f.plan.id)).commitments[0]).toMatchObject({budgetMinutes:180,scheduledMinutes:240});expect(await planningRows()).toEqual(before);});
it("cached Google busy is advisory with explicit acknowledgement; stale/unknown retain honest semantics and no provider call",async()=>{const f=await fixture(),provider=fakeCalendar();provider.queryBusyIntervals.mockResolvedValue([{start:"2026-10-05T09:00Z",end:"2026-10-05T11:00Z"}]);const calendar=calendarService(calendarRepository(db,pool),provider,calendarCipher(),()=>calendarClock);const auth=await calendar.start(a);await calendar.callback(a,{state:new URL(auth.url).searchParams.get("state"),code:"fake",denied:false});const conn=(await calendar.workspace(a)).connection!,listed=await calendar.refreshCalendars(a,conn.id);await calendar.select(a,conn.id,{expectedVersion:listed.version,calendarIds:["work"]});await calendar.refreshAvailability(a,conn.id,{weekStartDate:f.plan.weekStartDate});const input=await command(f);await expect(service.create(a,f.plan.id,input)).rejects.toMatchObject({details:{kind:"GOOGLE_BUSY"}});const first=await service.create(a,f.plan.id,{...input,acknowledgeBusy:true});expect(first.state).toBe("planned");expect(provider.queryBusyIntervals).toHaveBeenCalledOnce();await db.update(calendarAvailabilityCache).set({lastError:"incomplete"}).where(eq(calendarAvailabilityCache.ownerId,a.userId));expect(await service.preview(a,f.plan.id,{...f.placement,startTime:"12:00",endTime:"13:00"})).toMatchObject({calendarStatus:"stale",busyConflict:false});await calendar.disconnect(a,conn.id);expect(await service.preview(a,f.plan.id,{...f.placement,startTime:"12:00",endTime:"13:00"})).toMatchObject({calendarStatus:"unknown",busyConflict:null});});
it("final save rechecks changed plan/settings context rather than trusting preview",async()=>{const f=await fixture(),input=await command(f);await amend(f,[120]);await expect(service.create(a,f.plan.id,input)).rejects.toMatchObject({details:{kind:"EFFECTIVE_VERSION"}});const next=await command(f);await db.update(focusableHours).set({version:2,windows:[]}).where(eq(focusableHours.ownerId,a.userId));await expect(service.create(a,f.plan.id,next)).rejects.toMatchObject({details:{kind:"REVIEW_CHANGED"}});expect(await db.select().from(timeBlock)).toHaveLength(0);});
it("failed SQL rolls back aggregate and receipt; migration backfill preserves all historical IDs",async()=>{const f=await fixture(),first=await create(f),input=await command(f,{startTime:"12:00",endTime:"13:00"});const failure=schedulingService(repo,clock,()=>first.id);await expect(failure.create(a,f.plan.id,input)).rejects.toMatchObject({code:"DATABASE_UNAVAILABLE"});expect((await pool.query("SELECT 1 FROM mutation_receipt WHERE owner_id=$1 AND mutation_id=$2",[a.userId,input.mutationId])).rowCount).toBe(0);await db.delete(timeBlock);await amend(f,[]);await amend(f,[180]);const before=await planningRows();await db.delete(commitmentIdentity);const sql=await readFile("src/db/migrations/0008_local_time_blocks.sql","utf8");await pool.query(sql.slice(sql.indexOf("INSERT INTO commitment_identity")));expect(await db.select().from(commitmentIdentity)).toHaveLength(2);expect(await planningRows()).toEqual(before);const view=await service.view(a,f.plan.id);await service.create(a,f.plan.id,await command({...f,placement:{...f.placement,commitmentId:view.commitments[0].id}}));});

it("current committed week accepts only a future placement within its remaining days",async()=>{const f=await fixture(a,"2026-09-28"),input=await command(f,{date:"2026-10-02",startTime:"14:00",endTime:"15:00"});const b=await service.create(a,f.plan.id,input);expect(b.start).toBe("2026-10-02T13:00:00.000Z");await expect(service.preview(a,f.plan.id,{...f.placement,date:"2026-10-02",startTime:"12:00",endTime:"13:00"})).rejects.toMatchObject({code:"VALIDATION"});});

it("calendar projections span original plans, exclude other owners/cancelled/out-of-range blocks and clip recorded days",async()=>{
 const first=await fixture(),x=await create(first),second=await fixture(a,"2026-10-12",false),y=await create(second),other=await fixture(b);
 await service.create(b,other.plan.id,await command(other,{},b));
 const cancelled=await create(first,{startTime:"12:00",endTime:"13:00"});await service.cancel(a,cancelled.id,{mutationId:randomUUID(),expectedVersion:1});
 const future=await fixture(a,"2026-11-09",false);await create(future);
 const month=await readCalendarProjection(db,a,"2026-10-14","month","Europe/London");expect(month.blocks.map(v=>v.id)).toEqual([x.id,y.id]);expect(month.blocks.map(v=>[v.planId,v.commitmentId,v.weekStartDate])).toEqual([[first.plan.id,x.commitmentId,"2026-10-05"],[second.plan.id,y.commitmentId,"2026-10-12"]]);expect(JSON.stringify(month)).not.toContain('ownerId');
 expect((await readCalendarProjection(db,b,"2026-10-14","month","Europe/London")).blocks).toHaveLength(1);
 expect((await readCalendarProjection(db,a,"2026-10-06","day","Europe/London")).blocks).toEqual([]);
 await db.insert(focusSession).values({id:randomUUID(),ownerId:a.userId,timeBlockId:x.id,startedAt:new Date("2026-10-04T22:30Z"),endedAt:new Date("2026-10-05T00:30Z"),outcome:"partial",endNote:"Private end note",version:2,createdAt:new Date("2026-10-04T22:30Z"),updatedAt:new Date("2026-10-05T00:30Z")});
 const day=await readCalendarProjection(db,a,"2026-10-05","day","Europe/London");expect(day.recordedMilliseconds).toBe(90*60000);expect(JSON.stringify(day)).not.toContain('Private');
});
