import {afterAll,beforeAll,beforeEach,expect,it} from "vitest";
import {randomUUID} from "node:crypto";
import {eq,inArray} from "drizzle-orm";
import {migrate} from "drizzle-orm/node-postgres/migrator";
import {connectDatabase} from "../../src/db/connect";
import {weeklyReviewDecision,weeklyReview,dailyReflection,focusSession,timeBlock,commitmentIdentity,weeklyPlan,weeklyCommitment,weeklyPlanAmendment,amendmentCommitment,action,goal,milestone,mutationReceipt,user} from "../../src/db/schema";
import {weeklyReviewService} from "../../src/modules/weekly-reviews/service";
import {weeklyReviewRepository} from "../../src/modules/weekly-reviews/repository";
import {weeklyFixture} from "../weekly-review-fixture";
import {requireTestDatabaseURL} from "../../scripts/test-database";
import {provisionLocalUser} from "../../scripts/local-user";
const {db,pool}=connectDatabase(requireTestDatabaseURL().url),a={userId:""},b={userId:""};
const finish=(expectedVersion=1)=>({mutationId:randomUUID(),expectedVersion,confirmArchive:true});
beforeAll(async()=>{await migrate(db,{migrationsFolder:"src/db/migrations"});for(const [suffix,actor] of [["A",a],["B",b]] as const)actor.userId=(await provisionLocalUser(db,{email:process.env[`TEST_USER_${suffix}_EMAIL`],password:process.env[`TEST_USER_${suffix}_PASSWORD`],name:`Weekly review ${suffix}`,timezone:"Europe/London"})).id;});
async function clean(){for(const table of [weeklyReviewDecision,weeklyReview,dailyReflection,focusSession,timeBlock,commitmentIdentity,mutationReceipt,amendmentCommitment,weeklyPlanAmendment,weeklyCommitment,weeklyPlan,action,milestone,goal])await db.delete(table).where(inArray(table.ownerId,[a.userId,b.userId]));await db.update(user).set({timezone:"Europe/London"}).where(inArray(user.id,[a.userId,b.userId]));}
beforeEach(clean);afterAll(async()=>{await clean();await pool.end();});
async function snapshot(){const out:Record<string,unknown>={};for(const table of ["goal","milestone","weekly_plan","weekly_commitment","weekly_plan_amendment","amendment_commitment","commitment_identity","time_block","focus_session","daily_reflection"])out[table]=(await pool.query(`SELECT row_to_json(t) FROM ${table} t WHERE owner_id=$1 ORDER BY row_to_json(t)::text`,[a.userId])).rows;return out;}
async function carry(f:Awaited<ReturnType<typeof weeklyFixture>>,r:Awaited<ReturnType<typeof f.reviews.save>>,budget=75,owner=a){const p=await f.plans.create(owner,{mutationId:randomUUID(),weekStartDate:"2026-10-12",provisionalCapacityMinutes:480,reserveMinutes:120}),candidate=(await f.plans.candidates(owner)).find(c=>c.actionId===f.sources[0].id)!;return f.plans.save(owner,p.id,{mutationId:randomUUID(),expectedVersion:1,provisionalCapacityMinutes:480,reserveMinutes:120,carry:{reviewId:r.id,commitmentId:f.decisions.find(d=>d.kind==="carry")!.commitmentId},commitments:[{actionId:f.sources[0].id,budgetMinutes:budget,source:candidate.source}]});}
it("clean/repeatable schema, unique owner/plan, decisions constraints and durable Draft",async()=>{await migrate(db,{migrationsFolder:"src/db/migrations"});const f=await weeklyFixture(db,a),r=await f.reviews.save(a,f.save());expect(r.decisions).toHaveLength(3);const [row]=await db.select().from(weeklyReview);await expect(db.insert(weeklyReview).values({...row,id:randomUUID()})).rejects.toThrow();const [d]=await db.select().from(weeklyReviewDecision);for(const extra of [{proposedBudgetMinutes:0,kind:"carry"},{proposedBudgetMinutes:1,kind:"drop"},{ownerId:b.userId},{commitmentId:randomUUID()}])await expect(db.insert(weeklyReviewDecision).values({...d,commitmentId:randomUUID(),...extra} as typeof weeklyReviewDecision.$inferInsert)).rejects.toThrow();const other=connectDatabase(requireTestDatabaseURL().url);try{expect(await weeklyReviewService(weeklyReviewRepository(other.db)).get(a,r.id)).toEqual(r);}finally{await other.pool.end();}});
it("current/future and never-committed weeks cannot manufacture reviews",async()=>{const f=await weeklyFixture(db,a);for(const instant of ["2026-10-06T12:00Z","2026-10-04T12:00Z"]){f.setNow(instant);await expect(f.reviews.save(a,f.save())).rejects.toMatchObject({details:{kind:"WEEK_UNFINISHED"}});}expect((await f.reviews.workspace(a,"2026-10-05")).facts).toBeNull();f.setNow("2026-10-12T12:00Z");const draft=await f.plans.create(a,{mutationId:randomUUID(),weekStartDate:"2026-10-12",provisionalCapacityMinutes:480,reserveMinutes:120});f.setNow("2026-10-19T12:00Z");await expect(f.reviews.save(a,f.save({planId:draft.id}))).rejects.toMatchObject({code:"CONFLICT"});expect((await f.reviews.workspace(a,"2026-10-12")).state).toBe("uncommitted");expect(await db.select().from(weeklyReview)).toHaveLength(0);});
it("original/final summaries, two reasons, dropped and added histories, cancelled context and all outcomes are exact",async()=>{const f=await weeklyFixture(db,a),v=(await f.reviews.workspace(a)).facts!;expect(v.plan.id).toBe(f.plan.id);expect(v.originalSummary.totalMinutes).toBe(360);expect(v.finalSummary.totalMinutes).toBe(315);expect(v.amendments).toHaveLength(2);expect(v.commitments).toHaveLength(4);expect(v.commitments.find(c=>c.commitment.actionId===f.sources[2].id)).toMatchObject({dropped:true,inFinalPlan:false,scheduledMilliseconds:3600000,recordedMilliseconds:0});expect(v.commitments.find(c=>c.commitment.actionId===f.sources[3].id)).toMatchObject({firstSequence:1,source:{eligible:false}});expect(v.scheduledMilliseconds).toBe(240*60000);expect(v.recordedMilliseconds).toBe(106*60000);expect(v.commitments.flatMap(c=>c.sessions).map(s=>s.session.outcome).sort()).toEqual(["abandoned","completed","partial"]);expect(v.daily.filter(d=>d.state==="finalized")).toHaveLength(3);expect(v.daily.filter(d=>d.state==="unfinished")).toHaveLength(1);});
it("cross-week ended and active contributions clip, past finalization allowed during global active",async()=>{const f=await weeklyFixture(db,a);await f.session(f.blocks[0].id,"2026-10-11T22:40Z","2026-10-11T23:25Z","abandoned");expect((await f.reviews.workspace(a,f.week)).facts!.recordedMilliseconds).toBe(126*60000);f.setNow("2026-10-11T22:50Z");await f.focus.start(a,f.blocks[1].id,{mutationId:randomUUID(),expectedBlockVersion:1,acknowledgeRemoved:false});f.setNow("2026-10-12T09:00Z");const r=await f.reviews.save(a,f.save());expect((await f.reviews.workspace(a,f.week)).facts!.recordedMilliseconds).toBe(136*60000);await expect(f.reviews.finalize(a,r.id,finish())).resolves.toMatchObject({status:"finalized"});f.setNow("2026-10-13T09:00Z");expect((await f.reviews.workspace(a,f.week)).facts!.recordedMilliseconds).toBe(136*60000);});
it("later finalized daily reflection is excluded by historical cutoff without copying bodies",async()=>{const f=await weeklyFixture(db,a),r=await f.reviews.save(a,f.save()),final=await f.reviews.finalize(a,r.id,finish());const draft=(await f.daily.day(a,"2026-10-09")).reflection!;f.setNow("2026-10-12T11:00Z");await f.daily.finalize(a,draft.id,{mutationId:randomUUID(),expectedVersion:1});const facts=(await f.reviews.workspace(a,f.week)).facts!;expect(facts.daily[4]).toMatchObject({state:"missing",reflection:null});expect(facts.daily.filter(d=>d.state==="finalized")).toHaveLength(3);expect(facts.review).toEqual(final);});
it("empty note and missing actionable decisions reject with no effects; terminal source needs no decision",async()=>{const f=await weeklyFixture(db,a),r=await f.reviews.save(a,f.save({note:"",decisions:[]}));await expect(f.reviews.finalize(a,r.id,finish())).rejects.toMatchObject({code:"VALIDATION"});const next=await f.reviews.save(a,f.save({reviewId:r.id,expectedVersion:1,note:"A note",decisions:[]}));await expect(f.reviews.finalize(a,r.id,finish(2))).rejects.toMatchObject({details:{kind:"DECISIONS_REQUIRED"}});expect(next.status).toBe("draft");expect((await f.actions.getAction(a,f.sources[2].id)).action.state).toBe("open");const third=await f.reviews.save(a,f.save({reviewId:r.id,expectedVersion:2}));expect(third.decisions.map(d=>d.actionId)).not.toContain(f.sources[3].id);await expect(f.reviews.finalize(a,r.id,finish(3))).resolves.toMatchObject({status:"finalized"});});
it("valid Drop archives exactly once while Carry/Defer/source estimates and planning/execution/daily bytes stay untouched",async()=>{const f=await weeklyFixture(db,a),before=await snapshot(),original=await db.select().from(action),r=await f.reviews.save(a,f.save()),cmd=finish(),final=await f.reviews.finalize(a,r.id,cmd);expect(await snapshot()).toEqual(before);const rows=await db.select().from(action);for(const i of [0,1,3])expect(rows.find(v=>v.id===f.sources[i].id)).toEqual(original.find(v=>v.id===f.sources[i].id));expect(rows.find(v=>v.id===f.sources[2].id)).toMatchObject({state:"archived",version:2,estimateMinutes:240,archivedAt:new Date(f.clock())});expect(await f.reviews.finalize(a,r.id,cmd)).toEqual(final);expect(await db.select().from(weeklyPlan)).toHaveLength(1);expect(await db.select().from(weeklyReviewDecision)).toHaveLength(3);});
it.each(["edit","complete","archive","goal"])("concurrent %s source change invalidates all rollover effects without partial finalization",async kind=>{const f=await weeklyFixture(db,a),r=await f.reviews.save(a,f.save()),id=f.sources[2].id;if(kind==="edit")await f.actions.updateAction(a,id,{mutationId:randomUUID(),expectedVersion:1,title:"Changed intent",estimateMinutes:90});else if(kind==="complete")await f.actions.completeAction(a,id,{mutationId:randomUUID(),expectedVersion:1});else if(kind==="archive")await f.actions.archiveAction(a,id,{mutationId:randomUUID(),expectedVersion:1});else await f.goals.archiveGoal(a,f.goal.id,{mutationId:randomUUID(),expectedVersion:1});const before=await snapshot(),cmd=finish();await expect(f.reviews.finalize(a,r.id,cmd)).rejects.toMatchObject({details:{kind:"REVIEW_SOURCE"}});expect(await f.reviews.get(a,r.id)).toEqual(r);expect(await snapshot()).toEqual(before);expect(await db.select().from(mutationReceipt).where(eq(mutationReceipt.mutationId,cmd.mutationId))).toHaveLength(0);});
it("SQL failure after archival rolls every Drop, Review, decision and receipt back",async()=>{const f=await weeklyFixture(db,a),r=await f.reviews.save(a,f.save()),cmd=finish();await pool.query("CREATE FUNCTION reject_test_weekly_finish() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.status='finalized' THEN RAISE EXCEPTION 'Injected write failure'; END IF; RETURN NEW; END $$");await pool.query("CREATE TRIGGER test_weekly_finish BEFORE UPDATE ON weekly_review FOR EACH ROW EXECUTE FUNCTION reject_test_weekly_finish()");try{await expect(f.reviews.finalize(a,r.id,cmd)).rejects.toMatchObject({code:"DATABASE_UNAVAILABLE"});expect((await f.actions.getAction(a,f.sources[2].id)).action.state).toBe("open");expect(await f.reviews.get(a,r.id)).toEqual(r);expect(await db.select().from(mutationReceipt).where(eq(mutationReceipt.mutationId,cmd.mutationId))).toHaveLength(0);}finally{await pool.query("DROP TRIGGER test_weekly_finish ON weekly_review");await pool.query("DROP FUNCTION reject_test_weekly_finish()");}await expect(f.reviews.finalize(a,r.id,cmd)).resolves.toMatchObject({status:"finalized"});});
it("two Draft saves and save vs finish have exactly one version winner",async()=>{const f=await weeklyFixture(db,a),r=await f.reviews.save(a,f.save());const edits=await Promise.allSettled(["One","Two"].map(note=>f.reviews.save(a,f.save({reviewId:r.id,expectedVersion:1,note}))));expect(edits.filter(r=>r.status==="fulfilled")).toHaveLength(1);const current=await f.reviews.get(a,r.id);const race=await Promise.allSettled([f.reviews.save(a,f.save({reviewId:r.id,expectedVersion:2,note:"Last attempted note"})),f.reviews.finalize(a,r.id,finish(2))]);expect(race.filter(r=>r.status==="fulfilled")).toHaveLength(1);expect((await f.reviews.get(a,r.id)).version).toBe(3);await expect(f.reviews.save(a,f.save({reviewId:r.id,expectedVersion:1}))).rejects.toMatchObject({details:{kind:"REVIEW_VERSION"}});expect(current.version).toBe(2);});
it("concurrent review finalization and Action edit have one consistent order without partial Drop",async()=>{const f=await weeklyFixture(db,a),r=await f.reviews.save(a,f.save()),results=await Promise.allSettled([f.reviews.finalize(a,r.id,finish()),f.actions.updateAction(a,f.sources[2].id,{mutationId:randomUUID(),expectedVersion:1,title:"A changed target"})]);expect(results.filter(r=>r.status==="fulfilled")).toHaveLength(1);const state=await f.reviews.get(a,r.id),target=await f.actions.getAction(a,f.sources[2].id);expect(state.status==="finalized"?target.action.state:target.action.title).toBe(state.status==="finalized"?"archived":"A changed target");});
it("terminal note/decisions reject edits/reopen through services and SQL",async()=>{const f=await weeklyFixture(db,a),r=await f.reviews.save(a,f.save()),final=await f.reviews.finalize(a,r.id,finish());await expect(f.reviews.save(a,f.save({reviewId:r.id,expectedVersion:2}))).rejects.toMatchObject({details:{kind:"REVIEW_FINALIZED"}});await expect(f.reviews.finalize(a,r.id,finish(2))).rejects.toMatchObject({code:"CONFLICT"});await expect(pool.query("UPDATE weekly_review SET note='Changed',version=3 WHERE id=$1",[r.id])).rejects.toThrow();await expect(pool.query("UPDATE weekly_review_decision SET kind='defer',proposed_budget_minutes=NULL WHERE review_id=$1",[r.id])).rejects.toThrow();expect(await f.reviews.get(a,r.id)).toEqual(final);});
it("explicit Carry uses existing Draft service, new identity and edited budget; already present prevents duplicates; Defer stays ordinary",async()=>{const f=await weeklyFixture(db,a),r=await f.reviews.save(a,f.save()),final=await f.reviews.finalize(a,r.id,finish());const intents=await f.reviews.carries(a,"2026-10-12");expect(intents).toHaveLength(1);expect(intents[0]).toMatchObject({proposedBudgetMinutes:90,priorBudgetMinutes:150,eligible:true});expect(await f.reviews.carries(a,"2026-10-19")).toEqual([]);const next=await carry(f,r);expect(next.commitments[0].id).not.toBe(f.decisions[0].commitmentId);expect(next.commitments[0].budgetMinutes).toBe(75);expect((await f.plans.candidates(a)).map(c=>c.actionId)).toContain(f.sources[1].id);const command={mutationId:randomUUID(),expectedVersion:2,provisionalCapacityMinutes:480,reserveMinutes:120,carry:{reviewId:r.id,commitmentId:intents[0].commitmentId},commitments:next.commitments.map(c=>({actionId:c.actionId,budgetMinutes:c.budgetMinutes,source:c.source}))};await expect(f.plans.save(a,next.id,command)).rejects.toMatchObject({details:{kind:"ALREADY_INCLUDED"}});expect(await f.reviews.get(a,r.id)).toEqual(final);await f.plans.commit(a,next.id,{mutationId:randomUUID(),expectedVersion:2});await expect(f.plans.save(a,next.id,{...command,mutationId:randomUUID(),expectedVersion:3})).rejects.toMatchObject({details:{kind:"COMMITTED"}});expect(await db.select().from(weeklyPlanAmendment)).toHaveLength(2);});
it("Carry application revalidates ineligible source and preserves finalized intent",async()=>{const f=await weeklyFixture(db,a),r=await f.reviews.save(a,f.save()),final=await f.reviews.finalize(a,r.id,finish());await f.actions.completeAction(a,f.sources[0].id,{mutationId:randomUUID(),expectedVersion:1});expect((await f.reviews.carries(a,"2026-10-12"))[0].eligible).toBe(false);const p=await f.plans.create(a,{mutationId:randomUUID(),weekStartDate:"2026-10-12",provisionalCapacityMinutes:480,reserveMinutes:120});await expect(f.plans.save(a,p.id,{mutationId:randomUUID(),expectedVersion:1,provisionalCapacityMinutes:480,reserveMinutes:120,carry:{reviewId:r.id,commitmentId:f.decisions.find(d=>d.kind==="carry")!.commitmentId},commitments:[{actionId:f.sources[0].id,budgetMinutes:75,source:f.decisions.find(d=>d.kind==="carry")!.source}]})).rejects.toMatchObject({details:{kind:"SOURCES"}});expect((await f.plans.get(a,p.id)).plan.commitments).toEqual([]);expect(await f.reviews.get(a,r.id)).toEqual(final);});
it("owner isolation covers Review, facts, decisions, forged Drop and Carry proof; owner-scoped UUIDs",async()=>{const fa=await weeklyFixture(db,a),fb=await weeklyFixture(db,b),uuid=randomUUID(),r=await fa.reviews.save(a,fa.save({mutationId:uuid})),other=await fb.reviews.save(b,fb.save({mutationId:uuid}));expect(other.id).not.toBe(r.id);for(const id of [r.id,randomUUID()]){await expect(fb.reviews.get(b,id)).rejects.toMatchObject({code:"NOT_FOUND",message:"This weekly review is unavailable."});await expect(fb.reviews.finalize(b,id,finish())).rejects.toMatchObject({code:"NOT_FOUND"});await expect(fb.reviews.save(b,fb.save({reviewId:id,expectedVersion:1}))).rejects.toMatchObject({code:"NOT_FOUND"});}await expect(fb.reviews.save(b,fb.save({reviewId:other.id,expectedVersion:1,decisions:fa.decisions}))).rejects.toMatchObject({code:"NOT_FOUND"});expect((await fb.reviews.workspace(b)).facts!.plan.id).toBe(fb.plan.id);await fa.reviews.finalize(a,r.id,finish());const next=await fb.plans.create(b,{mutationId:randomUUID(),weekStartDate:"2026-10-12",provisionalCapacityMinutes:480,reserveMinutes:120});await expect(fb.plans.save(b,next.id,{mutationId:randomUUID(),expectedVersion:1,provisionalCapacityMinutes:480,reserveMinutes:120,carry:{reviewId:r.id,commitmentId:fa.decisions.find(d=>d.kind==="carry")!.commitmentId},commitments:[{actionId:fb.sources[0].id,budgetMinutes:30,source:fb.decisions.find(d=>d.kind==="carry")!.source}]})).rejects.toMatchObject({code:"NOT_FOUND",message:"This carry-forward intent is unavailable."});expect((await fa.actions.getAction(a,fa.sources[0].id)).action.state).toBe("open");});
it("original create/edit/final snapshots replay after later state and new database connection; changed command UUID conflicts",async()=>{const f=await weeklyFixture(db,a),create=f.save(),one=await f.reviews.save(a,create),edit=f.save({reviewId:one.id,expectedVersion:1,note:"A refined note"}),two=await f.reviews.save(a,edit),cmd=finish(2),final=await f.reviews.finalize(a,one.id,cmd),other=connectDatabase(requireTestDatabaseURL().url);try{const reloaded=weeklyReviewService(weeklyReviewRepository(other.db));expect(await reloaded.save(a,create)).toEqual(one);expect(await reloaded.save(a,edit)).toEqual(two);expect(await reloaded.finalize(a,one.id,cmd)).toEqual(final);}finally{await other.pool.end();}await expect(f.reviews.save(a,{...create,note:"Another payload"})).rejects.toMatchObject({details:{kind:"MUTATION_ID"}});expect((await f.actions.getAction(a,f.sources[2].id)).action.version).toBe(2);});
it("effort crossing from a previous Plan counts in the reviewed week without stealing its logical lineage",async()=>{const prior=await weeklyFixture(db,a,"2026-09-28");await prior.session(prior.blocks[0].id,"2026-10-04T22:40Z","2026-10-04T23:25Z","partial");const current=await weeklyFixture(db,a),facts=(await current.reviews.workspace(a,current.week)).facts!;expect(facts.recordedMilliseconds).toBe(131*60000);expect(facts.otherWork).toHaveLength(1);expect(facts.otherWork[0].block.commitmentId).toBe(prior.blocks[0].commitmentId);expect(facts.otherWork[0].recordedMilliseconds).toBe(25*60000);expect(facts.commitments).toHaveLength(4);});
it("drop/re-add same Action yields two reviewed lineages, separate scheduling, consistent decisions and one archive",async()=>{const f=await weeklyFixture(db,a);f.setNow("2026-10-10T09:00Z");const h=await f.amends.history(a,f.plan.id),source=(await f.plans.candidates(a)).find(c=>c.actionId===f.sources[2].id)!;await f.amends.confirm(a,f.plan.id,{mutationId:randomUUID(),expectedVersion:h.baseline.version,provisionalCapacityMinutes:720,reserveMinutes:150,reason:"Deliberately reconsider the removed dashboard work",commitments:[...h.effective.commitments.map(c=>({actionId:c.actionId,budgetMinutes:c.budgetMinutes})),{actionId:source.actionId,budgetMinutes:120,source:source.source}]});f.setNow("2026-10-12T09:00Z");const facts=(await f.reviews.workspace(a,f.week)).facts!,lineages=facts.commitments.filter(c=>c.commitment.actionId===source.actionId);expect(lineages).toHaveLength(2);expect(lineages.map(c=>c.scheduledMilliseconds)).toEqual([3600000,0]);const choices=facts.commitments.filter(c=>c.source?.eligible).map(c=>({...f.decisions.find(d=>d.actionId===c.commitment.actionId)!,commitmentId:c.commitment.id,source:c.source!.source}));const r=await f.reviews.save(a,f.save({decisions:choices}));await f.reviews.finalize(a,r.id,finish());expect((await f.actions.getAction(a,source.actionId)).action.version).toBe(2);expect((await f.reviews.get(a,r.id)).decisions.filter(d=>d.actionId===source.actionId)).toHaveLength(2);});
it("Milestone terminal transition while a Drop draft is open rejects finalization atomically",async()=>{const f=await weeklyFixture(db,a);const {milestoneService}=await import("../../src/modules/milestones/service"),{milestoneRepository}=await import("../../src/modules/milestones/repository");const service=milestoneService(milestoneRepository(db),f.clock),m=await service.createMilestone(a,f.goal.id,{mutationId:randomUUID(),title:"A considered scope",successCondition:"Work still matters"});await f.actions.updateAction(a,f.sources[2].id,{mutationId:randomUUID(),expectedVersion:1,title:f.sources[2].title,milestoneId:m.id,estimateMinutes:240});const source=(await f.plans.candidates(a)).find(c=>c.actionId===f.sources[2].id)!;const r=await f.reviews.save(a,f.save({decisions:f.decisions.map(d=>d.actionId===source.actionId?{...d,source:source.source}:d)}));await service.completeMilestone(a,m.id,{mutationId:randomUUID(),expectedVersion:1});const cmd=finish();await expect(f.reviews.finalize(a,r.id,cmd)).rejects.toMatchObject({details:{kind:"REVIEW_SOURCE"}});expect((await f.actions.getAction(a,source.actionId)).action).toMatchObject({state:"open",version:2});expect(await f.reviews.get(a,r.id)).toEqual(r);});

it("Review defaults to the current local week without finished plans and switches to finished evidence at local Monday",async()=>{
 const f=await weeklyFixture(db,a,"2026-09-28");
 f.setNow("2026-10-04T22:59:59Z");
 expect(await f.reviews.workspace(a)).toMatchObject({weekStartDate:"2026-09-28",currentWeekStartDate:"2026-09-28",state:"unfinished",weeks:[],facts:null});
 expect(await f.reviews.workspace(b)).toMatchObject({weekStartDate:"2026-09-28",weeks:[],facts:null});
 expect(await f.reviews.workspace(a,"2026-09-21")).toMatchObject({weekStartDate:"2026-09-21",state:"uncommitted",facts:null});
 f.setNow("2026-10-04T23:00:00Z");
 expect(await f.reviews.workspace(a)).toMatchObject({weekStartDate:"2026-09-28",currentWeekStartDate:"2026-10-05",state:"ready",facts:{plan:{id:f.plan.id}}});
 expect(await f.reviews.workspace(b)).toMatchObject({weekStartDate:"2026-10-05",currentWeekStartDate:"2026-10-05",state:"unfinished",weeks:[],facts:null});
 expect(await f.reviews.workspace(a,"2026-10-05")).toMatchObject({weekStartDate:"2026-10-05",state:"unfinished",facts:null});
 f.setNow("2026-10-19T12:00:00Z");
 expect(await f.reviews.workspace(a)).toMatchObject({weekStartDate:"2026-09-28",state:"ready"});
 expect(await db.select().from(weeklyReview)).toHaveLength(0);
});

it("current-week analytics are owned, reconcile to execution, expose no notes, and create no review",async()=>{
 const f=await weeklyFixture(db,a);f.setNow("2026-10-11T18:00Z");
 const workspace=await f.reviews.workspace(a,f.week),dashboard=workspace.analytics!;
 expect(workspace.facts).toBeNull();expect(dashboard.budgetMinutes).toBe(315);expect(dashboard.originalMinutes).toBe(360);
 expect(dashboard.scheduledMilliseconds).toBe(240*60000);expect(dashboard.recordedMilliseconds).toBe(106*60000);
 expect(dashboard.daily.reduce((n,d)=>n+d.recordedMilliseconds,0)).toBe(dashboard.recordedMilliseconds);
 expect(dashboard.goals.reduce((n,g)=>n+g.recordedMilliseconds,0)).toBe(dashboard.recordedMilliseconds);
 expect(dashboard.outcomes).toEqual({completed:1,partial:1,abandoned:1,active:0});
 expect(JSON.stringify(dashboard)).not.toContain('Production incident interrupted the attempt.');
 expect(JSON.stringify(dashboard)).not.toMatch(/endNote|"note"/);
 const foreign=(await f.reviews.workspace(b,f.week)).analytics!;
 expect(foreign.goals).toEqual([]);expect(foreign.recordedMilliseconds).toBe(0);expect(foreign.budgetMinutes).toBeNull();
 expect(await db.select().from(weeklyReview)).toHaveLength(0);
});
