import {afterAll,beforeAll,it,expect} from 'vitest';
import {mkdtemp,rm,stat} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {newAttempt,chatGPTOAuth} from '../../src/providers/chatgpt/oauth';
import {chatGPTCoach} from '../../src/providers/chatgpt/coaching';
import {startChatGPTFixture} from '../chatgpt-provider-fixture';
import {contextFixture} from '../coaching-fixture';
import {outputSchema,grounded} from '../../src/modules/coaching/domain';
import {buildContext} from '../../src/modules/coaching/context';
import {structuredSchema,systemPrompt} from '../../src/modules/coaching/provider';
import {hostId} from '../../src/modules/chatgpt/host';
let fixture:Awaited<ReturnType<typeof startChatGPTFixture>>;beforeAll(async()=>{fixture=await startChatGPTFixture();});afterAll(()=>fixture.close());
it('fresh independent PKCE/state/nonce and durable opaque host across concurrent launches',async()=>{const a=newAttempt(),b=newAttempt();expect(a.state).not.toBe(b.state);expect(a.nonce).not.toBe(b.nonce);expect(a.verifier).not.toBe(b.verifier);expect(a.challenge).not.toBe(a.verifier);const dir=await mkdtemp(join(tmpdir(),'chatgpt-host-'));try{const ids=await Promise.all(Array.from({length:5},()=>hostId(join(dir,'host.json'))));expect(new Set(ids).size).toBe(1);expect(ids[0]).toMatch(/^urn:uuid:/);expect((await stat(join(dir,'host.json'))).mode&0o777).toBe(0o600);}finally{await rm(dir,{recursive:true,force:true});}});
async function registration(mode='useful'){await fixture.control({mode});const oauth=chatGPTOAuth({testOrigin:fixture.origin}),a=newAttempt(),url=await oauth.authorize({clientId:null,hostId:'urn:uuid:fixture',redirectUri:'http://127.0.0.1:3100/auth/chatgpt/callback',...a}),u=await fixture.authorize(url),tokens=await oauth.exchange(u.searchParams.get('client_id')!,u.searchParams.get('code')!,a.verifier,'http://127.0.0.1:3100/auth/chatgpt/callback');return {oauth,a,tokens,clientId:u.searchParams.get('client_id')!,url};}
it('official registration parameters, issued ID, signed identity and displayed catalog',async()=>{const r=await registration(),u=new URL(r.url);expect(u.searchParams.get('client_id')).toBe('dynamic_agent_client');expect(u.searchParams.get('agent_name_hint')).toBe('One Better');expect(u.searchParams.get('resource')).toBe('https://api.openai.com/v1');expect(u.searchParams.get('scope')).toContain('chatgpt.tokens.use.direct');expect(await r.oauth.identity(r.tokens.credentials.idToken,r.clientId,r.a.nonce)).toMatchObject({subject:'chatgpt-subject',email:'same@example.test'});expect(await r.oauth.models(r.tokens.credentials.accessToken)).toEqual([{slug:'fixture-openai',displayName:'Fixture OpenAI'},{slug:'fixture-alternate',displayName:'Fixture Alternate'}]);});
it.each(['wrong_issuer','wrong_audience','wrong_nonce','missing_nonce','expired_identity'])('rejects signed identity with %s',async mode=>{const r=await registration(mode);await expect(r.oauth.identity(r.tokens.credentials.idToken,r.clientId,r.a.nonce)).rejects.toMatchObject({kind:'invalid_identity'});});
it('reauthorization reuses issued ID, omits registration name and can explicitly request permission',async()=>{const oauth=chatGPTOAuth({testOrigin:fixture.origin}),u=new URL(await oauth.authorize({clientId:'oaiapp_saved',hostId:'urn:uuid:fixture',redirectUri:'http://127.0.0.1:3100/auth/chatgpt/callback',...newAttempt(),enablePlan:true}));expect(u.searchParams.get('agent_name_hint')).toBeNull();expect(u.searchParams.get('client_id')).toBe('oaiapp_saved');expect(u.searchParams.get('prompt')).toBe('consent');});
const coach=()=>chatGPTCoach({model:'fixture-openai',credential:async()=> 'access-fixture-secret',baseURL:`${fixture.origin}/v1`});
it('OAuth Responses uses equivalent R5D instructions/schema with required streaming fields only',async()=>{await fixture.control({mode:'useful'});const c=buildContext(contextFixture()),r=await coach().generateCoaching(c,structuredSchema,new AbortController().signal);expect(r.usage).toEqual({inputTokens:100,outputTokens:60,cachedInputTokens:10});const {lastRequest}=await fixture.control();expect(lastRequest).toMatchObject({store:false,stream:true,instructions:systemPrompt,input:[{role:'user',content:JSON.stringify(c)}],text:{format:{schema:structuredSchema,strict:true}}});expect(Object.keys(lastRequest).sort()).toEqual(['input','instructions','model','store','stream','text']);});
it.each([['failed','failed','rate_limit'],['incomplete','incomplete','invalid_output'],['interrupted','interrupted','unavailable'],['admission_failure','admission','authentication']])('distinguishes %s without unsafe partial output',async(mode,stage,kind)=>{await fixture.control({mode});await expect(coach().generateCoaching(buildContext(contextFixture()),structuredSchema,new AbortController().signal)).rejects.toMatchObject({stage,kind});});
it('malformed completed JSON is rejected',async()=>{await fixture.control({mode:'malformed'});await expect(coach().generateCoaching(buildContext(contextFixture()),structuredSchema,new AbortController().signal)).rejects.toMatchObject({kind:'invalid_output'});});

it('live plan envelope compatibility: accepts completed item only after terminal completion with empty output',async()=>{await fixture.control({mode:'completed_empty'});const c=buildContext(contextFixture()),r=await coach().generateCoaching(c,structuredSchema,new AbortController().signal);const out=outputSchema.parse(r.output);expect(out.recommendations.every(p=>grounded(p,c))).toBe(true);expect(out.recommendations).toHaveLength(1);});
it('completed message item without terminal completion is still an interrupted failure',async()=>{await fixture.control({mode:'done_interrupted'});await expect(coach().generateCoaching(buildContext(contextFixture()),structuredSchema,new AbortController().signal)).rejects.toMatchObject({stage:'interrupted',kind:'unavailable'});});
it('tampered JWT signature is rejected',async()=>{const r=await registration(),parts=r.tokens.credentials.idToken!.split('.');parts[2]=(parts[2][0]==='A'?'B':'A')+parts[2].slice(1);await expect(r.oauth.identity(parts.join('.'),r.clientId,r.a.nonce)).rejects.toMatchObject({kind:'invalid_identity'});});
it('empty recommendations succeed and fabricated IDs fail the unchanged grounding contract',async()=>{const c=buildContext(contextFixture());await fixture.control({mode:'empty'});expect(outputSchema.parse((await coach().generateCoaching(c,structuredSchema,new AbortController().signal)).output).recommendations).toEqual([]);await fixture.control({mode:'fabricated'});const out=outputSchema.parse((await coach().generateCoaching(c,structuredSchema,new AbortController().signal)).output);expect(out.recommendations.every(p=>grounded(p,c))).toBe(false);});

it('OAuth Review uses the shared narrow schema and semantic prompt without new transport capabilities',async()=>{
 const {reviewSystemPrompt,reviewStructuredSchema}=await import('../../src/modules/coaching/provider');
 const {reviewInsightFixture}=await import('../review-insight-fixture');
 const {reviewOutputSchema}=await import('../../src/modules/coaching/domain');
 const {reviewInsightGrounded}=await import('../../src/modules/coaching/review-validation');
 await fixture.control({mode:'useful'});const c=buildContext(reviewInsightFixture()),r=await coach().generateCoaching(c,reviewStructuredSchema,new AbortController().signal);
 const out=reviewOutputSchema.parse(r.output);expect(out.insights).toHaveLength(1);expect(out.insights.every(p=>reviewInsightGrounded(p,c))).toBe(true);
 const {lastRequest}=await fixture.control();expect(lastRequest).toMatchObject({store:false,stream:true,instructions:reviewSystemPrompt,input:[{role:'user',content:JSON.stringify(c)}],text:{format:{schema:reviewStructuredSchema,strict:true}}});
 expect(Object.keys(lastRequest).sort()).toEqual(['input','instructions','model','store','stream','text']);
});
