import {it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {Temporal} from '@js-temporal/polyfill';
import {buildContext,fingerprint} from '../../src/modules/coaching/context';
import {scheduleCandidates} from '../../src/modules/coaching/candidates';
import {deriveFocusAvailability} from '../../src/modules/availability/domain';
import {weekRange,busyTotals} from '../../src/modules/calendar/domain';
import {deriveWeek} from '../../src/modules/weekly-reviews/domain';
import {contextFixture} from '../coaching-fixture';
function fixture(week='2026-10-05',now='2026-10-05T07:55:00Z',windows=[{weekday:1,startMinute:540,endMinute:1020}],busy:{start:string;end:string}[]=[]){
 const input=contextFixture();input.requestTime=now;input.scope.week=week;input.workspace.view!.plan.weekStartDate=week;input.scheduling!.weekStartDate=week;input.hours!.windows=windows;
 input.availability=deriveFocusAvailability(input.hours,{weekStartDate:week,timezone:'Europe/London',status:'fresh',intervals:busy,...busyTotals(busy,weekRange(week,'Europe/London')),fetchedAt:now,error:null},Date.parse(now));return input;
}
it.each(['2026-10-05T08:00:00Z','2026-10-05T08:00:40Z','2026-10-05T08:14:59Z','2026-10-05T08:15:00Z'])('excludes earlier today and the current minute at %s',now=>{const input=fixture(undefined,now),c=scheduleCandidates(input,now);expect(c.length).toBeGreaterThan(0);expect(c.every(v=>Temporal.Instant.compare(v.start,now)>0)).toBe(true);expect(c.some(v=>v.start==='2026-10-05T08:00:00Z')).toBe(false);});
it('subtracts touching/overlapping local blocks and intersects Calendar-open with Focusable Hours',()=>{const input=fixture(undefined,undefined,[{weekday:1,startMinute:540,endMinute:1020}],[{start:'2026-10-05T08:00Z',end:'2026-10-05T09:00Z'}]);input.scheduling!.blocks=[{id:randomUUID(),planId:input.scheduling!.planId,commitmentId:input.scheduling!.commitments[0].id,start:'2026-10-05T09:00Z',end:'2026-10-05T10:00Z',state:'planned',version:1,createdAt:input.requestTime!,updatedAt:input.requestTime!,cancelledAt:null,snapshot:input.scheduling!.commitments[0].snapshot,executionLocked:false,recordedMilliseconds:0,canFocus:true,reviewRequired:false,canCancel:true,canEdit:true}];const c=scheduleCandidates(input,input.requestTime!);expect(c[0].startLocalTime).toBe('11:00');expect(c.every(v=>Date.parse(v.start)>=Date.parse('2026-10-05T10:00Z')&&v.focusableHours==='inside'&&v.calendarStatus==='available')).toBe(true);});
it('requires actionable current Effective Plan membership, committed lifecycle, configured hours and fresh Calendar',()=>{for(const change of [(i:ReturnType<typeof fixture>)=>{i.sources[0].eligible=false;},(i:ReturnType<typeof fixture>)=>{i.effective!.commitments=[];},(i:ReturnType<typeof fixture>)=>{i.scheduling!.canSchedule=false;},(i:ReturnType<typeof fixture>)=>{i.workspace.view!.plan.state='draft';},(i:ReturnType<typeof fixture>)=>{i.hours=null;},(i:ReturnType<typeof fixture>)=>{i.availability!.status='stale';},(i:ReturnType<typeof fixture>)=>{i.availability!.status='unavailable';}]){const i=fixture();change(i);expect(scheduleCandidates(i,i.requestTime!)).toEqual([]);}});
it('rounds a Calendar busy boundary with seconds up to the next legal quarter hour',()=>{const i=fixture(undefined,undefined,[{weekday:1,startMinute:540,endMinute:1020}],[{start:'2026-10-05T08:00Z',end:'2026-10-05T09:00:30Z'}]);const c=scheduleCandidates(i,i.requestTime!);expect(c[0].start).toBe('2026-10-05T09:15:00Z');expect(c.every(v=>Date.parse(v.start)>=Date.parse('2026-10-05T09:00:30Z'))).toBe(true);});
it('has stable opaque IDs for unchanged slots, bounded alternatives, and never exceeds remaining budget',()=>{const i=fixture(),a=scheduleCandidates(i,i.requestTime!),b=scheduleCandidates(i,'2026-10-05T07:56Z');expect(a).toEqual(b);expect(a).toHaveLength(2);expect(a.every(c=>/^schedule_candidate_[a-f0-9]{16}$/.test(c.id)&&c.durationMinutes<=c.remainingUnscheduledMinutes)).toBe(true);i.scheduling!.commitments[0].scheduledMinutes=150;expect(scheduleCandidates(i,i.requestTime!)).toEqual([]);});
it.each(['2026-03-23','2026-10-19'])('uses elapsed durations and safe wall-clock boundaries around DST week %s',week=>{const i=fixture(week,`${week}T00:00Z`,[{weekday:7,startMinute:0,endMinute:240}]);const c=scheduleCandidates(i,i.requestTime!);expect(c.length).toBeGreaterThan(0);for(const v of c){expect((Date.parse(v.end)-Date.parse(v.start))/60000).toBe(v.durationMinutes);expect(Temporal.Instant.from(v.start).toZonedDateTimeISO('Europe/London').toPlainDate().toString()).toBe(v.localDate);expect(Date.parse(v.end)).toBeLessThanOrEqual(Date.parse(weekRange(week,'Europe/London').end));}});
it('does not cross local day/week end and expires advice as request time crosses midnight',()=>{const i=fixture('2026-10-05','2026-10-11T22:14Z',[{weekday:7,startMinute:1380,endMinute:1440}]);const c=scheduleCandidates(i,i.requestTime!);expect(c).toEqual([]); // A whole remaining hour no longer fits before midnight.
 i.scheduling!.commitments[0].budgetMinutes=75;const before=scheduleCandidates(i,i.requestTime!);expect(before).toHaveLength(1);expect(before[0].localDate).toBe('2026-10-11');expect(before[0].endLocalTime).toBe('23:45');const context=buildContext(i);i.requestTime='2026-10-11T23:00Z';expect(scheduleCandidates(i,i.requestTime)).toEqual([]);expect(fingerprint(buildContext(i))).not.toBe(fingerprint(context));});
it('keeps same context digest between clock ticks but invalidates expired candidates',()=>{const i=fixture(),first=buildContext(i);i.requestTime='2026-10-05T07:56Z';expect(fingerprint(buildContext(i))).toBe(fingerprint(first));i.requestTime='2026-10-05T08:00Z';expect(fingerprint(buildContext(i))).not.toBe(fingerprint(first));});
it('fully scheduled future work is evidence only; no lack-of-tracking recommendation or invented Carry',()=>{const i=fixture();i.scheduling!.commitments[0].scheduledMinutes=150;i.scheduling!.commitments[0].recordedMilliseconds=0;const c=buildContext(i);expect(c.signals.filter(s=>s.worthConsidering)).toEqual([]);expect(c.signals.map(s=>s.kind)).toContain('fully_scheduled');expect(c.signals.map(s=>s.kind)).not.toContain('repeated_carry');});
it('requires actual consecutive finalized Carry decisions and breaks on a draft or missing week',()=>{const i=fixture(),plan=i.workspace.view!.plan;
 const prior=(week:string,status:'draft'|'finalized',kind:'carry'|'defer')=>{const p={...plan,weekStartDate:week};return deriveWeek(p,[],p.timezone,'2026-10-05T07:55Z',[],[],[],[],{id:randomUUID(),planId:p.id,status,note:'Private',version:2,createdAt:p.createdAt,updatedAt:p.updatedAt,finalizedAt:status==='finalized'?'2026-10-05T07:55Z':null,decisions:[{commitmentId:plan.commitments[0].id,actionId:plan.commitments[0].actionId,kind,proposedBudgetMinutes:60,source:plan.commitments[0].source}]});};
 i.recent=[prior('2026-09-28','finalized','carry'),prior('2026-09-21','finalized','carry')];const c=buildContext(i);expect(c.signals.filter(s=>s.kind==='repeated_carry')).toHaveLength(1);expect(c.facts.find(f=>f.key.startsWith('carry:'))?.data.consecutiveCarries).toBe(2);i.recent[1].review!.status='draft';expect(buildContext(i).signals.some(s=>s.kind==='repeated_carry')).toBe(false);i.recent=[prior('2026-09-21','finalized','carry')];expect(buildContext(i).signals.some(s=>s.kind==='repeated_carry')).toBe(false);
});
it('a selected Focus Goal without a commitment supplies a deliberate review signal',()=>{const i=fixture();i.effective!.commitments=[];i.scheduling!.commitments=[];const c=buildContext(i);expect(c.signals.find(s=>s.kind==='focus_without_commitment')?.target?.kind).toBe('goal');});
it('no-recorded-focus signal requires an elapsed planned block and stays separate from Action completion',()=>{const i=fixture(undefined,'2026-10-05T09:01Z');i.scheduling!.commitments[0].recordedMilliseconds=0;i.scheduling!.blocks=[{id:randomUUID(),planId:i.scheduling!.planId,commitmentId:i.scheduling!.commitments[0].id,start:'2026-10-05T08:00Z',end:'2026-10-05T09:00Z',state:'planned',version:1,createdAt:i.requestTime!,updatedAt:i.requestTime!,cancelledAt:null,snapshot:i.scheduling!.commitments[0].snapshot,executionLocked:false,recordedMilliseconds:0,canFocus:true,reviewRequired:false,canCancel:false,canEdit:false}];expect(buildContext(i).signals.some(s=>s.kind==='unrecorded')).toBe(true);i.scheduling!.commitments[0].recordedMilliseconds=1000;expect(buildContext(i).signals.some(s=>s.kind==='unrecorded')).toBe(false);});
it('derives Review execution difference/amendment signals and preserves independent original/final budgets',()=>{const i=fixture(),plan=i.workspace.view!.plan;i.scope.contextType='weekly_review';const amended={id:randomUUID(),planId:plan.id,sequenceNumber:1,reason:'Change scope deliberately',version:1,createdAt:'2026-10-06T08:00Z',provisionalCapacityMinutes:600,reserveMinutes:120,commitments:plan.commitments.map(c=>({...c,snapshot:c.snapshot!,budgetMinutes:210}))};i.review=deriveWeek(plan,[amended],plan.timezone,'2026-10-12T08:00Z',[],[],[],[],null);const c=buildContext(i);expect(c.scheduleCandidates).toEqual([]);expect(c.reviewCandidates?.map(s=>s.type)).toEqual(expect.arrayContaining(['planning_execution_gap']));expect(c.facts.find(f=>f.key==='review_summary')?.data).toMatchObject({original:{totalMinutes:150},final:{totalMinutes:210}});});
it('recent-attention evidence uses finalized weeks only, and current protected time suppresses Calendar attention advice',()=>{const i=fixture(),plan=i.workspace.view!.plan;const prior=(week:string)=>deriveWeek({...plan,weekStartDate:week},[],plan.timezone,'2026-10-05T07:55Z',[],[],[],[],{id:randomUUID(),planId:plan.id,status:'finalized',note:'Private',version:2,createdAt:plan.createdAt,updatedAt:plan.updatedAt,finalizedAt:'2026-10-05T07:55Z',decisions:[]});i.recent=[prior('2026-09-28'),prior('2026-09-21')];expect(buildContext(i).signals.some(s=>s.kind==='attention')).toBe(false);i.scheduling!.commitments[0].scheduledMinutes=0;expect(buildContext(i).signals.some(s=>s.kind==='attention')).toBe(true);i.recent[1].review!.status='draft';expect(buildContext(i).signals.some(s=>s.kind==='attention')).toBe(false);});
