import { describe, expect, it } from 'vitest';
import { randomUUID } from 'node:crypto';
import { buildContext, canonical, fingerprint } from '../../src/modules/coaching/context';
import { outputSchema, grounded, rationaleAllowed, type CoachingContext } from '../../src/modules/coaching/domain';
import { readAIConfiguration, testAIBaseURL } from '../../src/modules/coaching/configuration';
import { deriveWeek } from '../../src/modules/weekly-reviews/domain';
import { deriveFocusAvailability } from '../../src/modules/availability/domain';
import { weekRange, busyTotals, type Availability } from '../../src/modules/calendar/domain';
import { contextFixture, suggestions } from '../coaching-fixture';
describe('owned coaching evidence and output',()=>{
  it('keeps separate original/current budgets, reserve, recorded and unscheduled quantities',()=>{const input=contextFixture(),context=buildContext(input),plan=context.facts.find(f=>f.key.startsWith('plan:'))!,c=context.facts.find(f=>f.reference?.kind==='commitment')!;expect(plan.data.original).toMatchObject({totalMinutes:150,usableMinutes:480});expect(c.data).toMatchObject({budgetMinutes:150,scheduledMinutes:45,unscheduledMinutes:105,recordedMilliseconds:600000});expect(context.facts.find(f=>f.reference?.kind==='focus_cycle')?.data.intent).toBe('Ship small slices');expect(input.scheduling?.commitments[0].scheduledMinutes).toBe(45);});
  it('is a whitelist: ignores OAuth, calendar identifiers, event content, session notes and arbitrary raw fields',()=>{const input=contextFixture();Object.assign(input,{accessToken:'secret-token',googleId:'google-id',endNote:'PRIVATE-END-NOTE',rawProvider:{title:'PRIVATE-MEETING'}});Object.assign(input.workspace,{ownerId:'PRIVATE-OWNER',note:'PRIVATE-DRAFT'});expect(JSON.stringify(buildContext(input))).not.toMatch(/secret-token|google-id|PRIVATE/);});
  it('includes relevant/current-plan sources, excludes unrelated candidates and bounds optional cycle candidates',()=>{const input=contextFixture(),source=input.sources[0];input.sources.push(...Array.from({length:30},()=>({...source,actionId:randomUUID(),context:{...source.context,action:{...source.context.action,id:randomUUID(),title:'Optional candidate'}}})));input.sources.push({...source,actionId:randomUUID(),context:{...source.context,goal:{...source.context.goal!,id:randomUUID(),title:'Unrelated secret goal'}}});const context=buildContext(input);expect(context.facts.some(f=>f.key.startsWith('source:'))).toBe(false);expect(context.stateFingerprint).toMatch(/^[a-f0-9]{64}$/);expect(JSON.stringify(context)).not.toContain('Unrelated secret goal');});
  it('Calendar excludes all reflection bodies even when recent finalized reviews exist',()=>{const input=contextFixture(),plan=input.workspace.view!.plan,facts=deriveWeek(plan,[],plan.timezone,'2026-10-12T09:00Z',[],[],[],[],{id:randomUUID(),planId:plan.id,status:'finalized',note:'PRIVATE-FINAL',version:2,createdAt:plan.createdAt,updatedAt:'2026-10-12T09:00Z',finalizedAt:'2026-10-12T09:00Z',decisions:[]});input.recent=[facts];input.review=facts;expect(JSON.stringify(buildContext(input))).not.toContain('PRIVATE-FINAL');});
  it('Review includes finalized texts through the terminal cutoff, never drafts or late finalizations',()=>{const input=contextFixture(),plan=input.workspace.view!.plan,at='2026-10-12T09:00:00.000Z',daily=(date:string,note:string,status:'draft'|'finalized',finalizedAt:string|null)=>({id:randomUUID(),localDate:date,note,status,version:2,createdAt:plan.createdAt,updatedAt:at,finalizedAt});input.scope.contextType='weekly_review';input.review=deriveWeek(plan,[],plan.timezone,at,[],[],[],[daily('2026-10-05','ALLOWED-DAILY','finalized',at),daily('2026-10-06','PRIVATE-DRAFT','draft',null),daily('2026-10-07','PRIVATE-LATE','finalized','2026-10-12T09:01:00.000Z')],{id:randomUUID(),planId:plan.id,status:'finalized',note:'ALLOWED-WEEKLY',version:2,createdAt:plan.createdAt,updatedAt:at,finalizedAt:at,decisions:[]});const text=JSON.stringify(buildContext(input));expect(text).toContain('ALLOWED-DAILY');expect(text).toContain('ALLOWED-WEEKLY');expect(text).not.toMatch(/PRIVATE-DRAFT|PRIVATE-LATE/);input.review.review!.status='draft';input.review.review!.note='PRIVATE-WEEK-DRAFT';expect(JSON.stringify(buildContext(input))).not.toContain('PRIVATE-WEEK-DRAFT');});
  it('rejects unsupported types, extra mutation fields, over three, bad dates, empty evidence and excessive text',()=>{const context=buildContext(contextFixture()),valid=suggestions(context);expect(outputSchema.safeParse({recommendations:valid}).success).toBe(true);for(const invalid of [{recommendations:Array(4).fill(valid[0])},{recommendations:[{...valid[0],type:'create_action'}]},{recommendations:[{...valid[0],ownerId:randomUUID()}]},{recommendations:[{...valid[0],localDate:'2026-02-30'}]},{recommendations:[{...valid[0],evidenceRefs:[]}]},{recommendations:[{...valid[0],rationale:'x'.repeat(321)}]}])expect(outputSchema.safeParse(invalid).success).toBe(false);expect(outputSchema.parse({recommendations:[]})).toEqual({recommendations:[]});});
  it('rejects fabricated candidates/signals/evidence and numerical or historical prose',()=>{const context=buildContext(contextFixture()),r=suggestions(context)[0];expect(grounded(r,context)).toBe(true);expect(grounded({...r,signalId:'invented'},context)).toBe(false);expect(grounded({...r,type:'schedule_candidate',candidateId:'schedule_candidate_fake'},context)).toBe(false);expect(grounded({...r,evidenceRefs:['made-up']},context)).toBe(false);for(const rationale of ['Make room for 2 hours.','It carried across two weeks.','Add work on Saturday.','Drop this commitment.','Schedule Atlantis.'])expect(grounded({...r,rationale},context)).toBe(false);});
  it('fingerprint is stable across object key ordering but changes on material facts',()=>{const input=contextFixture(),context=buildContext(input);const shuffled=JSON.parse(JSON.stringify(context));shuffled.facts=shuffled.facts.map((f:object)=>Object.fromEntries(Object.entries(f).reverse()));expect(fingerprint(shuffled)).toBe(fingerprint(context));expect(canonical({b:2,a:1})).toBe(canonical({a:1,b:2}));input.cycles.current!.version++;expect(fingerprint(buildContext(input))).not.toBe(fingerprint(context));});
  it('identical fresh Calendar refresh stays stable; changed busy intervals or stale coverage invalidate advice',()=>{const input=contextFixture(),range=weekRange(input.scope.week,'Europe/London'),now=Date.parse('2026-10-03T09:00:00Z');input.hours={id:randomUUID(),version:1,windows:[{weekday:1,startMinute:540,endMinute:1020}],createdAt:'2026-10-01T09:00Z',updatedAt:'2026-10-01T09:00Z'};let calendar:Availability={weekStartDate:input.scope.week,timezone:'Europe/London',status:'fresh' as const,intervals:[],...busyTotals([],range),fetchedAt:'2026-10-03T09:00:00Z',error:null};input.availability=deriveFocusAvailability(input.hours,calendar,now);const first=fingerprint(buildContext(input));calendar={...calendar,fetchedAt:'2026-10-03T09:01:00Z'};input.availability=deriveFocusAvailability(input.hours,calendar,now+60000);expect(fingerprint(buildContext(input))).toBe(first);input.availability=deriveFocusAvailability(input.hours,{...calendar,status:'stale'},now+3600000);expect(fingerprint(buildContext(input))).not.toBe(first);const intervals=[{start:'2026-10-05T08:00:00Z',end:'2026-10-05T09:00:00Z'}];input.availability=deriveFocusAvailability(input.hours,{...calendar,intervals,...busyTotals(intervals,range)},now+60000);expect(fingerprint(buildContext(input))).not.toBe(first);});
  it('handles missing keys and incomplete models without breaking core configuration',()=>{expect(readAIConfiguration({}).state).toBe('disabled');expect(readAIConfiguration({AI_PROVIDER:'openai',OPENAI_API_KEY:'dummy'}).state).toBe('incomplete');expect(readAIConfiguration({AI_PROVIDER:'anthropic',ANTHROPIC_API_KEY:'dummy',ANTHROPIC_MODEL:'fixture-model'}).provider?.name).toBe('anthropic');expect(testAIBaseURL({})).toBeUndefined();expect(()=>testAIBaseURL({AI_TEST_BASE_URL:'https://example.com'})).toThrow();});
  it('empty context has no references and cannot support an invented recommendation',()=>{const c:CoachingContext={schemaVersion:2,stateFingerprint:'none',requestTime:'2026-10-03T09:00Z',signals:[],scheduleCandidates:[],contextType:'calendar',week:'2026-10-05',today:'2026-10-03',timezone:'Europe/London',planId:null,facts:[]};expect(suggestions(c)).toEqual([]);expect(grounded({type:'observation',signalId:'invented',rationale:'Unsupported',evidenceRefs:['anything']},c)).toBe(false);});
});

it('allows qualitative availability language and modal may while rejecting actual duration/date claims',()=>{expect(rationaleAllowed('Protecting a focused block within available hours may help follow through.')).toBe(true);for(const text of ['Protect an hour for this work.','Make room for two hours.','Plan this work in May.','Schedule 09:00 tomorrow.'])expect(rationaleAllowed(text)).toBe(false);});

it('General work provides real Action and commitment evidence without a fabricated Goal reference',()=>{
  const input=contextFixture();input.cycles={...input.cycles,current:null,cycles:[]};
  for(const c of [input.workspace.view!.plan.commitments[0],input.effective!.commitments[0],input.scheduling!.commitments[0]]){
    c.snapshot={...c.snapshot!,goal:null};c.source={...c.source,goalId:null,goalVersion:null};
  }
  input.sources[0]={...input.sources[0],source:{...input.sources[0].source,goalId:null,goalVersion:null},context:{...input.sources[0].context,goal:null}};
  const context=buildContext(input);
  expect(context.facts.filter(f=>f.reference?.kind==='goal')).toEqual([]);
  expect(context.facts.find(f=>f.reference?.kind==='commitment')?.data.actionId).toBe(input.sources[0].actionId);
  expect(context.scheduleCandidates.every(c=>c.commitmentId===input.scheduling!.commitments[0].id)).toBe(true);
  expect(context.facts.find(f=>f.reference?.kind==='commitment')?.data.goalId).toBeNull();
  expect(JSON.stringify(context)).not.toMatch(/goal:general|goal:null/);
  for(const r of suggestions(context))expect(grounded(r,context)).toBe(true);
  input.scope.contextType='weekly_review';input.requestTime='2026-10-12T09:00:00Z';const plan=input.workspace.view!.plan;
  input.review=deriveWeek(plan,[],plan.timezone,input.requestTime,[],[],input.sources,[],null);
  const review=buildContext(input);expect(review.reviewCandidates?.some(c=>c.type==='planning_execution_gap')).toBe(true);expect(review.facts.filter(f=>f.reference?.kind==='goal')).toEqual([]);expect(JSON.stringify(review)).not.toMatch(/goal:general|goal:null/);
});
