import {describe,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {cycleFields,createCycleSchema,updateCycleSchema,transitionCycleSchema,currentCycle,checkTransition,checkVersion,type FocusCycle} from '../../src/modules/focus-cycles/domain';
const fields={title:'  A useful horizon  ',startDate:'2026-10-01',endDate:'2026-11-30',goals:[]};
const c:FocusCycle={id:randomUUID(),...fields,title:'A useful horizon',intent:null,status:'draft',goals:[{goalId:randomUUID(),goalVersion:1,title:'Goal',outcome:'Outcome',archivedAt:null}],version:1,createdAt:'2026-10-03T09:00Z',updatedAt:'2026-10-03T09:00Z',activatedAt:null,finishedAt:null,archivedAt:null};
describe('Focus Cycle validation and explicit lifecycle',()=>{
 it('trims metadata and normalizes optional empty intent',()=>{expect(cycleFields.parse(fields)).toMatchObject({title:'A useful horizon',intent:null});expect(cycleFields.parse({...fields,intent:'   '})).toMatchObject({intent:null});});
 it.each([{title:' '},{title:'x'.repeat(161)},{intent:'x'.repeat(2001)},{intent:'\0'},{startDate:'2026-02-30'},{endDate:'2026-09-30'},{startDate:'1999-01-01'},{goals:[{goalId:'bad',goalVersion:1}]},{goals:[{goalId:randomUUID(),goalVersion:0}]},{ownerId:'forged'}])('rejects invalid or forged fields %j',invalid=>{expect(cycleFields.safeParse({...fields,...invalid}).success).toBe(false);});
 it('rejects duplicate membership and over fifty Goals',()=>{const m={goalId:randomUUID(),goalVersion:1};expect(cycleFields.safeParse({...fields,goals:[m,m]}).success).toBe(false);expect(cycleFields.safeParse({...fields,goals:Array.from({length:51},()=>({...m,goalId:randomUUID()}))}).success).toBe(false);});
 it('requires IDs and positive explicit versions; strict transition has no fields',()=>{expect(createCycleSchema.safeParse(fields).success).toBe(false);expect(updateCycleSchema.safeParse({...fields,mutationId:randomUUID(),expectedVersion:0}).success).toBe(false);expect(transitionCycleSchema.safeParse({mutationId:randomUUID(),expectedVersion:1,title:'extra'}).success).toBe(false);});
 it('current context is inclusive local-date projection, not a status mutation',()=>{const active={...c,status:'active' as const};expect(currentCycle([active],'2026-10-01')).toEqual(active);expect(currentCycle([active],'2026-11-30')).toEqual(active);expect(currentCycle([active],'2026-12-01')).toBeNull();expect(active.status).toBe('active');});
 it('activation needs Draft, a selected Goal and dates covering today',()=>{expect(()=>checkTransition(c,'activate','2026-10-03')).not.toThrow();for(const v of [{...c,goals:[]},{...c,status:'finished' as const},c])expect(()=>checkTransition(v,'activate','2026-12-01')).toThrow();});
 it('finish is only for Active; archived cannot transition again; stale version conflicts',()=>{expect(()=>checkTransition(c,'finish','2026-10-03')).toThrow();expect(()=>checkTransition({...c,status:'active'},'finish','2026-12-01')).not.toThrow();expect(()=>checkTransition({...c,status:'archived'},'archive','2026-10-03')).toThrow();expect(()=>checkVersion(c,2)).toThrow();});
});
