import { afterAll, beforeAll, beforeEach, expect, it } from "vitest";
import { googleCalendarProvider, mapCalendars, mapFreeBusy } from "../../src/providers/google/calendar";
import { calendarScopes } from "../../src/modules/calendar/domain";
import { startCalendarFixture } from "../calendar-fixture-server";
let fixture: Awaited<ReturnType<typeof startCalendarFixture>>; let provider: ReturnType<typeof googleCalendarProvider>;
const appOrigin = "http://127.0.0.1:3101", range = { start: "2026-09-27T23:00:00Z", end: "2026-10-04T23:00:00Z" };
beforeAll(async () => { fixture = await startCalendarFixture(appOrigin); provider = googleCalendarProvider({ clientId: "calendar-test-client", clientSecret: "calendar-test-secret", redirectUri: `${appOrigin}/api/calendar/callback`, testOrigin: fixture.origin }); });
beforeEach(() => fixture.controls({})); afterAll(async () => fixture.close());
async function grant() { const auth = await provider.authorization("test-state"); const page = await fetch(auth.url); const text = await page.text(); const approved = await fetch(text.match(/href="([^"]+)"/)![1].replaceAll("&amp;", "&"), { redirect: "manual" }); const url = new URL(approved.headers.get("location")!); return provider.exchange(url.searchParams.get("code")!, auth.verifier); }
it("requests exactly CalendarList and accessible-calendar FreeBusy scopes, offline access, state and PKCE", async () => { const auth = await provider.authorization("test-state"); const url = new URL(auth.url); expect(url.searchParams.get("scope")?.split(" ")).toEqual([...calendarScopes]); expect(url.searchParams.get("access_type")).toBe("offline"); expect(url.searchParams.get("code_challenge_method")).toBe("S256"); expect(url.searchParams.get("state")).toBe("test-state"); expect(url.searchParams.get("redirect_uri")).toBe(`${appOrigin}/api/calendar/callback`); expect(url.toString()).not.toContain(auth.verifier); });
it("library exchanges PKCE code, inspects actual scopes/subject and refreshes without browser tokens", async () => { const value = await grant(); expect(value.scopes).toEqual([...calendarScopes]); expect(value.accountId).toBe("different-google-account"); expect(value.refreshToken).toBeTruthy(); fixture.controls({ omitRefresh: true }); const refreshed = await provider.refresh(value.refreshToken!); expect(refreshed.refreshToken).toBe(value.refreshToken); expect(refreshed.accountId).toBe(value.accountId); });
it("rejects actually missing scopes even when the token response claims requested scopes", async () => { fixture.controls({ limitedScopes: true }); await expect(grant()).rejects.toMatchObject({ kind: "reauthorization_required" }); });
it("CalendarList retrieves both pages, filters unusable roles and retains only minimum metadata", async () => { const token = await grant(); const calendars = await provider.listCalendars(token.accessToken); expect(calendars.map(c => c.id)).toEqual(["work-calendar", "holidays-calendar", "personal-calendar"]); expect(Object.keys(calendars[2]).sort()).toEqual(["accessRole", "id", "primary", "summary", "timezone"]); expect(fixture.calls.filter(c => c.path.endsWith("calendarList"))).toHaveLength(2); });
it("page-two failure never promotes a partial CalendarList", async () => { const token = await grant(); fixture.controls({ pageTwoFailure: true }); await expect(provider.listCalendars(token.accessToken)).rejects.toMatchObject({ kind: "unavailable" }); expect(fixture.calls.filter(c => c.path.endsWith("calendarList"))).toHaveLength(2); });
it("maps timing only and rejects partial, missing, invalid range and malformed busy responses", async () => {
  const good = { timeMin: range.start, timeMax: range.end, calendars: { work: { busy: [{ start: "2026-09-28T10:00+01:00", end: "2026-09-28T11:00+01:00", title: "Unused fixture detail" }] } } };
  expect(mapFreeBusy(good, ["work"], range)).toEqual([{ start: "2026-09-28T09:00:00Z", end: "2026-09-28T10:00:00Z" }]);
  for (const value of [{}, { ...good, timeMax: "2026-10-03T23:00Z" }, { ...good, calendars: {} }, { ...good, calendars: { work: { busy: [], errors: [{}] } } }, { ...good, calendars: { work: {} } }, { ...good, calendars: { work: { busy: [{ start: "no-offset", end: "bad" }] } } }]) expect(() => mapFreeBusy(value, ["work"], range)).toThrow();
});
it("FreeBusy queries only explicit IDs and makes per-calendar failure incomplete", async () => { const token = await grant(); await provider.queryBusyIntervals(token.accessToken, ["work-calendar", "personal-calendar"], range); expect(fixture.calls.at(-1)?.calendarIds).toEqual(["work-calendar", "personal-calendar"]); fixture.controls({ partial: true }); await expect(provider.queryBusyIntervals(token.accessToken, ["work-calendar", "personal-calendar"], range)).rejects.toMatchObject({ kind: "incomplete" }); });
it("unknown roles are safely unselectable and malformed listing is rejected", () => { expect(mapCalendars({ items: [{ id: "x", accessRole: "unknown" }] }).calendars).toEqual([]); expect(() => mapCalendars({ items: [{ id: "x" }] })).toThrow(); });
it("invalid grant is sanitized without leaking tokens or raw library requests", async () => { const token = await grant(); fixture.controls({ revoked: true }); try { await provider.refresh(token.refreshToken!); throw new Error("Expected failure"); } catch (error) { expect(error).toMatchObject({ kind: "reauthorization_required", message: "Calendar provider request failed." }); expect(JSON.stringify(error)).not.toContain(token.refreshToken); } });
