import {fixtureSignIn} from "./sign-in-helper";
import { test, expect, type Page, type BrowserContext } from "@playwright/test";
import { randomUUID } from "node:crypto";
import { inArray } from "drizzle-orm";
import { connectDatabase } from "../../src/db/connect";
import { focusSession, timeBlock, commitmentIdentity, weeklyPlanAmendment, amendmentCommitment, weeklyPlan, weeklyCommitment, action, goal, milestone, mutationReceipt, user } from "../../src/db/schema";
import { createAuthentication } from "../../src/server/auth-factory";
import { requireTestDatabaseURL } from "../../scripts/test-database";
const origin = "http://127.0.0.1:3101";
let database: ReturnType<typeof connectDatabase>; let ownerIds: string[];
const cookies: Record<string, Parameters<BrowserContext["addCookies"]>[0]> = {};
const command = (extra = {}) => ({ mutationId: randomUUID(), title: "Draft planning wireframe", ...extra });
const transition = (expectedVersion = 1) => ({ mutationId: randomUUID(), expectedVersion });
async function mutate(page: Page, path: string, input: object, method = "POST") { const response = await page.request.fetch(path, { method, headers: { Origin: origin }, data: input }); expect(response.status()).toBe(200); return response.json(); }
async function fixture(page: Page) {
  const parent = (await mutate(page, "/api/goals", { mutationId: randomUUID(), title: "Launch One Better MVP", outcome: "I rely on a clear planning loop every week." })).goal;
  const first = (await mutate(page, `/api/goals/${parent.id}/milestones`, { mutationId: randomUUID(), title: "Planning flow demonstrated", successCondition: "One user completes the main flow." })).milestone;
  const second = (await mutate(page, `/api/goals/${parent.id}/milestones`, { mutationId: randomUUID(), title: "Calendar availability understood", successCondition: "Busy time can be read safely." })).milestone;
  return { parent, first, second };
}
const section = (page: Page) => page.locator(".actions-section");
async function fill(page: Page, title: string, done = "", minutes = "", milestoneId = "") { await page.getByLabel("Title", { exact: true }).fill(title); await page.getByLabel("Done when (optional)", { exact: true }).fill(done); await page.getByLabel("Effort estimate in minutes (optional)").fill(minutes); await page.getByLabel("Milestone (optional)", { exact: true }).selectOption(milestoneId); }
test.beforeAll(async () => {test.setTimeout(90000);
  const target = requireTestDatabaseURL(); if (target.name === "execution_test") throw new Error("Action browser tests require a new isolated database.");
  database = connectDatabase(target.url); ownerIds = (await database.db.select({ id: user.id }).from(user)).map((row) => row.id);
  const auth = createAuthentication(database.db, { secret: process.env.BETTER_AUTH_SECRET!, baseURL: origin });
  for (const suffix of ["A", "B"]) {
    const response = await fixtureSignIn(()=>auth.handler(new Request(`${origin}/api/auth/sign-in/email`, { method: "POST", headers: { Origin: origin, "Content-Type": "application/json" }, body: JSON.stringify({ email: process.env[`TEST_USER_${suffix}_EMAIL`], password: process.env[`TEST_USER_${suffix}_PASSWORD`] }) }))); expect(response.status).toBe(200);
    cookies[suffix] = response.headers.getSetCookie().map((value) => { const pair = value.split(";")[0]; const index = pair.indexOf("="); return { name: pair.slice(0, index), value: pair.slice(index + 1), url: origin, httpOnly: true, sameSite: "Lax" as const }; });
  }
});
test.beforeEach(async ({ page }) => { await database.db.delete(mutationReceipt).where(inArray(mutationReceipt.ownerId, ownerIds)); await database.db.delete(amendmentCommitment).where(inArray(amendmentCommitment.ownerId, ownerIds)); await database.db.delete(weeklyPlanAmendment).where(inArray(weeklyPlanAmendment.ownerId, ownerIds)); await database.db.delete(focusSession).where(inArray(focusSession.ownerId, ownerIds)); await database.db.delete(timeBlock).where(inArray(timeBlock.ownerId, ownerIds)); await database.db.delete(commitmentIdentity).where(inArray(commitmentIdentity.ownerId, ownerIds)); await database.db.delete(weeklyCommitment).where(inArray(weeklyCommitment.ownerId, ownerIds)); await database.db.delete(weeklyPlan).where(inArray(weeklyPlan.ownerId, ownerIds)); await database.db.delete(action).where(inArray(action.ownerId, ownerIds)); await database.db.delete(milestone).where(inArray(milestone.ownerId, ownerIds)); await database.db.delete(goal).where(inArray(goal.ownerId, ownerIds)); await page.context().addCookies(cookies.A); });
test.afterAll(async () => { await database?.pool.end(); });
test("sign in → Goal → empty Actions → quick capture/linked work → reload/edit/reassign/complete/archive/history", async ({ page }) => {
  const { parent, first, second } = await fixture(page); await page.context().clearCookies(); await page.goto("/sign-in"); await page.getByLabel("Email", { exact: true }).fill(process.env.TEST_USER_A_EMAIL!); await page.getByLabel("Password", { exact: true }).fill(process.env.TEST_USER_A_PASSWORD!); await page.getByRole("button", { name: "Sign in", exact: true }).click(); await page.getByRole("navigation",{name:"Main navigation"}).getByRole("link",{name:"Goals",exact:true}).click();await page.getByRole("button", { name: `Preview ${parent.title}`, exact: true }).click();await page.getByRole("region",{name:"Goal preview"}).getByRole("link",{name:"Open goal workspace",exact:false}).click();
  await expect(section(page)).toContainText("Actions are concrete things you can do to move this goal forward.");
  await page.getByRole("button", { name: "Add action", exact: false }).click(); await expect(page.getByLabel("Title", { exact: true })).toBeFocused(); await fill(page, "Sketch planning flow"); await page.getByRole("button", { name: "Save action", exact: true }).click(); await expect(section(page).locator(".action-card")).toContainText("Goal-level action");
  await page.getByRole("button", { name: "Add action", exact: false }).click(); await fill(page, "Interview one prospective user", "Walk through the flow and capture three findings.", "120", first.id); await page.getByRole("button", { name: "Save action", exact: true }).click(); await expect(section(page).locator(".action-card")).toHaveCount(2); await page.reload(); await expect(section(page)).toContainText("Effort estimate: 2h");
  await page.getByRole("button", { name: "Edit action Interview one prospective user", exact: true }).click(); await expect(page.getByLabel("Done when (optional)", { exact: true })).toHaveValue("Walk through the flow and capture three findings."); await fill(page, "Interview two prospective users", "Capture three findings.", "90", ""); await page.getByRole("button", { name: "Save action", exact: true }).click();
  await page.getByRole("button", { name: "Edit action Interview two prospective users", exact: true }).click(); await page.getByLabel("Milestone (optional)", { exact: true }).selectOption(second.id); await page.getByRole("button", { name: "Save action", exact: true }).click(); await expect(section(page)).toContainText("Milestone: Calendar availability understood");
  await page.getByRole("button", { name: "Complete action Interview two prospective users", exact: true }).click(); await expect(page.getByRole("button", { name: "Cancel", exact: true })).toBeFocused(); await expect(page.getByRole("dialog")).toContainText("Capture three findings."); await expect(page.getByLabel("Evidence", { exact: false })).toHaveCount(0); await page.getByRole("button", { name: "Confirm action completion", exact: true }).click(); await expect(section(page).locator(".action-card")).toHaveCount(1); await expect(section(page)).toContainText("Effort estimate: 1h 30m"); await expect(section(page).locator(".action-card time")).toBeVisible(); await expect(section(page).locator(".action-card button")).toHaveCount(0);
  await page.getByRole("button", { name: "Open actions", exact: true }).click(); await expect(section(page)).toContainText("Sketch planning flow"); await page.getByRole("button", { name: "Archive action Sketch planning flow", exact: true }).click(); await page.getByRole("button", { name: "Cancel", exact: true }).click(); await expect(section(page)).toContainText("Sketch planning flow"); await page.getByRole("button", { name: "Archive action Sketch planning flow", exact: true }).click(); await page.getByRole("button", { name: "Archive action", exact: true }).click(); await expect(page.getByRole("dialog")).toHaveCount(0); await expect(section(page).locator(".action-card time")).toBeVisible(); await page.reload(); await expect(section(page)).toContainText("Sketch planning flow"); await expect(section(page).locator(".action-card time")).toBeVisible();
  await page.getByRole("button", { name: "Completed", exact: true }).click(); await expect(page).toHaveURL(/view=completed/); await expect(page).toHaveURL(/actionView=archived/); await page.getByRole("button", { name: "Completed actions", exact: true }).click(); await page.reload(); await expect(section(page)).toContainText("Interview two prospective users");
});
test("conflicts preserve fields and reviewed draft; terminal parents immediately refresh actions and prevent detachment", async ({ page }) => {
  const { parent, first } = await fixture(page); const value = (await mutate(page, `/api/goals/${parent.id}/actions`, command({ milestoneId: first.id, estimateMinutes: 45 }))).action; await page.goto(`/goals/${parent.id}`);
  await page.getByRole("button", { name: `Edit action ${value.title}`, exact: true }).click(); await fill(page, "Useful unsaved draft", "Keep these findings", "60", ""); await mutate(page, `/api/actions/${value.id}`, { ...command({ title: "Saved elsewhere", milestoneId: first.id, estimateMinutes: 90 }), expectedVersion: 1 }, "PATCH"); await page.getByRole("button", { name: "Save action", exact: true }).click(); await expect(section(page).getByRole("alert")).toContainText("changed elsewhere"); await expect(page.getByLabel("Title", { exact: true })).toHaveValue("Useful unsaved draft"); await page.getByRole("button", { name: "Review latest saved version", exact: true }).click(); await expect(page.getByRole("dialog")).toContainText("Saved elsewhere"); await page.getByRole("button", { name: "Save action", exact: true }).click(); await expect(section(page)).toContainText("Useful unsaved draft");
  await page.getByRole("button", { name: "Edit action Useful unsaved draft", exact: true }).click(); await page.getByLabel("Milestone (optional)", { exact: true }).selectOption(first.id); await page.getByRole("button", { name: "Save action", exact: true }).click();
  await page.getByRole("button", { name: `Complete ${first.title}`, exact: true }).click(); await page.getByRole("button", { name: "Confirm completion", exact: true }).click(); await expect(section(page)).toContainText("Its milestone is completed. This action remains open as read-only history."); await expect(section(page).locator(".action-card button")).toHaveCount(0); await page.reload(); await expect(section(page)).toContainText("Useful unsaved draft");
  const latest = (await (await page.request.get(`/api/actions/${value.id}`)).json()).action; expect((await page.request.patch(`/api/actions/${value.id}`, { headers: { Origin: origin }, data: { ...command(), expectedVersion: latest.version, milestoneId: null } })).status()).toBe(409);
  await page.getByRole("button", { name: "Add action", exact: false }).click(); await expect(page.getByLabel("Milestone (optional)", { exact: true }).locator(`option[value="${first.id}"]`)).toHaveCount(0); await page.getByRole("button", { name: "Cancel", exact: true }).click();
});
test("archived milestone and archived Goal retain exact Action snapshots and readonly UI; active drafts survive parent races", async ({ page }) => {
  const { parent, first, second } = await fixture(page); const linked = (await mutate(page, `/api/goals/${parent.id}/actions`, command({ title: "Linked history", milestoneId: first.id, estimateMinutes: 30 }))).action; const only = (await mutate(page, `/api/goals/${parent.id}/actions`, command({ title: "Goal-only history", estimateMinutes: 60 }))).action; await page.goto(`/goals/${parent.id}`);
  await page.getByRole("button", { name: `Archive ${first.title}`, exact: true }).click(); await page.getByRole("button", { name: "Archive milestone", exact: true }).click(); await expect(section(page)).toContainText("Its milestone is archived. This action remains open as read-only history."); expect((await (await page.request.get(`/api/actions/${linked.id}`)).json()).action).toEqual(linked);
  await page.getByRole("button", { name: "Edit action Goal-only history", exact: true }).click(); await fill(page, "Preserve this draft", "Not silently lost", "75", second.id); await mutate(page, `/api/goals/${parent.id}/archive`, transition()); await page.getByRole("button", { name: "Save action", exact: true }).click(); await expect(section(page).getByRole("alert")).toContainText("goal is archived"); await expect(page.getByLabel("Title", { exact: true })).toHaveValue("Preserve this draft"); await expect(page.getByRole("button", { name: "Save action", exact: true })).toBeDisabled(); await page.getByRole("button", { name: "Close without saving", exact: true }).click(); await page.reload(); await expect(section(page)).toContainText("Its actions are kept unchanged as read-only history."); await expect(section(page).locator(".action-card button")).toHaveCount(0); await expect(page.getByRole("button", { name: "Add action", exact: false })).toHaveCount(0); expect((await (await page.request.get(`/api/actions/${only.id}`)).json()).action).toEqual(only);
});
test("lost acknowledgements replay identical create/edit/complete/archive payloads without duplicate versions", async ({ page }) => {
  const { parent } = await fixture(page); await page.goto(`/goals/${parent.id}`);
  async function lose(url: string, method: string, submit: string) { const bodies: string[] = []; let first = true;
    await page.route(url, async (route) => { if (route.request().method() !== method) return route.continue(); bodies.push(route.request().postData()!); if (first) { first = false; expect((await route.fetch()).status()).toBe(200); await route.abort("failed"); } else await route.continue(); });
    await page.getByRole("button", { name: submit, exact: true }).click(); await expect(section(page).getByRole("alert")).toContainText("may have saved"); await expect(page.getByRole("button", { name: "Cancel", exact: true })).toBeDisabled(); await page.getByRole("button", { name: "Retry same change", exact: true }).click(); await expect(page.getByRole("dialog")).toHaveCount(0); expect(bodies).toHaveLength(2); expect(bodies[0]).toBe(bodies[1]); await page.unroute(url);
  }
  await page.getByRole("button", { name: "Add action", exact: false }).click(); await fill(page, "Captured once", "Clear finish", "45"); await lose(`**/api/goals/${parent.id}/actions`, "POST", "Save action"); await expect(section(page).locator(".action-card")).toHaveCount(1); const id = await section(page).locator(".action-card").getAttribute("data-action-id"); await page.getByRole("button", { name: "Edit action Captured once", exact: true }).click(); await fill(page, "Edited once", "Same finish", "60"); await lose(`**/api/actions/${id}`, "PATCH", "Save action"); await page.getByRole("button", { name: "Complete action Edited once", exact: true }).click(); await lose(`**/api/actions/${id}/complete`, "POST", "Confirm action completion"); expect((await (await page.request.get(`/api/actions/${id}`)).json()).action.version).toBe(3);
  const second = (await mutate(page, `/api/goals/${parent.id}/actions`, command({ title: "Archive once" }))).action; await page.getByRole("button", { name: "Open actions", exact: true }).click(); await page.getByRole("button", { name: "Archive action Archive once", exact: true }).click(); await lose(`**/api/actions/${second.id}/archive`, "POST", "Archive action"); expect((await (await page.request.get(`/api/actions/${second.id}`)).json()).action.version).toBe(2);
});
test("HTTP validation/CSRF/ownership/anonymous/terminal errors and no standalone route", async ({ page, browser }) => {
  const { parent, first } = await fixture(page); const value = (await mutate(page, `/api/goals/${parent.id}/actions`, command({ milestoneId: first.id }))).action;
  for (const extra of [{ title: " " }, { doneWhen: 1 }, { estimateMinutes: 0 }, { estimateMinutes: 1.5 }, { estimateMinutes: "60" }, { goalId: randomUUID() }, { ownerId: ownerIds[1] }]) { const response = await page.request.post(`/api/goals/${parent.id}/actions`, { headers: { Origin: origin }, data: command(extra) }); expect(response.status()).toBe(400); expect((await response.json()).error.code).toBe("VALIDATION"); }
  expect((await page.request.post("/api/actions", { headers: { Origin: origin }, data: command() })).status()).toBe(404);
  expect((await page.request.post(`/api/actions/${value.id}/complete`, { headers: { Origin: "https://foreign.example.test" }, data: transition() })).status()).toBe(403);
  await mutate(page, `/api/actions/${value.id}/complete`, transition()); for (const [method, path, data] of [["PATCH", "", { ...command(), expectedVersion: 2 }], ["POST", "/archive", transition(2)], ["POST", "/complete", transition(2)]] as const) expect((await page.request.fetch(`/api/actions/${value.id}${path}`, { method, headers: { Origin: origin }, data })).status()).toBe(409);
  const foreign = await browser.newContext(); await foreign.addCookies(cookies.B); const anonymous = await browser.newContext();
  try { for (const context of [foreign, anonymous]) for (const [method, url, data] of [["GET", `/api/goals/${parent.id}/actions`, undefined], ["POST", `/api/goals/${parent.id}/actions`, command()], ["GET", `/api/actions/${value.id}`, undefined], ["PATCH", `/api/actions/${value.id}`, { ...command(), expectedVersion: 2 }], ["POST", `/api/actions/${value.id}/complete`, transition(2)], ["POST", `/api/actions/${value.id}/archive`, transition(2)]] as const) { const response = await context.request.fetch(url, { method, headers: { Origin: origin }, data }); expect(response.status()).toBe(context === anonymous ? 401 : 404); expect((await response.json()).error).not.toHaveProperty("current"); } } finally { await foreign.close(); await anonymous.close(); }
});
test("optional field feedback, escaped text, responsive layout, keyboard and explicit load failure", async ({ page }) => {
  const { parent } = await fixture(page); await page.setViewportSize({ width: 390, height: 844 }); await page.goto(`/goals/${parent.id}`); await page.getByRole("button", { name: "Add action", exact: false }).focus(); await page.keyboard.press("Enter"); await fill(page, "<script>alert(1)</script>", "<img src=x> is text", "0"); await page.getByRole("button", { name: "Save action", exact: true }).click(); await expect(page.locator("#action-estimate-error")).toContainText("at least 1"); await page.getByLabel("Effort estimate in minutes (optional)").fill("30"); await page.getByRole("button", { name: "Save action", exact: true }).click(); await expect(section(page)).toContainText("<script>alert(1)</script>"); expect(await section(page).locator("script,img").count()).toBe(0); expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.route(`**/api/goals/${parent.id}/actions`, (route) => route.fulfill({ status: 503, contentType: "application/json", body: JSON.stringify({ error: { code: "DATABASE_UNAVAILABLE", message: "Unavailable" } }) })); await page.getByRole("button", { name: "Completed actions", exact: true }).click(); await expect(section(page).getByRole("alert")).toContainText("could not be refreshed"); await expect(page.getByText("No completed actions yet.", { exact: true })).toHaveCount(0); await page.unroute(`**/api/goals/${parent.id}/actions`); await page.getByRole("button", { name: "Retry loading actions", exact: true }).click(); await expect(page.getByText("No completed actions yet.", { exact: true })).toBeVisible();
});
test("a newer milestone context read supersedes delayed Action reads without stale controls or stuck loading", async ({ page }) => {
  const { parent, first } = await fixture(page); await mutate(page, `/api/goals/${parent.id}/actions`, command({ title: "Historical open work", milestoneId: first.id })); await page.goto(`/goals/${parent.id}`);
  let release!: () => void; const held = new Promise<void>((resolve) => { release = resolve; });
  let observed!: () => void; const started = new Promise<void>((resolve) => { observed = resolve; }); let firstRead = true;
  await page.route(`**/api/goals/${parent.id}/actions`, async (route) => {
    if (route.request().method() !== "GET" || !firstRead) return route.continue(); firstRead = false;
    const response = await route.fetch(); observed(); await held; await route.fulfill({ response });
  });
  try {
    await page.getByRole("button", { name: "Completed actions", exact: true }).click(); await started;
    await page.getByRole("button", { name: `Complete ${first.title}`, exact: true }).click(); await page.getByRole("button", { name: "Confirm completion", exact: true }).click();
    await expect(section(page)).not.toContainText("Loading actions…"); await expect(page.getByText("No completed actions yet.", { exact: true })).toBeVisible();
    release(); await page.getByRole("button", { name: "Open actions", exact: true }).click(); await expect(section(page)).toContainText("Its milestone is completed. This action remains open as read-only history."); await expect(section(page).locator(".action-card button")).toHaveCount(0);
  } finally { release(); await page.unroute(`**/api/goals/${parent.id}/actions`); }
});
