import {fixtureSignIn} from "./sign-in-helper";
import { signInThroughUI } from "./sign-in-helper";
import { test, expect, type Page, type BrowserContext } from "@playwright/test";
import { randomUUID } from "node:crypto";
import { inArray } from "drizzle-orm";
import { connectDatabase } from "../../src/db/connect";
import { focusSession, timeBlock, commitmentIdentity, weeklyPlanAmendment, amendmentCommitment, action, goal, milestone, mutationReceipt, user, weeklyCommitment, weeklyPlan } from "../../src/db/schema";
import { createAuthentication } from "../../src/server/auth-factory";
import { requireTestDatabaseURL } from "../../scripts/test-database";
import { addDays } from "../../src/modules/planning/domain";
const origin = "http://127.0.0.1:3101";
let database: ReturnType<typeof connectDatabase>; let ownerIds: string[];
const cookies: Record<string, Parameters<BrowserContext["addCookies"]>[0]> = {};
async function mutate(page: Page, path: string, input: object, method = "POST") { const response = await page.request.fetch(path, { method, headers: { Origin: origin }, data: input }); expect(response.status(), await response.text()).toBe(200); return response.json(); }
async function fixture(page: Page) {
  const parent = (await mutate(page, "/api/goals", { mutationId: randomUUID(), title: "A useful One Better system", outcome: "I choose meaningful work without filling every minute." })).goal;
  const first = (await mutate(page, `/api/goals/${parent.id}/milestones`, { mutationId: randomUUID(), title: "Weekly planning usable", successCondition: "One realistic week is deliberately planned." })).milestone;
  const second = (await mutate(page, `/api/goals/${parent.id}/milestones`, { mutationId: randomUUID(), title: "Next useful outcome", successCondition: "Context moves are explicit." })).milestone;
  const values = [];
  for (const [title, estimateMinutes, milestoneId] of [["Build capacity editor", 120, null], ["Implement planning persistence", 240, first.id], ["Test planning flow", 45, second.id]] as const) values.push((await mutate(page, `/api/goals/${parent.id}/actions`, { mutationId: randomUUID(), title, estimateMinutes, milestoneId, doneWhen: "The chosen outcome can be demonstrated." })).action);
  const workspace = await (await page.request.get("/api/weekly-plans")).json(); const candidates = (await (await page.request.get("/api/weekly-plans/candidates")).json()).candidates;
  const selections = values.map((v, i) => ({ actionId: v.id, source: candidates.find((c: { actionId: string }) => c.actionId === v.id).source, budgetMinutes: [180, 120, 90][i] }));
  return { parent, first, second, values, selections, week: workspace.currentWeekStartDate };
}
test.beforeAll(async () => {test.setTimeout(90000);
  const target = requireTestDatabaseURL(); if (target.name === "execution_test") throw new Error("Planning browser tests require a new isolated database.");
  database = connectDatabase(target.url); ownerIds = (await database.db.select({ id: user.id }).from(user)).map((row) => row.id);
  const auth = createAuthentication(database.db, { secret: process.env.BETTER_AUTH_SECRET!, baseURL: origin });
  for (const suffix of ["A", "B"]) { const response = await fixtureSignIn(()=>auth.handler(new Request(`${origin}/api/auth/sign-in/email`, { method: "POST", headers: { Origin: origin, "Content-Type": "application/json" }, body: JSON.stringify({ email: process.env[`TEST_USER_${suffix}_EMAIL`], password: process.env[`TEST_USER_${suffix}_PASSWORD`] }) }))); expect(response.status).toBe(200); cookies[suffix] = response.headers.getSetCookie().map((value) => { const pair = value.split(";")[0], index = pair.indexOf("="); return { name: pair.slice(0, index), value: pair.slice(index + 1), url: origin, httpOnly: true, sameSite: "Lax" as const }; }); }
});
test.beforeEach(async ({ page }) => { await database.db.delete(mutationReceipt).where(inArray(mutationReceipt.ownerId, ownerIds)); await database.db.delete(amendmentCommitment).where(inArray(amendmentCommitment.ownerId, ownerIds)); await database.db.delete(weeklyPlanAmendment).where(inArray(weeklyPlanAmendment.ownerId, ownerIds)); await database.db.delete(focusSession).where(inArray(focusSession.ownerId, ownerIds)); await database.db.delete(timeBlock).where(inArray(timeBlock.ownerId, ownerIds)); await database.db.delete(commitmentIdentity).where(inArray(commitmentIdentity.ownerId, ownerIds)); await database.db.delete(weeklyCommitment).where(inArray(weeklyCommitment.ownerId, ownerIds)); await database.db.delete(weeklyPlan).where(inArray(weeklyPlan.ownerId, ownerIds)); await database.db.delete(action).where(inArray(action.ownerId, ownerIds)); await database.db.delete(milestone).where(inArray(milestone.ownerId, ownerIds)); await database.db.delete(goal).where(inArray(goal.ownerId, ownerIds)); await page.context().addCookies(cookies.A); });
test.afterAll(async () => { await database?.pool.end(); });

async function committed(page: Page) {
  const f = await fixture(page); const created = (await mutate(page, "/api/weekly-plans", { mutationId: randomUUID(), weekStartDate: f.week, provisionalCapacityMinutes: 720, reserveMinutes: 180 })).plan;
  const saved = (await mutate(page, `/api/weekly-plans/${created.id}`, { mutationId: randomUUID(), expectedVersion: 1, provisionalCapacityMinutes: 720, reserveMinutes: 180, commitments: f.selections }, "PATCH")).plan;
  const plan = (await mutate(page, `/api/weekly-plans/${saved.id}/commit`, { mutationId: randomUUID(), expectedVersion: saved.version })).plan;
  const urgent = (await mutate(page, `/api/goals/${f.parent.id}/actions`, { mutationId: randomUUID(), title: "Investigate production issue", estimateMinutes: 45, doneWhen: "Cause understood" })).action;
  return { ...f, plan, urgent, url: `/api/weekly-plans/${plan.id}/amendments` };
}
const history = async (page: Page, url: string) => (await page.request.get(url)).json();
const command = (plan: { version: number; commitments: { actionId: string; budgetMinutes: number }[] }, extra = {}) => ({ mutationId: randomUUID(), expectedVersion: plan.version, provisionalCapacityMinutes: 600, reserveMinutes: 120, commitments: plan.commitments.map(({ actionId, budgetMinutes }) => ({ actionId, budgetMinutes })), reason: "Production support reduced focus capacity", ...extra });
async function begin(page: Page) { await page.getByRole("button", { name: "Amend plan", exact: true }).click(); await expect(page.getByLabel("Revised weekly focus capacity in minutes")).toBeFocused(); }
async function confirm(page: Page) { await page.getByRole("button", { name: "Review amendment", exact: true }).click(); const dialog = page.getByRole("dialog"); await expect(dialog.getByRole("button", { name: "Keep adjusting" })).toBeFocused(); await dialog.getByRole("button", { name: "Confirm amendment", exact: true }).click(); await expect(page.locator(".committed-plan").getByRole("status")).toContainText("Amendment confirmed"); }
test("real sign in → original → intentional amendments with full diff → current/history/original → second immutable snapshot → reload", async ({ page }) => {
  test.setTimeout(90000);
  const f = await committed(page); await page.context().clearCookies(); await page.goto("/sign-in"); await page.getByLabel("Email", { exact: true }).fill(process.env.TEST_USER_A_EMAIL!); await page.getByLabel("Password", { exact: true }).fill(process.env.TEST_USER_A_PASSWORD!); await signInThroughUI(page); await page.locator(".settings-menu summary").click();await page.getByRole("link", { name: "Weekly planning", exact: true }).click();
  const original = page.locator("[data-original-plan]"); await original.getByText("Original Plan", { exact: false }).click(); await expect(original.getByLabel("Capacity summary")).toContainText("Still uncommitted2h 30m"); await expect(original).toContainText("Test planning flow"); await original.locator("summary").click();
  await begin(page); await expect(page.getByLabel("Revised weekly focus capacity in minutes")).toHaveValue("720"); await expect(page.getByLabel("Revised protected reserve in minutes")).toHaveValue("180"); for (const [i,v] of f.values.entries()) await expect(page.locator(`[data-amend-action="${v.id}"]`).getByLabel("Revised budget in minutes")).toHaveValue(String([180,120,90][i]));
  await page.getByLabel("Revised weekly focus capacity in minutes").fill("540"); await page.getByLabel("Revised protected reserve in minutes").fill("120"); await page.locator(`[data-amend-action="${f.values[2].id}"]`).getByRole("button", { name: "Drop commitment" }).click(); await page.locator(`[data-amend-action="${f.values[0].id}"]`).getByLabel("Revised budget in minutes").fill("150"); await page.locator(`[data-amend-candidate="${f.urgent.id}"]`).getByRole("button").click(); await expect(page.locator(`[data-amend-action="${f.urgent.id}"]`).getByLabel("Revised budget in minutes")).toHaveValue(""); await page.locator(`[data-amend-action="${f.urgent.id}"]`).getByLabel("Revised budget in minutes").fill("45"); await page.getByLabel("Reason for this amendment").fill("Production support reduced available focus time.");
  await page.getByRole("button", { name: "Review amendment", exact: true }).click(); const dialog = page.getByRole("dialog"); for (const text of ["Capacity: 12h → 9h", "Reserve: 3h → 2h", "Dropped: Test planning flow · 1h 30m", "Budget: Build capacity editor · 3h → 2h 30m", "Added: Investigate production issue · 45m", "Committed total: 6h 30m → 5h 15m", "Uncommitted: 2h 30m → 1h 45m"]) await expect(dialog).toContainText(text); await dialog.getByRole("button", { name: "Confirm amendment" }).click(); await expect(page.getByRole("heading", { name: "Committed · 1 amendment", exact: true })).toBeVisible();
  const firstHistory = await history(page, f.url); const first = firstHistory.amendments[0]; const entry = page.locator('[data-amendment-sequence="1"]'); await expect(entry).toContainText("Production support reduced available focus time."); await expect(entry).toContainText(new Date(first.createdAt).getUTCFullYear().toString()); await entry.getByText("Inspect full snapshot").click(); await expect(entry).toContainText("Investigate production issue"); await entry.locator("summary").click(); await original.locator("summary").click(); await expect(original).toContainText("Test planning flow"); await expect(original.getByLabel("Capacity summary")).toContainText("Weekly capacity12h"); await original.locator("summary").click();
  await begin(page); await page.getByLabel("Revised protected reserve in minutes").fill("150"); await page.getByLabel("Reason for this amendment").fill("Protect recovery time after support work."); await confirm(page); await page.reload(); await expect(page.getByRole("heading", { name: "Committed · 2 amendments", exact: true })).toBeVisible(); await expect(page.locator(".plan-history .amendment-history-entry")).toHaveCount(2); const persisted = await history(page, f.url); expect(persisted.amendments[0]).toEqual(first); const { version: _old, ...before } = f.plan; const { version: _new, ...after } = persisted.baseline; void _old; void _new; expect(after).toEqual(before); await expect(page.locator(".committed-plan").getByLabel("Capacity summary").first()).toContainText("Still uncommitted1h 15m");
});
test("cancel leaves every persisted value unchanged; next editor copies latest effective plan", async ({ page }) => { const f = await committed(page); await page.goto("/planning"); const before = await history(page,f.url); await begin(page); await page.getByLabel("Revised weekly focus capacity in minutes").fill("400"); await page.locator(`[data-amend-action="${f.values[0].id}"]`).getByRole("button").click(); await page.getByLabel("Reason for this amendment").fill("Unsaved proposal"); await page.getByRole("button",{ name:"Cancel amendment" }).click(); expect(await history(page,f.url)).toEqual(before); await expect(page.getByRole("button", { name: "Amend plan", exact: true })).toBeFocused(); await begin(page); await expect(page.getByLabel("Revised weekly focus capacity in minutes")).toHaveValue("720"); await expect(page.getByLabel("Reason for this amendment")).toHaveValue(""); await expect(page.locator("[data-amend-action]")).toHaveCount(3); });
test("reason/no-op/over-capacity block review; all-dropped zero-capacity is legitimate", async ({ page }) => { const f = await committed(page); await page.goto("/planning"); await begin(page); const review = page.getByRole("button", { name: "Review amendment", exact: true }); await page.getByLabel("Reason for this amendment").fill("Reason alone"); await expect(review).toBeDisabled(); await page.getByLabel("Revised weekly focus capacity in minutes").fill("300"); await expect(review).toBeDisabled(); await page.getByLabel("Revised weekly focus capacity in minutes").fill("0"); await page.getByLabel("Revised protected reserve in minutes").fill("0"); for (const v of f.values) await page.locator(`[data-amend-action="${v.id}"]`).getByRole("button").click(); await page.getByLabel("Reason for this amendment").fill("Illness: no remaining focus capacity."); await expect(review).toBeEnabled(); await confirm(page); await expect(page.locator(".committed-plan").getByLabel("Capacity summary").first()).toContainText("Weekly capacity0m"); await expect(page.getByText("No focus work committed.", { exact: false })).toBeVisible(); expect((await history(page,f.url)).baseline.provisionalCapacityMinutes).toBe(720); });
test("stale editor retains proposal and requires explicit latest-plan restart; no silent merge", async ({ page, context }) => { const f = await committed(page); await page.goto("/planning"); await begin(page); await page.getByLabel("Revised weekly focus capacity in minutes").fill("660"); await page.getByLabel("Reason for this amendment").fill("My retained proposal"); const other = await context.newPage(); await other.goto("/planning"); await begin(other); await other.getByLabel("Revised protected reserve in minutes").fill("120"); await other.getByLabel("Reason for this amendment").fill("Other tab won"); await confirm(other); await page.getByRole("button", { name:"Review amendment", exact:true }).click(); await page.getByRole("dialog").getByRole("button", { name:"Confirm amendment" }).click(); await expect(page.locator(".committed-plan").getByRole("alert")).toContainText("Current Plan changed elsewhere"); await expect(page.getByLabel("Revised weekly focus capacity in minutes")).toHaveValue("660"); await expect(page.getByLabel("Reason for this amendment")).toHaveValue("My retained proposal"); await expect(page.getByRole("button", { name:"Review amendment",exact:true })).toBeDisabled(); await page.getByRole("button", { name:"Review latest Current Plan and start again" }).click(); await expect(page.getByLabel("Revised weekly focus capacity in minutes")).toHaveValue("720"); await expect(page.getByLabel("Revised protected reserve in minutes")).toHaveValue("120"); await page.getByLabel("Revised weekly focus capacity in minutes").fill("660"); await page.getByLabel("Reason for this amendment").fill("Reapplied deliberately"); await confirm(page); expect((await history(page,f.url)).amendments.map((a: { sequenceNumber: number }) => a.sequenceNumber)).toEqual([1,2]); await other.close(); });
test("lost response retries identical receipt; current read reflects later amendment", async ({ page }) => { const f = await committed(page); await page.goto("/planning"); await begin(page); await page.getByLabel("Revised weekly focus capacity in minutes").fill("600"); await page.getByLabel("Reason for this amendment").fill("First accepted change"); const payloads: string[] = []; let dropped = false; await page.route("**/api/weekly-plans/*/amendments", async route => { if (route.request().method() !== "POST") return route.continue(); payloads.push(route.request().postData()!); const response = await route.fetch(); expect(response.status()).toBe(200); if (!dropped) { dropped = true; await route.fulfill({ status:200, contentType:"application/json", body:"interrupted" }); } else await route.fulfill({ response }); }); await page.getByRole("button", { name:"Review amendment",exact:true }).click(); await page.getByRole("dialog").getByRole("button", { name:"Confirm amendment" }).click(); await expect(page.getByRole("button", { name:"Retry same command" })).toBeVisible(); await expect(page.getByLabel("Revised weekly focus capacity in minutes")).toBeDisabled(); await expect(page.getByRole("button", { name:"Cancel amendment" })).toBeDisabled(); const latest = await history(page,f.url); await mutate(page,f.url,command(latest.baseline,{ reserveMinutes:150 })); await page.getByRole("button", { name:"Retry same command" }).click(); await expect(page.getByRole("heading", { name:"Committed · 2 amendments",exact:true })).toBeVisible(); expect(payloads[0]).toBe(payloads[1]); expect(payloads).toHaveLength(2); expect((await history(page,f.url)).amendments).toHaveLength(2); });
test("source text/state changes never refresh carried snapshots while budget changes", async ({ page }) => { const f = await committed(page); await mutate(page,`/api/actions/${f.values[0].id}`,{ mutationId:randomUUID(),expectedVersion:1,title:"New live title",estimateMinutes:10,doneWhen:"New definition",milestoneId:null },"PATCH"); await mutate(page,`/api/actions/${f.values[0].id}/complete`,{ mutationId:randomUUID(),expectedVersion:2 }); await mutate(page,`/api/goals/${f.parent.id}/archive`,{ mutationId:randomUUID(),expectedVersion:1 }); await page.goto("/planning"); await begin(page); const carried = page.locator(`[data-amend-action="${f.values[0].id}"]`); await expect(carried).toContainText("Build capacity editor"); await expect(carried).toContainText("Action estimate: 2h"); await carried.getByLabel("Revised budget in minutes").fill("90"); await page.getByLabel("Reason for this amendment").fill("Budget revised while preserving historical work"); await confirm(page); const current = await history(page,f.url); expect(current.effective.commitments.find((c: { actionId:string }) => c.actionId===f.values[0].id).snapshot).toEqual(f.plan.commitments.find((c: { actionId:string })=>c.actionId===f.values[0].id).snapshot); });
test("newly added changed source requires remove/review/re-add; no automatic refresh", async ({ page }) => { const f = await committed(page); await page.goto("/planning"); await begin(page); await page.locator(`[data-amend-candidate="${f.urgent.id}"]`).getByRole("button").click(); const card=page.locator(`[data-amend-action="${f.urgent.id}"]`); await card.getByLabel("Revised budget in minutes").fill("45"); await page.getByLabel("Reason for this amendment").fill("Urgent work selected"); await mutate(page,`/api/actions/${f.urgent.id}`,{ mutationId:randomUUID(),expectedVersion:1,title:"Updated urgent work",estimateMinutes:30,doneWhen:null,milestoneId:null },"PATCH"); await page.getByRole("button",{name:"Review amendment",exact:true}).click(); await page.getByRole("dialog").getByRole("button",{name:"Confirm amendment"}).click(); await expect(page.locator(".committed-plan").getByRole("alert")).toContainText("newly added Action changed"); await expect(card).toContainText("Investigate production issue"); expect((await history(page,f.url)).amendments).toHaveLength(0); await card.getByRole("button").click(); await page.getByRole("button",{name:"Refresh eligible Actions"}).click(); await expect(page.locator(`[data-amend-candidate="${f.urgent.id}"]`)).toContainText("Updated urgent work"); await page.locator(`[data-amend-candidate="${f.urgent.id}"]`).getByRole("button").click(); await card.getByLabel("Revised budget in minutes").fill("45"); await confirm(page); await expect(page.locator(".committed-plan .commitment-list").first()).toContainText("Updated urgent work"); });
test("HTTP ownership, missing-ID indistinguishability, Origin, anonymous, strict inputs, immutable methods", async ({ page,browser }) => { const f=await committed(page); const first=(await mutate(page,f.url,command(f.plan))).amendment; const foreign=await browser.newContext(); await foreign.addCookies(cookies.B); const anonymous=await browser.newContext(); try { for (const ctx of [foreign,anonymous]) for (const [method,path,data] of [["GET",f.url,undefined],["POST",f.url,command(f.plan)],["GET",`/api/weekly-plan-amendments/${first.id}`,undefined]] as const) { const r=await ctx.request.fetch(path,{method,headers:{Origin:origin},data}); expect(r.status()).toBe(ctx===foreign?404:401); expect((await r.json()).error).not.toHaveProperty("current"); } const known=await foreign.request.get(`/api/weekly-plan-amendments/${first.id}`); const missing=await foreign.request.get(`/api/weekly-plan-amendments/${randomUUID()}`); const { requestId: _a, ...knownError } = (await known.json()).error; const { requestId: _b, ...missingError } = (await missing.json()).error; void _a; void _b; expect(knownError).toEqual(missingError); } finally { await foreign.close();await anonymous.close(); } for (const method of ["PATCH","DELETE","PUT"]) expect((await page.request.fetch(`/api/weekly-plan-amendments/${first.id}`,{method,headers:{Origin:origin},data:{}})).status()).toBe(405); expect((await page.request.post(f.url,{headers:{Origin:"https://wrong.example"},data:command(f.plan)})).status()).toBe(403); expect((await page.request.post(f.url,{headers:{Origin:origin},data:command(f.plan,{ownerId:ownerIds[0]})})).status()).toBe(400); });
test("future amendment keyboard/narrow flow and finished historical week read-only", async ({ page }) => { const f=await committed(page); const future=addDays(f.week,7); const created=(await mutate(page,"/api/weekly-plans",{mutationId:randomUUID(),weekStartDate:future,provisionalCapacityMinutes:720,reserveMinutes:180})).plan; const saved=(await mutate(page,`/api/weekly-plans/${created.id}`,{mutationId:randomUUID(),expectedVersion:1,provisionalCapacityMinutes:720,reserveMinutes:180,commitments:f.selections},"PATCH")).plan; await mutate(page,`/api/weekly-plans/${saved.id}/commit`,{mutationId:randomUUID(),expectedVersion:2}); await page.setViewportSize({width:390,height:844}); await page.goto(`/planning?week=${future}`); await begin(page); await page.getByLabel("Revised protected reserve in minutes").fill("120"); await page.getByLabel("Reason for this amendment").fill("Future week rebalanced"); await page.getByRole("button",{name:"Review amendment",exact:true}).focus(); await page.keyboard.press("Enter"); await expect(page.getByRole("dialog").getByRole("button",{name:"Keep adjusting"})).toBeFocused(); await page.keyboard.press("Escape"); await expect(page.getByRole("dialog")).toHaveCount(0); expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true); await page.getByRole("button",{name:"Cancel amendment"}).click(); await database.pool.query("UPDATE weekly_plan SET week_start_date=$1 WHERE id=$2",[addDays(f.week,-7),f.plan.id]); await page.goto(`/planning?week=${addDays(f.week,-7)}`); await expect(page.getByText("This week has finished. Its Current Plan",{exact:false})).toBeVisible(); await expect(page.getByRole("button",{name:"Amend plan",exact:true})).toHaveCount(0); expect((await page.request.post(f.url,{headers:{Origin:origin},data:command(f.plan)})).status()).toBe(409); });

test("error recovery cannot silently advance an open proposal over a newer effective version", async ({ page }) => {
  const f = await committed(page); await page.goto("/planning"); await begin(page);
  await page.locator(`[data-amend-candidate="${f.urgent.id}"]`).getByRole("button").click(); await page.locator(`[data-amend-action="${f.urgent.id}"]`).getByLabel("Revised budget in minutes").fill("45"); await page.getByLabel("Reason for this amendment").fill("Unsaved urgent proposal");
  await mutate(page, `/api/actions/${f.urgent.id}/complete`, { mutationId: randomUUID(), expectedVersion: 1 });
  await page.getByRole("button", { name: "Review amendment", exact: true }).click(); await page.getByRole("dialog").getByRole("button", { name: "Confirm amendment" }).click(); await expect(page.locator(".committed-plan").getByRole("alert")).toContainText("no longer eligible");
  await mutate(page, f.url, command(f.plan)); await page.getByRole("button", { name: "Retry loading saved plan", exact: true }).click(); await expect(page.locator(".committed-plan").getByRole("alert")).toContainText("Current Plan changed elsewhere"); await expect(page.getByLabel("Reason for this amendment")).toHaveValue("Unsaved urgent proposal"); await expect(page.getByRole("button", { name: "Review amendment", exact: true })).toBeDisabled(); expect((await history(page,f.url)).amendments).toHaveLength(1);
});
