import {fixtureSignIn} from "./sign-in-helper";
import { test, expect, type Page, type BrowserContext } from "@playwright/test";
import { randomUUID } from "node:crypto";
import { inArray } from "drizzle-orm";
import { connectDatabase } from "../../src/db/connect";
import { focusableHours, calendarAvailabilityCache, calendarConnection, calendarOAuthFlow, user } from "../../src/db/schema";
import { createAuthentication } from "../../src/server/auth-factory";
import { requireTestDatabaseURL } from "../../scripts/test-database";
const origin="http://127.0.0.1:3101",week="2028-01-03";let database:ReturnType<typeof connectDatabase>,owners:string[];const cookies:Record<string,Parameters<BrowserContext["addCookies"]>[0]>={};
const windows=[{weekday:1,startMinute:540,endMinute:720},{weekday:1,startMinute:840,endMinute:1020},{weekday:2,startMinute:540,endMinute:720},{weekday:2,startMinute:840,endMinute:1020},{weekday:3,startMinute:540,endMinute:720},{weekday:4,startMinute:540,endMinute:720},{weekday:4,startMinute:840,endMinute:1020},{weekday:5,startMinute:540,endMinute:720}];
const control=async(values:object={})=>{expect((await fetch(`${process.env.CALENDAR_TEST_ORIGIN}/control`,{method:"POST",body:JSON.stringify(values)})).ok).toBe(true);};
async function clean(){await database.db.delete(focusableHours).where(inArray(focusableHours.ownerId,owners));await database.pool.query("DELETE FROM mutation_receipt WHERE owner_id=ANY($1) AND result ? 'windows'",[owners]);await database.db.delete(calendarAvailabilityCache).where(inArray(calendarAvailabilityCache.ownerId,owners));await database.db.delete(calendarOAuthFlow).where(inArray(calendarOAuthFlow.ownerId,owners));await database.db.delete(calendarConnection).where(inArray(calendarConnection.ownerId,owners));}
test.beforeAll(async()=>{test.setTimeout(90000);const target=requireTestDatabaseURL();if(target.name==="execution_test")throw new Error("Browser tests require a new disposable DB.");database=connectDatabase(target.url);owners=(await database.db.select({id:user.id}).from(user)).map(v=>v.id);const auth=createAuthentication(database.db,{secret:process.env.BETTER_AUTH_SECRET!,baseURL:origin});for(const suffix of ["A","B"]){const response=await fixtureSignIn(()=>auth.handler(new Request(`${origin}/api/auth/sign-in/email`,{method:"POST",headers:{Origin:origin,"Content-Type":"application/json"},body:JSON.stringify({email:process.env[`TEST_USER_${suffix}_EMAIL`],password:process.env[`TEST_USER_${suffix}_PASSWORD`]})})));expect(response.status).toBe(200);cookies[suffix]=response.headers.getSetCookie().map(v=>{const pair=v.split(";")[0],i=pair.indexOf("=");return {name:pair.slice(0,i),value:pair.slice(i+1),url:origin,httpOnly:true,sameSite:"Lax" as const};});}});
test.beforeEach(async({page})=>{await clean();await control();await page.context().addCookies(cookies.A);});test.afterAll(async()=>{await clean();await database.pool.end();});
async function mutation(page:Page,path:string,data:object,method="POST"){const response=await page.request.fetch(path,{method,headers:{Origin:origin},data});expect(response.status(),await response.text()).toBe(200);return response.json();}
async function hours(page:Page,entries=windows){const saved=(await (await page.request.get("/api/focusable-hours")).json()).schedule;return mutation(page,"/api/focusable-hours",{mutationId:randomUUID(),scheduleId:saved?.id??null,expectedVersion:saved?.version??0,windows:entries},"PUT");}
async function connect(page:Page){await page.goto("/integrations");await page.getByRole("button",{name:"Connect Google Calendar",exact:true}).click();await page.getByRole("link",{name:"Approve test Calendar access"}).click();await expect(page.getByRole("checkbox",{name:/^Personal/})).toBeVisible();await page.getByRole("checkbox",{name:/^Work/}).check();await page.getByRole("checkbox",{name:/^Personal/}).check();await page.getByRole("button",{name:"Save calendar selection"}).click();await expect(page.getByText("Calendar selection saved. Weekly planning stays unchanged.")).toBeVisible();return (await (await page.request.get("/api/calendar")).json()).connection.id as string;}
async function addWindow(page:Page,day:string,index:number,start:string,end:string){await page.getByRole("button",{name:`Add ${day} window`}).click();await page.getByLabel(`${day} window ${index} start`,{exact:true}).fill(start);await page.getByLabel(`${day} window ${index} end`,{exact:true}).fill(end);}
async function planningFacts(page:Page){return (await (await page.request.get(`/api/weekly-plans?week=${week}`)).json()).view;}
test('saved Hours and busy timing appear on Calendar without changing weekly tasks',async({page})=>{await hours(page);const id=await connect(page),before=await planningFacts(page);await mutation(page,'/api/calendar/'+id+'/availability',{weekStartDate:week});await page.goto('/calendar?week='+week);await page.getByRole('button',{name:'Close weekly planner',exact:true}).click();const advisory=page.getByRole('region',{name:'Calendar context'});await expect(advisory).toContainText('Calendar-open focus time12h 30m');await advisory.locator('summary').click();await expect(advisory).toContainText('Focusable Hours24h');await expect(advisory).toContainText('Busy within those hours11h 30m');expect(await planningFacts(page)).toEqual(before);await control({partial:true});await page.getByRole('button',{name:'Refresh Calendar context',exact:true}).click();await expect(advisory).toContainText('Stale');expect(await planningFacts(page)).toEqual(before);await mutation(page,'/api/calendar/'+id+'/disconnect',{});await page.reload();await expect(advisory).toContainText('Connect Calendar');expect(await planningFacts(page)).toEqual(before);});
test("stable two-tab conflict retains draft; explicit review then intentional replacement",async({page})=>{await hours(page,[windows[0]]);await page.goto("/availability");const other=await page.context().newPage();await other.goto("/availability");await page.getByLabel("Monday window 1 end",{exact:true}).fill("13:00");await other.getByLabel("Monday window 1 end",{exact:true}).fill("14:00");await page.getByRole("button",{name:"Save Focusable Hours",exact:true}).click();await expect(page.getByText("Focusable Hours saved. Your weekly plans remain unchanged.")).toBeVisible();await other.getByRole("button",{name:"Save Focusable Hours",exact:true}).click();await expect(other.locator(".hours-settings").getByRole("alert")).toContainText("changed elsewhere");await expect(other.getByLabel("Monday window 1 end",{exact:true})).toHaveValue("14:00");await expect(other.getByRole("button",{name:"Save Focusable Hours",exact:true})).toBeDisabled();await other.getByRole("button",{name:"Review latest saved hours"}).click();await expect(other.getByLabel("Monday window 1 end",{exact:true})).toHaveValue("14:00");await other.getByRole("button",{name:"Save Focusable Hours",exact:true}).click();await expect(other.getByText("Focusable Hours saved. Your weekly plans remain unchanged.")).toBeVisible();expect((await (await page.request.get("/api/focusable-hours")).json()).schedule.version).toBe(3);await other.close();});
test("lost save acknowledgement retries identical command and original result survives later edits",async({page})=>{await page.goto("/availability");await addWindow(page,"Monday",1,"09:00","12:00");const bodies:string[]=[];let lost=false;await page.route("**/api/focusable-hours",async route=>{if(route.request().method()!=="PUT")return route.continue();bodies.push(route.request().postData()!);if(!lost){lost=true;await route.fetch();return route.abort("failed");}return route.continue();});await page.getByRole("button",{name:"Save Focusable Hours",exact:true}).click();await expect(page.getByRole("button",{name:"Retry same hours save"})).toBeVisible();await expect(page.getByLabel("Monday window 1 start",{exact:true})).toBeDisabled();await page.getByRole("button",{name:"Retry same hours save"}).click();await expect(page.getByText("Focusable Hours saved. Your weekly plans remain unchanged.")).toBeVisible();expect(bodies).toHaveLength(2);expect(bodies[1]).toBe(bodies[0]);await page.reload();await expect(page.getByLabel("Monday window 1 end",{exact:true})).toHaveValue("12:00");const first=(await (await page.request.get("/api/focusable-hours")).json()).schedule;await hours(page,[]);const retry=await mutation(page,"/api/focusable-hours",JSON.parse(bodies[0]),"PUT");expect(retry.schedule).toEqual(first);});
test("overlap and overnight errors retain fields; 24:00 end and empty schedule save",async({page})=>{await page.goto("/availability");await addWindow(page,"Monday",1,"22:00","01:00");await page.getByRole("button",{name:"Save Focusable Hours",exact:true}).click();await expect(page.locator(".hours-settings").getByRole("alert")).toContainText("Start must be before end");await page.getByLabel("Monday window 1 end",{exact:true}).fill("24:00");await addWindow(page,"Monday",2,"23:00","24:00");await page.getByRole("button",{name:"Save Focusable Hours",exact:true}).click();await expect(page.locator(".hours-settings").getByRole("alert")).toContainText("windows overlap");await page.getByRole("button",{name:"Remove Monday window 2"}).click();await page.getByRole("button",{name:"Save Focusable Hours",exact:true}).click();await expect(page.getByText("Focusable Hours saved. Your weekly plans remain unchanged.")).toBeVisible();await page.reload();await expect(page.getByLabel("Monday window 1 end",{exact:true})).toHaveValue("24:00");await page.getByRole("button",{name:"Remove Monday window 1"}).click();await page.getByRole("button",{name:"Save Focusable Hours",exact:true}).click();await expect(page.getByText("No Focusable Hours configured.",{exact:false})).toBeVisible();});
test('partial timing stays unknown on Calendar instead of suggesting free hours',async({page})=>{await hours(page);const id=await connect(page);await control({partial:true});await mutation(page,'/api/calendar/'+id+'/availability',{weekStartDate:week});await page.goto('/calendar?week='+week);const advisory=page.getByRole('region',{name:'Calendar context'});await expect(advisory).toContainText('Google timing unavailable');await expect(advisory).toContainText('Calendar-open focus timeUnknown');});
test("anonymous, origins, strict inputs, owner-scoped mutation IDs and matching foreign/missing safety",async({page,browser})=>{const first=await hours(page);const other=await browser.newContext();await other.addCookies(cookies.B);const foreign=await other.newPage();const anonymous=await browser.newContext();for(const path of ["/api/focusable-hours",`/api/focus-availability?week=${week}`])expect((await anonymous.request.get(`${origin}${path}`)).status()).toBe(401);const input={mutationId:randomUUID(),scheduleId:null,expectedVersion:0,windows};expect((await page.request.put("/api/focusable-hours",{headers:{Origin:"https://evil.test"},data:input})).status()).toBe(403);expect((await page.request.put("/api/focusable-hours",{headers:{Origin:origin},data:{...input,ownerId:owners[1]}})).status()).toBe(400);expect((await (await foreign.request.get(`${origin}/api/focusable-hours`)).json()).schedule).toBeNull();
for(const id of [first.schedule.id,randomUUID()]){expect((await foreign.request.get(`${origin}/api/focusable-hours/${id}`)).status()).toBe(404);expect((await foreign.request.get(`${origin}/api/focus-availability?week=${week}&scheduleId=${id}`)).status()).toBe(404);expect((await foreign.request.put(`${origin}/api/focusable-hours`,{headers:{Origin:origin},data:{...input,scheduleId:id,expectedVersion:1}})).status()).toBe(404);}const own=await foreign.request.put(`${origin}/api/focusable-hours`,{headers:{Origin:origin},data:input});expect(own.status()).toBe(200);expect((await (await foreign.request.get(`${origin}/api/focus-availability?week=${week}`)).json()).availability.openMinutes).toBeNull();expect((await (await page.request.get("/api/focusable-hours")).json()).schedule).toEqual(first.schedule);await anonymous.close();await other.close();});
test('selection invalidation leaves Calendar-open time unknown; narrow Hours remain usable',async({page})=>{await hours(page);const id=await connect(page);await mutation(page,'/api/calendar/'+id+'/availability',{weekStartDate:week});const connection=(await (await page.request.get('/api/calendar')).json()).connection;await mutation(page,'/api/calendar/'+id,{expectedVersion:connection.version,calendarIds:[]},'PATCH');await page.goto('/calendar?week='+week);await expect(page.getByRole('region',{name:'Calendar context'})).toContainText('Calendar-open focus timeUnknown');await page.setViewportSize({width:390,height:844});await page.goto('/availability');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);});
