import {fixtureSignIn} from "./sign-in-helper";
import { test, expect, type Page, type BrowserContext } from "@playwright/test";
import { randomUUID } from "node:crypto";
import { inArray } from "drizzle-orm";
import { connectDatabase } from "../../src/db/connect";
import { calendarAvailabilityCache, calendarConnection, calendarOAuthFlow, user } from "../../src/db/schema";
import { createAuthentication } from "../../src/server/auth-factory";
import { requireTestDatabaseURL } from "../../scripts/test-database";
import { signInThroughUI } from "./sign-in-helper";
const origin = "http://127.0.0.1:3101"; let database: ReturnType<typeof connectDatabase>, ownerIds: string[]; const cookies: Record<string, Parameters<BrowserContext["addCookies"]>[0]> = {};
const control = async (values: object = {}) => { const result = await fetch(`${process.env.CALENDAR_TEST_ORIGIN}/control`, { method: "POST", body: JSON.stringify(values) }); expect(result.ok).toBe(true); };
async function cleanCalendars() { await database.db.delete(calendarAvailabilityCache).where(inArray(calendarAvailabilityCache.ownerId, ownerIds)); await database.db.delete(calendarOAuthFlow).where(inArray(calendarOAuthFlow.ownerId, ownerIds)); await database.db.delete(calendarConnection).where(inArray(calendarConnection.ownerId, ownerIds)); }
test.beforeAll(async () => {test.setTimeout(90000); const target = requireTestDatabaseURL(); if (target.name === "execution_test") throw new Error("Calendar browser tests require a new isolated database."); database = connectDatabase(target.url); ownerIds = (await database.db.select({ id: user.id }).from(user)).map(v => v.id); const auth = createAuthentication(database.db, { secret: process.env.BETTER_AUTH_SECRET!, baseURL: origin }); for (const suffix of ["A", "B"]) { const result = await fixtureSignIn(()=>auth.handler(new Request(`${origin}/api/auth/sign-in/email`, { method: "POST", headers: { Origin: origin, "Content-Type": "application/json" }, body: JSON.stringify({ email: process.env[`TEST_USER_${suffix}_EMAIL`], password: process.env[`TEST_USER_${suffix}_PASSWORD`] }) }))); expect(result.status).toBe(200); cookies[suffix] = result.headers.getSetCookie().map(value => { const pair = value.split(";")[0], i = pair.indexOf("="); return { name: pair.slice(0, i), value: pair.slice(i + 1), url: origin, httpOnly: true, sameSite: "Lax" as const }; }); } });
test.beforeEach(async ({ page }) => { await cleanCalendars(); await control(); await page.context().addCookies(cookies.A); }); test.afterAll(async () => { await cleanCalendars(); await database.pool.end(); });
async function mutate(page: Page, path: string, input?: object, method = "POST") { const result = await page.request.fetch(path, { method, headers: { Origin: origin }, data: input }); expect(result.status(), await result.text()).toBe(200); return result.json(); }
async function connect(page: Page) { await page.goto("/integrations"); await page.getByRole("button", { name: "Connect Google Calendar", exact: true }).click(); await expect(page.getByRole("heading", { name: "Simulated Google Calendar consent" })).toBeVisible(); await page.getByRole("link", { name: "Approve test Calendar access" }).click(); await page.waitForURL(/integrations/); if (!page.url().endsWith("calendar=success")) { const flows = await database.db.select({ result: calendarOAuthFlow.result }).from(calendarOAuthFlow); const calls = await (await fetch(`${process.env.CALENDAR_TEST_ORIGIN}/control`)).json(); throw new Error(`Simulated callback failed: ${JSON.stringify({ flows, calls })}`); } await expect(page.getByText("Google Calendar connected. Choose which calendars inform planning.", { exact: true })).toBeVisible(); await expect(page.getByRole("checkbox", { name: "Personal", exact: false })).toBeVisible(); await expect(page.getByRole("button", { name: "Save calendar selection" })).toBeEnabled(); return (await (await page.request.get("/api/calendar")).json()).connection; }
async function select(page: Page) { const value = await connect(page); await page.getByRole("checkbox", { name: /^Work/ }).check(); await page.getByRole("checkbox", { name: /^Personal/ }).check(); await page.getByRole("button", { name: "Save calendar selection" }).click(); await expect(page.getByText("Calendar selection saved. Weekly planning stays unchanged.")).toBeVisible(); return value.id as string; }
async function refresh(page: Page) { const details = page.locator(".focus-daily"); await expect(details).toBeVisible(); if (!await details.evaluate(e=>(e as HTMLDetailsElement).open)) await details.locator("summary").click(); await page.getByRole("button", { name: "Refresh Calendar load" }).click(); await expect(page.getByRole("button", { name: "Refresh Calendar load" }).or(page.getByRole("link", { name: "Reconnect Google Calendar", exact: true }))).toBeVisible(); }
async function planningFacts(page: Page) { const workspace = await (await page.request.get("/api/weekly-plans")).json(); if (workspace.view?.plan.state === "committed") return (await (await page.request.get(`/api/weekly-plans/${workspace.view.plan.id}/amendments`)).json()); return workspace.view; }
test("real sign in → explicit simulated consent → select work/personal → load/advisory → reload → failed refresh/stale → disconnect leaves plan unchanged", async ({ page }) => {
  test.setTimeout(90000);
  await page.context().clearCookies(); await page.goto("/sign-in"); await page.getByLabel("Email", { exact: true }).fill(process.env.TEST_USER_A_EMAIL!); await page.getByLabel("Password", { exact: true }).fill(process.env.TEST_USER_A_PASSWORD!); await signInThroughUI(page);
  const before = await planningFacts(page); const id = await select(page); await page.getByRole("link", { name: "Return to weekly planning" }).click(); const load = page.getByLabel("Calendar load", { exact: true }); await expect(load).toContainText("Calendar availability is unavailable"); await refresh(page);
  await expect(load).toContainText("Google-reported busy time: 15h 30m"); await expect(load).toContainText("Tue5h 30m busy"); await expect(load).toContainText("Fri1h busy"); await expect(load).toContainText("Your focus capacity remains your decision"); expect(await planningFacts(page)).toEqual(before);
  await page.reload(); await expect(load).toContainText("Fresh"); await expect(load).toContainText("15h 30m"); await control({ failure: true }); await refresh(page); await expect(load).toContainText("Stale · previously fetched"); await expect(load).toContainText("could not be reached"); await expect(load).toContainText("15h 30m"); expect(await planningFacts(page)).toEqual(before);
  await control(); await page.goto("/integrations"); await expect(page.getByRole("checkbox", { name: /^Work/ })).toBeChecked(); await expect(page.getByRole("checkbox", { name: /^Personal/ })).toBeChecked(); await expect(page.getByRole("button", { name: "Disconnect Google Calendar" })).toBeEnabled(); await page.getByRole("button", { name: "Disconnect Google Calendar" }).click(); const dialog = page.getByRole("dialog"); await expect(dialog.getByRole("button", { name: "Keep connected" })).toBeFocused(); await dialog.getByRole("button", { name: "Disconnect Calendar", exact: true }).click(); await expect(page.getByText("Calendar disconnected. Credentials, selection and cached timing removed.")).toBeVisible(); const workspace = await (await page.request.get(`/api/calendar/${id}`)).json(); expect(workspace.connection.state).toBe("disconnected"); expect(workspace.availability.status).toBe("not_configured"); expect(await planningFacts(page)).toEqual(before);
});
test("primary is never selected automatically and unavailable roles/metadata do not reach the UI", async ({ page }) => { await connect(page); await expect(page.getByRole("checkbox", { name: /^Work/ })).not.toBeChecked(); await expect(page.getByRole("checkbox", { name: /^Personal/ })).not.toBeChecked(); await expect(page.getByText("Unavailable role")).toHaveCount(0); const value = await (await page.request.get("/api/calendar")).json(); expect(value.connection.selectedCalendarIds).toEqual([]); expect(JSON.stringify(value)).not.toMatch(/fixture-access|fixture-refresh|encryptedCredentials|description|attendees/); await page.reload(); await expect(page.getByRole("checkbox", { name: /^Work/ })).not.toBeChecked(); });
test("partial failure without previous success stays unavailable; later failure preserves complete timing", async ({ page }) => { await select(page); await control({ partial: true }); await page.goto("/planning"); const load = page.getByLabel("Calendar load", { exact: true }); await refresh(page); await expect(load).toContainText("availability is incomplete"); await expect(load).toContainText("No complete timing is available yet"); await expect(load).not.toContainText("0m busy"); await control(); await refresh(page); await expect(load).toContainText("15h 30m"); await control({ partial: true }); await refresh(page); await expect(load).toContainText("Stale · previously fetched"); await expect(load).toContainText("15h 30m"); await page.reload(); await expect(load).toContainText("Stale · previously fetched"); });
test("externally inaccessible selected calendar requires explicit removal; selection clears old timing", async ({ page }) => { await select(page); await page.goto("/planning"); await refresh(page); await control({ missingPersonal: true }); await page.goto("/integrations"); await expect(page.getByText("Remove this selection before saving.")).toBeVisible(); await expect(page.getByRole("button", { name: "Save calendar selection" })).toBeDisabled(); await page.getByRole("checkbox", { name: /^Unavailable calendar/ }).uncheck(); await page.getByRole("button", { name: "Save calendar selection" }).click(); await expect(page.getByText("Calendar selection saved. Weekly planning stays unchanged.")).toBeVisible(); await page.goto("/planning"); await expect(page.getByLabel("Calendar load", { exact: true })).toContainText("Calendar availability is unavailable"); await refresh(page); await expect(page.getByLabel("Calendar load", { exact: true })).toContainText("14h 30m"); });
test("revoked credentials show reconnect; explicit repair creates no duplicate connection", async ({ page }) => { const id = await select(page); await page.goto("/planning"); await refresh(page); await control({ revoked: true }); await refresh(page); await expect(page.getByLabel("Calendar load", { exact: true })).toContainText("Reconnect Google Calendar"); await page.goto("/integrations"); await expect(page.getByText("Connection needs attention.")).toBeVisible(); await control(); await page.getByRole("button", { name: "Reconnect Google Calendar" }).click(); await page.getByRole("link", { name: "Approve test Calendar access" }).click(); await expect(page.getByRole("checkbox", { name: /^Personal/ })).toBeChecked(); const value = await (await page.request.get("/api/calendar")).json(); expect(value.connection.id).toBe(id); expect(value.connection.state).toBe("connected"); expect(await database.db.select().from(calendarConnection)).toHaveLength(1); });
test("anonymous/foreign resources and mutation origins retain secure HTTP semantics", async ({ page, browser }) => { const id = await select(page); const other = await browser.newContext(); await other.addCookies(cookies.B); const foreign = await other.newPage(); const missing = randomUUID(); const normalize = async (result: Awaited<ReturnType<Page["request"]["get"]>>) => { expect(result.status()).toBe(404); const value = await result.json() as { error: { requestId?: string } }; delete value.error.requestId; return value; };
  for (const [path, method, body] of [["", "GET", undefined], ["", "PATCH", { expectedVersion: 1, calendarIds: [] }], ["/calendars", "POST", undefined], ["/availability", "POST", { weekStartDate: "2026-09-28" }], ["/disconnect", "POST", undefined]] as const) {
    const first = await foreign.request.fetch(`${origin}/api/calendar/${id}${path}`, { method, headers: { Origin: origin }, data: body }); const second = await foreign.request.fetch(`${origin}/api/calendar/${missing}${path}`, { method, headers: { Origin: origin }, data: body }); expect(await normalize(first)).toEqual(await normalize(second));
  }
  const anonymous = await browser.newContext(); expect((await anonymous.request.post(`${origin}/api/calendar/connect`, { headers: { Origin: origin } })).status()).toBe(401); expect((await page.request.post("/api/calendar/connect", { headers: { Origin: "https://evil.test" } })).status()).toBe(403); expect((await foreign.request.get(`${origin}/api/calendar`)).status()).toBe(200); await anonymous.close(); await other.close();
});
test("bad state, missing scope and cancelled consent safely return to clean Integrations URLs", async ({ page }) => { await page.goto("/api/calendar/callback?state=bad&code=fixture-invalid"); await expect(page).toHaveURL(/\/integrations\?calendar=failed$/); expect((await (await page.request.get("/api/calendar")).json()).connection).toBeNull(); await control({ limitedScopes: true }); await page.getByRole("button", { name: "Connect Google Calendar" }).click(); await page.getByRole("link", { name: "Approve test Calendar access" }).click(); await expect(page).toHaveURL(/\/integrations\?calendar=failed$/); expect((await (await page.request.get("/api/calendar")).json()).connection).toBeNull(); const auth = await mutate(page, "/api/calendar/connect"); const state = new URL(auth.url).searchParams.get("state"); await page.goto(`/api/calendar/callback?state=${state}&error=access_denied`); await expect(page).toHaveURL(/\/integrations\?calendar=cancelled$/); });
test("concurrent selection conflict retains unsaved choices until latest selection review", async ({ page }) => { const id = await select(page); await page.getByRole("checkbox", { name: /^Personal/ }).uncheck(); const value = (await (await page.request.get("/api/calendar")).json()).connection; await mutate(page, `/api/calendar/${id}`, { expectedVersion: value.version, calendarIds: ["personal-calendar"] }, "PATCH"); await page.getByRole("button", { name: "Save calendar selection" }).click(); await expect(page.getByText("Calendar selection changed elsewhere. Review the latest saved selection.")).toBeVisible(); await expect(page.getByRole("checkbox", { name: /^Work/ })).toBeChecked(); await expect(page.getByRole("checkbox", { name: /^Personal/ })).not.toBeChecked(); await expect(page.getByRole("button", { name: "Save calendar selection" })).toBeDisabled(); await page.getByRole("button", { name: "Review latest saved selection" }).click(); await expect(page.getByRole("checkbox", { name: /^Work/ })).not.toBeChecked(); await expect(page.getByRole("checkbox", { name: /^Personal/ })).toBeChecked(); });
test("lost selection acknowledgement retries identical payload and persists through reload", async ({ page }) => { const value = await connect(page); await page.getByRole("checkbox", { name: /^Work/ }).check(); const bodies: string[] = []; let lost = false; await page.route(`**/api/calendar/${value.id}`, async route => { if (route.request().method() !== "PATCH") return route.continue(); bodies.push(route.request().postData()!); if (!lost) { lost = true; await route.fetch(); return route.abort("failed"); } return route.continue(); }); await page.getByRole("button", { name: "Save calendar selection" }).click(); await expect(page.getByRole("button", { name: "Retry same Calendar change" })).toBeVisible(); await expect(page.getByRole("checkbox", { name: /^Work/ })).toBeDisabled(); await page.getByRole("button", { name: "Retry same Calendar change" }).click(); await expect(page.getByText("Calendar selection saved. Weekly planning stays unchanged.")).toBeVisible(); expect(bodies).toHaveLength(2); expect(bodies[1]).toBe(bodies[0]); await page.reload(); await expect(page.getByRole("checkbox", { name: /^Work/ })).toBeChecked(); });
test("narrow layout, keyboard disconnect cancellation and explicit zero busy display", async ({ page }) => { await page.setViewportSize({ width: 390, height: 844 }); await select(page); await page.getByRole("button", { name: "Disconnect Google Calendar" }).focus(); await page.keyboard.press("Enter"); await expect(page.getByRole("dialog").getByRole("button", { name: "Keep connected" })).toBeFocused(); await page.keyboard.press("Escape"); await expect(page.getByRole("button", { name: "Disconnect Google Calendar" })).toBeFocused(); await control({ emptyBusy: true }); await page.goto("/planning"); await refresh(page); await expect(page.getByLabel("Calendar load", { exact: true })).toContainText("Google-reported busy time: 0m"); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); });
