import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
import {mkdir,writeFile} from 'node:fs/promises';
import {connectDatabase} from '../../src/db/connect';
import {requireTestDatabaseURL} from '../../scripts/test-database';
import {provisionLocalUser} from '../../scripts/local-user';
import {createAuthentication} from '../../src/server/auth-factory';
import {fixtureSignIn} from './sign-in-helper';
import {executionFixture} from '../focus-database';
import {databaseCoaching,coachingCalendarFixture,coachingCleanupTables} from '../coaching-database';
const database=connectDatabase(requireTestDatabaseURL().url),origin='http://127.0.0.1:3101',headers={Origin:origin},screenshots='docs/r5e-evidence/fixtures';let owner='';
async function control(mode='useful'){return (await fetch(`${process.env.CHATGPT_TEST_ORIGIN}/control`,{method:'POST',body:JSON.stringify({mode,subject:'chatgpt-subject',clientId:'oaiapp_fixture'})})).json();}
test.beforeEach(async({page})=>{await control();owner=(await provisionLocalUser(database.db,{email:`chatgpt-browser-${randomUUID()}@example.test`,password:'Disposable-ChatGPT-Browser!',name:'ChatGPT browser',timezone:'Europe/London'})).id;const row=(await database.pool.query('SELECT email FROM app_user WHERE id=$1',[owner])).rows[0];const auth=createAuthentication(database.db,{secret:process.env.BETTER_AUTH_SECRET!,baseURL:origin}),login=await fixtureSignIn(()=>auth.handler(new Request(`${origin}/api/auth/sign-in/email`,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({email:row.email,password:'Disposable-ChatGPT-Browser!'})})));await page.context().addCookies(login.headers.getSetCookie().map(v=>{const p=v.split(';')[0],i=p.indexOf('=');return {name:p.slice(0,i),value:p.slice(i+1),url:origin,httpOnly:true,sameSite:'Lax' as const};}));});
test.afterEach(async()=>{for(const t of ['chatgpt_oauth_flow','chatgpt_connection',...coachingCleanupTables])await database.pool.query(`DELETE FROM ${t} WHERE owner_id=$1`,[owner]);await database.pool.query('DELETE FROM app_user WHERE id=$1',[owner]);});test.afterAll(()=>database.pool.end());
async function connect(page:import('@playwright/test').Page){await page.goto('/integrations');await page.getByRole('button',{name:'Continue with ChatGPT',exact:true}).click();await expect(page.getByLabel('Coaching model')).toBeEnabled();await page.getByLabel('Coaching model').selectOption('fixture-openai');await expect(page.getByRole('button',{name:'Use ChatGPT for coaching',exact:true})).toBeEnabled();await page.getByRole('button',{name:'Use ChatGPT for coaching',exact:true}).click();await expect(page.getByRole('button',{name:'Use configured provider'})).toBeEnabled();}
test('real OAuth client → model discovery/selection → R5D Evidence/Preview/Schedule → stale; reload does not invoke AI',async({page})=>{test.setTimeout(90000);const now='2026-10-03T09:00:00.000Z',week='2028-01-03',d=databaseCoaching(database.db,database.pool,()=>now);await writeFile(process.env.EXECUTION_TEST_CLOCK_FILE!,now);await page.setViewportSize({width:1440,height:1000});await connect(page);await executionFixture(database.db,{userId:owner},week,()=>now);await d.hours.save({userId:owner},{mutationId:randomUUID(),expectedVersion:0,scheduleId:null,windows:[{weekday:1,startMinute:540,endMinute:1020}]});await coachingCalendarFixture(database.db,database.pool,{userId:owner},week,now);await mkdir(screenshots,{recursive:true});await page.screenshot({path:`screenshots/connection.png`.replace('screenshots',screenshots),fullPage:true});const before=(await control()).responseCount;await page.goto(`/calendar?week=${week}`);const coach=page.getByRole('region',{name:'Coach',exact:true});await coach.getByRole('button',{name:'Get coaching',exact:true}).click();await expect(coach.getByRole('button',{name:'Preview',exact:true})).toBeVisible();await coach.getByText('Why?',{exact:true}).first().click();await expect(coach).toContainText('Evidence');await coach.getByRole('button',{name:'Preview',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('No Google busy overlap');await page.getByRole('dialog').getByRole('button',{name:'Schedule block',exact:true}).click();await expect(coach).toContainText('Facts changed since this advice');await page.reload();expect((await control()).responseCount).toBe(before+1);expect((await database.pool.query('SELECT id FROM time_block WHERE owner_id=$1',[owner])).rows).toHaveLength(2);expect((await database.pool.query('SELECT id FROM weekly_plan_amendment WHERE owner_id=$1',[owner])).rows).toHaveLength(0);});
test('missing plan permission is a clear connected state, no model/coaching invocation',async({page})=>{await control('no_permission');await page.goto('/integrations');await page.getByRole('button',{name:'Continue with ChatGPT',exact:true}).click();await expect(page.getByText('Connected to ChatGPT, but plan usage is not enabled.').first()).toBeVisible();await expect(page.getByLabel('Coaching model')).toHaveCount(0);await expect(page.getByRole('button',{name:'Enable plan usage'})).toBeVisible();});
test('disconnect/reconnect keeps registration/model, revocation failure is honest, narrow settings have no overflow',async({page})=>{await connect(page);const first=(await database.pool.query('SELECT id,client_id,selected_model FROM chatgpt_connection WHERE owner_id=$1',[owner])).rows[0];await control('revoke_failure');await page.getByRole('button',{name:'Disconnect',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Disconnect ChatGPT',exact:true}).click();await expect(page.getByText('Disconnected locally.',{exact:true})).toBeVisible();await expect(page.getByText('Credentials removed locally.',{exact:false})).toBeVisible();await control();await page.getByRole('button',{name:'Reconnect',exact:true}).click();await expect(page.getByLabel('Coaching model')).toHaveValue('fixture-openai');expect((await database.pool.query('SELECT id,client_id,selected_model FROM chatgpt_connection WHERE owner_id=$1',[owner])).rows[0]).toEqual(first);await page.setViewportSize({width:390,height:844});await page.reload();await expect(page.getByLabel('Coaching model')).toBeEnabled();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);await page.screenshot({path:`${screenshots}/narrow-connection.png`,fullPage:true});expect(await page.content()).not.toContain('access-fixture-secret');});
test('authentication, Origin, strict payloads, foreign IDs and callback clean errors',async({page,browser})=>{const anonymous=await browser.newContext();expect((await anonymous.request.get(`${origin}/api/chatgpt`)).status()).toBe(401);await anonymous.close();expect((await page.request.post('/api/chatgpt/connect',{data:{connectionId:null}})).status()).toBe(403);expect((await page.request.post('/api/chatgpt/connect',{headers,data:{connectionId:null,ownerId:'forged'}})).status()).toBe(400);expect((await page.request.post('/api/chatgpt/connect',{headers,data:{connectionId:randomUUID()}})).status()).toBe(404);expect((await page.request.patch(`/api/chatgpt/${randomUUID()}`,{headers,data:{expectedVersion:1,selectedModel:'fixture-openai'}})).status()).toBe(404);expect((await page.request.post(`/api/chatgpt/${randomUUID()}/disconnect`,{headers,data:{expectedVersion:1}})).status()).toBe(404);await page.goto('/auth/chatgpt/callback?state=wrong&code=PRIVATE_CODE');await expect(page).toHaveURL(/integrations\?chatgpt=failed$/);expect(await page.content()).not.toContain('PRIVATE_CODE');expect((await page.request.get('/api/chatgpt')).headers()['cache-control']).toBe('private, no-store');});
