import {test,expect} from '@playwright/test';
import {fixtureSignIn} from './sign-in-helper';
import {createAuthentication} from '../../src/server/auth-factory';
import {randomUUID} from 'node:crypto';
import {writeFile,mkdir} from 'node:fs/promises';
import {connectDatabase} from '../../src/db/connect';
import {requireTestDatabaseURL} from '../../scripts/test-database';
import {provisionLocalUser} from '../../scripts/local-user';
import {executionFixture} from '../focus-database';
import {weeklyFixture} from '../weekly-review-fixture';
import {databaseCoaching,coachingCleanupTables,coachingCalendarFixture} from '../coaching-database';
const database=connectDatabase(requireTestDatabaseURL().url),origin='http://127.0.0.1:3101',headers={Origin:origin},week='2028-01-03',clock=()=> '2026-10-03T09:00:00.000Z';let owner='';
const screenshots='docs/r5d-evidence/fixtures';
async function control(mode='useful',reset=false){return (await fetch(`${process.env.AI_TEST_BASE_URL}/control`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,reset})})).json();}
test.beforeEach(async({page})=>{test.setTimeout(90000);await writeFile(process.env.EXECUTION_TEST_CLOCK_FILE!,clock());await control('useful',true);const email=`coach-browser-${randomUUID()}@example.test`;owner=(await provisionLocalUser(database.db,{email,password:'Disposable-Coaching-Browser!',name:'Morgan Lee',timezone:'Europe/London'})).id;const auth=createAuthentication(database.db,{secret:process.env.BETTER_AUTH_SECRET!,baseURL:origin}),login=await fixtureSignIn(()=>auth.handler(new Request(`${origin}/api/auth/sign-in/email`,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({email,password:'Disposable-Coaching-Browser!'})})));await page.context().addCookies(login.headers.getSetCookie().map(value=>{const pair=value.split(';')[0],i=pair.indexOf('=');return {name:pair.slice(0,i),value:pair.slice(i+1),url:origin,httpOnly:true,sameSite:'Lax' as const};}));});
test.afterEach(async()=>{for(const t of coachingCleanupTables)await database.pool.query(`DELETE FROM ${t} WHERE owner_id=$1`,[owner]);await database.pool.query('DELETE FROM app_user WHERE id=$1',[owner]);});test.afterAll(()=>database.pool.end());
async function seed(){const f=await executionFixture(database.db,{userId:owner},week,clock),d=databaseCoaching(database.db,database.pool,clock);const c=await d.cycles.create({userId:owner},{mutationId:randomUUID(),title:'Make the planning loop useful',intent:'One small usable slice, with breathing room',startDate:'2026-10-01',endDate:'2026-11-30',goals:[{goalId:f.goal.id,goalVersion:1}]});await d.cycles.transition({userId:owner},c.id,'activate',{mutationId:randomUUID(),expectedVersion:1});await d.hours.save({userId:owner},{mutationId:randomUUID(),scheduleId:null,expectedVersion:0,windows:[{weekday:1,startMinute:540,endMinute:1020}]});await coachingCalendarFixture(database.db,database.pool,{userId:owner},week,clock());return f;}
test('explicit generation → grounded Why → ordinary preview → schedule; reload has no model call and facts stale afterward',async({page})=>{await seed();await page.setViewportSize({width:1440,height:1000});await page.goto(`/calendar?week=${week}`);const coach=page.getByRole('region',{name:'Coach',exact:true});await expect(coach.getByRole('button',{name:'Get coaching',exact:true})).toBeVisible();expect((await control()).calls).toBe(0);await coach.getByRole('button',{name:'Get coaching',exact:true}).click();await expect(coach.getByRole('button',{name:'Preview',exact:true})).toBeVisible();expect((await control()).calls).toBe(1);await coach.getByText('Why?',{exact:true}).first().click();await expect(coach).toContainText('180m committed, 120m scheduled');await mkdir(screenshots,{recursive:true});await page.screenshot({path:`${screenshots}/calendar-coach.png`,fullPage:true});await page.reload();await expect(coach.getByRole('button',{name:'Preview',exact:true})).toBeVisible();expect((await control()).calls).toBe(1);await coach.getByRole('button',{name:'Preview',exact:true}).click();await expect(page.getByRole('dialog')).toContainText('After this block');await expect(page.getByRole('dialog')).toContainText('No Google busy overlap in this snapshot.');await page.screenshot({path:`${screenshots}/schedule-preview.png`,fullPage:true});await page.getByRole('dialog').getByRole('button',{name:'Schedule block',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(coach).toContainText('Facts changed since this advice');await expect(coach.getByRole('button',{name:'Preview',exact:true})).toBeDisabled();expect((await control()).calls).toBe(1);expect((await database.pool.query('SELECT * FROM time_block WHERE owner_id=$1',[owner])).rows).toHaveLength(2);expect((await database.pool.query('SELECT * FROM weekly_plan_amendment WHERE owner_id=$1',[owner])).rows).toHaveLength(0);await page.screenshot({path:`${screenshots}/stale-advice.png`,fullPage:true});});
test('stale source change rejects an already-open preview without creating a block',async({page})=>{const f=await seed();await page.goto(`/calendar?week=${week}`);const coach=page.getByRole('region',{name:'Coach',exact:true});await coach.getByRole('button',{name:'Get coaching',exact:true}).click();await coach.getByRole('button',{name:'Preview',exact:true}).click();await expect(page.getByRole('dialog').getByRole('button',{name:'Schedule block',exact:true})).toBeVisible();await f.actions.completeAction({userId:owner},f.action.id,{mutationId:randomUUID(),expectedVersion:1});await page.getByRole('dialog').getByRole('button',{name:'Schedule block',exact:true}).click();await expect(page.getByRole('dialog').getByRole('alert')).toContainText('stale');expect((await database.pool.query('SELECT * FROM time_block WHERE owner_id=$1',[owner])).rows).toHaveLength(1);});
test('uncertain generation retries the same run; provider failure stays small and core Calendar remains usable',async({page})=>{await seed();await page.goto(`/calendar?week=${week}`);const coach=page.getByRole('region',{name:'Coach',exact:true});let lost=true;await page.route('**/api/coaching',async route=>{if(route.request().method()==='POST'&&lost){lost=false;await route.fetch();await route.abort('failed');}else await route.continue();});await coach.getByRole('button',{name:'Get coaching',exact:true}).click();await coach.getByRole('button',{name:'Retry same coaching request',exact:true}).click();await expect(coach.getByRole('button',{name:'Preview',exact:true})).toBeVisible();expect((await control()).calls).toBe(1);await control('authentication');await coach.getByRole('button',{name:'Refresh coaching',exact:true}).click();await expect(coach).toContainText('connection needs attention');await expect(page.getByRole('region',{name:'Work for this week',exact:true})).toBeVisible();await expect(page.getByRole('link',{name:'Goals',exact:true})).toBeVisible();await page.screenshot({path:`${screenshots}/provider-error.png`,fullPage:true});expect(await page.content()).not.toContain('SECRET_FIXTURE_PAYLOAD');});
test('selective empty response, mobile layout and calm disabled UI',async({page})=>{await seed();await control('empty');await page.setViewportSize({width:390,height:844});await page.goto(`/calendar?week=${week}`);const coach=page.getByRole('region',{name:'Coach',exact:true});await coach.getByRole('button',{name:'Get coaching',exact:true}).click();await expect(coach).toContainText('No useful suggestion is supported');expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);await page.screenshot({path:`${screenshots}/mobile-empty.png`,fullPage:true});await page.route('**/api/coaching?**',route=>route.fulfill({json:{enabled:false,provider:null,configuration:'disabled',fingerprint:null,run:null}}));await page.reload();await expect(coach).toContainText('Connect an AI provider');await expect(coach.getByRole('button',{name:'Get coaching',exact:true})).toHaveCount(0);});
test('Weekly Review coaching is explicit; only finalized reflection text leaves the app and decisions stay human-owned',async({page})=>{const f=await weeklyFixture(database.db,{userId:owner},'2026-09-28'),draft=await f.reviews.save({userId:owner},f.save());await f.reviews.finalize({userId:owner},draft.id,{mutationId:randomUUID(),expectedVersion:1,confirmArchive:true});await writeFile(process.env.EXECUTION_TEST_CLOCK_FILE!,'2026-10-12T09:00:00.000Z');const before=(await database.pool.query('SELECT row_to_json(t) FROM weekly_review_decision t WHERE owner_id=$1',[owner])).rows;await page.setViewportSize({width:1440,height:1000});await page.goto('/review?week=2026-09-28');const coach=page.getByRole('region',{name:'Coach’s perspective',exact:true});await coach.getByRole('button',{name:'Get coaching',exact:true}).click();await expect(coach.locator('.coach-suggestion')).toHaveCount(1);const state=await control(),sent=JSON.stringify(state.lastContext);expect(sent).toContain('Keep the review focused.');expect(sent).toContain('Core flow delivered, with tests still to do.');expect(sent).not.toContain('An unfinished daily draft.');expect(sent).not.toContain('Interrupted; tests remain.');expect((await database.pool.query('SELECT row_to_json(t) FROM weekly_review_decision t WHERE owner_id=$1',[owner])).rows).toEqual(before);await page.screenshot({path:`${screenshots}/weekly-perspective.png`,fullPage:true});});
test('authentication, Origin, strict fields, foreign runs and no AI mutation endpoint',async({page,browser})=>{await seed();const anonymous=await browser.newContext();expect((await anonymous.request.get(`${origin}/api/coaching?contextType=calendar&week=${week}`)).status()).toBe(401);await anonymous.close();const view=await page.request.get(`/api/coaching?contextType=calendar&week=${week}`);expect(view.headers()['cache-control']).toBe('private, no-store');const command={contextType:'calendar',week,fingerprint:(await view.json()).fingerprint,mutationId:randomUUID()};expect((await page.request.post('/api/coaching',{data:command})).status()).toBe(403);expect((await page.request.post('/api/coaching',{headers,data:{...command,ownerId:'forged'}})).status()).toBe(400);const generated=await page.request.post('/api/coaching',{headers,data:command});expect(generated.status()).toBe(200);const id=(await generated.json()).run.id;expect((await page.request.post(`/api/coaching/${id}/apply`,{headers,data:{index:0}})).status()).toBe(404);expect((await page.request.post(`/api/coaching/${randomUUID()}/preview`,{headers,data:{index:0}})).status()).toBe(404);});
