import {test,expect,type Page} from '@playwright/test';
import {fixtureAPISignIn} from './sign-in-helper';
import {randomUUID} from 'node:crypto';
import {writeFile} from 'node:fs/promises';
import {connectDatabase} from '../../src/db/connect';
import {provisionLocalUser} from '../../scripts/local-user';
import {requireTestDatabaseURL} from '../../scripts/test-database';
import {weeklyFixture} from '../weekly-review-fixture';
import type {FocusCycle} from '../../src/modules/focus-cycles/domain';
const origin='http://127.0.0.1:3101',database=connectDatabase(requireTestDatabaseURL().url);let owner='',email='';let testOwners:string[]=[];
const headers={Origin:origin},fields=(overrides={})=>({mutationId:randomUUID(),title:'October — November: One Better',intent:'A useful small planning practice',startDate:'2026-10-01',endDate:'2026-11-30',goals:[],...overrides});
async function createGoal(page:Page,title='Ship One Better'){const r=await page.request.post('/api/goals',{headers,data:{mutationId:randomUUID(),title,outcome:'Usable every week'}});expect(r.status()).toBe(200);return (await r.json()).goal;}
async function createCycle(page:Page,overrides={}){const r=await page.request.post('/api/focus-cycles',{headers,data:fields(overrides)});expect(r.status()).toBe(200);return (await r.json()).cycle as FocusCycle;}
async function transition(page:Page,c:FocusCycle,kind:string){const r=await page.request.post(`/api/focus-cycles/${c.id}/${kind}`,{headers,data:{mutationId:randomUUID(),expectedVersion:c.version}});expect(r.status()).toBe(200);return (await r.json()).cycle as FocusCycle;}
test.beforeEach(async({page})=>{await writeFile(process.env.EXECUTION_TEST_CLOCK_FILE!,'2026-10-03T09:00:00.000Z');email=`cycle-browser-${randomUUID()}@example.test`;owner=(await provisionLocalUser(database.db,{email,password:'Disposable-Cycle-Browser!',name:'Morgan Lee',timezone:'Europe/London'})).id;testOwners=[owner];const login=await fixtureAPISignIn(()=>page.request.post('/api/auth/sign-in/email',{headers,data:{email,password:'Disposable-Cycle-Browser!'}}));expect(login.status()).toBe(200);});
test.afterEach(async()=>{for(const table of ['focus_cycle_goal','focus_cycle','weekly_review_decision','weekly_review','daily_reflection','focus_session','time_block','amendment_commitment','weekly_plan_amendment','commitment_identity','weekly_commitment','weekly_plan','action','milestone','goal','mutation_receipt'])await database.pool.query(`DELETE FROM ${table} WHERE owner_id=ANY($1)`,[testOwners]);await database.pool.query("DELETE FROM app_user WHERE id=ANY($1)",[testOwners]);});test.afterAll(()=>database.pool.end());
test('create, activate, edit membership, reload, finish and inspect frozen past cycle without changing Goals',async({page})=>{
 const g=await createGoal(page),other=await createGoal(page,'Run consistently');await page.goto('/goals');await page.locator('.goal-cycle-disclosure > summary').click();await page.getByRole('button',{name:'Create Focus Cycle',exact:true}).click();await expect(page.getByLabel('Cycle title')).toBeFocused();await page.getByLabel('Cycle title').fill('Oct–Nov: make One Better useful');await page.getByLabel('Intent (optional)').fill('Choose less, learn more');await page.getByLabel('Start date',{exact:true}).fill('2026-10-01');await page.getByLabel('End date',{exact:true}).fill('2026-11-30');await page.getByRole('checkbox',{name:/Ship One Better/}).check();await page.getByRole('button',{name:'Save cycle',exact:true}).click();await page.getByText('Draft cycles · 1',{exact:true}).click();await page.getByRole('button',{name:'Activate cycle',exact:true}).click();await page.getByRole('button',{name:'Confirm activate',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('.focus-cycle-card.is-current')).toBeVisible();await page.reload();await page.locator('.goal-cycle-disclosure > summary').click();await expect(page.locator('.focus-cycle-card.is-current')).toContainText('Ship One Better');await expect(page.locator('[data-goal-id]').filter({hasText:other.title})).not.toBeVisible();await page.getByText('Other active Goals · 1',{exact:true}).click();await expect(page.locator('[data-goal-id]').filter({hasText:other.title})).toBeVisible();
 await page.getByRole('button',{name:'Edit cycle',exact:true}).click();await page.getByRole('checkbox',{name:/Ship One Better/}).uncheck();await page.getByRole('checkbox',{name:/Run consistently/}).check();await page.getByRole('button',{name:'Save cycle',exact:true}).click();await expect(page.locator('.focus-cycle-card.is-current')).toContainText('Run consistently');await page.getByRole('button',{name:'Finish cycle',exact:true}).click();await page.getByRole('button',{name:'Confirm finish',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.reload();await page.locator('.goal-cycle-disclosure > summary').click();await page.getByText('Past cycles · 1',{exact:true}).click();await expect(page.locator('.cycle-history').filter({hasText:'Past cycles'})).toContainText('Run consistently');await expect(page.getByRole('button',{name:'Edit cycle',exact:true})).toHaveCount(0);for(const goal of [g,other])expect((await (await page.request.get(`/api/goals/${goal.id}`)).json()).goal).toEqual(goal);await page.getByRole('button',{name:'Archive cycle',exact:true}).click();await page.getByRole('button',{name:'Confirm archive',exact:true}).click();await expect(page.locator('.cycle-history').filter({hasText:'Past cycles'})).toContainText('archived');
});
test('stale edit retains attempted metadata; explicit latest review permits intentional replacement',async({page,browser})=>{const c=await createCycle(page),ctx=await browser.newContext({storageState:await page.context().storageState()}),second=await ctx.newPage();await page.goto('/goals');await page.locator('.goal-cycle-disclosure > summary').click();await page.getByText('Draft cycles · 1',{exact:true}).click();await page.getByRole('button',{name:'Edit cycle',exact:true}).click();await page.getByLabel('Cycle title').fill('My attempted horizon');const update=await second.request.patch(`/api/focus-cycles/${c.id}`,{headers,data:{...fields({title:'Changed elsewhere'}),expectedVersion:1}});expect(update.status()).toBe(200);await page.getByRole('button',{name:'Save cycle',exact:true}).click();await expect(page.getByRole('dialog').getByRole('alert')).toContainText('changed');await expect(page.getByLabel('Cycle title')).toHaveValue('My attempted horizon');await page.getByRole('button',{name:'Review latest cycle and Goals',exact:true}).click();await page.getByRole('button',{name:'Save cycle',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);expect((await (await page.request.get('/api/focus-cycles')).json()).cycles[0]).toMatchObject({title:'My attempted horizon',version:3});await ctx.close();});
test('uncertain create locks edits and retries exact receipt, producing one cycle',async({page})=>{await createGoal(page);await page.goto('/goals');await page.locator('.goal-cycle-disclosure > summary').click();await page.getByRole('button',{name:'Create Focus Cycle',exact:true}).click();await page.getByLabel('Cycle title').fill('Only one saved cycle');let lost=true;await page.route('**/api/focus-cycles',async route=>{if(route.request().method()==='POST'&&lost){lost=false;await route.fetch();await route.abort('failed');}else await route.continue();});await page.getByRole('button',{name:'Save cycle',exact:true}).click();await expect(page.getByRole('button',{name:'Retry same command',exact:true})).toBeVisible();await expect(page.getByLabel('Cycle title')).toBeDisabled();await expect(page.getByRole('button',{name:'Cancel',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Retry same command',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);expect((await (await page.request.get('/api/focus-cycles')).json()).cycles).toHaveLength(1);});
test('ownership, Origin, strict fields, unsupported lifecycle and no destructive route',async({page,browser})=>{const c=await createCycle(page),anonymous=await browser.newContext();expect((await anonymous.request.get(`${origin}/api/focus-cycles`)).status()).toBe(401);await anonymous.close();expect((await page.request.get('/api/focus-cycles')).headers()['cache-control']).toBe('private, no-store');expect((await page.request.post('/api/focus-cycles',{data:fields()})).status()).toBe(403);expect((await page.request.post('/api/focus-cycles',{headers,data:fields({ownerId:'forged'})})).status()).toBe(400);expect((await page.request.post(`/api/focus-cycles/${c.id}/finish`,{headers,data:{mutationId:randomUUID(),expectedVersion:1}})).status()).toBe(409);expect((await page.request.delete(`/api/focus-cycles/${c.id}`,{headers})).status()).toBe(405);const otherEmail=`other-${randomUUID()}@example.test`;const stranger=await provisionLocalUser(database.db,{email:otherEmail,password:'Disposable-Cycle-Browser!',name:'Other',timezone:'Europe/London'});testOwners.push(stranger.id);const other=await browser.newContext();expect((await other.request.post(`${origin}/api/auth/sign-in/email`,{headers,data:{email:otherEmail,password:'Disposable-Cycle-Browser!'}})).status()).toBe(200);for(const id of [c.id,randomUUID()])expect((await other.request.patch(`${origin}/api/focus-cycles/${id}`,{headers,data:{...fields(),expectedVersion:1}})).status()).toBe(404);await other.close();});
test('end date does not automatically finish or archive Goals; explicit finish frees the Active slot',async({page})=>{const g=await createGoal(page),c=await createCycle(page,{goals:[{goalId:g.id,goalVersion:1}],endDate:'2026-10-03'}),active=await transition(page,c,'activate');await writeFile(process.env.EXECUTION_TEST_CLOCK_FILE!,'2026-10-04T09:00:00.000Z');await page.goto('/goals');await page.locator('.goal-cycle-disclosure > summary').click();await expect(page.getByText('This horizon has ended.',{exact:false})).toBeVisible();expect((await (await page.request.get('/api/focus-cycles')).json()).current).toBeNull();await page.getByRole('button',{name:'Finish cycle',exact:true}).click();await page.getByRole('button',{name:'Confirm finish',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);expect((await (await page.request.get(`/api/goals/${g.id}`)).json()).goal).toEqual(g);expect(active.status).toBe('active');});
test('Calendar keeps all tasks and current Focus Cycle context without eligibility filtering',async({page})=>{const f=await weeklyFixture(database.db,{userId:owner},'2026-09-28'),outside=await createGoal(page,'Other useful work');await f.actions.createAction({userId:owner},outside.id,{mutationId:randomUUID(),title:'An outside-cycle Action',estimateMinutes:60});const c=await createCycle(page,{goals:[{goalId:outside.id,goalVersion:1}]});await transition(page,c,'activate');await page.goto('/calendar?week=2026-09-28');await expect(page.getByLabel('Current Focus Cycle',{exact:true})).toContainText(c.title);await expect(page.getByRole('region',{name:'Work for this week'})).toContainText('Build weekly review flow');await page.goto('/planning?week=2026-10-05');await expect(page.getByLabel('Current Focus Cycle',{exact:true})).toContainText(c.title);const card=page.getByRole('region',{name:'What matters this week?'});await expect(card).toContainText('An outside-cycle Action');await expect(card).toContainText('Build weekly review flow');await expect(card.getByRole('spinbutton')).toHaveCount(0);await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);});
