import {fixtureSignIn} from "./sign-in-helper";
import {test,expect,type Page,type BrowserContext} from "@playwright/test";
import {randomUUID} from "node:crypto";
import {writeFile,mkdir} from "node:fs/promises";
import {inArray} from "drizzle-orm";
import {connectDatabase} from "../../src/db/connect";
import {weeklyReviewDecision,weeklyReview,dailyReflection,focusSession,timeBlock,commitmentIdentity,weeklyPlan,weeklyCommitment,weeklyPlanAmendment,amendmentCommitment,action,goal,milestone,mutationReceipt,user} from "../../src/db/schema";
import {createAuthentication} from "../../src/server/auth-factory";
import {executionFixture} from "../focus-database";
import {focusNow} from "../focus-fixtures";
import {requireTestDatabaseURL} from "../../scripts/test-database";
import {signInThroughUI} from "./sign-in-helper";
const origin="http://127.0.0.1:3101";let database:ReturnType<typeof connectDatabase>,owners:string[];const cookies:Record<string,Parameters<BrowserContext["addCookies"]>[0]>={};
async function clock(value:string){await writeFile(process.env.EXECUTION_TEST_CLOCK_FILE!,value);}
async function clean(){for(const table of [weeklyReviewDecision,weeklyReview,dailyReflection,focusSession,timeBlock,commitmentIdentity,mutationReceipt,amendmentCommitment,weeklyPlanAmendment,weeklyCommitment,weeklyPlan,action,milestone,goal])await database.db.delete(table).where(inArray(table.ownerId,owners));await database.pool.query("UPDATE app_user SET timezone='Europe/London' WHERE id=ANY($1)",[owners]);}
test.beforeAll(async()=>{test.setTimeout(90000);const target=requireTestDatabaseURL();if(target.name==="execution_test")throw new Error("Requires isolated DB");database=connectDatabase(target.url);const rows=await database.db.select().from(user);owners=rows.map(v=>v.id);const auth=createAuthentication(database.db,{secret:process.env.BETTER_AUTH_SECRET!,baseURL:origin});for(const suffix of ["A","B"]){const response=await fixtureSignIn(()=>auth.handler(new Request(`${origin}/api/auth/sign-in/email`,{method:"POST",headers:{Origin:origin,"Content-Type":"application/json"},body:JSON.stringify({email:process.env[`TEST_USER_${suffix}_EMAIL`],password:process.env[`TEST_USER_${suffix}_PASSWORD`]})})));expect(response.status).toBe(200);cookies[suffix]=response.headers.getSetCookie().map(v=>{const pair=v.split(";")[0],i=pair.indexOf("=");return {name:pair.slice(0,i),value:pair.slice(i+1),url:origin,httpOnly:true,sameSite:"Lax" as const};});}});
test.beforeEach(async({page})=>{await clean();await clock(focusNow);await page.context().addCookies(cookies.A);});test.afterAll(async()=>{await clean();await clock(new Date().toISOString());await database.pool.end();});
async function fixture(){const owner=(await database.db.select().from(user)).find(v=>v.email===process.env.TEST_USER_A_EMAIL)!;return executionFixture(database.db,{userId:owner.id});}
async function begin(page:Page,blockId:string){await page.locator(`[data-focus-block="${blockId}"]`).getByRole("button",{name:"Start focus",exact:true}).click();await expect(page.locator("[data-active-session]")).toBeVisible();}
async function end(page:Page,outcome="partial",note=""){await page.getByRole("button",{name:"End focus",exact:true}).click();await expect(page.getByLabel("Session outcome")).toBeFocused();await page.getByLabel("Session outcome").selectOption(outcome);await page.getByLabel(/^End note/).fill(note);await page.getByRole("button",{name:"Save session outcome"}).click();await expect(page.getByRole("dialog")).toHaveCount(0);await expect(page.getByRole("region",{name:"Session recorded",exact:true})).toBeVisible();await page.getByRole("button",{name:"Choose another block",exact:true}).click();if(await page.locator(".focus-earlier").count()&&!await page.locator(".focus-earlier").evaluate(e=>(e as HTMLDetailsElement).open))await page.locator(".focus-earlier > summary").click();}
const workspace=async(page:Page)=>(await (await page.request.get("/api/focus")).json());
test("real sign-in → today's block → one-click start → timer/reload/navigation recovery → two outcomes and actual aggregation",async({page})=>{const f=await fixture();await page.context().clearCookies();await page.goto("/sign-in");await page.getByLabel("Email",{exact:true}).fill(process.env.TEST_USER_A_EMAIL!);await page.getByLabel("Password",{exact:true}).fill(process.env.TEST_USER_A_PASSWORD!);await signInThroughUI(page);await page.getByRole("link",{name:"Focus",exact:true}).click();await expect(page.locator(`[data-focus-block="${f.block.id}"]`)).toContainText("Build focus-session UI");await page.clock.install({time:new Date(focusNow)});await begin(page,f.block.id);const initial=await workspace(page);expect(initial.active.session.startedAt).toBe(focusNow);await clock("2026-10-06T09:32:00.123Z");await page.clock.fastForward(47*60000);await expect(page.getByLabel("Elapsed session time")).toHaveText("00:47:00");await page.reload();await expect(page.locator("[data-active-session]")).toHaveAttribute("data-active-session",initial.active.session.id);await expect(page.getByLabel("Elapsed session time")).toHaveText("00:47:00");await expect(page.getByRole("navigation",{name:"Main navigation"})).toBeVisible();await page.getByRole("link",{name:"Calendar",exact:true}).click();await page.getByRole("link",{name:"Focus",exact:true}).click();await expect(page.locator("[data-active-session]")).toHaveAttribute("data-active-session",initial.active.session.id);await end(page,"partial","Finished implementation; tests remain.");const row=page.locator(`[data-focus-block="${f.block.id}"]`);await expect(row).toContainText("47m");await row.locator("summary").click();await expect(row).toContainText("Partial progress");await expect(row).toContainText("Finished implementation; tests remain.");await clock("2026-10-06T09:33:00.123Z");await begin(page,f.block.id);await clock("2026-10-06T09:45:00.123Z");await end(page,"completed");expect((await workspace(page)).todayBlocks[0]).toMatchObject({recordedMilliseconds:59*60000,commitmentRecordedMilliseconds:59*60000,budgetMinutes:180,scheduledMinutes:120});await page.reload();await page.locator(".focus-earlier > summary").click();await row.locator("summary").click();await expect(row).toContainText("Completed as planned");await page.goto("/planning?week=2026-10-05");await page.locator(`[data-calendar-block="${f.block.id}"]`).click();const block=page.getByRole("region",{name:"Selected time block",exact:true});await expect(block).toContainText("original schedule is locked");await expect(block.getByRole("button",{name:"Reschedule"})).toHaveCount(0);await expect(block.getByRole("button",{name:"Cancel block"})).toHaveCount(0);await expect(block).toContainText("59m");expect((await (await page.request.get(`/api/actions/${f.action.id}`)).json()).action.state).toBe("open");});
test("stale second tab exposes existing session and Return to focus; never silently replaces it",async({page,browser})=>{const f=await fixture(),second=await f.create("2026-10-06","14:00","15:00"),context=await browser.newContext(),other=await context.newPage();try{await context.addCookies(cookies.A);await page.goto("/focus");await other.goto("/focus");await begin(page,f.block.id);await other.locator(`[data-focus-block="${second.id}"]`).getByRole("button",{name:"Start focus",exact:true}).click();await expect(other.locator(".focus-error")).toContainText("already have an active");await other.getByRole("button",{name:"Return to focus"}).click();await expect(other.locator("#active-focus")).toBeFocused();expect((await workspace(other)).active.session.timeBlockId).toBe(f.block.id);expect((await database.db.select().from(focusSession))).toHaveLength(1);}finally{await context.close();}});
test("removed commitment requires explicit acknowledgement; active amendment/drop/re-add preserves session lineage",async({page})=>{const f=await fixture();await f.amend([]);await page.goto("/focus");await page.getByRole("button",{name:"Start focus",exact:true}).click();await expect(page.getByRole("button",{name:"Start focus anyway"})).toBeDisabled();await page.getByRole("checkbox",{name:"I understand this work is outside my current plan"}).check();await page.getByRole("button",{name:"Start focus anyway"}).click();await expect(page.locator("[data-active-session]")).toBeVisible();const active=(await workspace(page)).active.session;await f.amend([120]);await page.getByRole("button",{name:"Refresh focus"}).click();await expect(page.locator(".active-focus")).toContainText("removed from the current plan");expect((await workspace(page)).active.session).toEqual(active);await clock("2026-10-06T09:00:00.123Z");await end(page,"abandoned","Interrupted by an incident.");const row=page.locator(`[data-focus-block="${f.block.id}"]`);await row.locator("summary").click();await expect(row).toContainText("Abandoned");expect((await workspace(page)).todayBlocks[0].recordedMilliseconds).toBe(15*60000);await page.goto("/planning?week=2026-10-05");const view=await (await page.request.get(`/api/weekly-plans/${f.plan.id}/time-blocks`)).json();expect(view.commitments[0].recordedMilliseconds).toBe(0);await expect(page.getByRole("region",{name:"Work for this week"})).toContainText("Build focus-session UI");});
test("partial budget amendment while active does not stop timer; frozen labels survive source archive",async({page})=>{const f=await fixture();await page.goto("/focus");await begin(page,f.block.id);await expect(page.locator("[data-active-session]")).toBeVisible();const active=(await workspace(page)).active.session;await f.amend([120]);await f.actions.updateAction(f.actor,f.action.id,{mutationId:randomUUID(),expectedVersion:1,title:"Changed live Action",estimateMinutes:30,doneWhen:null,milestoneId:null});await f.goals.archiveGoal(f.actor,f.goal.id,{mutationId:randomUUID(),expectedVersion:1});await page.reload();await expect(page.locator(".active-focus")).toContainText("Build focus-session UI");await expect(page.locator(".focus-metrics")).toContainText("2h budget");expect((await workspace(page)).active.session).toEqual(active);await clock("2026-10-06T10:00:00.123Z");await end(page,"completed");});
test("lost start and end responses retry exact commands and reread current saved truth",async({page})=>{const f=await fixture();await page.goto("/focus");let lostStart=false,lostEnd=false;const starts:unknown[]=[],ends:unknown[]=[];await page.route(`**/api/time-blocks/${f.block.id}/focus-sessions`,async route=>{starts.push(route.request().postDataJSON());const response=await route.fetch();if(!lostStart){lostStart=true;await route.fulfill({status:200,contentType:"application/json",body:"broken response"});}else await route.fulfill({response});});await page.getByRole("button",{name:"Start focus",exact:true}).click();await expect(page.getByRole("button",{name:"Retry same command"})).toBeVisible();await page.getByRole("button",{name:"Retry same command"}).click();await expect(page.locator("[data-active-session]")).toBeVisible();expect(starts[1]).toEqual(starts[0]);const active=(await workspace(page)).active.session;await page.route(`**/api/focus-sessions/${active.id}/end`,async route=>{ends.push(route.request().postDataJSON());const response=await route.fetch();if(!lostEnd){lostEnd=true;await route.fulfill({status:200,contentType:"application/json",body:"broken response"});}else await route.fulfill({response});});await clock("2026-10-06T09:15:00.123Z");await page.getByRole("button",{name:"End focus"}).click();await page.getByLabel("Session outcome").selectOption("partial");await page.getByLabel(/^End note/).fill("Retain this note");await page.getByRole("button",{name:"Save session outcome"}).click();await expect(page.getByLabel(/^End note/)).toBeDisabled();await page.getByRole("button",{name:"Retry same command"}).click();await expect(page.getByRole("dialog")).toHaveCount(0);expect(ends[1]).toEqual(ends[0]);expect((await database.db.select().from(focusSession))).toHaveLength(1);await expect(page.getByRole("region",{name:"Session recorded",exact:true})).toBeVisible();await page.getByRole("button",{name:"Choose another block",exact:true}).click();await page.locator(".focus-earlier > summary").click();await page.locator(".focus-history summary").click();await expect(page.locator(".focus-history")).toContainText("Retain this note");});
test("ownership and HTTP contracts: all foreign/missing resources, strict clocks/notes, no terminal edits/deletes",async({page,browser})=>{const f=await fixture(),start={mutationId:randomUUID(),expectedBlockVersion:1,acknowledgeRemoved:false};const result=await page.request.post(`/api/time-blocks/${f.block.id}/focus-sessions`,{headers:{Origin:origin},data:start});expect(result.status()).toBe(200);const s=(await result.json()).session,context=await browser.newContext();try{await context.addCookies(cookies.B);for(const id of [s.id,randomUUID()]){expect((await context.request.get(`${origin}/api/focus-sessions/${id}`)).status()).toBe(404);expect((await context.request.post(`${origin}/api/focus-sessions/${id}/end`,{headers:{Origin:origin},data:{mutationId:randomUUID(),expectedVersion:1,outcome:"partial"}})).status()).toBe(404);}for(const id of [f.block.id,randomUUID()]){expect((await context.request.post(`${origin}/api/time-blocks/${id}/focus-sessions`,{headers:{Origin:origin},data:start})).status()).toBe(404);expect((await context.request.get(`${origin}/api/focus?block=${id}`)).status()).toBe(404);}}finally{await context.close();}expect((await page.request.post(`/api/time-blocks/${f.block.id}/focus-sessions`,{headers:{Origin:"https://foreign.invalid"},data:start})).status()).toBe(403);expect((await page.request.post(`/api/time-blocks/${f.block.id}/focus-sessions`,{headers:{Origin:origin},data:{...start,startedAt:focusNow}})).status()).toBe(400);const read=await page.request.get(`/api/focus-sessions/${s.id}`);expect(read.headers()["cache-control"]).toBe("private, no-store");for(const method of ["PATCH","DELETE"])expect((await page.request.fetch(`/api/focus-sessions/${s.id}`,{method,headers:{Origin:origin},data:{}})).status()).toBe(405);await page.context().clearCookies();expect((await page.request.get("/api/focus")).status()).toBe(401);});
test("narrow keyboard flow, intentionally cancelled end, no backlog or horizontal overflow",async({page})=>{const f=await fixture();await page.setViewportSize({width:390,height:844});await page.goto("/focus");await begin(page,f.block.id);await page.getByRole("button",{name:"End focus"}).click();await page.keyboard.press("Escape");await expect(page.getByRole("dialog")).toHaveCount(0);await expect(page.getByRole("button",{name:"End focus"})).toBeFocused();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await mkdir(".cache/visual",{recursive:true});await page.screenshot({path:".cache/visual/phase-six-a-focus-narrow.png",fullPage:true});});
test("today uses User zone, DST repeated hour shows offsets, active runs through midnight/week boundary",async({page})=>{const f=await fixture();await clock("2026-10-05T23:30:00.000Z");await page.goto("/focus");await expect(page.locator(`[data-focus-block="${f.block.id}"]`)).toBeVisible();await database.pool.query("UPDATE app_user SET timezone='America/Los_Angeles' WHERE id=$1",[f.actor.userId]);await page.reload();await expect(page.getByText("Nothing scheduled for focus today.",{exact:false})).toBeVisible();await database.pool.query("UPDATE app_user SET timezone='Europe/London' WHERE id=$1",[f.actor.userId]);await clock("2026-10-11T22:30:00.000Z");await page.goto(`/focus?block=${f.block.id}`);await begin(page,f.block.id);await clock("2026-10-12T07:30:00.000Z");await page.reload();await expect(page.getByLabel("Elapsed session time")).toHaveText("09:00:00");await end(page,"abandoned");await clean();await clock("2026-10-25T00:30:00.000Z");const fall=await executionFixture(database.db,f.actor,"2026-10-19");await page.goto(`/focus?block=${fall.block.id}`);await begin(page,fall.block.id);await expect(page.locator(".active-focus")).toContainText("GMT+1");await clock("2026-10-25T01:30:00.000Z");await page.reload();await expect(page.getByLabel("Elapsed session time")).toHaveText("01:00:00");await end(page,"partial");await page.locator(".focus-history summary").click();await expect(page.locator(".focus-history")).toContainText("GMT+1");await expect(page.locator(".focus-history")).toContainText("GMT");});
test("empty Focus is honest and links to Calendar; future and cancelled selected blocks have no Start",async({page})=>{await page.goto("/focus");await expect(page.getByText("Nothing scheduled for focus today.",{exact:false})).toBeVisible();await expect(page.getByRole("link",{name:"Open Calendar",exact:true})).toHaveAttribute("href","/calendar");const owner=(await database.db.select().from(user)).find(v=>v.email===process.env.TEST_USER_A_EMAIL)!;const future=await executionFixture(database.db,{userId:owner.id},"2026-10-12");await page.goto(`/focus?block=${future.block.id}`);await expect(page.getByRole("button",{name:"Start focus",exact:true})).toHaveCount(0);await future.schedule.cancel(future.actor,future.block.id,{mutationId:randomUUID(),expectedVersion:1});await page.reload();await expect(page.getByRole("button",{name:"Start focus",exact:true})).toHaveCount(0);});
test("two simultaneous HTTP starts have one winner; visibility recovery derives elapsed rather than tick count",async({page})=>{const f=await fixture(),second=await f.create("2026-10-06","14:00","15:00");await page.clock.install({time:new Date(focusNow)});const results=await Promise.all([f.block,second].map(block=>page.request.post(`/api/time-blocks/${block.id}/focus-sessions`,{headers:{Origin:origin},data:{mutationId:randomUUID(),expectedBlockVersion:1,acknowledgeRemoved:false}})));expect(results.map(r=>r.status()).sort()).toEqual([200,409]);expect((await database.db.select().from(focusSession))).toHaveLength(1);await page.goto("/focus");await page.getByRole("button",{name:"Refresh focus"}).click();await clock("2026-10-06T09:15:00.123Z");await page.clock.setSystemTime(new Date("2026-10-06T09:15:00.123Z"));const recovered=page.waitForResponse(r=>r.url().endsWith("/api/focus")&&r.status()===200);await page.evaluate(()=>document.dispatchEvent(new Event("visibilitychange")));await recovered;await expect(page.getByLabel("Elapsed session time")).toHaveText("00:30:00");});

test("R3 launchpad orders Next and Later, keeps Earlier quiet and uses the shared header while active",async({page})=>{
 const f=await fixture(),last=await f.create("2026-10-06","16:00","17:00"),middle=await f.create("2026-10-06","14:00","15:00"),earlier=await f.create("2026-10-06","07:00","08:00");
 await page.goto("/focus");await expect(page.getByRole("heading",{name:"What am I focusing on next?",exact:true})).toBeVisible();
 await expect(page.getByRole("region",{name:"Next focus block",exact:true}).locator("[data-focus-block]")).toHaveAttribute("data-focus-block",f.block.id);
 expect(await page.getByRole("region",{name:"Later today",exact:true}).locator("[data-focus-block]").evaluateAll(elements=>elements.map(e=>e.getAttribute("data-focus-block")))).toEqual([middle.id,last.id]);
 await expect(page.locator(".focus-earlier")).not.toHaveAttribute("open","");await page.locator(".focus-earlier > summary").click();await expect(page.locator(`[data-focus-block="${earlier.id}"]`)).toBeVisible();
 expect((await workspace(page)).active).toBeNull();await begin(page,f.block.id);
 await expect(page.getByRole("navigation",{name:"Main navigation"})).toBeVisible();await expect(page.getByRole("button",{name:"Switch to dark mode"})).toBeVisible();await expect(page.getByRole("complementary",{name:"Today's schedule"})).toHaveCount(0);
 await expect(page.locator(".active-focus h1")).toHaveText(f.action.title);await expect(page.getByRole("complementary",{name:"Today's blocks"})).toBeVisible();await page.screenshot({path:".cache/reference4-focus-desktop.png",fullPage:false});await expect(page.getByRole("textbox",{name:"Notes Scratchpad",exact:true})).toBeVisible();
 await page.setViewportSize({width:390,height:844});await expect(page.getByRole("button",{name:"End focus",exact:true})).toBeInViewport();await page.screenshot({path:".cache/reference4-focus-mobile.png",fullPage:false});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.documentElement.scrollHeight<=innerHeight)).toBe(true);
});

test("R3 scratchpad makes no backend writes, prefills the end note and keeps edits when returning to focus",async({page})=>{
 const f=await fixture();await page.goto("/focus");await begin(page,f.block.id);const active=(await workspace(page)).active.session;
 const writes:string[]=[];page.on("request",request=>{if(["POST","PUT","PATCH","DELETE"].includes(request.method())&&request.url().includes("/api/"))writes.push(request.url());});
 const notes=page.getByRole("textbox",{name:"Notes Scratchpad",exact:true});await notes.fill("Decision: keep it simple.\nNext: verify recovery.");await page.getByRole("button",{name:"Refresh focus",exact:true}).click();
 expect(writes).toEqual([]);expect((await workspace(page)).active.session.endNote).toBeNull();
 await page.getByRole("button",{name:"End focus",exact:true}).click();await expect(page.getByLabel(/^End note/)).toHaveValue("Decision: keep it simple.\nNext: verify recovery.");
 await page.getByLabel(/^End note/).fill("Decision: keep it simple.\nNext: verify recovery, then ship.");await page.getByRole("button",{name:"Keep focusing",exact:true}).click();await expect(notes).toHaveValue("Decision: keep it simple.\nNext: verify recovery, then ship.");
 await clock("2026-10-06T09:05:00.123Z");await page.getByRole("button",{name:"End focus",exact:true}).click();await page.getByLabel("Session outcome").selectOption("partial");await page.getByRole("button",{name:"Save session outcome",exact:true}).click();
 const summary=page.getByRole("region",{name:"Session recorded",exact:true});await expect(summary).toContainText("20m recorded");await expect(summary.locator(".focus-outcome-label")).toHaveText("Partial progress");
 await expect(summary.getByRole("link",{name:"Back to today",exact:true})).toHaveAttribute("href","/today");await expect(summary.getByRole("link",{name:"Back to Calendar",exact:true})).toHaveAttribute("href","/calendar");
 const saved=(await (await page.request.get(`/api/focus-sessions/${active.id}`)).json()).session;expect(saved.endNote).toBe("Decision: keep it simple.\nNext: verify recovery, then ship.");expect(saved.outcome).toBe("partial");
 expect((await (await page.request.get(`/api/actions/${f.action.id}`)).json()).action.state).toBe("open");
});

test("R3 transient notes warn before reload while the persisted session and authoritative timer recover",async({page})=>{
 const f=await fixture();await page.goto("/focus");await begin(page,f.block.id);const active=(await workspace(page)).active.session;await page.getByRole("textbox",{name:"Notes Scratchpad",exact:true}).fill("Unsaved tab-only thought");
 await clock("2026-10-06T09:22:00.123Z");const warning=page.waitForEvent("dialog"),reload=page.reload();const dialog=await warning;expect(dialog.type()).toBe("beforeunload");await dialog.accept();await reload;
 await expect(page.locator("[data-active-session]")).toHaveAttribute("data-active-session",active.id);await expect(page.getByLabel("Elapsed session time")).toHaveText(/^00:37:0\d$/);await expect(page.getByRole("textbox",{name:"Notes Scratchpad",exact:true})).toHaveValue("");
});

for(const [outcome,label,destination] of [["completed","Completed as planned","/today"],["abandoned","Abandoned","/calendar"]] as const)test(`R3 ${outcome} closes with a small acknowledgement and returns to ${destination}`,async({page})=>{
 const f=await fixture();await page.goto("/focus");await begin(page,f.block.id);await clock("2026-10-06T09:00:00.123Z");await page.getByRole("button",{name:"End focus",exact:true}).click();await expect(page.getByLabel("Session outcome")).toBeFocused();await page.getByLabel("Session outcome").selectOption(outcome);await page.getByRole("button",{name:"Save session outcome",exact:true}).click();
 const summary=page.getByRole("region",{name:"Session recorded",exact:true});await expect(summary).toContainText("15m recorded");await expect(summary.locator(".focus-outcome-label")).toHaveText(label);await expect(page.getByRole("region",{name:"Today's focus blocks"})).toHaveCount(0);
 expect((await (await page.request.get(`/api/actions/${f.action.id}`)).json()).action.state).toBe("open");await summary.getByRole("link",{name:destination==="/today"?"Back to today":"Back to Calendar",exact:true}).click();await expect(page).toHaveURL(new RegExp(`${destination}$`));
});
