import {fixtureSignIn} from "./sign-in-helper";
import {test,expect,type Page,type BrowserContext} from "@playwright/test";
import {randomUUID} from "node:crypto";



import {inArray} from "drizzle-orm";
import {connectDatabase} from "../../src/db/connect";
import {weeklyReviewDecision,weeklyReview,dailyReflection,focusSession,timeBlock,commitmentIdentity,weeklyPlan,weeklyCommitment,weeklyPlanAmendment,amendmentCommitment,action,goal,milestone,mutationReceipt,user,focusableHours,calendarAvailabilityCache,calendarOAuthFlow,calendarConnection} from "../../src/db/schema";
import {createAuthentication} from "../../src/server/auth-factory";
import {requireTestDatabaseURL} from "../../scripts/test-database";
import type {WeeklyPlan,PlanningSource,WeekWorkspace} from "../../src/modules/planning/domain";

const origin="http://127.0.0.1:3101",week="2028-01-03";let database:ReturnType<typeof connectDatabase>,owners:string[];const cookies:Record<string,Parameters<BrowserContext["addCookies"]>[0]>={};
async function clean(){for(const table of [weeklyReviewDecision,weeklyReview,dailyReflection,focusSession,timeBlock,commitmentIdentity,mutationReceipt,amendmentCommitment,weeklyPlanAmendment,weeklyCommitment,weeklyPlan,action,milestone,goal,focusableHours,calendarAvailabilityCache,calendarOAuthFlow,calendarConnection])await database.db.delete(table).where(inArray(table.ownerId,owners));await database.pool.query("UPDATE app_user SET timezone='Europe/London' WHERE id=ANY($1)",[owners]);}
test.beforeAll(async()=>{test.setTimeout(90000);const target=requireTestDatabaseURL();if(target.name==="execution_test")throw new Error("Requires isolated browser DB");database=connectDatabase(target.url);owners=(await database.db.select({id:user.id}).from(user)).map(v=>v.id);const auth=createAuthentication(database.db,{secret:process.env.BETTER_AUTH_SECRET!,baseURL:origin});for(const suffix of ["A","B"]){const response=await fixtureSignIn(()=>auth.handler(new Request(`${origin}/api/auth/sign-in/email`,{method:"POST",headers:{Origin:origin,"Content-Type":"application/json"},body:JSON.stringify({email:process.env[`TEST_USER_${suffix}_EMAIL`],password:process.env[`TEST_USER_${suffix}_PASSWORD`]})})));expect(response.status).toBe(200);cookies[suffix]=response.headers.getSetCookie().map(v=>{const pair=v.split(";")[0],i=pair.indexOf("=");return {name:pair.slice(0,i),value:pair.slice(i+1),url:origin,httpOnly:true,sameSite:"Lax" as const};});}});
test.beforeEach(async({page})=>{await clean();await fetch(`${process.env.CALENDAR_TEST_ORIGIN}/control`,{method:"POST",body:"{}"});await page.context().addCookies(cookies.A);});test.afterAll(async()=>{await clean();await database.pool.end();});
async function mutate(page:Page,path:string,data:object,method="POST"){const r=await page.request.fetch(path,{method,headers:{Origin:origin},data});expect(r.status(),await r.text()).toBe(200);return r.json();}
async function fixture(page:Page,create=true){
 const g=(await mutate(page,'/api/goals',{mutationId:randomUUID(),title:'Build a calmer weekly loop',outcome:'A planning system I rely on every week'})).goal;
 const a=(await mutate(page,`/api/goals/${g.id}/actions`,{mutationId:randomUUID(),title:'Simplify the weekly review',doneWhen:'Useful evidence in less than five minutes',estimateMinutes:120})).action;
 const other=(await mutate(page,`/api/goals/${g.id}/actions`,{mutationId:randomUUID(),title:'Protect existing work'})).action;
 const sources:PlanningSource[]=(await (await page.request.get('/api/weekly-plans/candidates')).json()).candidates;
 const current:WeekWorkspace=await (await page.request.get('/api/weekly-plans')).json();
 let plan:WeeklyPlan|null=null;
 if(create){plan=(await mutate(page,'/api/weekly-plans',{mutationId:randomUUID(),weekStartDate:current.currentWeekStartDate,provisionalCapacityMinutes:360,reserveMinutes:60})).plan;plan=(await mutate(page,`/api/weekly-plans/${plan!.id}`,{mutationId:randomUUID(),expectedVersion:1,provisionalCapacityMinutes:360,reserveMinutes:60,commitments:[{actionId:other.id,budgetMinutes:60,source:sources.find(s=>s.actionId===other.id)!.source}]},'PATCH')).plan;}
 return {g,a,other,plan,sources,current};
}
async function open(page:Page,f:Awaited<ReturnType<typeof fixture>>){await page.goto(`/goals/${f.g.id}`);await page.locator(`[data-action-id="${f.a.id}"]`).getByRole('button',{name:'Add to this week →',exact:true}).click();await expect(page.getByText('Available to commit:',{exact:false})).toBeVisible();}
const dialog=(page:Page)=>page.getByRole('dialog',{name:'Add to this week',exact:true});
const budget=(page:Page)=>page.getByLabel('Commitment budget in minutes');
const add=(page:Page)=>dialog(page).getByRole('button',{name:'Add to week',exact:true});
const saved=async(page:Page,id:string)=>(await (await page.request.get(`/api/weekly-plans/${id}`)).json()).plan as WeeklyPlan;

test('Goal overview → Action capture → explicit budget → Calendar Draft → reviewed baseline → Schedule',async({page})=>{
 const f=await fixture(page);await page.goto('/goals');await expect(page.locator(`[data-goal-id="${f.g.id}"]`)).toContainText('Next actions');await page.getByRole('button',{name:`Preview ${f.g.title}`,exact:true}).click();await page.getByRole('region',{name:'Goal preview'}).getByRole('link',{name:'Open goal workspace',exact:false}).click();
 await page.getByRole('button',{name:/^Add action/}).click();await page.getByLabel('Title',{exact:true}).fill('Prepare the next useful release');await page.getByLabel('Done when (optional)').fill('A reviewable release note');await page.getByRole('button',{name:'Save action',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);
 const row=page.locator('.action-card').filter({hasText:'Prepare the next useful release'});await row.getByRole('button',{name:'Add to this week →',exact:true}).click();await expect(budget(page)).toHaveValue('');await budget(page).fill('90');await add(page).click();await expect(page.getByRole('dialog')).toHaveCount(0);
 const plan=await saved(page,f.plan!.id);expect(plan.commitments).toHaveLength(2);expect(plan.commitments.find(c=>c.actionId===f.other.id)).toMatchObject({id:f.plan!.commitments[0].id,source:f.plan!.commitments[0].source,budgetMinutes:60,snapshot:null});expect(plan.commitments.find(c=>c.actionId!==f.other.id)).toMatchObject({budgetMinutes:90,snapshot:null});expect(plan.state).toBe('draft');
 await page.locator('.goal-this-week').getByRole('link',{name:'Calendar →',exact:true}).click();const rail=page.getByRole('region',{name:'Work for this week'});await expect(rail).toContainText('Prepare the next useful release');await expect(rail).toContainText('chosen · Draft');await expect(rail.getByRole('button',{name:/Schedule/})).toHaveCount(0);
 await rail.getByRole('link',{name:'Review and commit →',exact:true}).click();await page.getByRole('button',{name:'Review and commit',exact:true}).click();await page.getByRole('button',{name:'Commit this week',exact:true}).click();await expect(page.getByText('Your original baseline is committed and preserved.',{exact:true})).toBeVisible();
 await page.goto(`/calendar?week=${f.current.currentWeekStartDate}`);await expect(page.getByRole('region',{name:'Work for this week'}).getByRole('button',{name:/Schedule/})).toHaveCount(2);await page.getByRole('region',{name:'Work for this week'}).getByRole('button',{name:/Schedule/}).first().click();await expect(page.getByRole('dialog')).toBeVisible();
});
test('capacity, duplicate prevention, reload persistence and keyboard focus',async({page})=>{
 const f=await fixture(page);await open(page,f);await expect(budget(page)).toBeFocused();await expect(add(page)).toBeDisabled();await budget(page).fill('241');await expect(add(page)).toBeDisabled();await expect(page.getByText(/exceeds the available capacity/)).toBeVisible();await budget(page).fill('90');await budget(page).press('Escape');await expect(page.locator(`[data-action-id="${f.a.id}"]`).getByRole('button',{name:'Add to this week →',exact:true})).toBeFocused();
 await open(page,f);await budget(page).fill('90');await add(page).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.reload();await expect(page.locator(`[data-action-id="${f.a.id}"]`)).toContainText('This week · 1h 30m');await expect(page.locator(`[data-action-id="${f.a.id}"]`).getByRole('button',{name:/Add to this week/})).toHaveCount(0);expect((await saved(page,f.plan!.id)).commitments).toHaveLength(2);
});
test('concurrent plan changes preserve budget and all other choices after explicit review',async({page})=>{
 const f=await fixture(page);await open(page,f);await budget(page).fill('90');const old=f.plan!;
 await mutate(page,`/api/weekly-plans/${old.id}`,{mutationId:randomUUID(),expectedVersion:old.version,provisionalCapacityMinutes:420,reserveMinutes:80,commitments:old.commitments.map(c=>({actionId:c.actionId,budgetMinutes:70,source:c.source}))},'PATCH');await add(page).click();await expect(dialog(page).getByRole('alert')).toContainText('changed elsewhere');await expect(budget(page)).toHaveValue('90');await expect(add(page)).toBeDisabled();await dialog(page).getByRole('button',{name:'Review latest context'}).click();await expect(page.getByText('Latest week context',{exact:true})).toBeVisible();await expect(add(page)).toBeDisabled();await page.getByRole('button',{name:'Use reviewed context'}).click();await add(page).click();await expect(page.getByRole('dialog')).toHaveCount(0);const next=await saved(page,old.id);expect(next).toMatchObject({provisionalCapacityMinutes:420,reserveMinutes:80});expect(next.commitments.find(c=>c.actionId===f.other.id)?.budgetMinutes).toBe(70);expect(next.commitments.find(c=>c.actionId===f.a.id)?.budgetMinutes).toBe(90);
});
test('changed selected source is reviewed, terminal eligibility rejects and baseline is immutable',async({page})=>{
 const f=await fixture(page);await open(page,f);await budget(page).fill('90');await mutate(page,`/api/actions/${f.a.id}`,{mutationId:randomUUID(),expectedVersion:1,title:'A clearer review action',doneWhen:'Clear evidence',estimateMinutes:120},'PATCH');await add(page).click();await expect(dialog(page).getByRole('alert')).toBeVisible();await dialog(page).getByRole('button',{name:'Review latest context'}).click();await expect(page.getByText('A clearer review action',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Use reviewed context'}).click();
 await mutate(page,`/api/actions/${f.a.id}/complete`,{mutationId:randomUUID(),expectedVersion:2});await add(page).click();await dialog(page).getByRole('button',{name:'Review latest context'}).click();await page.getByRole('button',{name:'Use reviewed context'}).click();await expect(page.getByText(/This Action is no longer eligible/)).toBeVisible();await expect(add(page)).toBeDisabled();expect((await saved(page,f.plan!.id)).commitments).toHaveLength(1);
});
test('lost add response retries the exact command and renders current saved state',async({page})=>{
 const f=await fixture(page);await open(page,f);await budget(page).fill('90');const commands:string[]=[];let first=true;
 await page.route(`**/api/weekly-plans/${f.plan!.id}`,async route=>{if(route.request().method()!=='PATCH'){await route.continue();return;}commands.push(route.request().postData()!);const response=await route.fetch();if(first){first=false;await route.abort();}else await route.fulfill({response});});
 await add(page).click();await expect(page.getByRole('button',{name:'Retry same command'})).toBeVisible();await expect(budget(page)).toBeDisabled();await expect(dialog(page).getByRole('button',{name:'Cancel',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Retry same command'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);expect(commands).toHaveLength(2);expect(commands[0]).toBe(commands[1]);const plan=await saved(page,f.plan!.id);expect(plan.version).toBe(3);expect(plan.commitments).toHaveLength(2);
});
test('create future Draft with explicit capacity and reserve; lost creation is safely recovered',async({page})=>{
 const f=await fixture(page,false);await page.goto(`/goals/${f.g.id}`);await page.locator(`[data-action-id="${f.a.id}"]`).getByRole('button',{name:'Add to this week →',exact:true}).click();await page.getByLabel('Week containing').fill(week);await expect(page.getByLabel('Weekly focus capacity in minutes')).toBeVisible();await budget(page).fill('90');await page.getByLabel('Weekly focus capacity in minutes').fill('300');await page.getByLabel('Protected reserve in minutes').fill('60');let first=true;const bodies:string[]=[];await page.route('**/api/weekly-plans',async route=>{if(route.request().method()!=='POST'){await route.continue();return;}bodies.push(route.request().postData()!);const response=await route.fetch();if(first){first=false;await route.abort();}else await route.fulfill({response});});await page.getByRole('button',{name:'Create weekly draft',exact:true}).click();await page.getByRole('button',{name:'Retry same command'}).click();await expect(page.getByText('Available to commit:',{exact:false})).toBeVisible();expect(bodies[0]).toBe(bodies[1]);await expect(budget(page)).toHaveValue('90');await add(page).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.locator('.goal-this-week')).toContainText(`Week of ${week}`);await page.reload();await expect(page.locator('.goal-this-week')).toContainText(`Week of ${week}`);await page.locator('.goal-this-week').getByRole('link',{name:'Calendar →',exact:true}).click();await expect(page.getByRole('region',{name:'Work for this week'})).toContainText(f.a.title);
});
test('committed effective choices are shown; new work routes to amendment or future Draft',async({page})=>{
 const f=await fixture(page);await mutate(page,`/api/weekly-plans/${f.plan!.id}/commit`,{mutationId:randomUUID(),expectedVersion:f.plan!.version});await mutate(page,`/api/weekly-plans/${f.plan!.id}/amendments`,{mutationId:randomUUID(),expectedVersion:3,provisionalCapacityMinutes:360,reserveMinutes:60,reason:'Choose review work deliberately',commitments:[{actionId:f.a.id,budgetMinutes:150,source:f.sources.find(s=>s.actionId===f.a.id)!.source}]});
 await page.goto(`/goals/${f.g.id}`);await expect(page.locator('.goal-this-week')).toContainText('2h 30m committed');await expect(page.locator('.goal-this-week')).not.toContainText(f.other.title);await page.locator(`[data-action-id="${f.other.id}"]`).getByRole('button',{name:'Add to this week →',exact:true}).click();await expect(page.getByText(/This week is already committed/)).toBeVisible();await expect(page.getByRole('link',{name:'Amend the current plan →'})).toBeVisible();await expect(add(page)).toBeDisabled();
});
test('mobile layout and dialog keep controls accessible with no horizontal overflow',async({page})=>{
 const f=await fixture(page);await page.setViewportSize({width:390,height:844});await open(page,f);await budget(page).fill('90');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await expect(add(page)).toBeInViewport();await add(page).click();await expect(page.getByRole('dialog')).toHaveCount(0);await page.reload();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
});
test('existing changed Draft source requires deliberate planning review; committing elsewhere cannot be bypassed',async({page})=>{
 const f=await fixture(page);await mutate(page,`/api/actions/${f.other.id}`,{mutationId:randomUUID(),expectedVersion:1,title:'Existing work changed'},'PATCH');await open(page,f);await budget(page).fill('90');await expect(page.getByText('Existing choices need source review.',{exact:false})).toBeVisible();await expect(add(page)).toBeDisabled();await dialog(page).getByRole('button',{name:'Cancel',exact:true}).click();
 const pool:PlanningSource[]=(await (await page.request.get('/api/weekly-plans/candidates')).json()).candidates;await mutate(page,`/api/weekly-plans/${f.plan!.id}`,{mutationId:randomUUID(),expectedVersion:2,provisionalCapacityMinutes:360,reserveMinutes:60,commitments:[{actionId:f.other.id,budgetMinutes:60,source:pool.find(c=>c.actionId===f.other.id)!.source}]},'PATCH');await open(page,f);await budget(page).fill('90');await mutate(page,`/api/weekly-plans/${f.plan!.id}/commit`,{mutationId:randomUUID(),expectedVersion:3});await add(page).click();await dialog(page).getByRole('button',{name:'Review latest context'}).click();await page.getByRole('button',{name:'Use reviewed context'}).click();await expect(page.getByText(/This week is already committed/)).toBeVisible();await expect(add(page)).toBeDisabled();expect((await saved(page,f.plan!.id)).commitments).toHaveLength(1);
});
test('detail Goal editing retains checkpoint history; archiving leaves chosen work and history read-only',async({page})=>{
 const f=await fixture(page);await page.goto(`/goals/${f.g.id}`);await page.getByRole('button',{name:'Add milestone',exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('A useful planning checkpoint');await page.getByLabel('Success condition',{exact:true}).fill('The weekly loop works');await page.getByRole('button',{name:'Save milestone',exact:true}).click();await expect(page.locator('.milestone-card')).toContainText('A useful planning checkpoint');await page.getByRole('button',{name:`Edit ${f.g.title}`,exact:true}).click();await page.getByLabel('Title',{exact:true}).fill('A clearer direction');await page.getByRole('button',{name:'Save goal',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('heading',{name:'A clearer direction',exact:true})).toBeVisible();await expect(page.locator('.milestone-card')).toContainText('A useful planning checkpoint');await expect(page.locator('.goal-this-week')).toContainText('Draft source context needs review');await page.getByRole('button',{name:'Archive A clearer direction',exact:true}).click();await page.getByRole('button',{name:'Archive goal',exact:true}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByRole('button',{name:'Add action',exact:true})).toHaveCount(0);await expect(page.locator('.goal-this-week')).toContainText(f.other.title);expect((await saved(page,f.plan!.id)).commitments).toHaveLength(1);await page.reload();await expect(page.getByText('Archived goal',{exact:true})).toBeVisible();
});

test('Goal preview changes context without writing plans; opening a goal keeps week choice explicit',async({page})=>{
 const f=await fixture(page);const second=(await mutate(page,'/api/goals',{mutationId:randomUUID(),title:'Make time for reading',outcome:'Useful ideas become everyday changes'})).goal;
 await mutate(page,`/api/goals/${second.id}/milestones`,{mutationId:randomUUID(),title:'Try one idea from a book',successCondition:'A practical change is used in real life'});
 await page.goto('/goals');await page.getByRole('button',{name:`Preview ${second.title}`,exact:true}).click();const preview=page.getByRole('region',{name:'Goal preview'});await expect(preview).toContainText(second.outcome);await expect(preview).toContainText('Try one idea from a book');await expect(page.getByRole('complementary',{name:'Goal context'})).toContainText('0m');
 await page.getByRole('button',{name:`Preview ${f.g.title}`,exact:true}).click();await expect(preview).toContainText(f.g.outcome);await expect(page.getByRole('complementary',{name:'Goal context'})).toContainText('1h');expect(await saved(page,f.plan!.id)).toEqual(f.plan);
 await preview.getByRole('link',{name:'Open goal workspace',exact:false}).click();await expect(page).toHaveURL(new RegExp(`/goals/${f.g.id}$`));await expect(page.getByRole('heading',{name:f.g.title,exact:true,level:1})).toBeVisible();await expect(page.getByRole('navigation',{name:'Choose goal'}).getByRole('link',{name:f.g.title,exact:true})).toHaveAttribute('aria-current','page');
 await page.setViewportSize({width:390,height:844});await page.reload();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});
