import {fixtureSignIn} from "./sign-in-helper";
import { signInThroughUI } from "./sign-in-helper";
import { test, expect, type Page, type BrowserContext } from "@playwright/test";
import { randomUUID } from "node:crypto";
import { inArray } from "drizzle-orm";
import { connectDatabase } from "../../src/db/connect";
import { focusSession, timeBlock, commitmentIdentity, weeklyPlanAmendment, amendmentCommitment, weeklyPlan, weeklyCommitment, action, goal, milestone, mutationReceipt, user } from "../../src/db/schema";
import { createAuthentication } from "../../src/server/auth-factory";
import { requireTestDatabaseURL } from "../../scripts/test-database";
const origin = "http://127.0.0.1:3101";
let database: ReturnType<typeof connectDatabase>; let ownerIds: string[];
const cookies: Record<string, Parameters<BrowserContext["addCookies"]>[0]> = {};
const checkpoint = (overrides = {}) => ({ mutationId: randomUUID(), title: "Weekly planning loop is usable", successCondition: "Choose commitments against realistic capacity and preserve the plan.", ...overrides });
const transition = (expectedVersion = 1) => ({ mutationId: randomUUID(), expectedVersion });
async function createGoal(page: Page) {
  const response = await page.request.post("/api/goals", { headers: { Origin: origin }, data: { mutationId: randomUUID(), title: "Launch One Better MVP", outcome: "I rely on a usable planning system every week." } }); expect(response.status()).toBe(200); return (await response.json()).goal;
}
async function createMilestone(page: Page, goalId: string, input = checkpoint()) {
  const response = await page.request.post(`/api/goals/${goalId}/milestones`, { headers: { Origin: origin }, data: input }); expect(response.status()).toBe(200); return (await response.json()).milestone;
}
async function fill(page: Page, title: string, condition: string) { await page.getByLabel("Title", { exact: true }).fill(title); await page.getByLabel("Success condition", { exact: true }).fill(condition); }
test.beforeAll(async () => {test.setTimeout(90000);
  const target = requireTestDatabaseURL(); if (target.name === "execution_test") throw new Error("Milestone browser tests require a newly isolated database.");
  database = connectDatabase(target.url); ownerIds = (await database.db.select({ id: user.id }).from(user)).map((row) => row.id);
  // Real auth factory and DB sessions; fixture helper respects the enabled rate limit.
  const auth = createAuthentication(database.db, { secret: process.env.BETTER_AUTH_SECRET!, baseURL: origin });
  for (const suffix of ["A", "B"]) {
    const response = await fixtureSignIn(()=>auth.handler(new Request(`${origin}/api/auth/sign-in/email`, { method: "POST", headers: { Origin: origin, "Content-Type": "application/json" }, body: JSON.stringify({ email: process.env[`TEST_USER_${suffix}_EMAIL`], password: process.env[`TEST_USER_${suffix}_PASSWORD`] }) }))); expect(response.status).toBe(200);
    cookies[suffix] = response.headers.getSetCookie().map((value) => { const pair = value.split(";")[0]; const index = pair.indexOf("="); return { name: pair.slice(0, index), value: pair.slice(index + 1), url: origin, httpOnly: true, sameSite: "Lax" as const }; });
  }
});
test.beforeEach(async ({ page }) => {
  await database.db.delete(mutationReceipt).where(inArray(mutationReceipt.ownerId, ownerIds)); await database.db.delete(amendmentCommitment).where(inArray(amendmentCommitment.ownerId, ownerIds)); await database.db.delete(weeklyPlanAmendment).where(inArray(weeklyPlanAmendment.ownerId, ownerIds)); await database.db.delete(focusSession).where(inArray(focusSession.ownerId, ownerIds)); await database.db.delete(timeBlock).where(inArray(timeBlock.ownerId, ownerIds)); await database.db.delete(commitmentIdentity).where(inArray(commitmentIdentity.ownerId, ownerIds)); await database.db.delete(weeklyCommitment).where(inArray(weeklyCommitment.ownerId, ownerIds)); await database.db.delete(weeklyPlan).where(inArray(weeklyPlan.ownerId, ownerIds)); await database.db.delete(action).where(inArray(action.ownerId, ownerIds)); await database.db.delete(milestone).where(inArray(milestone.ownerId, ownerIds)); await database.db.delete(goal).where(inArray(goal.ownerId, ownerIds)); await page.context().addCookies(cookies.A);
});
test.afterAll(async () => { await database?.pool.end(); });
test("real sign-in → owned Goal → empty milestones → create/reload/edit/complete/evidence/archive/history", async ({ page }) => {
  test.setTimeout(90000);
  const parent = await createGoal(page); await page.context().clearCookies(); await page.goto("/sign-in"); await page.getByLabel("Email", { exact: true }).fill(process.env.TEST_USER_A_EMAIL!); await page.getByLabel("Password", { exact: true }).fill(process.env.TEST_USER_A_PASSWORD!); await signInThroughUI(page);
  await page.getByRole("navigation",{name:"Main navigation"}).getByRole("link",{name:"Goals",exact:true}).click();await page.getByRole("button", { name: `Preview ${parent.title}`, exact: true }).click();await page.getByRole("region",{name:"Goal preview"}).getByRole("link",{name:"Open goal workspace",exact:false}).click(); await expect(page.getByText("Milestones describe observable outcomes", { exact: false })).toBeVisible();
  await page.getByRole("button", { name: "Add milestone", exact: false }).click(); await expect(page.getByLabel("Title", { exact: true })).toBeFocused(); await fill(page, "Weekly planning loop is usable", "Choose commitments against capacity\nand preserve the resulting plan."); await page.getByRole("button", { name: "Save milestone", exact: true }).click();
  await expect(page.getByRole("dialog")).toHaveCount(0); const card = page.locator(".milestone-card"); await expect(card).toContainText("Choose commitments against capacity"); const id = await card.getAttribute("data-milestone-id"); await page.reload(); await expect(card).toBeVisible();
  await page.getByRole("button", { name: "Edit Weekly planning loop is usable", exact: true }).click(); await fill(page, "Unsaved", "Discard me"); await page.getByRole("button", { name: "Cancel", exact: true }).click(); await expect(card).toContainText("Weekly planning loop is usable");
  await page.getByRole("button", { name: "Edit Weekly planning loop is usable", exact: true }).click(); await fill(page, "Planning loop demonstrated", "Plan and close three real weeks without losing history."); await page.getByRole("button", { name: "Save milestone", exact: true }).click(); await expect(card).toContainText("Plan and close three real weeks");
  await page.getByRole("button", { name: "Complete Planning loop demonstrated", exact: true }).click(); await expect(page.getByRole("heading", { name: "Did the success condition happen?" })).toBeVisible(); await expect(page.getByRole("dialog")).toContainText("Plan and close three real weeks"); await page.getByLabel("Evidence / result (optional)").fill("Completed the flow for three consecutive weeks."); await page.getByRole("button", { name: "Confirm completion", exact: true }).click(); await expect(card).toContainText("Completed the flow for three consecutive weeks."); await expect(card.getByRole("button")).toHaveCount(0); await page.reload(); await expect(card).toContainText("Planning loop demonstrated");
  expect((await (await page.request.get(`/api/milestones/${id}`)).json()).milestone).toMatchObject({ version: 3, state: "completed", evidence: "Completed the flow for three consecutive weeks." });
  await page.getByRole("button", { name: "Active", exact: true }).click(); await expect(card).toHaveCount(0); await page.getByRole("button", { name: "Add milestone", exact: false }).click(); await fill(page, "Calendar availability understood", "Busy periods can be read safely."); await page.getByRole("button", { name: "Save milestone", exact: true }).click(); await page.getByRole("button", { name: "Archive Calendar availability understood", exact: true }).click(); await expect(page.getByRole("button", { name: "Cancel", exact: true })).toBeFocused(); await page.getByRole("button", { name: "Cancel", exact: true }).click(); await expect(card).toBeVisible();
  await page.getByRole("button", { name: "Archive Calendar availability understood", exact: true }).click(); await page.getByRole("button", { name: "Archive milestone", exact: true }).click(); await expect(page.getByRole("dialog")).toHaveCount(0); await expect(card.locator(".state-caption")).toHaveText("Archived"); await expect(card).toContainText("Calendar availability understood"); await page.reload(); await expect(card).toContainText("Busy periods can be read safely."); await expect(card.getByRole("button")).toHaveCount(0); expect((await (await page.request.get(`/api/goals/${parent.id}`)).json()).goal).toEqual(parent);
});
test("two tabs preserve stale edit draft until explicit review, then save with a fresh version", async ({ page }) => {
  const parent = await createGoal(page); const child = await createMilestone(page, parent.id); await page.goto(`/goals/${parent.id}`); const other = await page.context().newPage(); await other.goto(page.url());
  for (const current of [page, other]) await current.getByRole("button", { name: `Edit ${child.title}`, exact: true }).click();
  await fill(page, "Saved winner", "The first definition wins."); await page.getByRole("button", { name: "Save milestone", exact: true }).click(); await expect(page.getByRole("dialog")).toHaveCount(0); await expect(page.getByRole("heading", { name: "Saved winner", exact: true })).toBeVisible(); await fill(other, "My draft", "My retained success condition"); await other.getByRole("button", { name: "Save milestone", exact: true }).click();
  await expect(other.locator(".milestones-section [role=alert]")).toContainText("changed elsewhere"); await expect(other.getByLabel("Success condition", { exact: true })).toHaveValue("My retained success condition"); await expect(other.getByRole("button", { name: "Save milestone", exact: true })).toBeDisabled(); await other.getByRole("button", { name: "Review latest saved version" }).click(); await expect(other.getByText("Latest saved version reviewed.", { exact: false })).toBeVisible(); await other.getByRole("button", { name: "Save milestone", exact: true }).click(); await expect(other.getByRole("dialog")).toHaveCount(0);
  expect((await (await page.request.get(`/api/milestones/${child.id}`)).json()).milestone).toMatchObject({ title: "My draft", successCondition: "My retained success condition", version: 3 }); await other.close();
});
test("stale completion retains evidence and requires review of the changed success condition", async ({ page }) => {
  const parent = await createGoal(page); const child = await createMilestone(page, parent.id); await page.goto(`/goals/${parent.id}`); await page.getByRole("button", { name: `Complete ${child.title}`, exact: true }).click(); await page.getByLabel("Evidence / result (optional)").fill("My evidence draft");
  expect((await page.request.patch(`/api/milestones/${child.id}`, { headers: { Origin: origin }, data: { ...checkpoint({ successCondition: "A newly declared success condition" }), expectedVersion: 1 } })).status()).toBe(200);
  await page.getByRole("button", { name: "Confirm completion", exact: true }).click(); await expect(page.locator(".milestones-section [role=alert]")).toContainText("changed elsewhere"); await expect(page.getByLabel("Evidence / result (optional)")).toHaveValue("My evidence draft"); await page.getByRole("button", { name: "Review latest saved version" }).click(); await expect(page.getByRole("dialog")).toContainText("A newly declared success condition"); await page.getByRole("button", { name: "Confirm completion", exact: true }).click(); await expect(page.locator(".milestone-card")).toContainText("My evidence draft");
});
test("archived Goal keeps all history read-only and blocks a draft already open", async ({ page }) => {
  const parent = await createGoal(page); const active = await createMilestone(page, parent.id); const completed = await createMilestone(page, parent.id, checkpoint({ title: "Completed checkpoint" })); const archived = await createMilestone(page, parent.id, checkpoint({ title: "Archived checkpoint" }));
  await page.request.post(`/api/milestones/${completed.id}/complete`, { headers: { Origin: origin }, data: { ...transition(), evidence: "Observed success" } }); await page.request.post(`/api/milestones/${archived.id}/archive`, { headers: { Origin: origin }, data: transition() });
  await page.goto(`/goals/${parent.id}`); await page.getByRole("button", { name: `Edit ${active.title}`, exact: true }).click(); await fill(page, "Retained draft", "Must survive a parent archive"); expect((await page.request.post(`/api/goals/${parent.id}/archive`, { headers: { Origin: origin }, data: transition() })).status()).toBe(200); await page.getByRole("button", { name: "Save milestone", exact: true }).click(); await expect(page.locator(".milestones-section [role=alert]")).toContainText("goal is archived"); await expect(page.getByLabel("Success condition", { exact: true })).toHaveValue("Must survive a parent archive"); await expect(page.getByRole("button", { name: "Save milestone", exact: true })).toBeDisabled(); await page.getByRole("button", { name: "Close without saving" }).click();
  await page.reload(); await expect(page.getByText("Its milestones are kept as read-only history.", { exact: false })).toBeVisible(); await expect(page.getByRole("button", { name: "Add milestone", exact: false })).toHaveCount(0); await expect(page.locator(".milestone-card").getByRole("button")).toHaveCount(0);
  for (const [view, text] of [["Completed", "Observed success"], ["Archived", "Archived checkpoint"], ["Active", active.title]]) { await page.getByRole("button", { name: view, exact: true }).click(); await expect(page.locator(".milestone-card")).toContainText(text); }
  expect((await page.request.post(`/api/goals/${parent.id}/milestones`, { headers: { Origin: origin }, data: checkpoint() })).status()).toBe(409);
});
test("lost acknowledgements reuse identical create/edit/complete/archive commands", async ({ page }) => {
  const parent = await createGoal(page); await page.goto(`/goals/${parent.id}`);
  async function lose(url: string, method: string, submit: string) {
    const bodies: string[] = []; let first = true;
    await page.route(url, async (route) => { if (route.request().method() !== method) return route.continue(); bodies.push(route.request().postData()!); if (first) { first = false; expect((await route.fetch()).status()).toBe(200); await route.abort("failed"); } else await route.continue(); });
    await page.getByRole("button", { name: submit, exact: true }).click(); await expect(page.locator(".milestones-section [role=alert]")).toContainText("may have saved"); await expect(page.getByRole("button", { name: "Cancel", exact: true })).toBeDisabled(); await page.getByRole("button", { name: "Retry same change", exact: true }).click(); await expect(page.getByRole("dialog")).toHaveCount(0); expect(bodies).toHaveLength(2); expect(bodies[0]).toBe(bodies[1]); await page.unroute(url);
  }
  await page.getByRole("button", { name: "Add milestone", exact: false }).click(); await fill(page, "One logical checkpoint", "Persisted exactly once"); await lose(`**/api/goals/${parent.id}/milestones`, "POST", "Save milestone"); const id = await page.locator(".milestone-card").getAttribute("data-milestone-id"); await page.getByRole("button", { name: "Edit One logical checkpoint", exact: true }).click(); await fill(page, "Edited once", "Edited once despite retry"); await lose(`**/api/milestones/${id}`, "PATCH", "Save milestone"); await page.getByRole("button", { name: "Complete Edited once", exact: true }).click(); await page.getByLabel("Evidence / result (optional)").fill("Completed once"); await lose(`**/api/milestones/${id}/complete`, "POST", "Confirm completion"); expect((await (await page.request.get(`/api/milestones/${id}`)).json()).milestone.version).toBe(3);
  await page.getByRole("button", { name: "Active", exact: true }).click(); const second = await createMilestone(page, parent.id, checkpoint({ title: "Archive once" })); await page.reload(); await page.getByRole("button", { name: "Archive Archive once", exact: true }).click(); await lose(`**/api/milestones/${second.id}/archive`, "POST", "Archive milestone"); expect((await (await page.request.get(`/api/milestones/${second.id}`)).json()).milestone.version).toBe(2);
  expect((await (await page.request.get(`/api/goals/${parent.id}/milestones`)).json()).milestones).toHaveLength(2);
});
test("server validation, terminal restrictions, CSRF, two-owner isolation and anonymous routes", async ({ page, browser }) => {
  const parent = await createGoal(page); const child = await createMilestone(page, parent.id);
  for (const fields of [{ title: " " }, { successCondition: " " }, { goalId: randomUUID() }, { ownerId: ownerIds[1] }]) { const response = await page.request.post(`/api/goals/${parent.id}/milestones`, { headers: { Origin: origin }, data: checkpoint(fields) }); expect(response.status()).toBe(400); expect((await response.json()).error.code).toBe("VALIDATION"); }
  expect((await page.request.post(`/api/milestones/${child.id}/complete`, { headers: { Origin: "https://foreign.example.test" }, data: transition() })).status()).toBe(403);
  expect((await page.request.post(`/api/milestones/${child.id}/complete`, { headers: { Origin: origin }, data: transition() })).status()).toBe(200);
  for (const [method, path, input] of [["PATCH", "", { ...checkpoint(), expectedVersion: 2 }], ["POST", "/complete", transition(2)], ["POST", "/archive", transition(2)]] as const) expect((await page.request.fetch(`/api/milestones/${child.id}${path}`, { method, headers: { Origin: origin }, data: input })).status()).toBe(409);
  const foreign = await browser.newContext(); await foreign.addCookies(cookies.B); const stranger = await foreign.newPage();
  const anonymous = await browser.newContext(); const anon = await anonymous.newPage();
  try {
    for (const current of [stranger, anon]) for (const [method, url, input] of [["GET", `/api/goals/${parent.id}/milestones`, undefined], ["POST", `/api/goals/${parent.id}/milestones`, checkpoint()], ["GET", `/api/milestones/${child.id}`, undefined], ["PATCH", `/api/milestones/${child.id}`, { ...checkpoint(), expectedVersion: 2 }], ["POST", `/api/milestones/${child.id}/complete`, transition(2)], ["POST", `/api/milestones/${child.id}/archive`, transition(2)]] as const) {
      const response = await current.request.fetch(url, { method, headers: { Origin: origin }, data: input }); expect(response.status()).toBe(current === anon ? 401 : 404); const error = (await response.json()).error; expect(error).not.toHaveProperty("details.current");
    }
    await stranger.goto(`/goals/${parent.id}`); await expect(stranger.getByRole("heading", { name: "404" })).toBeVisible(); await anon.goto(`/goals/${parent.id}`); await expect(anon.getByRole("heading", { name: "Welcome to One Better.", exact: true })).toBeVisible();
  } finally { await foreign.close(); await anonymous.close(); }
});
test("plain text, keyboard focus, responsive width and load failure stay explicit", async ({ page }) => {
  const parent = await createGoal(page); await page.setViewportSize({ width: 390, height: 844 }); await page.goto(`/goals/${parent.id}`); await page.getByRole("button", { name: "Add milestone", exact: false }).focus(); await page.keyboard.press("Enter"); await expect(page.getByLabel("Title", { exact: true })).toBeFocused(); await fill(page, "<script>alert(1)</script>", "<img src=x onerror=alert(1)> is plain text."); await page.getByRole("button", { name: "Save milestone", exact: true }).click(); await expect(page.locator(".milestone-card")).toContainText("<script>alert(1)</script>"); expect(await page.locator(".milestone-card script, .milestone-card img").count()).toBe(0); expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.route(`**/api/goals/${parent.id}/milestones`, (route) => route.fulfill({ status: 503, contentType: "application/json", body: JSON.stringify({ error: { code: "DATABASE_UNAVAILABLE", message: "Unavailable" } }) })); await page.getByRole("button", { name: "Completed", exact: true }).click(); await expect(page.locator(".milestones-section [role=alert]")).toContainText("could not be refreshed"); await expect(page.getByText("No completed milestones yet.", { exact: true })).toHaveCount(0); await page.unroute(`**/api/goals/${parent.id}/milestones`); await page.getByRole("button", { name: "Retry loading milestones" }).click(); await expect(page.getByText("No completed milestones yet.", { exact: true })).toBeVisible();
});
