import {fixtureSignIn} from "./sign-in-helper";
import { signInThroughUI } from "./sign-in-helper";
import { test, expect, type Page, type BrowserContext } from "@playwright/test";
import { randomUUID } from "node:crypto";
import { inArray } from "drizzle-orm";
import { connectDatabase } from "../../src/db/connect";
import { focusSession, timeBlock, commitmentIdentity, weeklyPlanAmendment, amendmentCommitment, action, goal, milestone, mutationReceipt, user, weeklyCommitment, weeklyPlan } from "../../src/db/schema";
import { createAuthentication } from "../../src/server/auth-factory";
import { requireTestDatabaseURL } from "../../scripts/test-database";
import { addDays } from "../../src/modules/planning/domain";
const origin = "http://127.0.0.1:3101";
let database: ReturnType<typeof connectDatabase>; let ownerIds: string[];
const cookies: Record<string, Parameters<BrowserContext["addCookies"]>[0]> = {};
async function mutate(page: Page, path: string, input: object, method = "POST") { const response = await page.request.fetch(path, { method, headers: { Origin: origin }, data: input }); expect(response.status(), await response.text()).toBe(200); return response.json(); }
async function fixture(page: Page) {
  const parent = (await mutate(page, "/api/goals", { mutationId: randomUUID(), title: "A useful One Better system", outcome: "I choose meaningful work without filling every minute." })).goal;
  const first = (await mutate(page, `/api/goals/${parent.id}/milestones`, { mutationId: randomUUID(), title: "Weekly planning usable", successCondition: "One realistic week is deliberately planned." })).milestone;
  const second = (await mutate(page, `/api/goals/${parent.id}/milestones`, { mutationId: randomUUID(), title: "Next useful outcome", successCondition: "Context moves are explicit." })).milestone;
  const values = [];
  for (const [title, estimateMinutes, milestoneId] of [["Build capacity editor", 120, null], ["Implement planning persistence", 240, first.id], ["Test planning flow", 45, second.id]] as const) values.push((await mutate(page, `/api/goals/${parent.id}/actions`, { mutationId: randomUUID(), title, estimateMinutes, milestoneId, doneWhen: "The chosen outcome can be demonstrated." })).action);
  const workspace = await (await page.request.get("/api/weekly-plans")).json(); const candidates = (await (await page.request.get("/api/weekly-plans/candidates")).json()).candidates;
  const selections = values.map((v, i) => ({ actionId: v.id, source: candidates.find((c: { actionId: string }) => c.actionId === v.id).source, budgetMinutes: [180, 120, 90][i] }));
  return { parent, first, second, values, selections, week: workspace.currentWeekStartDate };
}
async function createDraft(page: Page) { await page.getByLabel("Weekly focus capacity in minutes").fill("720"); await page.getByLabel("Protected reserve in minutes").fill("180"); await page.getByRole("button", { name: "Create weekly draft", exact: true }).click(); await expect(page.getByRole("button", { name: "Save draft", exact: true })).toBeVisible(); }
async function select(page: Page, id: string, budget: string) { await page.locator(`[data-candidate-action="${id}"]`).getByRole("button", { name: "Add to this week" }).click(); const card = page.locator(`[data-selected-action="${id}"]`); await expect(card.getByLabel("This week’s budget in minutes")).toHaveValue(""); await card.getByLabel("This week’s budget in minutes").fill(budget); }
async function save(page: Page) { await page.getByRole("button", { name: "Save draft", exact: true }).click(); await expect(page.getByRole("status")).toContainText("Draft saved"); }
async function baseline(page: Page) { await page.getByRole("button", { name: "Review and commit" }).click(); const dialog = page.getByRole("dialog"); await expect(dialog.getByRole("button", { name: "Keep drafting" })).toBeFocused(); await dialog.getByRole("button", { name: "Commit this week" }).click(); await expect(page.getByText("Your original commitments", { exact: true })).toBeVisible(); }
test.beforeAll(async () => {test.setTimeout(90000);
  const target = requireTestDatabaseURL(); if (target.name === "execution_test") throw new Error("Planning browser tests require a new isolated database.");
  database = connectDatabase(target.url); ownerIds = (await database.db.select({ id: user.id }).from(user)).map((row) => row.id);
  const auth = createAuthentication(database.db, { secret: process.env.BETTER_AUTH_SECRET!, baseURL: origin });
  for (const suffix of ["A", "B"]) { const response = await fixtureSignIn(()=>auth.handler(new Request(`${origin}/api/auth/sign-in/email`, { method: "POST", headers: { Origin: origin, "Content-Type": "application/json" }, body: JSON.stringify({ email: process.env[`TEST_USER_${suffix}_EMAIL`], password: process.env[`TEST_USER_${suffix}_PASSWORD`] }) }))); expect(response.status).toBe(200); cookies[suffix] = response.headers.getSetCookie().map((value) => { const pair = value.split(";")[0], index = pair.indexOf("="); return { name: pair.slice(0, index), value: pair.slice(index + 1), url: origin, httpOnly: true, sameSite: "Lax" as const }; }); }
});
test.beforeEach(async ({ page }) => { await database.db.delete(mutationReceipt).where(inArray(mutationReceipt.ownerId, ownerIds)); await database.db.delete(amendmentCommitment).where(inArray(amendmentCommitment.ownerId, ownerIds)); await database.db.delete(weeklyPlanAmendment).where(inArray(weeklyPlanAmendment.ownerId, ownerIds)); await database.db.delete(focusSession).where(inArray(focusSession.ownerId, ownerIds)); await database.db.delete(timeBlock).where(inArray(timeBlock.ownerId, ownerIds)); await database.db.delete(commitmentIdentity).where(inArray(commitmentIdentity.ownerId, ownerIds)); await database.db.delete(weeklyCommitment).where(inArray(weeklyCommitment.ownerId, ownerIds)); await database.db.delete(weeklyPlan).where(inArray(weeklyPlan.ownerId, ownerIds)); await database.db.delete(action).where(inArray(action.ownerId, ownerIds)); await database.db.delete(milestone).where(inArray(milestone.ownerId, ownerIds)); await database.db.delete(goal).where(inArray(goal.ownerId, ownerIds)); await page.context().addCookies(cookies.A); });
test.afterAll(async () => { await database?.pool.end(); });
test("sign in → shell → 12h/3h/9h → deliberate budgets → over-capacity → save/reload → review → immutable baseline", async ({ page }) => {
  test.setTimeout(90000);
  const f = await fixture(page); await page.context().clearCookies(); await page.goto("/sign-in"); await page.getByLabel("Email", { exact: true }).fill(process.env.TEST_USER_A_EMAIL!); await page.getByLabel("Password", { exact: true }).fill(process.env.TEST_USER_A_PASSWORD!); await signInThroughUI(page); await page.locator(".settings-menu summary").click();await page.getByRole("link", { name: "Weekly planning", exact: true }).click(); await createDraft(page);
  for (let i = 0; i < f.values.length; i++) await select(page, f.values[i].id, String(f.selections[i].budgetMinutes));
  await expect(page.getByLabel("Capacity summary")).toContainText("6h 30m"); await expect(page.getByLabel("Capacity summary")).toContainText("2h 30m"); await expect(page.getByLabel("Capacity summary")).toContainText("Breathing room is healthy"); await expect(page.locator(`[data-selected-action="${f.values[0].id}"]`)).toContainText("Action estimate: 2h");
  await page.locator(`[data-selected-action="${f.values[0].id}"]`).getByLabel("This week’s budget in minutes").fill("600"); await save(page); await expect(page.getByRole("status")).toContainText("Resolve over-capacity before committing"); await expect(page.getByLabel("Capacity summary").getByRole("alert")).toContainText("over capacity"); await expect(page.getByRole("button", { name: "Review and commit" })).toBeDisabled(); await page.reload(); await expect(page.locator(`[data-selected-action="${f.values[0].id}"]`).getByLabel("This week’s budget in minutes")).toHaveValue("600");
  await page.locator(`[data-selected-action="${f.values[0].id}"]`).getByLabel("This week’s budget in minutes").fill("180"); await save(page); await page.getByRole("button", { name: "Review and commit" }).click(); const dialog = page.getByRole("dialog"); await expect(dialog).toContainText("9h"); await expect(dialog).toContainText(f.first.title); await dialog.getByRole("button", { name: "Keep drafting" }).click(); await expect(page.getByText("Your original commitments", { exact: true })).toHaveCount(0); await baseline(page); await page.reload(); await expect(page.locator(".commitment-card")).toHaveCount(3); await expect(page.getByLabel("Capacity summary")).toContainText("Still uncommitted2h 30m"); await expect(page.getByRole("button", { name: /Save draft|Add to this week|Remove commitment/ })).toHaveCount(0);
});
test("source edits and terminal parents leave frozen historical meaning and budget unchanged", async ({ page }) => {
  const f = await fixture(page); await page.goto("/planning"); await createDraft(page); await select(page, f.values[0].id, "180"); await select(page, f.values[1].id, "120"); await save(page); await baseline(page);
  await mutate(page, `/api/actions/${f.values[0].id}`, { mutationId: randomUUID(), expectedVersion: 1, title: "Renamed current source", estimateMinutes: 10, doneWhen: "New definition", milestoneId: f.second.id }, "PATCH"); await mutate(page, `/api/actions/${f.values[0].id}/complete`, { mutationId: randomUUID(), expectedVersion: 2 }); await mutate(page, `/api/milestones/${f.first.id}/archive`, { mutationId: randomUUID(), expectedVersion: 1 }); await mutate(page, `/api/goals/${f.parent.id}/archive`, { mutationId: randomUUID(), expectedVersion: 1 }); await page.reload();
  await expect(page.locator(".commitment-list")).toContainText("Build capacity editor"); await expect(page.locator(".commitment-list")).toContainText("Action estimate: 2h"); await expect(page.locator(".commitment-list")).toContainText(f.first.title); await expect(page.locator(".commitment-list")).not.toContainText("Renamed current source"); await expect(page.locator(".commitment-list")).toContainText("3h this week");
});
test("version conflicts retain capacity, reserve, selections and budgets before explicit latest-plan review", async ({ page }) => {
  const f = await fixture(page); await page.goto("/planning"); await createDraft(page); await select(page, f.values[0].id, "180"); await save(page); const current = (await (await page.request.get(`/api/weekly-plans?week=${f.week}`)).json()).view.plan;
  await page.getByLabel("Weekly focus capacity in minutes").fill("660"); await page.getByLabel("Protected reserve in minutes").fill("120"); await page.locator(`[data-selected-action="${f.values[0].id}"]`).getByLabel("This week’s budget in minutes").fill("210");
  await mutate(page, `/api/weekly-plans/${current.id}`, { mutationId: randomUUID(), expectedVersion: current.version, provisionalCapacityMinutes: 600, reserveMinutes: 240, commitments: [f.selections[1]] }, "PATCH"); await page.getByRole("button", { name: "Save draft", exact: true }).click(); await expect(page.locator(".planning-workspace").getByRole("alert")).toContainText("changed elsewhere"); await page.getByRole("button", { name: "Review latest saved plan" }).click(); await expect(page.getByRole("status")).toContainText("Latest saved version reviewed"); await expect(page.getByLabel("Weekly focus capacity in minutes")).toHaveValue("660"); await expect(page.getByLabel("Protected reserve in minutes")).toHaveValue("120"); await expect(page.locator(`[data-selected-action="${f.values[0].id}"]`).getByLabel("This week’s budget in minutes")).toHaveValue("210"); await save(page); await page.reload(); await expect(page.locator(`[data-selected-action="${f.values[0].id}"]`)).toBeVisible(); await expect(page.locator(`[data-selected-action="${f.values[1].id}"]`)).toHaveCount(0);
});
test("active Milestone reassignment blocks commitment until latest source is reviewed and explicitly accepted", async ({ page }) => {
  const f = await fixture(page); await page.goto("/planning"); await createDraft(page); await select(page, f.values[1].id, "120"); await save(page);
  await mutate(page, `/api/actions/${f.values[1].id}`, { mutationId: randomUUID(), expectedVersion: 1, title: f.values[1].title, milestoneId: f.second.id, estimateMinutes: 240 }, "PATCH"); await page.getByRole("button", { name: "Review and commit" }).click(); await page.getByRole("dialog").getByRole("button", { name: "Commit this week" }).click(); await expect(page.locator(".planning-workspace").getByRole("alert")).toContainText("Review the selected commitments"); await page.getByRole("button", { name: "Refresh saved context" }).click(); await page.getByRole("button", { name: "Review latest source" }).click(); await expect(page.locator(".source-review")).toContainText(f.second.title); await page.getByRole("button", { name: "Accept reviewed source" }).click(); await save(page); await baseline(page); await expect(page.locator(".commitment-list")).toContainText(f.second.title);
});
test("terminal sources stay selected until deliberately removed; empty drafts cannot commit", async ({ page }) => {
  const f = await fixture(page); await page.goto("/planning"); await createDraft(page); await expect(page.getByRole("button", { name: "Review and commit" })).toBeDisabled(); await select(page, f.values[1].id, "120"); await save(page); await mutate(page, `/api/milestones/${f.first.id}/complete`, { mutationId: randomUUID(), expectedVersion: 1 }); await page.reload(); const selected = page.locator(`[data-selected-action="${f.values[1].id}"]`); await expect(selected).toContainText("milestone is completed"); await expect(page.getByRole("button", { name: "Review and commit" })).toBeDisabled(); await selected.getByRole("button", { name: "Remove commitment" }).click(); await save(page); await expect(page.locator(`[data-candidate-action="${f.values[1].id}"]`)).toHaveCount(0); await expect(page.getByRole("button", { name: "Review and commit" })).toBeDisabled();
});
for (const stage of ["create", "save", "commit"] as const) test(`lost ${stage} response retries the identical command and shows current persisted state`, async ({ page }) => {
  const f = await fixture(page); await page.goto("/planning"); if (stage !== "create") { await createDraft(page); await select(page, f.values[0].id, "180"); if (stage === "commit") await save(page); }
  const payloads: string[] = []; let dropped = false; const path = stage === "create" ? "**/api/weekly-plans" : stage === "save" ? "**/api/weekly-plans/*" : "**/api/weekly-plans/*/commit";
  await page.route(path, async (route) => { if (route.request().method() !== (stage === "save" ? "PATCH" : "POST")) return route.continue(); payloads.push(route.request().postData()!); const response = await route.fetch(); expect(response.status()).toBe(200); if (!dropped) { dropped = true; await route.fulfill({ status: 200, contentType: "application/json", body: "interrupted" }); } else await route.fulfill({ response }); });
  if (stage === "create") { await page.getByLabel("Weekly focus capacity in minutes").fill("720"); await page.getByLabel("Protected reserve in minutes").fill("180"); await page.getByRole("button", { name: "Create weekly draft" }).click(); } else if (stage === "save") await page.getByRole("button", { name: "Save draft", exact: true }).click(); else { await page.getByRole("button", { name: "Review and commit" }).click(); await page.getByRole("dialog").getByRole("button", { name: "Commit this week" }).click(); }
  await expect(page.getByRole("button", { name: "Retry same command" })).toBeVisible(); if (stage !== "commit") await expect(page.getByLabel("Weekly focus capacity in minutes")).toBeDisabled(); await page.getByRole("button", { name: "Retry same command" }).click(); await expect(page.getByRole("status")).toContainText(stage === "commit" ? "baseline is committed" : stage === "save" ? "Draft saved" : "Draft created"); expect(payloads).toHaveLength(2); expect(payloads[1]).toBe(payloads[0]); await page.reload(); await expect(page.getByText(stage === "commit" ? "Your original commitments" : "Your selected commitments", { exact: true })).toBeVisible();
});
test("HTTP owner isolation, anonymous rejection, exact Origin, strict inputs and no destructive endpoint", async ({ page, browser }) => {
  const f = await fixture(page); const plan = (await mutate(page, "/api/weekly-plans", { mutationId: randomUUID(), weekStartDate: f.week, provisionalCapacityMinutes: 720, reserveMinutes: 180 })).plan;
  const foreign = await browser.newContext(); await foreign.addCookies(cookies.B); const anonymous = await browser.newContext();
  try { for (const context of [foreign, anonymous]) { for (const [method, path, data] of [["GET", `/api/weekly-plans/${plan.id}`, undefined], ["PATCH", `/api/weekly-plans/${plan.id}`, { mutationId: randomUUID(), expectedVersion: 1, provisionalCapacityMinutes: 600, reserveMinutes: 120, commitments: [] }], ["POST", `/api/weekly-plans/${plan.id}/commit`, { mutationId: randomUUID(), expectedVersion: 1 }]] as const) { const response = await context.request.fetch(path, { method, headers: { Origin: origin }, data }); expect(response.status()).toBe(context === anonymous ? 401 : 404); expect((await response.json()).error).not.toHaveProperty("current"); } }
    expect((await (await foreign.request.get("/api/weekly-plans")).json()).savedWeeks).toEqual([]); expect((await (await foreign.request.get("/api/weekly-plans/candidates")).json()).candidates).toEqual([]);
  } finally { await foreign.close(); await anonymous.close(); }
  expect((await page.request.post("/api/weekly-plans", { headers: { Origin: "https://wrong.example" }, data: {} })).status()).toBe(403); expect((await page.request.post("/api/weekly-plans", { headers: { Origin: origin }, data: { mutationId: randomUUID(), weekStartDate: f.week, provisionalCapacityMinutes: 720, reserveMinutes: 180, ownerId: ownerIds[0] } })).status()).toBe(400); expect((await page.request.delete(`/api/weekly-plans/${plan.id}`, { headers: { Origin: origin } })).status()).toBe(405);
});
test("week navigation, historical baseline, no new finished week, keyboard, small-screen and explicit load failure", async ({ page }) => {
  const f = await fixture(page); await page.setViewportSize({ width: 390, height: 844 }); await page.goto("/planning"); await createDraft(page); await select(page, f.values[0].id, "180"); await save(page); await baseline(page); await page.getByRole("link", { name: "Next week →", exact: true }).click(); await expect(page.getByLabel("Weekly focus capacity in minutes")).toBeVisible(); await page.getByRole("link", { name: "← Previous week", exact: true }).click(); await expect(page.getByText("Your original commitments", { exact: true })).toBeVisible(); await page.goto(`/planning?week=${addDays(f.week, -7)}`); await expect(page.getByText("This week has finished.", { exact: false })).toBeVisible(); await expect(page.getByRole("button", { name: "Create weekly draft" })).toHaveCount(0);
  await page.goto(`/planning?week=${addDays(f.week, 7)}`); await createDraft(page); await page.locator(`[data-candidate-action="${f.values[0].id}"]`).getByRole("button").focus(); await page.keyboard.press("Enter"); await expect(page.locator(`[data-selected-action="${f.values[0].id}"]`)).toBeVisible(); expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.route("**/api/weekly-plans/candidates", (route) => route.fulfill({ status: 503, contentType: "application/json", body: JSON.stringify({ error: { code: "DATABASE_UNAVAILABLE", message: "Candidates unavailable" } }) })); await page.getByRole("button", { name: "Refresh eligible Actions" }).click(); await expect(page.locator(".planning-workspace").getByRole("alert")).toContainText("Candidates unavailable"); await expect(page.locator(`[data-selected-action="${f.values[0].id}"]`)).toBeVisible();
});
