import {test,expect,type Page} from '@playwright/test';
import {mkdir,writeFile} from 'node:fs/promises';
import {randomUUID} from 'node:crypto';
import {connectDatabase} from '../../src/db/connect';
import {requireTestDatabaseURL} from '../../scripts/test-database';
import {createAuthentication} from '../../src/server/auth-factory';
import {fixtureSignIn} from './sign-in-helper';
import {seedR5F,r5fPassword} from '../r5f-scenario';
import {reviewQualityNow,reviewQualityWeek,reviewPrivacyMarkers,type ReviewQualityKind} from '../review-insight-fixture';
import {coachingCleanupTables} from '../coaching-database';
const database=connectDatabase(requireTestDatabaseURL().url),origin='http://127.0.0.1:3101',screenshots='docs/r5f-evidence/fixtures';let scenario:Awaited<ReturnType<typeof seedR5F>>;
async function control(mode='useful',reset=false){return(await fetch(`${process.env.AI_TEST_BASE_URL}/control`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode,reset})})).json();}
test.beforeAll(async()=>{scenario=await seedR5F(database.db,database.pool);await mkdir(screenshots,{recursive:true});});
test.beforeEach(async()=>{test.setTimeout(90000);await writeFile(process.env.EXECUTION_TEST_CLOCK_FILE!,reviewQualityNow);await control('useful',true);});
test.afterAll(async()=>{if(scenario){const owners=scenario.fixtures.map(f=>f.actor.userId);for(const table of coachingCleanupTables)await database.pool.query(`DELETE FROM ${table} WHERE owner_id=ANY($1)`,[owners]);await database.pool.query('DELETE FROM app_user WHERE id=ANY($1)',[owners]);}await database.pool.end();});
async function signIn(page:Page,kind:ReviewQualityKind){const f=scenario.fixtures.find(f=>f.kind===kind)!;const auth=createAuthentication(database.db,{secret:process.env.BETTER_AUTH_SECRET!,baseURL:origin}),login=await fixtureSignIn(()=>auth.handler(new Request(`${origin}/api/auth/sign-in/email`,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({email:f.email,password:r5fPassword})})));await page.context().clearCookies();await page.context().addCookies(login.headers.getSetCookie().map(value=>{const pair=value.split(';')[0],i=pair.indexOf('=');return {name:pair.slice(0,i),value:pair.slice(i+1),url:origin,httpOnly:true,sameSite:'Lax' as const};}));await page.goto(`/review?week=${reviewQualityWeek}`);return page.getByRole('region',{name:'Coach’s perspective',exact:true});}
test('multi-evidence, reflection and real repeated-Carry topics keep Evidence/Coach/Question separate',async({page})=>{
 test.setTimeout(90000);await page.setViewportSize({width:1440,height:1000});for(const kind of ['gap_reflection','repeated_carry','no_reflection'] as const){const coach=await signIn(page,kind);await coach.getByRole('button',{name:/^(Get|Refresh) coaching$/}).click();await expect(coach.locator('.coach-review-insight')).toHaveCount(1);await expect(coach.getByRole('heading',{name:'Evidence',exact:true})).toBeVisible();await expect(coach.getByRole('heading',{name:'Coach',exact:true})).toBeVisible();await expect(coach.getByRole('heading',{name:'Question',exact:true})).toBeVisible();await expect(coach.getByRole('button',{name:'Preview',exact:true})).toHaveCount(0);if(kind==='gap_reflection')await expect(coach).toContainText(reviewPrivacyMarkers.daily);if(kind==='repeated_carry')await expect(coach).toContainText('2 distinct finalized Reviews');const sent=JSON.stringify((await control()).lastContext);for(const marker of [reviewPrivacyMarkers.draftDaily,reviewPrivacyMarkers.draftWeekly,reviewPrivacyMarkers.late,reviewPrivacyMarkers.session])expect(sent).not.toContain(marker);await page.screenshot({path:`${screenshots}/${kind}.png`,fullPage:true});}
 const calls=(await control()).calls;await page.reload();await expect(page.getByRole('region',{name:'Coach’s perspective',exact:true}).locator('.coach-review-insight')).toHaveCount(1);expect((await control()).calls).toBe(calls);
});
test('already-protected next week, clean week and completed source produce calm successful zero-insight states',async({page})=>{
 test.setTimeout(90000);for(const kind of ['already_addressed','clean','completed'] as const){const coach=await signIn(page,kind);await coach.getByRole('button',{name:/^(Get|Refresh) coaching$/}).click();await expect(coach).toContainText('No useful suggestion is supported');await expect(coach.locator('.coach-review-insight')).toHaveCount(0);expect((await control()).lastContext.reviewCandidates).toEqual([]);await page.screenshot({path:`${screenshots}/${kind}.png`,fullPage:true});}
});
test('next-week Draft changes stale saved Review prose and hide it until an explicit refresh',async({page})=>{
 const f=scenario.fixtures.find(f=>f.kind==='gap_reflection')!,coach=await signIn(page,f.kind);await coach.getByRole('button',{name:/^(Get|Refresh) coaching$/}).click();await expect(coach.locator('.coach-review-insight')).toHaveCount(1);await expect.poll(async()=>(await control()).calls).toBe(1);
 const source=(await scenario.services.plans.candidates(f.actor))[0];let next=await scenario.services.plans.create(f.actor,{mutationId:randomUUID(),weekStartDate:'2028-01-10',provisionalCapacityMinutes:180,reserveMinutes:30});next=await scenario.services.plans.save(f.actor,next.id,{mutationId:randomUUID(),expectedVersion:next.version,provisionalCapacityMinutes:180,reserveMinutes:30,commitments:[{actionId:source.actionId,budgetMinutes:90,source:source.source}]});expect(next.state).toBe('draft');await page.reload();await expect(coach).toContainText('Facts changed since this advice');await expect(coach.locator('.coach-review-insight')).toHaveCount(0);expect((await control()).calls).toBe(1);await page.screenshot({path:`${screenshots}/stale.png`,fullPage:true});await coach.getByRole('button',{name:'Refresh coaching',exact:true}).click();await expect(coach.locator('.coach-review-insight')).toHaveCount(1);await expect(coach).toContainText('draft plan; 90m selected');
});
test('provider failure and withheld malformed output leave Review and human decisions usable',async({page})=>{
 const f=scenario.fixtures[0],before=(await database.pool.query('SELECT row_to_json(t) FROM weekly_review_decision t WHERE owner_id=$1',[f.actor.userId])).rows,coach=await signIn(page,f.kind);for(const [mode,message] of [['authentication','connection needs attention'],['malformed','could not be verified']]){await control(mode);await coach.getByRole('button',{name:/^(Get|Refresh) coaching$/}).click();await expect(coach).toContainText(message);await expect(coach.locator('.coach-review-insight')).toHaveCount(0);await expect(page.getByRole('link',{name:'Calendar',exact:true})).toBeVisible();expect(await page.content()).not.toContain('SECRET_FIXTURE_PAYLOAD');await page.screenshot({path:`${screenshots}/${mode}.png`,fullPage:true});}
 expect((await database.pool.query('SELECT row_to_json(t) FROM weekly_review_decision t WHERE owner_id=$1',[f.actor.userId])).rows).toEqual(before);
});
