import {fixtureSignIn} from "./sign-in-helper";
import {test,expect,type Page,type BrowserContext} from "@playwright/test";
import {randomUUID} from "node:crypto";
import {inArray} from "drizzle-orm";
import {connectDatabase} from "../../src/db/connect";
import {weeklyReviewDecision,weeklyReview,dailyReflection,focusSession,timeBlock,commitmentIdentity,weeklyPlan,weeklyCommitment,weeklyPlanAmendment,amendmentCommitment,action,goal,milestone,mutationReceipt,user,focusableHours,calendarAvailabilityCache,calendarOAuthFlow,calendarConnection} from "../../src/db/schema";
import {createAuthentication} from "../../src/server/auth-factory";
import {requireTestDatabaseURL} from "../../scripts/test-database";
import type {WeeklyPlan} from "../../src/modules/planning/domain";
import type {SchedulingView,TimeBlock,PlacementReview} from "../../src/modules/scheduling/domain";
const origin="http://127.0.0.1:3101",week="2028-01-03";let database:ReturnType<typeof connectDatabase>,owners:string[];const cookies:Record<string,Parameters<BrowserContext["addCookies"]>[0]>={};
async function clean(){for(const table of [weeklyReviewDecision,weeklyReview,dailyReflection,focusSession,timeBlock,commitmentIdentity,mutationReceipt,amendmentCommitment,weeklyPlanAmendment,weeklyCommitment,weeklyPlan,action,milestone,goal,focusableHours,calendarAvailabilityCache,calendarOAuthFlow,calendarConnection])await database.db.delete(table).where(inArray(table.ownerId,owners));await database.pool.query("UPDATE app_user SET timezone='Europe/London' WHERE id=ANY($1)",[owners]);}
test.beforeAll(async()=>{test.setTimeout(90000);const target=requireTestDatabaseURL();if(target.name==="execution_test")throw new Error("Requires isolated browser DB");database=connectDatabase(target.url);owners=(await database.db.select({id:user.id}).from(user)).map(v=>v.id);const auth=createAuthentication(database.db,{secret:process.env.BETTER_AUTH_SECRET!,baseURL:origin});for(const suffix of ["A","B"]){const response=await fixtureSignIn(()=>auth.handler(new Request(`${origin}/api/auth/sign-in/email`,{method:"POST",headers:{Origin:origin,"Content-Type":"application/json"},body:JSON.stringify({email:process.env[`TEST_USER_${suffix}_EMAIL`],password:process.env[`TEST_USER_${suffix}_PASSWORD`]})})));expect(response.status).toBe(200);cookies[suffix]=response.headers.getSetCookie().map(v=>{const pair=v.split(";")[0],i=pair.indexOf("=");return {name:pair.slice(0,i),value:pair.slice(i+1),url:origin,httpOnly:true,sameSite:"Lax" as const};});}});
test.beforeEach(async({page})=>{await clean();await fetch(`${process.env.CALENDAR_TEST_ORIGIN}/control`,{method:"POST",body:"{}"});await page.context().addCookies(cookies.A);});test.afterAll(async()=>{await clean();await database.pool.end();});
async function mutate(page:Page,path:string,data:object,method="POST"){const r=await page.request.fetch(path,{method,headers:{Origin:origin},data});expect(r.status(),await r.text()).toBe(200);return r.json();}
async function fixture(page:Page,commit=true){const g=(await mutate(page,"/api/goals",{mutationId:randomUUID(),title:"Make meaningful progress",outcome:"A calmer week with protected time"})).goal;const act=(await mutate(page,`/api/goals/${g.id}/actions`,{mutationId:randomUUID(),title:"Build weekly planning UI",estimateMinutes:240,doneWhen:"The planning loop is usable"})).action;const candidate=(await (await page.request.get("/api/weekly-plans/candidates")).json()).candidates[0];let plan:WeeklyPlan=(await mutate(page,"/api/weekly-plans",{mutationId:randomUUID(),weekStartDate:week,provisionalCapacityMinutes:720,reserveMinutes:180})).plan;plan=(await mutate(page,`/api/weekly-plans/${plan.id}`,{mutationId:randomUUID(),expectedVersion:1,provisionalCapacityMinutes:720,reserveMinutes:180,commitments:[{actionId:act.id,budgetMinutes:180,source:candidate.source}]},"PATCH")).plan;if(commit)plan=(await mutate(page,`/api/weekly-plans/${plan.id}/commit`,{mutationId:randomUUID(),expectedVersion:2})).plan;await mutate(page,"/api/focusable-hours",{mutationId:randomUUID(),scheduleId:null,expectedVersion:0,windows:Array.from({length:5},(_,i)=>({weekday:i+1,startMinute:540,endMinute:1020}))},"PUT");return {g,act,plan,url:`/api/weekly-plans/${plan.id}/time-blocks`};}
const read=async(page:Page,url:string):Promise<SchedulingView>=>(await page.request.get(url)).json();
async function apiCreate(page:Page,f:Awaited<ReturnType<typeof fixture>>,date="2028-01-04",startTime="10:00",endTime="11:30"){const input={commitmentId:(await read(page,f.url)).commitments[0].id,date,startTime,endTime},r:PlacementReview=await mutate(page,`${f.url}/preview`,input);const command={...input,mutationId:randomUUID(),expectedPlanVersion:r.planVersion,reviewKey:r.reviewKey,acknowledgeOutsideHours:r.outsideHours,acknowledgeBusy:!!r.busyConflict};return {block:(await mutate(page,f.url,command)).block as TimeBlock,command};}
test("HTTP ownership, no-store, strict input, Origin and anonymous safety; no deletion endpoint",async({page,browser})=>{const f=await fixture(page),{block,command}=await apiCreate(page,f);const foreign=await browser.newContext();await foreign.addCookies(cookies.B);const anon=await browser.newContext();try{for(const ctx of [foreign,anon])for(const [path,method,data] of [[f.url,"GET",undefined],[f.url,"POST",command],[`${f.url}/preview`,"POST",{commitmentId:block.commitmentId,date:"2028-01-05",startTime:"10:00",endTime:"11:00"}],[`/api/time-blocks/${block.id}`,"GET",undefined],[`/api/time-blocks/${block.id}`,"PATCH",{...command,expectedVersion:1}],[`/api/time-blocks/${block.id}/cancel`,"POST",{mutationId:randomUUID(),expectedVersion:1}]] as const){const r=await ctx.request.fetch(path,{method,headers:{Origin:origin},data});expect(r.status()).toBe(ctx===foreign?404:401);expect((await r.json()).error).not.toHaveProperty("current");}const known=(await (await foreign.request.get(`/api/time-blocks/${block.id}`)).json()).error,missing=(await (await foreign.request.get(`/api/time-blocks/${randomUUID()}`)).json()).error;delete known.requestId;delete missing.requestId;expect(known).toEqual(missing);}finally{await foreign.close();await anon.close();}expect((await page.request.get(f.url)).headers()["cache-control"]).toContain("no-store");expect((await page.request.delete(`/api/time-blocks/${block.id}`,{headers:{Origin:origin}})).status()).toBe(405);expect((await page.request.post(f.url,{headers:{Origin:"https://evil.test"},data:command})).status()).toBe(403);expect((await page.request.post(f.url,{headers:{Origin:origin},data:{...command,ownerId:owners[1]}})).status()).toBe(400);});
