import {fixtureSignIn} from "./sign-in-helper";
import {test,expect,type Page,type BrowserContext} from "@playwright/test";
import {randomUUID} from "node:crypto";
import {writeFile,mkdir} from "node:fs/promises";
import {inArray} from "drizzle-orm";
import {connectDatabase} from "../../src/db/connect";
import {weeklyReviewDecision,weeklyReview,dailyReflection,focusSession,timeBlock,commitmentIdentity,weeklyPlan,weeklyCommitment,weeklyPlanAmendment,amendmentCommitment,action,goal,milestone,mutationReceipt,user} from "../../src/db/schema";
import {createAuthentication} from "../../src/server/auth-factory";
import {weeklyFixture} from "../weekly-review-fixture";

import {requireTestDatabaseURL} from "../../scripts/test-database";

const origin="http://127.0.0.1:3101";let database:ReturnType<typeof connectDatabase>,owners:string[];const cookies:Record<string,Parameters<BrowserContext["addCookies"]>[0]>={};
async function clock(value:string){await writeFile(process.env.EXECUTION_TEST_CLOCK_FILE!,value);}
async function clean(){for(const table of [weeklyReviewDecision,weeklyReview,dailyReflection,focusSession,timeBlock,commitmentIdentity,mutationReceipt,amendmentCommitment,weeklyPlanAmendment,weeklyCommitment,weeklyPlan,action,milestone,goal])await database.db.delete(table).where(inArray(table.ownerId,owners));await database.pool.query("UPDATE app_user SET timezone='Europe/London' WHERE id=ANY($1)",[owners]);}
test.beforeAll(async()=>{test.setTimeout(90000);const target=requireTestDatabaseURL();if(target.name==="execution_test")throw new Error("Requires isolated DB");database=connectDatabase(target.url);const rows=await database.db.select().from(user);owners=rows.map(v=>v.id);const auth=createAuthentication(database.db,{secret:process.env.BETTER_AUTH_SECRET!,baseURL:origin});for(const suffix of ["A","B"]){const response=await fixtureSignIn(()=>auth.handler(new Request(`${origin}/api/auth/sign-in/email`,{method:"POST",headers:{Origin:origin,"Content-Type":"application/json"},body:JSON.stringify({email:process.env[`TEST_USER_${suffix}_EMAIL`],password:process.env[`TEST_USER_${suffix}_PASSWORD`]})})));expect(response.status).toBe(200);cookies[suffix]=response.headers.getSetCookie().map(v=>{const pair=v.split(";")[0],i=pair.indexOf("=");return {name:pair.slice(0,i),value:pair.slice(i+1),url:origin,httpOnly:true,sameSite:"Lax" as const};});}});
test.beforeEach(async({page})=>{await clean();await clock("2026-10-12T09:00:00.000Z");await page.context().addCookies(cookies.A);});test.afterAll(async()=>{await clean();await clock(new Date().toISOString());await database.pool.end();});
async function fixture(){const owner=(await database.db.select().from(user)).find(v=>v.email===process.env.TEST_USER_A_EMAIL)!;return weeklyFixture(database.db,{userId:owner.id});}
const read=async(page:Page,week="2026-10-05")=>(await (await page.request.get(`/api/weekly-reviews?week=${week}`)).json());
async function choose(page:Page,f:Awaited<ReturnType<typeof fixture>>){for(const d of f.decisions){const row=page.locator(`[data-weekly-commitment="${d.commitmentId}"]`);await row.getByRole("button",{name:d.kind[0].toUpperCase()+d.kind.slice(1),exact:true}).click();if(d.kind==="carry"){await expect(row.getByLabel("Fresh proposed next-week budget in minutes")).toHaveValue("");await row.getByLabel("Fresh proposed next-week budget in minutes").fill("90");}}await page.getByLabel("Weekly reflection",{exact:true}).fill("Support changed capacity. Carry a smaller review slice; defer tests and archive the dashboard work.");}
async function save(page:Page){await page.getByRole("button",{name:"Save review draft",exact:true}).click();await expect(page.getByRole("status")).toContainText("draft saved");}
async function finish(page:Page){await page.getByRole("button",{name:"Finish weekly review",exact:true}).click();await expect(page.getByRole("button",{name:"Keep draft"})).toBeFocused();await expect(page.getByRole("button",{name:"Confirm weekly finish"})).toBeDisabled();await page.getByLabel("I confirm archiving these Drop Actions.").check();await page.getByRole("button",{name:"Confirm weekly finish"}).click();await expect(page.locator("[data-finalized-weekly-review]")).toBeVisible();}
async function historyBytes(owner:string){const result:Record<string,unknown>={};for(const table of ["goal","milestone","weekly_plan","weekly_commitment","weekly_plan_amendment","amendment_commitment","commitment_identity","time_block","focus_session","daily_reflection"])result[table]=(await database.pool.query(`SELECT row_to_json(t) FROM ${table} t WHERE owner_id=$1 ORDER BY row_to_json(t)::text`,[owner])).rows;return result;}
test('finished week supports reflection and explicit Carry, Defer and Drop; next week preselects only unfinished Carry',async({page})=>{
 const f=await fixture(),before=await historyBytes(f.actor.userId);await page.goto('/review?week=2026-10-05');await expect(page.locator('.weekly-summaries')).toContainText('6h');await expect(page.locator('.weekly-summaries')).toContainText('5h 15m');await expect(page.locator('.week-activity')).not.toHaveAttribute('open','');await choose(page,f);await save(page);const draft=(await read(page)).facts.review;await page.reload();await expect(page.getByLabel('Weekly reflection',{exact:true})).toHaveValue(draft.note);await finish(page);const final=(await read(page)).facts.review;expect(final.status).toBe('finalized');expect(await historyBytes(f.actor.userId)).toEqual(before);await page.getByRole('link',{name:'Plan the following week'}).click();const card=page.getByRole('region',{name:'What matters this week?'});
 const checked=card.locator('input:checked');await expect(checked).toHaveCount(1);await expect(card.locator('.is-chosen')).toContainText('1h 30m');await card.getByRole('button',{name:'Plan my week',exact:true}).click();await expect(card).toHaveCount(0);const next=await (await page.request.get('/api/weekly-plans?week=2026-10-12')).json();expect(next.view.plan.commitments).toHaveLength(1);expect(next.view.plan.commitments[0].budgetMinutes).toBe(90);expect(next.view.plan.commitments[0].id).not.toBe(f.decisions.find(d=>d.kind==='carry')!.commitmentId);expect((await read(page)).facts.review).toEqual(final);
});
test("stale tabs retain attempted note and decisions; explicit latest review precedes resave; finalized race keeps attempted draft",async({page,browser})=>{const f=await fixture();await page.goto("/review?week=2026-10-05");await choose(page,f);await save(page);const context=await browser.newContext(),other=await context.newPage();try{await context.addCookies(cookies.A);await other.goto(`${origin}/review?week=2026-10-05`);await other.getByLabel("Weekly reflection",{exact:true}).fill("My stale attempted weekly note");await page.getByLabel("Weekly reflection",{exact:true}).fill("Newer saved weekly note");await save(page);await other.getByRole("button",{name:"Save review draft"}).click();await expect(other.locator(".daily-error")).toContainText("changed elsewhere");await expect(other.getByLabel("Weekly reflection",{exact:true})).toHaveValue("My stale attempted weekly note");await other.getByRole("button",{name:"Review latest saved review and source context"}).click();await save(other);await finish(other);await page.getByLabel("Weekly reflection",{exact:true}).fill("Attempt after finalization");await page.getByRole("button",{name:"Save review draft"}).click();await expect(page.locator(".daily-error")).toContainText("changed elsewhere");await page.getByRole("button",{name:"Review latest saved review and source context"}).click();await expect(page.locator("[data-finalized-weekly-review]")).toHaveText("My stale attempted weekly note");await page.getByText("Your unsaved attempted review").click();await expect(page.locator(".daily-reflection")).toContainText("Attempt after finalization");}finally{await context.close();}});
test("source becomes terminal after Draft save; finalization is blocked with no partial archives; stale choice removal permits deliberate finish",async({page})=>{const f=await fixture();await page.goto("/review?week=2026-10-05");await choose(page,f);await save(page);await f.actions.completeAction(f.actor,f.sources[0].id,{mutationId:randomUUID(),expectedVersion:1});await page.getByRole("button",{name:"Finish weekly review"}).click();await expect(page.locator(".daily-error")).toContainText("Action or its parent changed");expect((await f.actions.getAction(f.actor,f.sources[2].id)).action.state).toBe("open");await page.getByRole("button",{name:"Review latest saved review and source context"}).click();await page.getByRole("button",{name:"Remove stale decision"}).click();await save(page);await finish(page);await page.getByRole("link",{name:"Plan the following week"}).click();await expect(page.locator(".planning-carries")).toHaveCount(0);});
test("lost Draft/final response replays original exact payload and never repeats Drop",async({page})=>{const f=await fixture();await page.goto("/review?week=2026-10-05");await choose(page,f);const saves:unknown[]=[],finals:unknown[]=[];await page.route("**/api/weekly-reviews",async route=>{saves.push(route.request().postDataJSON());const r=await route.fetch();await route.fulfill(saves.length===1?{status:200,contentType:"application/json",body:"Lost acknowledgement"}:{response:r});});await page.getByRole("button",{name:"Save review draft"}).click();await expect(page.getByLabel("Weekly reflection",{exact:true})).toBeDisabled();await page.getByRole("button",{name:"Retry same command"}).click();await expect(page.getByRole("status")).toContainText("draft saved");expect(saves[1]).toEqual(saves[0]);const r=(await read(page)).facts.review;await page.route(`**/api/weekly-reviews/${r.id}/finalize`,async route=>{finals.push(route.request().postDataJSON());const response=await route.fetch();await route.fulfill(finals.length===1?{status:200,contentType:"application/json",body:"Lost final acknowledgement"}:{response});});await page.getByRole("button",{name:"Finish weekly review"}).click();await page.getByLabel("I confirm archiving these Drop Actions.").check();await page.getByRole("button",{name:"Confirm weekly finish"}).click();await expect(page.getByRole("button",{name:"Keep draft"})).toBeDisabled();await page.getByRole("button",{name:"Retry same command"}).click();await expect(page.locator("[data-finalized-weekly-review]")).toBeVisible();expect(finals[1]).toEqual(finals[0]);expect((await f.actions.getAction(f.actor,f.sources[2].id)).action.version).toBe(2);expect((await read(page)).facts.review.version).toBe(2);});
test('already planned following weeks stay unchanged; terminal Carry is excluded from new planning suggestions',async({page})=>{const f=await fixture(),r=await f.reviews.save(f.actor,f.save());await f.reviews.finalize(f.actor,r.id,{mutationId:randomUUID(),expectedVersion:1,confirmArchive:true});const p=await f.plans.create(f.actor,{mutationId:randomUUID(),weekStartDate:'2026-10-12',provisionalCapacityMinutes:480,reserveMinutes:120}),source=(await f.plans.candidates(f.actor)).find(c=>c.actionId===f.sources[1].id)!;await f.plans.save(f.actor,p.id,{mutationId:randomUUID(),expectedVersion:1,provisionalCapacityMinutes:480,reserveMinutes:120,commitments:[{actionId:source.actionId,budgetMinutes:30,source:source.source}]});await f.plans.commit(f.actor,p.id,{mutationId:randomUUID(),expectedVersion:2});await page.goto('/planning?week=2026-10-12');await expect(page.getByRole('region',{name:'Work for this week'})).toContainText(source.context.action.title);expect((await f.amends.history(f.actor,p.id)).amendments).toHaveLength(0);await f.actions.completeAction(f.actor,f.sources[0].id,{mutationId:randomUUID(),expectedVersion:1});expect((await (await page.request.get('/api/weekly-plans/quick-context?week=2026-10-12')).json()).unfinished).toEqual([]);expect((await read(page)).facts.review.status).toBe('finalized');});
test("ownership, missing/foreign errors, strict payloads, anonymous/Origin/cache and no destructive routes",async({page,browser})=>{const f=await fixture(),r=await f.reviews.save(f.actor,f.save());const context=await browser.newContext();try{await context.addCookies(cookies.B);const bodies=[];for(const id of [r.id,randomUUID()]){const response=await context.request.get(`${origin}/api/weekly-reviews/${id}`);expect(response.status()).toBe(404);const body=await response.json();delete body.error.requestId;bodies.push(body);expect((await context.request.post(`${origin}/api/weekly-reviews/${id}/finalize`,{headers:{Origin:origin},data:{mutationId:randomUUID(),expectedVersion:1,confirmArchive:true}})).status()).toBe(404);expect((await context.request.put(`${origin}/api/weekly-reviews`,{headers:{Origin:origin},data:f.save({reviewId:id,expectedVersion:1})})).status()).toBe(404);}expect(bodies[0]).toEqual(bodies[1]);expect((await (await context.request.get(`${origin}/api/weekly-reviews?week=2026-10-05`)).json()).facts).toBeNull();expect((await (await context.request.get(`${origin}/api/weekly-reviews/carries?week=2026-10-12`)).json()).carries).toEqual([]);}finally{await context.close();}expect((await page.request.put("/api/weekly-reviews",{headers:{Origin:"https://evil.invalid"},data:f.save()})).status()).toBe(403);for(const extra of [{ownerId:f.actor.userId},{note:"x".repeat(4001)},{decisions:[{...f.decisions[0],kind:"carry",proposedBudgetMinutes:0}]}])expect((await page.request.put("/api/weekly-reviews",{headers:{Origin:origin},data:f.save(extra)})).status()).toBe(400);expect((await page.request.get(`/api/weekly-reviews/${r.id}`)).headers()["cache-control"]).toBe("private, no-store");for(const method of ["PATCH","DELETE"])expect((await page.request.fetch(`/api/weekly-reviews/${r.id}`,{method,data:{},headers:{Origin:origin}})).status()).toBe(405);await page.context().clearCookies();expect((await page.request.get("/api/weekly-reviews")).status()).toBe(401);});
test("narrow keyboard review, unsaved navigation guard, cancel/Escape focus and useful unfinished/uncommitted states",async({page})=>{const f=await fixture();await page.setViewportSize({width:390,height:844});await page.goto("/review?week=2026-10-12");await expect(page.getByRole("heading",{name:"This week has not finished yet."})).toBeVisible();await page.goto("/review?week=2026-09-28");await expect(page.getByRole("heading",{name:"No weekly tasks were picked for these dates."})).toBeVisible();await page.goto("/review?week=2026-10-05");await choose(page,f);await expect(page.getByRole("link",{name:"5 Oct 2026",exact:true})).toHaveAttribute("aria-disabled","true");await save(page);await page.getByRole("button",{name:"Finish weekly review"}).click();await expect(page.getByRole("button",{name:"Keep draft"})).toBeFocused();await page.keyboard.press("Escape");await expect(page.getByRole("dialog")).toHaveCount(0);await expect(page.getByRole("button",{name:"Finish weekly review"})).toBeFocused();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await mkdir(".cache/visual",{recursive:true});await page.screenshot({path:".cache/visual/phase-seven-a-narrow.png",fullPage:true});});

test("R4 Weekly review is completable with all evidence collapsed, using explicit Carry budgets and Drop confirmation",async({page})=>{
 const f=await fixture();await page.setViewportSize({width:390,height:844});await page.goto("/review?week=2026-10-05");
 await expect(page.getByRole("region",{name:"Rollover decisions"}).getByText("3 remaining",{exact:true})).toBeVisible();await expect(page.locator(".feedback-details[open]")).toHaveCount(0);
 expect(await page.evaluate(()=>document.querySelector('.feedback-decisions')!.getBoundingClientRect().top<document.querySelector('.feedback-reflection')!.getBoundingClientRect().top&&document.querySelector('.feedback-reflection')!.getBoundingClientRect().top<document.querySelector('.feedback-evidence')!.getBoundingClientRect().top)).toBe(true);
 await choose(page,f);for(const d of f.decisions)await expect(page.locator(`[data-weekly-commitment="${d.commitmentId}"]`).getByRole("button",{name:d.kind[0].toUpperCase()+d.kind.slice(1),exact:true})).toHaveAttribute("aria-pressed","true");
 await expect(page.getByRole("region",{name:"Rollover decisions"}).getByText("0 remaining",{exact:true})).toBeVisible();await save(page);await finish(page);await expect(page.locator(".feedback-details[open]")).toHaveCount(0);await expect(page.getByText("✓ Finalized · read-only",{exact:true})).toBeVisible();await expect(page.getByRole("button",{name:"Carry",exact:true})).toHaveCount(0);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 const next=await page.request.get("/api/weekly-plans?week=2026-10-12");expect((await next.json()).view).toBeNull();
});

test("R4 full plan, resolved work, cancelled schedule, sessions and finalized daily evidence remain accessible",async({page})=>{
 const f=await fixture();await page.goto("/review?week=2026-10-05");await expect(page.getByText("No finalized reflection considered",{exact:true}).first()).not.toBeVisible();
 await page.locator('.week-activity summary').click();const history=page.locator('.week-activity');await expect(history).toContainText('Started the week');await expect(history).not.toContainText('Amendment');
 const row=page.locator(`[data-weekly-commitment="${f.decisions.find(d=>d.kind==='defer')!.commitmentId}"]`);await row.getByText("Details",{exact:true}).click();await expect(row).toContainText("Sessions · 2");await expect(row.getByText("Production incident interrupted the attempt.",{exact:true})).toBeVisible();
 await page.getByText("Other commitment history · 1",{exact:true}).click();await expect(page.locator("[data-weekly-commitment]").filter({hasText:"Investigate production support"})).toContainText("This action is completed");
 const dropped=page.locator(`[data-weekly-commitment="${f.decisions.find(d=>d.kind==='drop')!.commitmentId}"]`);await dropped.getByText("Details",{exact:true}).click();await expect(dropped.getByText(/Cancelled interval · excluded/)).toBeVisible();
 await page.getByText("View daily reflections",{exact:true}).click();await expect(page.getByText("Clear original intent; leave room for interruptions.",{exact:true})).toBeVisible();await expect(page.getByText("Unfinished draft · not finalized evidence",{exact:true})).toBeVisible();
});

test("Review on Sunday shows the current week with useful empty-state navigation and protects unsaved choices",async({page})=>{
 const owner=(await database.db.select().from(user)).find(v=>v.email===process.env.TEST_USER_A_EMAIL)!;
 await weeklyFixture(database.db,{userId:owner.id},"2026-09-28");await clock("2026-10-04T12:00:00Z");
 for(const width of [1280,390]){
  await page.setViewportSize({width,height:844});await page.goto("/review");
  await expect(page.getByRole("heading",{name:"Week of 28 Sept 2026",exact:true})).toBeVisible();
  await expect(page.getByText(/Current week · Weekly review opens 5 Oct 2026/)).toBeVisible();
  await expect(page.getByRole("navigation",{name:"Finished review weeks"})).toHaveCount(0);
  await expect(page.getByRole("link",{name:"Open Daily Review",exact:true})).toHaveAttribute("href","/today");
  await expect(page.getByRole("link",{name:"Pick this week’s tasks",exact:true})).toHaveAttribute("href","/planning?week=2026-09-28");
  await page.getByRole("link",{name:"← Previous week",exact:true}).click();
  await expect(page.getByRole("heading",{name:"Week of 21 Sept 2026",exact:true})).toBeVisible();
  await expect(page.getByRole("heading",{name:"No weekly tasks were picked for these dates.",exact:true})).toBeVisible();
  await page.getByRole("link",{name:"This week",exact:true}).click();
  await page.getByRole("link",{name:"Next week →",exact:true}).click();
  await expect(page.getByRole("heading",{name:"Week of 5 Oct 2026",exact:true})).toBeVisible();
  await page.getByRole("link",{name:"This week",exact:true}).click();await page.reload();
  await expect(page.getByRole("heading",{name:"Week of 28 Sept 2026",exact:true})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await mkdir(".cache/visual",{recursive:true});await page.screenshot({path:`.cache/visual/review-current-week-${width}.png`,fullPage:true});
 }
 await clock("2026-10-04T23:00:00Z");await page.goto("/review");
 await expect(page.getByRole("heading",{name:"Week of 5 Oct 2026",exact:true})).toBeVisible();
 await page.getByRole("link",{name:"← Previous week",exact:true}).click();
 await expect(page.getByLabel("Weekly review summary",{exact:true})).toBeVisible();
 await page.getByLabel("Weekly reflection",{exact:true}).fill("Keep my unsaved reflection while inspecting navigation.");
 for(const name of ["← Previous week","This week","Next week →"]){const link=page.getByRole("link",{name,exact:true});await expect(link).toHaveAttribute("aria-disabled","true");await link.click({force:true});await expect(page.getByLabel("Weekly reflection",{exact:true})).toHaveValue("Keep my unsaved reflection while inspecting navigation.");}
});

test("analytics remain usable in-progress, inspect daily facts, preserve privacy and enable deliberate review only after close",async({page})=>{
 const f=await fixture();await clock("2026-10-11T18:00Z");
 for(const width of [1440,390]){
  await page.setViewportSize({width,height:960});await page.goto("/review?week=2026-10-05");
  const dashboard=page.getByRole("region",{name:"Weekly analytics dashboard"});await expect(dashboard).toBeVisible();
  await expect(page.getByRole("heading",{name:"How your week unfolded",exact:true})).toBeVisible();
  const data=(await read(page)).analytics;expect(data.recordedMilliseconds).toBe(106*60000);expect(data.budgetMinutes).toBe(315);expect(data.sessionCount).toBe(3);
  await expect(dashboard).toContainText("1h 46m");expect(await dashboard.innerText()).not.toContain("Production incident interrupted the attempt.");expect(await dashboard.innerText()).not.toContain("An unfinished daily draft.");
  await expect(page.getByLabel("Weekly reflection",{exact:true})).toHaveCount(0);
  await page.getByRole("button",{name:/Tuesday 6 Oct: scheduled/}).click();await expect(page.getByRole("button",{name:/Tuesday 6 Oct: scheduled/})).toHaveAttribute("aria-pressed","true");
  await expect(page.getByRole("link",{name:"Inspect day →",exact:true})).toHaveAttribute("href","/today?date=2026-10-06");
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await mkdir("docs/screenshots/review-analytics",{recursive:true});await page.screenshot({path:`docs/screenshots/review-analytics/weekly-${width}.png`,fullPage:true});
 }
 await page.getByRole("link",{name:"Inspect day →",exact:true}).click();await expect(page.getByRole("region",{name:"Daily analytics dashboard"})).toBeVisible();

 await page.setViewportSize({width:1440,height:960});await page.screenshot({path:"docs/screenshots/review-analytics/daily.png",fullPage:true,caret:"initial"});
 await clock("2026-10-12T09:00Z");await page.goto("/review?week=2026-10-05");await choose(page,f);await expect(page.getByRole("link",{name:"Inspect day →",exact:true})).toHaveAttribute("aria-disabled","true");await page.getByRole("link",{name:"Inspect day →",exact:true}).click({force:true});await expect(page.getByLabel("Weekly reflection",{exact:true})).toHaveValue("Support changed capacity. Carry a smaller review slice; defer tests and archive the dashboard work.");await save(page);await finish(page);
 await expect(page.getByRole("region",{name:"Weekly analytics dashboard"})).toBeVisible();await expect(page.locator("[data-finalized-weekly-review]")).toBeVisible();
 await page.screenshot({path:"docs/screenshots/review-analytics/finished-week.png",fullPage:true});
});
