import {createServer} from 'node:http';
import {createHash,randomUUID} from 'node:crypto';
import {generateKeyPair,exportJWK,SignJWT} from 'jose';
import type {AddressInfo} from 'node:net';
import {coachingOutput,suggestions} from './coaching-fixture';
import type {CoachingContext} from '../src/modules/coaching/domain';
export async function startChatGPTFixture(clock=()=>new Date().toISOString()){
 const keys=await generateKeyPair('RS256'),jwk=await exportJWK(keys.publicKey);Object.assign(jwk,{kid:'fixture',alg:'RS256',use:'sig'});
 let origin='',mode='useful',clientId='oaiapp_fixture',subject='chatgpt-subject',refreshToken='refresh-fixture-1',refreshCount=0,responseCount=0,exchangeCount=0,lastRequest:Record<string,unknown>|null=null;const codes=new Map<string,{nonce:string;challenge:string;clientId:string;redirect:string}>();
 const server=createServer(async(req,res)=>{try{let raw='';for await(const chunk of req)raw+=chunk;const u=new URL(req.url!,origin),json=(data:unknown,status=200)=>{res.statusCode=status;res.setHeader('Content-Type','application/json');res.end(JSON.stringify(data));};
 if(u.pathname==='/control'){if(req.method==='POST'){const d=JSON.parse(raw);mode=d.mode??mode;clientId=d.clientId??clientId;subject=d.subject??subject;}return json({mode,refreshCount,responseCount,exchangeCount,lastRequest});}
 if(u.pathname==='/.well-known/openid-configuration')return json({issuer:origin,authorization_endpoint:`${origin}/authorize`,token_endpoint:`${origin}/token`,jwks_uri:`${origin}/jwks`,revocation_endpoint:`${origin}/revoke`});
 if(u.pathname==='/jwks')return json({keys:[jwk]});
 if(u.pathname==='/authorize'){const code=randomUUID(),id=u.searchParams.get('client_id')==='dynamic_agent_client'?clientId:u.searchParams.get('client_id')!;codes.set(code,{nonce:u.searchParams.get('nonce')!,challenge:u.searchParams.get('code_challenge')!,clientId:id,redirect:u.searchParams.get('redirect_uri')!});const redirect=new URL(u.searchParams.get('redirect_uri')!);redirect.searchParams.set('code',code);redirect.searchParams.set('state',u.searchParams.get('state')!);redirect.searchParams.set('client_id',id);res.writeHead(302,{Location:redirect.toString()});return res.end();}
 if(u.pathname==='/token'){const body=new URLSearchParams(raw);if(body.get('client_id')==='dynamic_agent_client')return json({error:'invalid_client'},400);const refresh=body.get('grant_type')==='refresh_token';let nonce='refresh-nonce';if(refresh){refreshCount++;if(mode==='refresh_terminal'||body.get('refresh_token')!==refreshToken)return json({error:'invalid_grant'},400);if(mode==='refresh_temporary')return json({error:'temporarily_unavailable'},503);refreshToken=`refresh-fixture-${refreshCount+1}`;}else{exchangeCount++;const c=codes.get(body.get('code')!);codes.delete(body.get('code')!);if(!c||c.clientId!==body.get('client_id')||c.redirect!==body.get('redirect_uri')||c.challenge!==createHash('sha256').update(body.get('code_verifier')??'').digest('base64url'))return json({error:'invalid_grant'},400);nonce=c.nonce;}
 const now=Math.floor(Date.parse(clock())/1000);let claims:Record<string,unknown>={nonce:mode==='wrong_nonce'?'wrong':nonce,email:'same@example.test',name:'Fixture ChatGPT'};if(mode==='missing_nonce')claims={email:'same@example.test'};const token=await new SignJWT(claims).setProtectedHeader({alg:'RS256',kid:'fixture'}).setIssuer(mode==='wrong_issuer'?'https://wrong.test':origin).setAudience(mode==='wrong_audience'?'wrong-client':body.get('client_id')!).setSubject(subject).setExpirationTime(mode==='expired_identity'?now-60:now+3600).sign(keys.privateKey);
 return json({token_type:'Bearer',access_token:'access-fixture-secret',refresh_token:refreshToken,id_token:token,expires_in:mode==='short_expiry'?1:3600,scope:mode==='no_permission'?'openid profile email':'openid profile email offline_access resource.invoke chatgpt.tokens.use.direct'});}
 if(u.pathname==='/revoke')return json({},mode==='revoke_failure'?503:200);
 if(u.pathname==='/v1/models')return json({models:[{slug:'fixture-openai',display_name:'Fixture OpenAI',visibility:'list'},{slug:'fixture-alternate',display_name:'Fixture Alternate',visibility:'list'},{slug:'hidden',display_name:'Hidden',visibility:'hide'}]});
 if(u.pathname==='/v1/responses'){responseCount++;const body=JSON.parse(raw);lastRequest=body;if(mode==='admission_failure')return json({detail:'SECRET_PRIVATE_ADMISSION'},403);const context=JSON.parse(body.input[0].content) as CoachingContext;const out=mode==='malformed'?'bad json':JSON.stringify(mode==='fabricated'?{recommendations:[{...suggestions(context)[0],candidateId:'fabricated'}]}:coachingOutput(context,mode==='empty'));const status=mode==='failed'?'failed':mode==='incomplete'?'incomplete':'completed';const response={id:'response_fixture',object:'response',created_at:nowSeconds(),status,output:[{type:'message',id:'msg_fixture',role:'assistant',status:'completed',content:[{type:'output_text',text:out,annotations:[]}]}],usage:{input_tokens:100,output_tokens:60,input_tokens_details:{cached_tokens:10},output_tokens_details:{reasoning_tokens:0},total_tokens:160},error:status==='failed'?{code:'subscription_sharing_usage_limit_exceeded',message:'SECRET_PRIVATE_FAILURE'}:null};res.setHeader('Content-Type','text/event-stream');res.write(`event: response.created\ndata: ${JSON.stringify({type:'response.created',response:{...response,status:'in_progress'}})}\n\n`);if(mode==='completed_empty'||mode==='done_interrupted')res.write(`event: response.output_item.done\ndata: ${JSON.stringify({type:'response.output_item.done',output_index:0,item:response.output[0]})}\n\n`);if(mode!=='interrupted'&&mode!=='done_interrupted')res.write(`event: response.${status}\ndata: ${JSON.stringify({type:`response.${status}`,response:mode==='completed_empty'?{...response,output:[]}:response})}\n\n`);return res.end();}
 return json({},404);
 }catch{res.statusCode=500;res.end('{}');}});
 function nowSeconds(){return Math.floor(Date.parse(clock())/1000);}
 await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));origin=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;
 return {origin,async authorize(url:string){const r=await fetch(url,{redirect:'manual'});return new URL(r.headers.get('location')!);},async control(data:Record<string,unknown>={}){await fetch(`${origin}/control`,{method:'POST',body:JSON.stringify(data)});return (await fetch(`${origin}/control`)).json();},close:()=>new Promise<void>((r,j)=>server.close(e=>e?j(e):r()))};
}
