import {z} from 'zod';
import {createHash,randomUUID} from 'node:crypto';
import type {Actor} from '../../domain/actor';
import {ApplicationError} from '../../domain/errors';
import {parseCommand} from '../goals/domain';
import {credentialCipher} from '../calendar/encryption';
import {newAttempt,type OAuthTransport} from '../../providers/chatgpt/oauth';
import {ChatGPTFailure,planGranted,startSchema,updateSchema,versionSchema,type Connection,type Credentials,type ChatGPTWorkspace} from './domain';
import type {ChatGPTRepository,ChatGPTStore,StoredConnection} from './repository';
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
const missing=()=>new ApplicationError('NOT_FOUND','This ChatGPT connection is unavailable.');
const publicConnection=(c:StoredConnection):Connection=>{const {ownerId:_owner,encryptedCredentials:_secret,...data}=c;void _owner;void _secret;return {...data,createdAt:c.createdAt.toISOString(),updatedAt:c.updatedAt.toISOString(),catalogAt:c.catalogAt?.toISOString()??null};};
type Attempt={nonce:string;verifier:string;redirectUri:string;connectionId:string|null;expectedClientId:string|null;expectedSubject:string|null;expectedVersion:number|null};
export function chatGPTService(deps:{repository:ChatGPTRepository;cipher:ReturnType<typeof credentialCipher>;oauth:OAuthTransport;host:()=>Promise<string>;redirectUri:string;clock?:()=>string}){
 const clock=deps.clock??(()=>new Date().toISOString()),aad=(owner:string,id:string)=>`chatgpt:${owner}:${id}:credentials`,encode=(c:StoredConnection,v:Credentials)=>deps.cipher.encrypt(JSON.stringify(v),aad(c.ownerId,c.id)),decode=(c:StoredConnection):Credentials=>{try{return JSON.parse(deps.cipher.decrypt(c.encryptedCredentials!,aad(c.ownerId,c.id)));}catch{throw new ChatGPTFailure('authentication');}};
 const requireConnection=async(s:ChatGPTStore,id:string)=>{id=parseCommand(z.uuid(),id);const c=await s.get(id);if(!c)throw missing();return c;};
 const unchanged=(c:StoredConnection,v:number)=>{if(c.version!==v)throw new ApplicationError('CONFLICT','This connection changed. Refresh Settings and try again.');};
 async function access(s:ChatGPTStore,c:StoredConnection){if(c.status!=='connected'||!planGranted(c.scopes))throw new ChatGPTFailure('authentication');let v=decode(c);if(Date.parse(v.expiresAt)>Date.parse(clock())+120_000)return {c,v};
  try{const refreshed=await deps.oauth.refresh(c.clientId,v);v=refreshed.credentials;c={...c,scopes:refreshed.grantedScopes??c.scopes,encryptedCredentials:encode(c,v),updatedAt:new Date(clock()),version:c.version+1};await s.save(c);if(!planGranted(c.scopes))throw new ChatGPTFailure('authentication');return {c,v};}
  catch(e){if(e instanceof ChatGPTFailure&&e.kind==='terminal_refresh'){await s.save({...c,status:'needs_sign_in',encryptedCredentials:null,updatedAt:new Date(clock()),version:c.version+1});}throw e;}
 }
 return {
 async workspace(actor:Actor):Promise<ChatGPTWorkspace>{return {configured:true,connections:await deps.repository.read(actor.userId,async s=>(await s.list()).map(publicConnection))};},
 async start(actor:Actor,input:unknown){const {connectionId}=parseCommand(startSchema,input);return deps.repository.locked(actor.userId,async s=>{const c=connectionId?await requireConnection(s,connectionId):null,attempt=newAttempt(),host=await deps.host();const data:Attempt={nonce:attempt.nonce,verifier:attempt.verifier,redirectUri:deps.redirectUri,connectionId,expectedClientId:c?.clientId??null,expectedSubject:c?.subject??null,expectedVersion:c?.version??null};const url=await deps.oauth.authorize({clientId:c?.clientId??null,hostId:host,redirectUri:deps.redirectUri,...attempt,enablePlan:!!c&&!planGranted(c.scopes)});await s.saveAttempt({ownerId:actor.userId,stateHash:hash(attempt.state),encryptedAttempt:deps.cipher.encrypt(JSON.stringify(data),`chatgpt:${actor.userId}:attempt`),expiresAt:new Date(Date.parse(clock())+10*60_000),consumedAt:null});return {url};});},
 async callback(actor:Actor,input:{state:string|null;code:string|null;clientId:string|null;denied:boolean}){return deps.repository.locked(actor.userId,async s=>{const f=await s.attempt();if(!input.state||!f||f.stateHash!==hash(input.state)||f.consumedAt)return 'failed';const expired=f.expiresAt.getTime()<=Date.parse(clock());const data:Attempt=JSON.parse(deps.cipher.decrypt(f.encryptedAttempt!,`chatgpt:${actor.userId}:attempt`));await s.saveAttempt({...f,consumedAt:new Date(clock()),encryptedAttempt:null});if(expired)return 'failed';if(input.denied)return 'cancelled';if(!input.code)return 'failed';if(data.expectedClientId&&input.clientId&&input.clientId!==data.expectedClientId)return 'failed';const clientId=data.expectedClientId??input.clientId;if(!clientId||clientId==='dynamic_agent_client'||clientId.length>200||!/^[-a-zA-Z0-9_.]+$/.test(clientId))return 'failed';
  let c=data.connectionId?await requireConnection(s,data.connectionId):(await s.list()).find(c=>c.clientId===clientId)??null;
  if(data.connectionId)unchanged(c!,data.expectedVersion!);
  const now=new Date(clock());if(!c){c={id:randomUUID(),ownerId:actor.userId,clientId,subject:null,email:null,name:null,scopes:[],encryptedCredentials:null,status:'pending',active:false,useForCoaching:false,selectedModel:null,models:[],catalogAt:null,version:1,createdAt:now,updatedAt:now,revocationConfirmed:null};await s.save(c);} // Save issued ID before exchanging an expiring code.
  try{const t=await deps.oauth.exchange(clientId,input.code,data.verifier,data.redirectUri),identity=await deps.oauth.identity(t.credentials.idToken,clientId,data.nonce);if((data.expectedSubject&&identity.subject!==data.expectedSubject)||(c.subject&&identity.subject!==c.subject))return 'failed';const next={...c,...identity,scopes:t.grantedScopes??[],encryptedCredentials:encode(c,t.credentials),status:'connected' as const,active:true,models:[],catalogAt:null,version:c.version+1,updatedAt:now,revocationConfirmed:null};await s.save(next,true);return planGranted(next.scopes)?'success':'permission_disabled';}catch{return 'failed';}
 });},
 async refreshModels(actor:Actor,id:string){return deps.repository.locked(actor.userId,async s=>{let c=await requireConnection(s,id);const a=await access(s,c);c=a.c;const models=await deps.oauth.models(a.v.accessToken);c={...c,models,catalogAt:new Date(clock()),updatedAt:new Date(clock()),version:c.version+1};await s.save(c);return publicConnection(c);});},
 async update(actor:Actor,id:string,input:unknown){const command=parseCommand(updateSchema,input);return deps.repository.locked(actor.userId,async s=>{const c=await requireConnection(s,id);unchanged(c,command.expectedVersion);if(!c.active||c.status!=='connected')throw new ApplicationError('CONFLICT','Reconnect this ChatGPT account first.');const selected=command.selectedModel??c.selectedModel;if(command.selectedModel&&!c.models.some(m=>m.slug===command.selectedModel))throw new ApplicationError('VALIDATION','Choose a model from the current account catalog.');if(command.useForCoaching&&(!planGranted(c.scopes)||!selected||!c.models.some(m=>m.slug===selected)))throw new ApplicationError('CONFLICT','Enable ChatGPT plan usage and select an available model first.');const next={...c,selectedModel:selected,useForCoaching:command.useForCoaching??c.useForCoaching,updatedAt:new Date(clock()),version:c.version+1};await s.save(next);return publicConnection(next);});},
 async disconnect(actor:Actor,id:string,input:unknown){const {expectedVersion}=parseCommand(versionSchema,input);return deps.repository.locked(actor.userId,async s=>{const c=await requireConnection(s,id);unchanged(c,expectedVersion);if(c.status==='disconnected')return publicConnection(c);const v=c.encryptedCredentials?decode(c):null;
  // Disable durably before attempting remote revocation. A crash cannot leave
  // a disconnected UI using tokens, and refresh shares this cross-process lock.
  let next={...c,status:'disconnected' as const,encryptedCredentials:null,useForCoaching:false,models:[],catalogAt:null,updatedAt:new Date(clock()),version:c.version+1,revocationConfirmed:false};await s.save(next);await s.cancelAttempt();const confirmed=await deps.oauth.revoke(c.clientId,v?.refreshToken??null);next={...next,revocationConfirmed:confirmed};await s.save(next);return publicConnection(next);});},
 async credential(actor:Actor,id:string,model:string){return deps.repository.locked(actor.userId,async s=>{const c=await requireConnection(s,id);if(!c.active||!c.useForCoaching||c.selectedModel!==model||!c.models.some(m=>m.slug===model))throw new ChatGPTFailure('authentication');return (await access(s,c)).v.accessToken;});}
 };
}
