import {createHash,randomBytes} from 'node:crypto';
import {createRemoteJWKSet,jwtVerify,customFetch} from 'jose';
import {z} from 'zod';
import {ChatGPTFailure,resource,scopes,type Credentials,type Identity,type Model} from '../../modules/chatgpt/domain';
const tokenSchema=z.object({access_token:z.string().min(1),refresh_token:z.string().min(1).optional(),id_token:z.string().min(1).optional(),token_type:z.string(),expires_in:z.number().positive().max(86400*30),scope:z.string().optional()});
export type OAuthTransport=ReturnType<typeof chatGPTOAuth>;
export function newAttempt(){const state=randomBytes(32).toString('base64url'),nonce=randomBytes(32).toString('base64url'),verifier=randomBytes(32).toString('base64url');return {state,nonce,verifier,challenge:createHash('sha256').update(verifier).digest('base64url')};}
export function chatGPTOAuth(options:{testOrigin?:string;fetch?:typeof fetch;clock?:()=>string}={}){
 const http=options.fetch??fetch,auth=options.testOrigin??'https://auth.openai.com',api=options.testOrigin??'https://api.openai.com',clock=options.clock??(()=>new Date().toISOString());
 let discoveryPromise:Promise<{issuer:string;authorization_endpoint:string;token_endpoint:string;jwks_uri:string;revocation_endpoint:string}>|undefined;
 async function response(url:string,init?:RequestInit){let r:Response;try{r=await http(url,{...init,redirect:'error',cache:'no-store',signal:init?.signal??AbortSignal.timeout(15_000)});}catch{throw new ChatGPTFailure('temporary');}return r;}
 async function metadata(){return discoveryPromise??= (async()=>{const r=await response(`${auth}/.well-known/openid-configuration`);if(!r.ok)throw new ChatGPTFailure('temporary');const d=z.object({issuer:z.string(),authorization_endpoint:z.string().url(),token_endpoint:z.string().url(),jwks_uri:z.string().url(),revocation_endpoint:z.string().url()}).parse(await r.json());if(d.issuer!==auth||[d.authorization_endpoint,d.token_endpoint,d.jwks_uri,d.revocation_endpoint].some(v=>new URL(v).origin!==auth))throw new ChatGPTFailure('invalid_identity');return d;})().catch(e=>{discoveryPromise=undefined;throw e;});}
 async function tokens(body:URLSearchParams,prior?:Credentials){const m=await metadata(),r=await response(m.token_endpoint,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body});if(!r.ok){let code:string|undefined;try{code=(await r.json()).error;}catch{}if(body.get('grant_type')==='refresh_token'&&['invalid_grant','invalid_refresh_token','token_expired','refresh_token_expired','refresh_token_invalidated','refresh_token_reused'].includes(code??''))throw new ChatGPTFailure('terminal_refresh');throw new ChatGPTFailure(r.status===429?'rate_limit':r.status>=500?'temporary':'authentication');}let t:z.infer<typeof tokenSchema>;try{t=tokenSchema.parse(await r.json());if(t.token_type.toLowerCase()!=='bearer')throw new Error();}catch{throw new ChatGPTFailure('invalid_response');}return {credentials:{accessToken:t.access_token,refreshToken:t.refresh_token??prior?.refreshToken??null,idToken:t.id_token??prior?.idToken??null,expiresAt:new Date(Date.parse(clock())+t.expires_in*1000).toISOString()},grantedScopes:t.scope?.split(/\s+/).filter(Boolean)};}
 return {
  async authorize(input:{clientId:string|null;hostId:string;redirectUri:string;state:string;nonce:string;challenge:string;idTokenHint?:string|null;enablePlan?:boolean}){const m=await metadata(),url=new URL(m.authorization_endpoint);for(const [k,v] of Object.entries({client_id:input.clientId??'dynamic_agent_client',ext_agent_host_id:input.hostId,response_type:'code',redirect_uri:input.redirectUri,scope:scopes.join(' '),resource,state:input.state,nonce:input.nonce,code_challenge_method:'S256',code_challenge:input.challenge}))url.searchParams.set(k,v);if(!input.clientId)url.searchParams.set('agent_name_hint','One Better');if(input.idTokenHint)url.searchParams.set('id_token_hint',input.idTokenHint);if(input.enablePlan)url.searchParams.set('prompt','consent');return url.toString();},
  exchange:(clientId:string,code:string,verifier:string,redirectUri:string)=>tokens(new URLSearchParams({grant_type:'authorization_code',client_id:clientId,code,code_verifier:verifier,redirect_uri:redirectUri,resource})),
  refresh:(clientId:string,prior:Credentials)=>{if(!prior.refreshToken)throw new ChatGPTFailure('terminal_refresh');return tokens(new URLSearchParams({grant_type:'refresh_token',client_id:clientId,refresh_token:prior.refreshToken,resource}),prior);},
  async identity(token:string|null,clientId:string,nonce:string):Promise<Identity>{try{if(!token)throw new Error();const m=await metadata(),jwks=createRemoteJWKSet(new URL(m.jwks_uri),{[customFetch]:http,timeoutDuration:15_000});const {payload}=await jwtVerify(token,jwks,{issuer:m.issuer,audience:clientId,currentDate:new Date(clock()),requiredClaims:['exp','sub','nonce'],algorithms:['RS256','ES256']});if(payload.nonce!==nonce||!payload.sub)throw new Error();return {subject:payload.sub,email:typeof payload.email==='string'?payload.email:null,name:typeof payload.name==='string'?payload.name:null};}catch{throw new ChatGPTFailure('invalid_identity');}},
  async models(accessToken:string):Promise<Model[]>{const r=await response(`${api}/v1/models`,{headers:{Authorization:`Bearer ${accessToken}`}});if(!r.ok)throw new ChatGPTFailure(r.status===401||r.status===403?'authentication':r.status===429?'rate_limit':'temporary');try{const d=z.object({models:z.array(z.object({slug:z.string().min(1).max(160),display_name:z.string().min(1).max(160),visibility:z.string()})).max(300)}).parse(await r.json());return d.models.filter(m=>m.visibility==='list').map(m=>({slug:m.slug,displayName:m.display_name}));}catch{throw new ChatGPTFailure('invalid_response');}},
  async revoke(clientId:string,refreshToken:string|null){if(!refreshToken)return false;try{const m=await metadata();for(let attempt=0;attempt<2;attempt++){const r=await response(m.revocation_endpoint,{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({token:refreshToken,token_type_hint:'refresh_token',client_id:clientId})});if(r.status===200)return true;if(r.status<500)return false;if(attempt===0)await new Promise(r=>setTimeout(r,250));}return false;}catch{return false;}}
 };
}
