"use client";
import { useState } from "react";
import type { CarryIntent } from "@/modules/weekly-reviews/domain";
import { Context, duration } from "./planning-presentation";
export function CarryForwardPanel({intents,planState,included,locked,onAdd}:{intents:CarryIntent[];planState:"draft"|"committed"|null;included:string[];locked:boolean;onAdd:(intent:CarryIntent,budget:number)=>void}) {
  const [budgets,setBudgets]=useState<Record<string,string>>({});
  if(!intents.length)return null;
  return <section className="planning-carries" aria-label="Carried forward from last week's review"><h2>Carried forward from last week&apos;s review</h2><p className="small-note">Saved intent, not an automatic commitment. Choose a budget and add deliberately.</p>{intents.map(c=>{const budget=budgets[c.commitmentId]??String(c.proposedBudgetMinutes),valid=/^\d+$/.test(budget)&&Number(budget)>0&&Number(budget)<=10080,already=included.includes(c.actionId);return <article key={c.commitmentId} data-carry-intent={c.commitmentId} className="commitment-card"><Context value={c.context}/><p>Last week&apos;s final budget: {duration(c.priorBudgetMinutes)} · Proposed next-week budget: {duration(c.proposedBudgetMinutes)}</p>{already?<p>Already included in this week&apos;s plan.</p>:!c.eligible?<p>This Action changed after the review and is no longer available for planning.</p>:planState==="committed"?<p>Next week&apos;s plan is already committed. Review this carry-forward item in Weekly Planning and amend manually if appropriate.</p>:!planState?<p>Create this week&apos;s Draft first, then add this item explicitly.</p>:<><label htmlFor={`apply-carry-${c.commitmentId}`}>Chosen budget in minutes</label><input id={`apply-carry-${c.commitmentId}`} type="number" min="1" max="10080" value={budget} disabled={locked} onChange={e=>setBudgets({...budgets,[c.commitmentId]:e.target.value})}/><button className="quiet-button" disabled={locked||!valid} onClick={()=>onAdd(c,Number(budget))}>Add to this week&apos;s plan</button>{locked&&<p className="small-note">Save or discard any unsaved planning choices before adding this carry item.</p>}</>}</article>;})}</section>;
}
