'use client';
import {useEffect,useRef,useState} from 'react';
import {planGranted,type ChatGPTWorkspace,type Connection} from '@/modules/chatgpt/domain';
import {request,errorInfo} from './mutation-client';
const usageURL='https://chatgpt.com/settings/usage';
function Disconnect({cancel,confirm}:{cancel:()=>void;confirm:()=>void}){const dialog=useRef<HTMLDialogElement>(null),button=useRef<HTMLButtonElement>(null);useEffect(()=>{dialog.current?.showModal();button.current?.focus();},[]);return <dialog className="goal-dialog" ref={dialog} aria-labelledby="chatgpt-disconnect-title" onCancel={cancel}><h2 id="chatgpt-disconnect-title">Disconnect ChatGPT?</h2><p>This stops using this connection and removes its protected credentials. Your One Better account and planning data stay saved.</p><div className="dialog-actions"><button className="quiet-button" ref={button} onClick={cancel}>Keep connected</button><button className="primary-button" onClick={confirm}>Disconnect ChatGPT</button></div></dialog>;}
export function ChatGPTSettings({initial,callback}:{initial:ChatGPTWorkspace;callback?:string}){
 const [state,setState]=useState(initial),[busy,setBusy]=useState(initial.connections.some(c=>c.active&&c.status==='connected'&&planGranted(c.scopes))),[error,setError]=useState(''),[notice,setNotice]=useState(''),[disconnect,setDisconnect]=useState<Connection|null>(null);const automaticCatalog=useRef<{id:string;promise:Promise<{connection:Connection}>}|null>(null);const running=useRef(false),returnFocus=useRef<HTMLButtonElement|null>(null);
 const active=state.connections.find(c=>c.active);
 function apply(c:Connection){setState(s=>({...s,connections:s.connections.map(v=>v.id===c.id?c:v)}));}
 async function reload(){setState(await request<ChatGPTWorkspace>('/api/chatgpt'));}
 async function action(work:()=>Promise<void>){if(running.current)return;running.current=true;setBusy(true);setError('');try{await work();}catch(e){setError(errorInfo(e).message);try{await reload();}catch{}}finally{running.current=false;setBusy(false);}}
 async function catalog(c:Connection){const r=await request<{connection:Connection}>(`/api/chatgpt/${c.id}/models`,{method:'POST'});apply(r.connection);}
 useEffect(()=>{if(active?.status!=='connected'||!planGranted(active.scopes))return;let mounted=true;running.current=true;
 // Reuse the in-flight read when development Strict Mode mounts the effect twice.
 // Two catalog writes could otherwise invalidate the first visible version.
 if(automaticCatalog.current?.id!==active.id)automaticCatalog.current={id:active.id,promise:request<{connection:Connection}>(`/api/chatgpt/${active.id}/models`,{method:'POST'})};
 automaticCatalog.current.promise.then(r=>{if(mounted)apply(r.connection);}).catch(e=>{if(mounted){setError(errorInfo(e).message);void reload().catch(()=>{});}}).finally(()=>{if(mounted){running.current=false;setBusy(false);}});
 return ()=>{mounted=false;running.current=false;};
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[active?.id,active?.status]);
 async function connect(c:Connection|null){await action(async()=>{const r=await request<{url:string}>('/api/chatgpt/connect',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({connectionId:c?.id??null})});window.location.assign(r.url);});}
 async function change(c:Connection,fields:{selectedModel?:string;useForCoaching?:boolean}){await action(async()=>{const r=await request<{connection:Connection}>(`/api/chatgpt/${c.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedVersion:c.version,...fields})});apply(r.connection);setNotice(fields.selectedModel?'ChatGPT model saved.':fields.useForCoaching?'Coaching now uses your ChatGPT plan.':'Coaching returned to the server-configured provider.');});}
 return <section className="integration-settings" aria-labelledby="chatgpt-heading"><article className="integration-card"><div className="settings-integration-heading"><span className="settings-provider-mark" aria-hidden="true">◉</span><div><h3 id="chatgpt-heading">ChatGPT</h3><p>Use your eligible ChatGPT plan for optional coaching.</p></div><span className={`settings-connection-state ${active?.status==='connected'?'is-connected':''}`}>{active?.status==='connected'?'Connected':active?.status==='needs_sign_in'?'Sign in again':'Not connected'}</span></div>
 <p>Your ChatGPT connection authorizes AI usage. Your One Better login stays separate.</p>
 {callback==='success'&&<p role="status">ChatGPT connected. Select a model, then choose whether to use it for coaching.</p>}{callback==='permission_disabled'&&<p role="status">Connected to ChatGPT, but plan usage is not enabled.</p>}{callback==='cancelled'&&<p role="status">ChatGPT authorization was cancelled.</p>}{callback==='failed'&&<p role="alert">ChatGPT authorization could not be completed. Try signing in again.</p>}
 {!state.configured&&<p>ChatGPT connections need the local 127.0.0.1 app and server credential encryption configured.</p>}
 {state.connections.map(c=><div className="chatgpt-registration" key={c.id}><h4>{c.name??'ChatGPT account'} · Connection {c.id.slice(-6)} {c.active?'· active':''}</h4>{c.email&&<p>{c.email}</p>}
 <p>{c.status==='connected'?(planGranted(c.scopes)?c.active&&c.useForCoaching?'Using ChatGPT plan for coaching.':'ChatGPT plan usage is enabled.':'Connected to ChatGPT, but plan usage is not enabled.'):c.status==='needs_sign_in'?'This connection needs sign-in again.':c.status==='pending'?'Sign-in is incomplete. The issued registration is saved for retry.':'Disconnected locally.'}</p>
 {c.status==='connected'&&c.active&&planGranted(c.scopes)&&<><label htmlFor={`chatgpt-model-${c.id}`}>Coaching model</label><select id={`chatgpt-model-${c.id}`} value={c.selectedModel??''} disabled={busy||!c.models.length} onChange={e=>void change(c,{selectedModel:e.target.value})}><option value="" disabled>Select an available model</option>{c.models.map(m=><option key={m.slug} value={m.slug}>{m.displayName}</option>)}</select>{c.selectedModel&&!c.models.some(m=>m.slug===c.selectedModel)&&<p>The saved model is unavailable in this catalog. Select an available model; no substitute is used.</p>}<div className="settings-actions"><button className="quiet-button" disabled={busy} onClick={()=>void action(()=>catalog(c))}>Refresh models</button><button className="primary-button" disabled={busy||!c.selectedModel||!c.models.some(m=>m.slug===c.selectedModel)} onClick={()=>void change(c,{useForCoaching:!c.useForCoaching})}>{c.useForCoaching?'Use configured provider':'Use ChatGPT for coaching'}</button></div></>}
 <div className="settings-actions"><button className="quiet-button" disabled={busy} onClick={()=>void connect(c)}>{c.status==='connected'&&!planGranted(c.scopes)?'Enable plan usage':'Reconnect'}</button>{c.status!=='disconnected'&&<button className="quiet-button" disabled={busy} onClick={e=>{returnFocus.current=e.currentTarget;setDisconnect(c);}}>Disconnect</button>}<a href={usageURL} target="_blank" rel="noreferrer">Manage ChatGPT usage ↗</a></div>{c.revocationConfirmed===false&&c.status==='disconnected'&&<p>Credentials removed locally. Remote revocation could not be confirmed; disconnect the app in ChatGPT Settings if needed.</p>}</div>)}
 <div className="settings-actions"><button className="primary-button" disabled={busy||!state.configured} onClick={()=>void connect(null)}>Continue with ChatGPT</button>{state.connections.length>0&&<span>Connect another account or workspace.</span>}</div>
 <p className="settings-note">Requests use your ChatGPT plan allowance or credits. Review usage and limits in ChatGPT Settings. Opening this page does not generate coaching.</p>
 {notice&&<p role="status">{notice}</p>}{error&&<p role="alert">{error} <button className="quiet-button" disabled={busy} onClick={()=>void action(reload)}>Reload connection</button></p>}
 </article>{disconnect&&<Disconnect cancel={()=>{setDisconnect(null);returnFocus.current?.focus();}} confirm={()=>{const c=disconnect;setDisconnect(null);void action(async()=>{const r=await request<{connection:Connection}>(`/api/chatgpt/${c.id}/disconnect`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expectedVersion:c.version})});apply(r.connection);setNotice(r.connection.revocationConfirmed?'ChatGPT disconnected and remote revocation confirmed.':'ChatGPT disconnected locally. Remote revocation could not be confirmed.');returnFocus.current?.focus();});}}/>}</section>;
}
