'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import Link from 'next/link';
import type {Goal} from '@/modules/goals/domain';
import {cycleFields,withinCycle,type FocusCycle,type CycleWorkspace,type CycleTransition} from '@/modules/focus-cycles/domain';
import {request,errorInfo,type CommandError} from './mutation-client';
const label=(d:string)=>new Intl.DateTimeFormat('en-GB',{timeZone:'UTC',day:'numeric',month:'short',year:'numeric'}).format(new Date(`${d}T12:00Z`));
type Editor={kind:'create'|'edit'|CycleTransition;cycle?:FocusCycle};
export function FocusCyclesPanel({workspace,onChanged}:{workspace:CycleWorkspace;onChanged:()=>Promise<void>}){
 const [editor,setEditor]=useState<Editor|null>(null),[notice,setNotice]=useState('');const trigger=useRef<HTMLElement|null>(null);
 const active=workspace.cycles.find(c=>c.status==='active'),drafts=workspace.cycles.filter(c=>c.status==='draft'),past=workspace.cycles.filter(c=>c.status==='finished'||c.status==='archived');
 const open=(value:Editor,target:HTMLElement)=>{trigger.current=target;setEditor(value);setNotice('');};
 const close=()=>{setEditor(null);setTimeout(()=>trigger.current?.isConnected&&trigger.current.focus(),0);};
 const controls=(c:FocusCycle)=><div className="cycle-controls">{['draft','active'].includes(c.status)&&<button className="quiet-button" onClick={e=>open({kind:'edit',cycle:c},e.currentTarget)}>Edit cycle</button>}{c.status==='draft'&&<button className="primary-button" disabled={!!active||!withinCycle(c,workspace.today)||!c.goals.length} onClick={e=>open({kind:'activate',cycle:c},e.currentTarget)}>Activate cycle</button>}{c.status==='active'&&<button className="quiet-button" onClick={e=>open({kind:'finish',cycle:c},e.currentTarget)}>Finish cycle</button>}{c.status!=='archived'&&<button className="text-button" onClick={e=>open({kind:'archive',cycle:c},e.currentTarget)}>Archive cycle</button>}</div>;
 const body=(c:FocusCycle)=><><div className="cycle-title-row"><h3>{c.title}</h3><span className="reference-badge">{c.status}</span></div><p className="cycle-dates">{label(c.startDate)} — {label(c.endDate)}</p>{c.intent&&<p className="focus-note">{c.intent}</p>}<p className="small-note">{['finished','archived'].includes(c.status)?`${c.goals.length} Goals retained at finish/archive`:`${c.goals.filter(g=>!g.archivedAt).length} selected active Goals`}{c.goals.some(g=>g.archivedAt)&&' · Archived Goals remain context until removed.'}</p><ul className="cycle-goal-list">{c.goals.map(g=><li key={g.goalId}><Link href={`/goals/${g.goalId}`}><strong>{g.title}</strong></Link><p>{g.outcome}</p>{g.archivedAt&&<span className="small-note">Archived Goal · not available for new work</span>}</li>)}</ul>{controls(c)}</>;
 return <section className="focus-cycles-section" aria-label="Focus Cycles"><div className="cycle-section-heading"><div><p className="eyebrow">A horizon for what matters</p><h2>Current focus</h2></div><button className="quiet-button" onClick={e=>open({kind:'create'},e.currentTarget)}>Create Focus Cycle</button></div>
  {notice&&<p role="status" className="plan-notice">{notice}</p>}
  {active?<article className={`focus-cycle-card ${workspace.current?'is-current':'is-ended'}`} data-focus-cycle={active.id}>{!workspace.current&&<p className="cycle-ended">This horizon has ended. Finish or archive it to make room for another cycle. Your Goals stay active.</p>}{body(active)}</article>:<div className="cycle-empty"><h3>Choose what matters for the next few weeks.</h3><p>A Focus Cycle brings a few Goals into view. Your existing Goals and weekly work stay available.</p></div>}
  {drafts.length>0&&<details className="cycle-history"><summary>Draft cycles · {drafts.length}</summary>{drafts.map(c=><article className="focus-cycle-card" key={c.id}>{body(c)}{!withinCycle(c,workspace.today)&&<p className="small-note">Activate when today is within the cycle dates.</p>}{active&&<p className="small-note">Finish your Active cycle before activating another.</p>}</article>)}</details>}
  {past.length>0&&<details className="cycle-history"><summary>Past cycles · {past.length}</summary>{past.map(c=><article className="focus-cycle-card" key={c.id}>{body(c)}<p className="small-note">Read-only horizon and Goal context retained when finished or archived. Goal links open their current workspace.</p></article>)}</details>}
  {editor&&<CycleDialog editor={editor} today={workspace.today} onClose={close} onSaved={async()=>{await onChanged();close();setNotice('Focus Cycle saved. Your Goals, commitments and calendar have not changed.');}}/>}
 </section>;
}
function CycleDialog({editor,today,onClose,onSaved}:{editor:Editor;today:string;onClose:()=>void;onSaved:()=>Promise<void>}){
 const [base,setBase]=useState(editor.cycle),[title,setTitle]=useState(base?.title??''),[intent,setIntent]=useState(base?.intent??''),[start,setStart]=useState(base?.startDate??today),[end,setEnd]=useState(base?.endDate??today),[ids,setIds]=useState(base?.goals.map(g=>g.goalId)??[]),[goals,setGoals]=useState<Goal[]|null>(null),[error,setError]=useState<CommandError<FocusCycle>|null>(null),[busy,setBusy]=useState(false),[unconfirmed,setUnconfirmed]=useState(false);
 const dialog=useRef<HTMLDialogElement>(null),flight=useRef(false),pending=useRef<{url:string;method:'POST'|'PATCH';body:object}|null>(null);
 const edit=editor.kind==='edit'||editor.kind==='create',uncertain=unconfirmed,locked=busy||uncertain,conflict=error?.code==='CONFLICT';
 useEffect(()=>{dialog.current?.showModal();dialog.current?.querySelector<HTMLElement>('[data-cycle-focus]')?.focus();if(edit)void request<{goals:Goal[]}>('/api/goals?status=active').then(v=>setGoals(v.goals)).catch(e=>setError(errorInfo(e)));},[edit]);
 useEffect(()=>{if(!pending.current)return;const guard=(e:BeforeUnloadEvent)=>e.preventDefault();window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard);},[error]);
 async function review(){setBusy(true);try{const [v,g]=await Promise.all([request<CycleWorkspace>('/api/focus-cycles'),request<{goals:Goal[]}>('/api/goals?status=active')]);const c=v.cycles.find(c=>c.id===base?.id);if(base&&!c)throw new Error('Cycle unavailable');setBase(c);setGoals(g.goals);pending.current=null;setUnconfirmed(false);setError(c&&['finished','archived'].includes(c.status)&&edit?{code:'CONFLICT',kind:'CYCLE_TERMINAL',message:'The cycle is now read-only. Your attempted fields are retained.'}:null);}catch(e){setError({...errorInfo(e),code:'CONFLICT',message:'Latest context could not be loaded. Your attempted fields are retained.'});}finally{setBusy(false);}}
 async function submit(e:FormEvent){e.preventDefault();if(flight.current||conflict)return;if(!pending.current){let fields:object={};if(edit){const valid=cycleFields.safeParse({title,intent:intent||null,startDate:start,endDate:end,goals:ids.map(id=>({goalId:id,goalVersion:goals?.find(g=>g.id===id)?.version??base?.goals.find(g=>g.goalId===id)?.goalVersion??0}))});if(!valid.success){setError({code:'VALIDATION',message:valid.error.issues.map(i=>i.message).join(' ')});return;}fields=valid.data;}
 pending.current={url:editor.kind==='create'?'/api/focus-cycles':`/api/focus-cycles/${base!.id}${edit?'':`/${editor.kind}`}`,method:editor.kind==='edit'?'PATCH':'POST',body:{mutationId:crypto.randomUUID(),...fields,...(base?{expectedVersion:base.version}:{})}};}
 flight.current=true;setBusy(true);try{const c=pending.current;await request(c.url,{method:c.method,headers:{'Content-Type':'application/json'},body:JSON.stringify(c.body)});await onSaved();}catch(e){const info=errorInfo<FocusCycle>(e);setError(info);const unknown=['UNCERTAIN','DATABASE_UNAVAILABLE','INTERNAL'].includes(info.code);setUnconfirmed(unknown);if(!unknown)pending.current=null;}finally{flight.current=false;setBusy(false);}}
 const heading=edit?(editor.kind==='create'?'Create Focus Cycle':'Edit Focus Cycle'):`${editor.kind==='activate'?'Activate':editor.kind==='finish'?'Finish':'Archive'} Focus Cycle?`;
 const available=[...(goals??[]),...(base?.goals.filter(g=>!goals?.some(v=>v.id===g.goalId)).map(g=>({id:g.goalId,title:g.title,outcome:g.outcome,version:g.goalVersion,archivedAt:g.archivedAt??'unavailable',createdAt:'',updatedAt:''}))??[])];
 return <dialog ref={dialog} className="goal-dialog cycle-dialog" aria-labelledby="cycle-dialog-title" onCancel={e=>{e.preventDefault();if(!locked)onClose();}}><form onSubmit={submit} noValidate><p className="eyebrow">Choose a small horizon</p><h2 id="cycle-dialog-title">{heading}</h2>{edit?<><label htmlFor="cycle-title">Cycle title</label><input id="cycle-title" data-cycle-focus value={title} disabled={locked} onChange={e=>setTitle(e.target.value)}/><label htmlFor="cycle-intent">Intent (optional)</label><textarea id="cycle-intent" rows={3} value={intent} disabled={locked} onChange={e=>setIntent(e.target.value)}/><div className="cycle-date-fields"><div><label htmlFor="cycle-start">Start date</label><input id="cycle-start" type="date" min="2000-01-01" max="9999-12-31" value={start} disabled={locked} onChange={e=>setStart(e.target.value)}/></div><div><label htmlFor="cycle-end">End date</label><input id="cycle-end" type="date" min="2000-01-01" max="9999-12-31" value={end} disabled={locked} onChange={e=>setEnd(e.target.value)}/></div></div><fieldset className="cycle-goal-picker"><legend>Select active Goals</legend>{goals===null?<p>Loading available Goals…</p>:available.length?available.map(g=><label key={g.id}><input type="checkbox" checked={ids.includes(g.id)} disabled={locked||!!g.archivedAt&&!ids.includes(g.id)} onChange={e=>setIds(e.target.checked?[...ids,g.id]:ids.filter(id=>id!==g.id))}/><span><strong>{g.title}</strong><small>{g.archivedAt?'Unavailable for selection · remove to save':g.outcome}</small></span></label>):<p>Create a Goal first, or save an empty Draft.</p>}</fieldset><p className="small-note">Selection gives context. It does not change Goal lifecycle, existing commitments or scheduled blocks.</p></>:<><p><strong>{base?.title}</strong></p><p>{editor.kind==='activate'?'This becomes your one Active cycle. Only dates within its horizon count as Current Focus.':editor.kind==='finish'?'The cycle and its Goal context become read-only. Your Goals stay active and all scheduled work stays in place.':'The cycle leaves your current or Draft view and retains its history. Your Goals and weekly work stay available.'}</p></>}{error&&<div role="alert" className="dialog-error"><p>{error.message}</p>{conflict&&error.kind!=='CYCLE_TERMINAL'&&<button type="button" className="quiet-button" disabled={busy} onClick={()=>void review()}>Review latest cycle and Goals</button>}{!conflict&&!uncertain&&goals===null&&<button type="button" className="quiet-button" onClick={()=>void review()}>Retry loading Goals</button>}</div>}<div className="dialog-actions"><button type="button" data-cycle-focus={!edit?'':undefined} className="quiet-button" disabled={locked} onClick={onClose}>Cancel</button><button className="primary-button" disabled={busy||conflict||edit&&goals===null}>{uncertain?'Retry same command':edit?'Save cycle':editor.kind==='activate'?'Confirm activate':editor.kind==='finish'?'Confirm finish':'Confirm archive'}</button></div></form></dialog>;
}
