import { capacitySummary, type PlanningSnapshot } from "@/modules/planning/domain";
export const duration = (minutes: number) => { const hours = Math.floor(minutes / 60); const rest = minutes % 60; return [hours ? `${hours}h` : "", rest || !hours ? `${rest}m` : ""].filter(Boolean).join(" "); };
export function Context({ value }: { value: PlanningSnapshot }) {
  return <div className="planning-context"><p><strong>Goal:</strong> {value.goal.title}</p><p className="muted">{value.goal.outcome}</p>{value.milestone && <p><strong>Milestone:</strong> {value.milestone.title}</p>}<h3>{value.action.title}</h3>{value.action.doneWhen && <p className="muted">Done when: {value.action.doneWhen}</p>}<p className="planning-estimate">Action estimate: {value.action.estimateMinutes === null ? "not set" : duration(value.action.estimateMinutes)} <span>· total effort, separate from this week’s budget</span></p></div>;
}
export function Capacity({ capacity, reserve, budgets }: { capacity: number; reserve: number; budgets: number[] }) {
  const summary = capacitySummary({ provisionalCapacityMinutes: capacity, reserveMinutes: reserve, commitments: budgets.map((budgetMinutes) => ({ budgetMinutes })) });
  return <div className="capacity-panel" aria-label="Capacity summary"><dl><div><dt>Weekly capacity</dt><dd>{duration(capacity)}</dd></div><div><dt>Protected reserve</dt><dd>{duration(reserve)}</dd></div><div className="capacity-rule"><dt>Available to commit</dt><dd>{duration(summary.usableMinutes)}</dd></div><div><dt>Committed budget</dt><dd>{duration(summary.totalMinutes)}</dd></div><div className={summary.remainingMinutes < 0 ? "over-capacity" : "breathing-room"}><dt>{summary.remainingMinutes < 0 ? "Over capacity" : "Still uncommitted"}</dt><dd>{duration(Math.abs(summary.remainingMinutes))}</dd></div></dl>{summary.remainingMinutes < 0 ? <p role="alert">This draft is over capacity. Adjust budgets, capacity or reserve before committing.</p> : <p>Breathing room is healthy. You don’t need to fill it.</p>}</div>;
}
