"use client";
import { goalTitle } from '@/modules/planning/general';
import { useEffect, useRef, useState } from "react";
import { addDays, type SourceGuard } from "@/modules/planning/domain";
import type { Decision, ReviewWorkspace, WeeklyFacts, WeeklyReview } from "@/modules/weekly-reviews/domain";
import { BetterStreak } from "./better-streak";
import {WeekActivity} from "./week-activity";
import { ReviewDashboard } from "./review-dashboard";
import { CoachPanel } from './coach-panel';
import { duration } from "./planning-presentation";
import { recordedTime } from "./focus-view";
import { request, errorInfo, type CommandError } from "./mutation-client";
import { FeedbackMetrics, FeedbackDetails, FinalizedLabel } from "./feedback-presentation";
const dateLabel=(date:string)=>new Intl.DateTimeFormat("en-GB",{timeZone:"UTC",day:"numeric",month:"short",year:"numeric"}).format(new Date(`${date}T12:00Z`));
const stamp=(date:string,zone:string)=>new Intl.DateTimeFormat("en-GB",{timeZone:zone,day:"numeric",month:"short",hour:"2-digit",minute:"2-digit",timeZoneName:"shortOffset"}).format(new Date(date));
const labels={completed:"Completed as planned",partial:"Partial progress",abandoned:"Abandoned"};
type Choice={commitmentId:string;actionId:string;kind:Decision["kind"];budget:string;source:SourceGuard};
const choicesFrom=(r:WeeklyReview|null)=>r?.decisions.map(d=>({commitmentId:d.commitmentId,actionId:d.actionId,kind:d.kind,budget:d.proposedBudgetMinutes===null?"":String(d.proposedBudgetMinutes),source:d.source}))??[];
function WeekSummary({facts}:{facts:WeeklyFacts}) {
  return <FeedbackMetrics className="daily-metrics weekly-summaries" label="Weekly review summary" items={[{label:"Initially picked",value:duration(facts.originalSummary.totalMinutes)},{label:"Tasks picked",value:duration(facts.finalSummary.totalMinutes)},{label:"Scheduled focus",value:recordedTime(facts.scheduledMilliseconds)},{label:"Recorded focus",value:recordedTime(facts.recordedMilliseconds)}]}/>;
}
function PlanHistory({facts}:{facts:WeeklyFacts}) {
  return <WeekActivity plan={facts.plan} changes={facts.amendments}/>;
}
function DailyEvidence({facts}:{facts:WeeklyFacts}) {
  const finalized=facts.daily.filter(d=>d.reflection).length;
  return <section aria-label="Daily reflections" className="feedback-daily-evidence"><div className="feedback-section-heading"><h2>Daily reflections</h2><span>{finalized} of 7 finalized</span></div><FeedbackDetails title="View daily reflections">{facts.daily.map(d=><div key={d.date} className="weekly-daily"><strong>{dateLabel(d.date)}</strong>{d.reflection?<><span className="feedback-finalized">Finalized daily reflection</span><p className="focus-note">{d.reflection.note}</p></>:<p className="small-note">{d.state==="unfinished"?"Unfinished draft · not finalized evidence":"No finalized reflection considered"}</p>}</div>)}{facts.review?.status==="finalized"&&<p className="small-note">Only daily reflections finalized by {stamp(facts.review.finalizedAt!,facts.timezone)} are part of this review context.</p>}</FeedbackDetails></section>;
}
export function WeeklyReviewView({initial}:{initial:ReviewWorkspace}) {
  const [view,setView]=useState(initial),[saved,setSaved]=useState(initial.facts?.review??null),[note,setNote]=useState(initial.facts?.review?.note??""),[choices,setChoices]=useState<Choice[]>(choicesFrom(initial.facts?.review??null));
  const [busy,setBusy]=useState(false),[pending,setPending]=useState<{url:string;method:"PUT"|"POST";body:object;final:boolean}|null>(null),[error,setError]=useState<CommandError<WeeklyReview>|null>(null),[notice,setNotice]=useState(""),[conflict,setConflict]=useState(false),[finishing,setFinishing]=useState(false),[confirmArchive,setConfirmArchive]=useState(false),[attempted,setAttempted]=useState<string|null>(null);
  const flight=useRef(false),dialog=useRef<HTMLDialogElement>(null),cancel=useRef<HTMLButtonElement>(null),finish=useRef<HTMLButtonElement>(null),wasFinishing=useRef(false);
  const facts=view.facts,finalized=saved?.status==="finalized",dirty=note!==(saved?.note??"")||JSON.stringify(choices)!==JSON.stringify(choicesFrom(saved)),locked=busy||!!pending;
  const required=facts?.commitments.filter(c=>c.source?.eligible)??[];
  const complete=required.every(c=>{const d=choices.find(d=>d.commitmentId===c.commitment.id);return d&&(d.kind!=="carry"||/^\d+$/.test(d.budget)&&Number(d.budget)>0&&Number(d.budget)<=10080);});
  const dropTitles=[...new Set(choices.filter(d=>d.kind==="drop").map(d=>facts?.commitments.find(c=>c.commitment.id===d.commitmentId)?.commitment.snapshot.action.title??"Action"))];
  const url=`/api/weekly-reviews?week=${initial.weekStartDate}`;
  useEffect(()=>{if(!dirty&&!pending)return;const guard=(e:BeforeUnloadEvent)=>e.preventDefault();window.addEventListener("beforeunload",guard);return()=>window.removeEventListener("beforeunload",guard);},[dirty,pending]);
  useEffect(()=>{if(finishing){wasFinishing.current=true;dialog.current?.showModal();cancel.current?.focus();}else if(wasFinishing.current){wasFinishing.current=false;finish.current?.focus();}},[finishing]);
  function adopt(v:ReviewWorkspace){setView(v);setSaved(v.facts?.review??null);setNote(v.facts?.review?.note??"");setChoices(choicesFrom(v.facts?.review??null));setConflict(false);}
  async function refresh(){if(flight.current)return;setBusy(true);try{const v=await request<ReviewWorkspace>(url);setView(v);if(v.facts?.review?.version!==saved?.version){setConflict(true);setError({code:"CONFLICT",kind:"REVIEW_VERSION",message:"This weekly review changed elsewhere. Your unsaved note and decisions are retained.",current:v.facts?.review??undefined});}}catch(e){setError(errorInfo<WeeklyReview>(e));}finally{setBusy(false);}}
  async function latest(){if(flight.current)return;setBusy(true);try{const v=await request<ReviewWorkspace>(url);setView(v);setSaved(v.facts?.review??null);if(v.facts?.review?.status==="finalized"){setAttempted(JSON.stringify({note,choices},null,2));setNote(v.facts.review.note);setChoices(choicesFrom(v.facts.review));}else{setChoices(choices.map(d=>{const s=v.facts?.commitments.find(c=>c.commitment.id===d.commitmentId)?.source;return s?.eligible?{...d,source:s.source}:d;}));}setConflict(false);setFinishing(false);setError(null);setNotice("Latest saved review and source context reviewed. Your attempted choices are retained; remove any resolved work, then save deliberately.");}catch(e){setError(errorInfo<WeeklyReview>(e));}finally{setBusy(false);}}
  async function send(command:NonNullable<typeof pending>){if(flight.current)return;flight.current=true;setBusy(true);setPending(command);setError(null);try{await request(command.url,{method:command.method,headers:{"Content-Type":"application/json"},body:JSON.stringify(command.body)});adopt(await request<ReviewWorkspace>(url));setPending(null);setFinishing(false);setNotice(command.final?"Weekly review finalized. Carry is an intent; add it deliberately in next week's plan.":"Weekly review draft saved.");}catch(e){const info=errorInfo<WeeklyReview>(e);setError(info);if(!["UNCERTAIN","DATABASE_UNAVAILABLE"].includes(info.code)){setPending(null);if(info.code==="CONFLICT")setConflict(true);}}finally{flight.current=false;setBusy(false);}}
  function save(){if(!facts)return;const decisions=choices.map(d=>({commitmentId:d.commitmentId,actionId:d.actionId,kind:d.kind,proposedBudgetMinutes:d.kind==="carry"?(d.budget.trim()?Number(d.budget):0):null,source:d.source}));void send({url:"/api/weekly-reviews",method:"PUT",final:false,body:{mutationId:crypto.randomUUID(),planId:facts.plan.id,reviewId:saved?.id??null,expectedVersion:saved?.version??0,note,decisions}});}
  async function reviewFinish(){if(locked||dirty||!saved||conflict)return;setBusy(true);try{const v=await request<ReviewWorkspace>(url);setView(v);if(v.facts?.review?.version!==saved.version){setConflict(true);setError({code:"CONFLICT",message:"The saved review changed. Review the latest note and decisions.",current:v.facts?.review??undefined});return;}const stale=choices.some(d=>{const s=v.facts?.commitments.find(c=>c.commitment.id===d.commitmentId)?.source;return !s?.eligible||Object.keys(d.source).some(k=>d.source[k as keyof SourceGuard]!==s.source[k as keyof SourceGuard]);});if(stale){setConflict(true);setError({code:"CONFLICT",kind:"REVIEW_SOURCE",message:"An Action or its parent changed. Inspect its latest context, review it, and save before finishing."});return;}setConfirmArchive(false);setFinishing(true);}catch(e){setError(errorInfo<WeeklyReview>(e));}finally{setBusy(false);}}
  const nav=(week:string,label:string)=><a key={`${week}:${label}`} className="quiet-button" aria-current={week===view.weekStartDate?"date":undefined} href={`/review?week=${week}`} aria-disabled={locked||dirty} onClick={e=>{if(locked||dirty)e.preventDefault();}}>{label}</a>;
  const errors=error&&<div className="daily-error" role="alert"><p>{error.message}</p>{error.current&&<><p>Latest saved reflection: {error.current.note}</p>{error.current.decisions.map(d=><p key={d.commitmentId}>{facts?.commitments.find(c=>c.commitment.id===d.commitmentId)?.commitment.snapshot.action.title} · {d.kind}{d.proposedBudgetMinutes!==null&&` · ${duration(d.proposedBudgetMinutes)}`}</p>)}</>}{pending?<button className="quiet-button" disabled={busy} onClick={()=>void send(pending)}>Retry same command</button>:conflict&&<><p className="small-note">Inspect current Action context below before accepting a newer source version.</p><button className="quiet-button" disabled={locked} onClick={()=>void latest()}>Review latest saved review and source context</button></>}</div>;
  const decisionEntries=facts?.commitments.filter(c=>finalized ? choices.some(d=>d.commitmentId===c.commitment.id) : c.source?.eligible||choices.some(d=>d.commitmentId===c.commitment.id))??[];
  const remaining=required.filter(c=>{const d=choices.find(d=>d.commitmentId===c.commitment.id);return !d||d.kind==="carry"&&(!/^\d+$/.test(d.budget)||Number(d.budget)<1||Number(d.budget)>10080);}).length;
  function pick(c:WeeklyFacts["commitments"][number],kind:Decision["kind"]|"") {
    const id=c.commitment.id,d=choices.find(d=>d.commitmentId===id);
    setChoices([...choices.filter(v=>v.commitmentId!==id),...(kind?[{commitmentId:id,actionId:c.commitment.actionId,kind,budget:kind==="carry"&&d?.kind==="carry"?d.budget:"",source:c.source!.source}]:[])].sort((a,b)=>a.commitmentId.localeCompare(b.commitmentId)));setNotice("");
  }
  function commitmentCard(c:WeeklyFacts["commitments"][number]) {
    const id=c.commitment.id,d=choices.find(d=>d.commitmentId===id),snapshot=c.commitment.snapshot;
    return <article className="daily-block feedback-work-card" key={id} data-weekly-commitment={id}>
      <div className="feedback-work-heading"><h3>{snapshot.action.title}</h3><span className="feedback-status">{c.inFinalPlan?"In final plan":"Dropped from plan during the week"}</span></div>
      <p className="feedback-goal">Goal · {goalTitle(snapshot.goal)}</p>
      <dl className="feedback-card-facts"><div><dt>{c.firstSequence===0?"Original budget":"Added budget"}</dt><dd>{duration(c.firstBudgetMinutes)}</dd></div><div><dt>{c.inFinalPlan?"Final budget":"Last budget before removal"}</dt><dd>{duration(c.latestBudgetMinutes)}</dd></div><div><dt>Scheduled</dt><dd>{recordedTime(c.scheduledMilliseconds)}</dd></div><div><dt>Recorded focus</dt><dd>{recordedTime(c.recordedMilliseconds)}</dd></div></dl>
      {c.sessions.length===0&&<p className="feedback-no-session">No focus session recorded in this week</p>}
      {finalized?<><p className="feedback-recorded-decision"><strong>Recorded decision: {d?.kind??"No rollover required"}</strong>{d?.kind==="carry"&&` · proposed ${duration(Number(d.budget))} next week`}</p>{!d&&<p className="small-note">Current source context: {c.source?.reason??"No rollover required."}</p>}</>:<>
        {c.source?.eligible?<><fieldset className="feedback-decision"><legend>What happens next?</legend><div>{([['carry','Carry'],['defer','Defer'],['drop','Drop']] as const).map(([kind,label])=><button key={kind} type="button" aria-pressed={d?.kind===kind} disabled={locked} onClick={()=>pick(c,kind)}>{label}</button>)}{d&&<button className="feedback-clear-choice" disabled={locked} onClick={()=>pick(c,"")}>Clear decision</button>}</div></fieldset>{c.source.context.action.title!==snapshot.action.title&&<p className="small-note">Current Action · {c.source.context.action.title}</p>}</>:<><p className="small-note">{c.source?.reason??"Source unavailable; no rollover required."}</p>{d&&<button className="quiet-button" disabled={locked} onClick={()=>setChoices(choices.filter(v=>v.commitmentId!==id))}>Remove stale decision</button>}</>}
        {d?.kind==="carry"&&<div className="feedback-carry-budget"><label htmlFor={`carry-budget-${id}`}>Fresh proposed next-week budget in minutes</label><input id={`carry-budget-${id}`} type="number" min="1" max="10080" step="1" value={d.budget} disabled={locked} onChange={e=>setChoices(choices.map(v=>v.commitmentId===id?{...v,budget:e.target.value}:v))}/><p className="small-note">A fresh proposal; prior budget {duration(c.latestBudgetMinutes)} is context only.</p></div>}
        {d?.kind==="defer"&&<p className="small-note">Keep this Action Open and available. No special next-week insertion.</p>}{d?.kind==="drop"&&<p className="weekly-drop-warning">This archives the Action when you finalize. Archived Actions cannot currently be restored.</p>}
      </>}
      <FeedbackDetails title="Details" className="feedback-commitment-details"><h4>Frozen intended outcome and finish condition</h4><p>{snapshot.goal?.outcome}</p>{snapshot.action.doneWhen&&<p>Done when · {snapshot.action.doneWhen}</p>}{snapshot.milestone&&<p>Milestone · {snapshot.milestone.title} · {snapshot.milestone.successCondition}</p>}<p className="small-note">{c.firstSequence===0?"In original baseline":"Added during the week"} · {stamp(c.firstAppearance,facts!.timezone)}</p>
        <h4>Original schedule</h4>{c.blocks.length?c.blocks.map(b=><div key={b.id} className="small-note"><p>{b.state==="cancelled"?"Cancelled interval · excluded from scheduled total":"Planned block"} · {stamp(b.start,facts!.timezone)} → {stamp(b.end,facts!.timezone)}</p>{!c.sessions.some(s=>s.session.timeBlockId===b.id)&&<p>No focus session recorded{b.state==="cancelled"?" for this cancelled block":" in this week"}</p>}</div>):<p>No blocks scheduled.</p>}
        {c.sessions.length>0&&<><h4>Sessions · {c.sessions.length}</h4>{c.sessions.map(s=><div key={s.session.id}><p>{s.session.outcome?labels[s.session.outcome]:"Still active · closed-week contribution is fixed"} · {recordedTime(s.recordedMilliseconds)} in this week</p><p className="small-note">{stamp(s.session.startedAt,facts!.timezone)} → {s.session.endedAt?stamp(s.session.endedAt,facts!.timezone):"Still active"}</p>{s.session.endNote&&<p className="focus-note">{s.session.endNote}</p>}</div>)}</>}
        {!finalized&&<><h4>Latest source context for this decision</h4>{c.source?.eligible?<><p>{goalTitle(c.source.context.goal)} · {c.source.context.goal?.outcome}</p><p>Current Action: {c.source.context.action.title} · Open and available · {c.source.context.action.doneWhen}</p>{c.source.context.milestone&&<p>{c.source.context.milestone.title} · {c.source.context.milestone.successCondition}</p>}</>:<p>{c.source?.reason??"Source unavailable; no rollover required."}</p>}</>}
      </FeedbackDetails>
    </article>;
  }
  return <div className="daily-workspace weekly-review-workspace reference-review feedback-workspace feedback-weekly">
    <div className="review-period-header"><nav className="review-mode-tabs" aria-label="Review mode"><a href="/today" aria-disabled={locked||dirty} onClick={e=>{if(locked||dirty)e.preventDefault();}}>Daily</a><a href={`/review?week=${view.weekStartDate}`} aria-current="page" aria-disabled={locked||dirty} onClick={e=>{if(locked||dirty)e.preventDefault();}}>Weekly</a></nav>
    <div className="focus-heading"><div><p className="eyebrow">Learn from the week. Choose what comes next.</p><h1>Week of {dateLabel(view.weekStartDate)}</h1><p className="feedback-date">{dateLabel(view.weekStartDate)} – {dateLabel(addDays(view.weekStartDate,6))} · {view.timezone}{finalized?" · Finalized review":" · Weekly review"}</p></div><button className="quiet-button" disabled={locked} onClick={()=>void refresh()}>Refresh review facts</button></div>
    <nav className="daily-navigation review-week-navigation" aria-label="Review week navigation">{nav(addDays(view.weekStartDate,-7),"← Previous week")}{nav(view.currentWeekStartDate,"This week")}{nav(addDays(view.weekStartDate,7),"Next week →")}</nav>
    </div>
    {view.weekStartDate===view.currentWeekStartDate?<p className="small-note review-week-context">Current week · Weekly review opens {dateLabel(addDays(view.weekStartDate,7))}, after Sunday ends in {view.timezone}.</p>:view.weekStartDate<view.currentWeekStartDate?<p className="small-note review-week-context">Finished week · This review covers the dates above.</p>:null}
    {view.weeks.length>0&&<nav className="daily-navigation review-finished-weeks" aria-label="Finished review weeks"><span className="small-note">Past weeks</span>{view.weeks.map(w=>nav(w.weekStartDate,dateLabel(w.weekStartDate)))}</nav>}
    {(dirty||pending)&&<p className="small-note">Save or discard your unsaved reflection and choices before changing weeks. Retry an unconfirmed command first.</p>}{notice&&<p role="status" className="plan-notice">{notice}</p>}{!finishing&&errors}
    {view.analytics?<ReviewDashboard habit={view.habit} data={view.analytics} navigationBlocked={locked||dirty} summary={facts?<WeekSummary facts={facts}/>:undefined}/>:view.habit&&<BetterStreak habit={view.habit}/>}
    {!facts?<div className="goal-empty review-lifecycle-card"><h2>{view.state==="unfinished"?"This week has not finished yet.":"No weekly tasks were picked for these dates."}</h2><p>{view.state==="unfinished"?`Review opens ${dateLabel(addDays(view.weekStartDate,7))}, after this week fully ends in ${view.timezone}. Until then, Daily Review shows your planned blocks, recorded focus and reflection for today.`:"Your focus and reflections still count. Review today or choose another week above."}</p><div className="review-empty-actions"><a className="primary-button" href="/today">Open Daily Review</a><a className="quiet-button" href={`/calendar?week=${view.currentWeekStartDate}`}>View this week&apos;s calendar</a><a className="quiet-button" href={`/planning?week=${view.currentWeekStartDate}`}>Pick this week’s tasks</a></div></div>:<>
      {!view.analytics&&<WeekSummary facts={facts}/>}
      <div className="feedback-layout">
        <div className="feedback-main-column">

          <section className="feedback-decisions" aria-label={finalized?"Recorded decisions":"Rollover decisions"}><div className="feedback-section-heading"><h2>{finalized?"Decisions recorded":"Needs your decision"}</h2><span>{finalized?`${choices.length} recorded`:`${remaining} remaining`}</span></div><p className="feedback-section-note">{finalized?"Carry remains an intent for deliberate planning. It does not create next week's plan.":"Carry proposes work for next week. Defer keeps it available. Drop archives the Action when you finish."}</p>{decisionEntries.length?decisionEntries.map(commitmentCard):<p className="small-note">No actionable commitments need a rollover decision.</p>}</section>
        </div>
        <aside className="feedback-reflection-column review-reflection-rail" aria-label="Weekly reflection and next steps">
          <section className="daily-reflection feedback-reflection"><div className="feedback-section-heading"><h2>Weekly reflection</h2>{finalized&&<FinalizedLabel/>}</div>
            {finalized?<><p className="small-note">Finished {stamp(saved.finalizedAt!,facts.timezone)}</p><p className="focus-note" data-finalized-weekly-review={saved.id}>{saved.note}</p>{attempted&&<FeedbackDetails title="Your unsaved attempted review"><pre className="focus-note">{attempted}</pre></FeedbackDetails>}<a className="primary-button" href={`/planning?week=${addDays(facts.plan.weekStartDate,7)}`}>Plan the following week</a></>:<><p>What worked? What changed? What should you remember going into next week?</p><label htmlFor="weekly-note" className="sr-only">Weekly reflection</label><textarea id="weekly-note" placeholder="What worked, and what would make next week better?" rows={5} value={note} disabled={locked} onChange={e=>{setNote(e.target.value);setNotice("");}}/><p className="small-note">Up to 4,000 characters · explicit saves, no autosave. {saved?"Saved draft.":"No review saved yet."}{dirty?" Unsaved changes.":""}</p><div className="dialog-actions"><button className="quiet-button" disabled={locked||conflict} onClick={save}>Save review draft</button>{dirty&&<button className="quiet-button" disabled={locked} onClick={()=>{setNote(saved?.note??"");setChoices(choicesFrom(saved));}}>Discard unsaved changes</button>}<button ref={finish} className="primary-button" disabled={locked||conflict||dirty||!saved?.note.trim()||!complete} onClick={()=>void reviewFinish()}>Finish weekly review</button></div>{!complete&&<p className="small-note">{remaining} {remaining===1?"commitment needs":"commitments need"} a decision or fresh Carry budget before finishing.</p>}{dirty&&<p className="small-note">Save your reflection and decisions before finishing.</p>}</>}
          </section>
          <p className="feedback-fact-note">Budgets, schedules and recorded focus are independent. Outcomes do not complete Actions.</p>
          <CoachPanel key={view.weekStartDate} contextType="weekly_review" week={view.weekStartDate} locked={locked||dirty} revision={JSON.stringify([facts.plan.version,saved?.version,facts.recordedMilliseconds,facts.daily.map(d=>[d.date,d.state,d.reflection?.finalizedAt])])}/>
        </aside>
        <section className="feedback-evidence" aria-label="Weekly evidence"><div className="feedback-section-heading"><h2>Evidence</h2><span>Here when you need it</span></div>
          <PlanHistory facts={facts}/>
          <FeedbackDetails title={`Other commitment history · ${facts.commitments.length-decisionEntries.length}`} className="feedback-all-commitments">{facts.commitments.filter(c=>!decisionEntries.some(d=>d.commitment.id===c.commitment.id)).map(commitmentCard)}<p className="small-note">Actionable commitments and their Details appear above. Every original, added and removed commitment retains its own identity.</p></FeedbackDetails>
          {facts.otherWork.length>0&&<FeedbackDetails title="Recorded work from other planning weeks">{facts.otherWork.map(w=><div key={w.block.id}><h3>{w.block.snapshot.action.title}</h3><p>Goal · {goalTitle(w.block.snapshot.goal)} · {recordedTime(w.recordedMilliseconds)} in this week</p><p className="small-note">Retains its original commitment. No new rollover decision is created here.</p><p>{stamp(w.block.start,facts.timezone)} → {stamp(w.block.end,facts.timezone)}</p>{w.block.snapshot.milestone&&<p>Milestone · {w.block.snapshot.milestone.title}</p>}{w.sessions.map(s=><div key={s.session.id}><p>{s.session.outcome?labels[s.session.outcome]:"Still active · closed-week contribution is fixed"} · {recordedTime(s.recordedMilliseconds)} in this week</p><p>{stamp(s.session.startedAt,facts.timezone)} → {s.session.endedAt?stamp(s.session.endedAt,facts.timezone):"Still active"}</p>{s.session.endNote&&<p className="focus-note">{s.session.endNote}</p>}</div>)}</div>)}</FeedbackDetails>}
          <DailyEvidence facts={facts}/>
        </section>
      </div>
      {finishing&&saved&&<dialog ref={dialog} className="goal-dialog weekly-finish-dialog feedback-finish-dialog" aria-labelledby="weekly-finish-title" onCancel={e=>{e.preventDefault();if(!locked)setFinishing(false);}}><h2 id="weekly-finish-title">Finish weekly review?</h2><WeekSummary facts={facts}/><h3>Your weekly reflection</h3><p className="focus-note">{saved.note}</p><h3>Deliberate next steps</h3>{saved.decisions.map(d=><p key={d.commitmentId}>{facts.commitments.find(c=>c.commitment.id===d.commitmentId)?.commitment.snapshot.action.title} · <strong>{d.kind}</strong>{d.kind==="carry"&&` · proposed ${duration(d.proposedBudgetMinutes!)} next week`}</p>)}{dropTitles.length>0&&<><p className="weekly-drop-warning">This archives: {dropTitles.join(", ")}. Archived Actions cannot currently be restored.</p><label className="acknowledgement"><input type="checkbox" checked={confirmArchive} disabled={locked} onChange={e=>setConfirmArchive(e.target.checked)}/>I confirm archiving these Drop Actions.</label></>}<p className="small-note">The note and decisions become read-only. Carry does not create or modify next week&apos;s plan.</p>{errors}<div className="dialog-actions"><button ref={cancel} className="quiet-button" disabled={locked} onClick={()=>setFinishing(false)}>Keep draft</button><button className="primary-button" disabled={locked||conflict||dropTitles.length>0&&!confirmArchive} onClick={()=>void send({url:`/api/weekly-reviews/${saved.id}/finalize`,method:"POST",final:true,body:{mutationId:crypto.randomUUID(),expectedVersion:saved.version,confirmArchive}})}>Confirm weekly finish</button></div></dialog>}
    </>}
  </div>;
}
