import assert from 'node:assert/strict';
import {randomBytes,randomUUID} from 'node:crypto';
import {spawn,type ChildProcess} from 'node:child_process';
import {once} from 'node:events';
import {setTimeout as delay} from 'node:timers/promises';
import {mkdtemp,writeFile,readFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Pool} from 'pg';
import {migrate} from 'drizzle-orm/node-postgres/migrator';
import {connectDatabase} from '../src/db/connect';
import {requireTestDatabaseURL,dropIsolatedTestDatabase} from './test-database';
import {provisionLocalUser} from './local-user';
import {startChatGPTFixture} from '../tests/chatgpt-provider-fixture';
import {credentialCipher} from '../src/modules/calendar/encryption';
import {databaseCoaching,coachingCalendarFixture} from '../tests/coaching-database';
import {executionFixture} from '../tests/focus-database';
import type {ChatGPTWorkspace,Connection} from '../src/modules/chatgpt/domain';
import type {CoachingView,CoachingRun} from '../src/modules/coaching/domain';
const origin='http://127.0.0.1:3102',week='2028-01-03',now='2026-10-03T09:00:00.000Z',name=`execution_test_${randomBytes(6).toString('hex')}`,target=new URL(requireTestDatabaseURL().url),adminURL=new URL(target);
target.pathname=`/${name}`;adminURL.pathname='/postgres';const admin=new Pool({connectionString:adminURL.toString()}),database=connectDatabase(target.toString()),directory=await mkdtemp(join(tmpdir(),'chatgpt-restart-')),clockFile=join(directory,'now'),hostFile=join(directory,'host.json'),key=randomBytes(32).toString('base64'),cipher=credentialCipher({qa:key},'qa'),fixture=await startChatGPTFixture();let child:ChildProcess|undefined,created=false;
async function start(){child=spawn(process.execPath,['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port','3102'],{env:{...process.env,NODE_ENV:'production',BETTER_AUTH_URL:origin,DATABASE_URL:target.toString(),EXECUTION_TEST_CLOCK_FILE:clockFile,AI_PROVIDER:'',OPENAI_API_KEY:'',OPENAI_MODEL:'',ANTHROPIC_API_KEY:'',ANTHROPIC_MODEL:'',AI_TEST_BASE_URL:'',GOOGLE_CALENDAR_CLIENT_ID:'',GOOGLE_CALENDAR_CLIENT_SECRET:'',GOOGLE_CALENDAR_REDIRECT_URI:'',CALENDAR_ENCRYPTION_KEYS:'',CALENDAR_ENCRYPTION_KEY_ID:'',CALENDAR_TEST_ORIGIN:'',CHATGPT_TEST_ORIGIN:fixture.origin,CHATGPT_TEST_MODE:'isolated-fixture',CHATGPT_HOST_FILE:hostFile,CHATGPT_ENCRYPTION_KEYS:JSON.stringify({qa:key}),CHATGPT_ENCRYPTION_KEY_ID:'qa'},stdio:'ignore'});for(let i=0;i<120;i++){if(child.exitCode!==null)throw new Error('Production process exited');try{if((await fetch(`${origin}/api/health`)).ok)return;}catch{}await delay(250);}throw new Error('Production process not ready');}
async function stop(){if(child&&child.exitCode===null){const ended=once(child,'exit');child.kill('SIGTERM');await ended;}child=undefined;}
try{
 await admin.query(`CREATE DATABASE "${name}"`);created=true;await migrate(database.db,{migrationsFolder:'src/db/migrations'});const user=await provisionLocalUser(database.db,{email:process.env.TEST_USER_A_EMAIL,password:process.env.TEST_USER_A_PASSWORD,name:'ChatGPT restart proof',timezone:'Europe/London'}),actor={userId:user.id};await executionFixture(database.db,actor,week,()=>now);const d=databaseCoaching(database.db,database.pool,()=>now);await d.hours.save(actor,{mutationId:randomUUID(),scheduleId:null,expectedVersion:0,windows:[{weekday:1,startMinute:540,endMinute:1020}]});await coachingCalendarFixture(database.db,database.pool,actor,week,now);await writeFile(clockFile,now);await start();
 const login=await fetch(`${origin}/api/auth/sign-in/email`,{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({email:process.env.TEST_USER_A_EMAIL,password:process.env.TEST_USER_A_PASSWORD})});assert.equal(login.status,200);const cookie=login.headers.getSetCookie().map(v=>v.split(';')[0]).join('; '),headers={cookie,Origin:origin,'Content-Type':'application/json'};
 async function request<T>(path:string,method='GET',body?:unknown):Promise<T>{const r=await fetch(`${origin}${path}`,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});assert.equal(r.status,200);return r.json();}
 const workspace=()=>request<ChatGPTWorkspace>('/api/chatgpt');
 async function connect(id:string|null){const a=await request<{url:string}>('/api/chatgpt/connect','POST',{connectionId:id}),u=new URL(a.url);assert.equal(u.searchParams.get('client_id'),id?'oaiapp_fixture':'dynamic_agent_client');const callback=await fixture.authorize(a.url),r=await fetch(callback,{headers,redirect:'manual'});assert.equal(r.status,303);assert.equal(r.headers.get('location'),`${origin}/integrations?chatgpt=success`);return (await workspace()).connections.find(c=>c.active)!;}
 let c=await connect(null);c=(await request<{connection:Connection}>(`/api/chatgpt/${c.id}/models`,'POST')).connection;c=(await request<{connection:Connection}>(`/api/chatgpt/${c.id}`,'PATCH',{expectedVersion:c.version,selectedModel:'fixture-openai',useForCoaching:true})).connection;
 const host=await readFile(hostFile,'utf8'),initial=(await database.pool.query('SELECT encrypted_credentials FROM chatgpt_connection WHERE id=$1',[c.id])).rows[0].encrypted_credentials;
 await stop();await start();assert.equal(await readFile(hostFile,'utf8'),host);assert.equal((await workspace()).connections[0].selectedModel,'fixture-openai');assert.equal((await database.pool.query('SELECT encrypted_credentials FROM chatgpt_connection WHERE id=$1',[c.id])).rows[0].encrypted_credentials,initial);
 const view=()=>request<CoachingView>(`/api/coaching?contextType=calendar&week=${week}`),generate=async()=>{const v=await view();return request<{run:CoachingRun}>('/api/coaching','POST',{contextType:'calendar',week,mutationId:randomUUID(),fingerprint:v.fingerprint});};
 assert.equal((await generate()).run.status,'succeeded');assert.equal((await fixture.control()).exchangeCount,1);assert.equal((await fixture.control()).refreshCount,0);
 // Expire only this disposable account's access token; retain the refresh token.
 // No production credential is copied, edited, or printed.
 await stop();const old=JSON.parse(cipher.decrypt(initial,`chatgpt:${actor.userId}:${c.id}:credentials`));old.expiresAt=new Date(Date.now()-1000).toISOString();await database.pool.query('UPDATE chatgpt_connection SET encrypted_credentials=$1 WHERE id=$2',[cipher.encrypt(JSON.stringify(old),`chatgpt:${actor.userId}:${c.id}:credentials`),c.id]);await start();assert.equal((await generate()).run.status,'succeeded');assert.equal((await fixture.control()).refreshCount,1);const rotated=(await database.pool.query('SELECT encrypted_credentials FROM chatgpt_connection WHERE id=$1',[c.id])).rows[0].encrypted_credentials;assert.notEqual(rotated,initial);assert.notEqual(JSON.parse(cipher.decrypt(rotated,`chatgpt:${actor.userId}:${c.id}:credentials`)).refreshToken,old.refreshToken);
 await stop();await start();assert.equal((await generate()).run.status,'succeeded');assert.equal((await fixture.control()).refreshCount,1);assert.equal((await fixture.control()).exchangeCount,1);c=(await workspace()).connections[0];assert.equal(c.selectedModel,'fixture-openai');await request(`/api/chatgpt/${c.id}/disconnect`,'POST',{expectedVersion:c.version});await stop();await start();assert.equal((await workspace()).connections[0].status,'disconnected');assert.equal((await view()).enabled,false);assert.equal((await fetch(`${origin}/calendar?week=${week}`,{headers})).status,200);assert.equal((await database.pool.query('SELECT encrypted_credentials FROM chatgpt_connection WHERE id=$1',[c.id])).rows[0].encrypted_credentials,null);
 c=await connect(c.id);assert.equal(c.selectedModel,'fixture-openai');assert.equal(c.id,(await workspace()).connections[0].id);assert.equal(await readFile(hostFile,'utf8'),host);assert.equal((await fixture.control()).exchangeCount,2);
 console.log('PASS: production stop/start preserves ChatGPT registration, host ID, encrypted credentials and selected model; coaching works without OAuth; expired access refreshes once, rotated replacement survives another restart; disconnect survives restart without affecting Better Auth; reconnect reuses issued client ID. All provider traffic is synthetic.');
}finally{await stop();await fixture.close();await database.pool.end();if(created)await dropIsolatedTestDatabase(admin,name);await admin.end();await rm(directory,{recursive:true,force:true});}
