import {randomBytes,randomUUID} from "node:crypto";
import {spawn,type ChildProcess} from "node:child_process";
import {once} from "node:events";
import {setTimeout as delay} from "node:timers/promises";
import {mkdtemp,writeFile,rm} from "node:fs/promises";
import {tmpdir} from "node:os";
import {join} from "node:path";
import assert from "node:assert/strict";
import {Pool} from "pg";
import {migrate} from "drizzle-orm/node-postgres/migrator";
import {chromium} from "@playwright/test";
import {connectDatabase} from "../src/db/connect";
import {requireTestDatabaseURL,dropIsolatedTestDatabase} from "./test-database";
import {provisionLocalUser} from "./local-user";
import {weeklyFixture} from "../tests/weekly-review-fixture";

import type {WeeklyReview,ReviewWorkspace} from "../src/modules/weekly-reviews/domain";
const origin="http://127.0.0.1:3102",{url}=requireTestDatabaseURL(),target=new URL(url),adminURL=new URL(url),name=`execution_test_${randomBytes(6).toString("hex")}`;
target.pathname=`/${name}`;adminURL.pathname="/postgres";const admin=new Pool({connectionString:adminURL.toString()}),database=connectDatabase(target.toString()),directory=await mkdtemp(join(tmpdir(),"weekly-review-restart-")),clockFile=join(directory,"now");let created=false,child:ChildProcess|undefined;
const browser=await chromium.launch(process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH?{executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH}:{});
async function start(databaseURL=target.toString(),health=200){child=spawn(process.execPath,["node_modules/next/dist/bin/next","start","--hostname","127.0.0.1","--port","3102"],{env:{...process.env,NODE_ENV:"production",BETTER_AUTH_URL:origin,DATABASE_URL:databaseURL,EXECUTION_TEST_CLOCK_FILE:clockFile},stdio:"ignore"});for(let i=0;i<120;i++){if(child.exitCode!==null)throw new Error("Production process exited");try{if((await fetch(`${origin}/api/health`)).status===health)return;}catch{}await delay(250);}throw new Error("Production process not ready");}
async function stop(){if(child&&child.exitCode===null){const ended=once(child,"exit");child.kill("SIGTERM");await ended;}child=undefined;}
try{
 await admin.query(`CREATE DATABASE "${name}"`);created=true;await migrate(database.db,{migrationsFolder:"src/db/migrations"});const actor=await provisionLocalUser(database.db,{email:process.env.TEST_USER_A_EMAIL,password:process.env.TEST_USER_A_PASSWORD,name:"Weekly review restart proof",timezone:"Europe/London"}),f=await weeklyFixture(database.db,{userId:actor.id});await writeFile(clockFile,f.clock());await start();
 const signin=await fetch(`${origin}/api/auth/sign-in/email`,{method:"POST",headers:{Origin:origin,"Content-Type":"application/json"},body:JSON.stringify({email:process.env.TEST_USER_A_EMAIL,password:process.env.TEST_USER_A_PASSWORD})});assert.equal(signin.status,200);const cookies=signin.headers.getSetCookie().map(v=>v.split(";")[0]),cookie=cookies.join("; ");
 const page=await browser.newPage();await page.context().addCookies(cookies.map(v=>{const i=v.indexOf("=");return {name:v.slice(0,i),value:v.slice(i+1),url:origin,httpOnly:true,sameSite:"Lax" as const};}));
 async function read<T>(path:string):Promise<T>{const r=await fetch(`${origin}${path}`,{headers:{cookie}});assert.equal(r.status,200);return r.json() as Promise<T>;}
 async function mutate(path:string,method:string,data:object):Promise<WeeklyReview>{const r=await fetch(`${origin}${path}`,{method,headers:{cookie,Origin:origin,"Content-Type":"application/json"},body:JSON.stringify(data)});assert.equal(r.status,200);return (await r.json()).review;}
 const snapshot=async()=>{const result:Record<string,unknown>={};for(const table of ["goal","milestone","weekly_plan","weekly_commitment","weekly_plan_amendment","amendment_commitment","commitment_identity","time_block","focus_session","daily_reflection"])result[table]=(await database.pool.query(`SELECT row_to_json(t) FROM ${table} t WHERE owner_id=$1 ORDER BY row_to_json(t)::text`,[actor.id])).rows;return result;},before=await snapshot();
 const sourceBefore=(await database.pool.query("SELECT row_to_json(t) FROM action t WHERE id=ANY($1) ORDER BY id",[[f.sources[0].id,f.sources[1].id]])).rows;
 const path="/api/weekly-reviews",createCommand=f.save(),draft=await mutate(path,"PUT",createCommand);assert.equal(draft.version,1);assert.equal(draft.decisions.length,3);await stop();await start();
 assert.deepEqual((await read<ReviewWorkspace>(`${path}?week=${f.week}`)).facts!.review,draft);assert.deepEqual(await mutate(path,"PUT",createCommand),draft);await page.goto(`${origin}/review`);assert.equal(await page.getByLabel("Weekly reflection",{exact:true}).inputValue(),draft.note);await page.reload();assert.equal(await page.getByLabel("Fresh proposed next-week budget in minutes").inputValue(),"90");
 const editCommand=f.save({reviewId:draft.id,expectedVersion:1,note:"Use the recovered draft to plan a smaller next-week review slice.",decisions:draft.decisions.map(d=>d.kind==="carry"?{...d,proposedBudgetMinutes:95}:d)}),edited=await mutate(path,"PUT",editCommand),finishPath=`${path}/${draft.id}/finalize`,finishCommand={mutationId:randomUUID(),expectedVersion:2,confirmArchive:true};await writeFile(clockFile,"2026-10-12T10:00:00.321Z");const final=await mutate(finishPath,"POST",finishCommand);assert.equal(final.version,3);assert.equal(final.finalizedAt,"2026-10-12T10:00:00.321Z");await stop();await start();
 assert.deepEqual(await mutate(path,"PUT",createCommand),draft);assert.deepEqual(await mutate(path,"PUT",editCommand),edited);assert.deepEqual(await mutate(finishPath,"POST",finishCommand),final);assert.deepEqual((await read<{review:WeeklyReview}>(`${path}/${draft.id}`)).review,final);await page.reload();await page.locator(`[data-finalized-weekly-review="${draft.id}"]`).waitFor();assert.equal(await page.locator("[data-finalized-weekly-review]").innerText(),final.note);assert.equal(await page.getByLabel("Weekly reflection",{exact:true}).count(),0);
 assert.deepEqual(await snapshot(),before);assert.deepEqual((await database.pool.query("SELECT row_to_json(t) FROM action t WHERE id=ANY($1) ORDER BY id",[[f.sources[0].id,f.sources[1].id]])).rows,sourceBefore);const drop=(await database.pool.query("SELECT state,version,archived_at FROM action WHERE id=$1",[f.sources[2].id])).rows[0];assert.equal(drop.state,"archived");assert.equal(drop.version,2);assert.equal(drop.archived_at.toISOString(),final.finalizedAt);assert.equal((await database.pool.query("SELECT 1 FROM weekly_review WHERE owner_id=$1",[actor.id])).rowCount,1);assert.equal((await database.pool.query("SELECT 1 FROM weekly_review_decision WHERE owner_id=$1",[actor.id])).rowCount,3);assert.equal((await database.pool.query("SELECT 1 FROM mutation_receipt WHERE owner_id=$1 AND result ? 'decisions'",[actor.id])).rowCount,3);assert.equal((await database.pool.query("SELECT 1 FROM weekly_plan WHERE owner_id=$1",[actor.id])).rowCount,1);
 await stop();const unavailable=new URL(target);unavailable.pathname=`/execution_test_unavailable${Date.now()}`;await start(unavailable.toString(),503);for(const [api,method,data] of [[path,"GET",undefined],[`${path}/${draft.id}`,"GET",undefined],[`${path}/carries?week=2026-10-12`,"GET",undefined],[path,"PUT",createCommand],[finishPath,"POST",finishCommand]] as const)assert.equal((await fetch(`${origin}${api}`,{method,headers:{cookie,Origin:origin,"Content-Type":"application/json"},body:data?JSON.stringify(data):undefined})).status,503);
 console.log("PASS: Weekly Review note and decisions survive actual production restart/browser reload; create/edit/finalize original receipts replay after second restart; one terminal Review/three decisions/three receipts, Drop archived exactly once with original timestamp/version, Carry/Defer sources and historical planning/execution/daily bytes unchanged, no automatic next Plan; all Weekly Review APIs return 503 with unavailable PostgreSQL.");
}finally{await browser.close();await stop();await database.pool.end();if(created)await dropIsolatedTestDatabase(admin,name);await admin.end();await rm(directory,{recursive:true,force:true});}
