// Disposable R4 feedback quality gate: normal and many-commitment weeks, real review commands, no normal data/provider calls.
import {randomBytes,randomUUID} from "node:crypto";
import {spawn,type ChildProcess} from "node:child_process";
import {once} from "node:events";
import {createInterface} from "node:readline/promises";
import {setTimeout as delay} from "node:timers/promises";
import {mkdtemp,writeFile,rm} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
import assert from "node:assert/strict";
import {Pool} from "pg";
import {migrate} from "drizzle-orm/node-postgres/migrator";
import {connectDatabase} from "../src/db/connect";
import {requireTestDatabaseURL} from "./test-database";
import {provisionLocalUser} from "./local-user";
import {weeklyFixture} from "../tests/weekly-review-fixture";
const {url}=requireTestDatabaseURL(),target=new URL(url),adminURL=new URL(url),name=`execution_test_${randomBytes(6).toString("hex")}`,origin="http://127.0.0.1:3104";target.pathname=`/${name}`;adminURL.pathname="/postgres";
const admin=new Pool({connectionString:adminURL.toString()}),database=connectDatabase(target.toString()),directory=await mkdtemp(join(tmpdir(),"feedback-r4-")),clockFile=join(directory,"now");let created=false,child:ChildProcess|undefined;const input=createInterface({input:process.stdin,output:process.stdout});
async function start(){child=spawn(process.execPath,["node_modules/next/dist/bin/next","start","--hostname","127.0.0.1","--port","3104"],{env:{...process.env,NODE_ENV:"production",DATABASE_URL:target.toString(),BETTER_AUTH_URL:origin,EXECUTION_TEST_CLOCK_FILE:clockFile},stdio:"ignore"});for(let i=0;i<120;i++){if(child.exitCode!==null)throw new Error("Manual app exited");try{if((await fetch(`${origin}/api/health`)).ok)return;}catch{}await delay(250);}throw new Error("Manual app not ready");}
async function stop(){if(child&&child.exitCode===null){const done=once(child,"exit");child.kill("SIGTERM");await done;}child=undefined;}
try{
 await admin.query(`CREATE DATABASE "${name}"`);created=true;await migrate(database.db,{migrationsFolder:"src/db/migrations"});const account=await provisionLocalUser(database.db,{email:"feedback-r4@example.test",password:"Disposable-Feedback-R4!",name:"Morgan Lee",timezone:"Europe/London"}),actor={userId:account.id},f=await weeklyFixture(database.db,actor);await writeFile(clockFile,f.clock());
 const stress=await weeklyFixture(database.db,actor,"2026-09-28");stress.setNow("2026-10-02T08:00:00.000Z");
 await stress.goals.updateGoal(actor,stress.goal.id,{mutationId:randomUUID(),expectedVersion:1,title:"Make deliberate room for meaningful work while preserving the people, learning and recovery that support a sustainable weekly rhythm",outcome:"Long context stays readable without hiding the decision."});
 const extras: Awaited<ReturnType<typeof stress.actions.createAction>>[]=[];for(const title of ["Refine the review experience so long commitment titles remain readable and a deliberate next step can be chosen without opening historical evidence","Prepare release notes","Make the onboarding example clearer","Document one decision","Read and capture a useful idea","Check the small-screen flow"]){extras.push(await stress.actions.createAction(actor,stress.goal.id,{mutationId:randomUUID(),title,estimateMinutes:45,doneWhen:"One small usable outcome is ready."}));}
 const candidates=await stress.plans.candidates(actor),h=await stress.amends.history(actor,stress.plan.id),selection=[{actionId:stress.sources[0].id,budgetMinutes:150},{actionId:stress.sources[1].id,budgetMinutes:120},...extras.map(a=>({actionId:a.id,budgetMinutes:30,source:candidates.find(c=>c.actionId===a.id)!.source}))];
 await stress.amends.confirm(actor,stress.plan.id,{mutationId:randomUUID(),expectedVersion:h.baseline.version,provisionalCapacityMinutes:720,reserveMinutes:150,reason:"Break the remaining work into small deliberate commitments and keep completed support work as history.",commitments:selection});
 stress.setNow("2026-10-03T08:00:00.000Z");const h2=await stress.amends.history(actor,stress.plan.id);
 await stress.amends.confirm(actor,stress.plan.id,{mutationId:randomUUID(),expectedVersion:h2.baseline.version,provisionalCapacityMinutes:720,reserveMinutes:180,reason:"Protect recovery while retaining the smaller next steps.",commitments:h2.effective.commitments.map(c=>({actionId:c.actionId,budgetMinutes:c.budgetMinutes}))});
 const h3=await stress.amends.history(actor,stress.plan.id),commitment=h3.effective.commitments.find(c=>c.actionId===extras[0].id)!,placement={commitmentId:commitment.id,date:"2026-10-03",startTime:"14:00",endTime:"15:00"},preview=await stress.schedule.preview(actor,stress.plan.id,placement);
 await stress.schedule.create(actor,stress.plan.id,{...placement,mutationId:randomUUID(),expectedPlanVersion:preview.planVersion,reviewKey:preview.reviewKey,acknowledgeOutsideHours:true,acknowledgeBusy:false});stress.setNow(f.clock());
 const snapshot=async()=>{const result:Record<string,unknown>={};for(const table of ["goal","milestone","time_block","focus_session","daily_reflection"])result[table]=(await database.pool.query(`SELECT row_to_json(t) FROM ${table} t WHERE owner_id=$1 ${table==='daily_reflection'?"AND local_date <> '2026-10-07'":''} ORDER BY row_to_json(t)::text`,[actor.userId])).rows;for(const table of ["weekly_plan","weekly_commitment","weekly_plan_amendment","commitment_identity"])result[table]=(await database.pool.query(`SELECT row_to_json(t) FROM ${table} t WHERE ${table==="weekly_plan"?"id":"plan_id"}=$1 ORDER BY row_to_json(t)::text`,[f.plan.id])).rows;result.amendment_commitment=(await database.pool.query("SELECT row_to_json(t) FROM amendment_commitment t WHERE amendment_id IN (SELECT id FROM weekly_plan_amendment WHERE plan_id=$1) ORDER BY row_to_json(t)::text",[f.plan.id])).rows;return result;},before=await snapshot();const actionBefore=(await database.pool.query("SELECT row_to_json(t) FROM action t WHERE owner_id=$1 AND id <> $2 ORDER BY id",[actor.userId,f.sources[2].id])).rows;
 await start();console.log(JSON.stringify({origin,week:f.week,email:"feedback-r4@example.test",originalBudgetMinutes:360,finalBudgetMinutes:315,scheduledMinutes:240,recordedMinutes:106,logicalIds:f.decisions.map(d=>({id:d.commitmentId,kind:d.kind})),stressWeek:stress.week,stressCommitments:10,stressAmendments:4,password:"Disposable-Feedback-R4!",commands:["restart","stop"]}));
 while(true){const command=(await input.question("R4 command: ")).trim();if(command==="stop")break;if(command==="restart"){await stop();await start();console.log("Production process restarted; saved reviews retained.");}else console.log("Use restart or stop after finalizing the Daily and Weekly reflections.");}
 const v=(await f.reviews.workspace(actor,f.week)).facts!,r=v.review!;assert.equal(r.status,"finalized");assert.ok(r.note.trim());assert.equal(v.commitments.length,4);assert.equal(v.amendments.length,2);assert.equal(v.scheduledMilliseconds,240*60000);assert.equal(v.recordedMilliseconds,106*60000);assert.deepEqual(await snapshot(),before);assert.deepEqual((await database.pool.query("SELECT row_to_json(t) FROM action t WHERE owner_id=$1 AND id <> $2 ORDER BY id",[actor.userId,f.sources[2].id])).rows,actionBefore);assert.equal((await f.actions.getAction(actor,f.sources[2].id)).action.state,"archived");const next=(await f.plans.workspace(actor,"2026-10-12")).view;assert.equal(next,null);assert.equal(r.decisions.find(d=>d.kind==="carry")!.proposedBudgetMinutes,90);const day=await f.daily.day(actor,"2026-10-07");assert.equal(day.reflection?.status,"finalized");assert.ok(day.reflection!.note.trim());assert.equal(day.recordedMilliseconds,48*60000);
 console.log("PASS: concise Daily 48m/multiple outcomes and saved/reloaded/finalized reflection; Weekly original/final/two reasons/4h scheduled/1h46 recorded, fresh 90m Carry + Defer + confirmed Drop, immutable final, no automatic next Plan; all source/history/execution bytes unchanged except deliberate Drop and Daily reflection. Stress fixture: 10 commitments, 4 amendments, 9 unresolved decisions and long frozen titles.");
}finally{input.close();await stop();await database.pool.end();if(created)await admin.query(`DROP DATABASE "${name}" WITH (FORCE)`);await admin.end();await rm(directory,{recursive:true,force:true});}
