/* global document, fetch */
const root=document.querySelector('#workspace'),nav=document.querySelector('#scenarios'),footer=document.querySelector('#completion');
let experiment,index=0,saved=false;
const responses=new Map();
const el=(tag,text,cls)=>{const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(cls)node.className=cls;return node;};
function field(parent,label,choices,current,onChange,id){const group=el('div',undefined,'field'),name=el('label',label),select=el('select');name.htmlFor=id;select.id=id;select.required=true;const empty=el('option','Choose an answer');empty.value='';select.append(empty);for(const choice of choices){const option=el('option',choice);option.value=choice;select.append(option);}select.value=current??'';select.addEventListener('change',()=>{onChange(select.value);updateCompletion();});group.append(name,select);parent.append(group);return select;}
function complete(row){return experiment.questions.every(q=>row[q.key])&&row.provider;}
function evidence(parent,scenario){parent.append(el('h4','Evidence'));if(!scenario.topics.length){const list=el('ul');for(const fact of scenario.overview)list.append(el('li',fact.label));parent.append(list,el('p','No eligible unresolved coaching relationship.','muted'));}for(const topic of scenario.topics){parent.append(el('h4',topic.title));const list=el('ul');for(const fact of topic.evidence)list.append(el('li',fact.label));parent.append(list);}if(scenario.reflections.length){const details=el('details'),summary=el('summary','Permitted finalized reflections · shared by all three versions');details.append(summary);for(const r of scenario.reflections)details.append(el('h4',r.label),el('p',r.note));parent.append(details);}}
function render(){
 const scenario=experiment.scenarios[index];let row=responses.get(scenario.id);if(!row){row={scenario:scenario.id,provider:'openai',notes:''};responses.set(scenario.id,row);}nav.replaceChildren();
 experiment.scenarios.forEach((s,i)=>{const button=el('button',`${i+1}. ${s.title}`);button.setAttribute('aria-current',String(i===index));button.addEventListener('click',()=>{index=i;render();});nav.append(button);});
 root.replaceChildren();const intro=el('section',undefined,'scenario');intro.append(el('p',`Scenario ${index+1} of 6 · Week of ${scenario.week}`,'tag'),el('h2',scenario.title),el('p',scenario.brief));root.append(intro);
 const variants=el('div',undefined,'variants');
 for(const key of ['A','B','C']){const panel=el('section',undefined,'variant');panel.setAttribute('aria-label',`Version ${key}`);panel.append(el('p',`Version ${key}`,'tag'),el('h3',experiment.strategies[key]));evidence(panel,scenario);
  if(key==='B'){for(const topic of scenario.topics){if(topic.question)panel.append(el('h4','Question'),el('p',topic.question.text,'question'));}if(!scenario.topics.some(t=>t.question))panel.append(el('p','No reviewed deterministic question fits an eligible topic.','status'));}
  if(key==='C'){const providerGroup=el('div',undefined,'provider'),providerLabel=el('label','Saved AI sample'),select=el('select');select.id='ai-provider';providerLabel.htmlFor=select.id;for(const [value,text] of [['openai','GPT-5.6-Sol'],['anthropic','Claude Haiku 4.5']]){const option=el('option',text);option.value=value;select.append(option);}select.value=row.provider;select.addEventListener('change',()=>{row.provider=select.value;for(const q of experiment.questions)delete row[q.key];saved=false;render();});providerGroup.append(providerLabel,select);panel.append(providerGroup);const sample=scenario.samples[row.provider];panel.append(el('p',`${sample.model} · existing R5F result`,'muted'));
   if(sample.status!=='accepted')panel.append(el('p',sample.status==='stale'?'Facts changed. Saved AI prose remains hidden.':'No AI coaching was surfaced. The existing validator withheld this response.','status'));
   else if(!sample.insights.length)panel.append(el('p','No useful AI insight was supported by these facts.','status'));
   for(const insight of sample.insights)panel.append(el('h4','Coach'),el('p',insight.interpretation),el('h4','Question'),el('p',insight.reflectionQuestion,'question'));
  }
  variants.append(panel);
 }
 root.append(variants);const evaluation=el('section',undefined,'evaluation');evaluation.append(el('h2','Your evaluation'),el('p','Evaluate this frozen scenario, including empty or withheld coaching. “No meaningful difference” is valid. These answers are your judgment, not model ratings.','muted'));const fields=el('div',undefined,'fields');
 experiment.questions.forEach(q=>field(fields,q.text,q.key==='betterDecision'?['A','B','C','No meaningful difference']:['Yes','No','Unsure','Not applicable'],row[q.key],value=>{row[q.key]=value;saved=false;},`${scenario.id}-${q.key}`));
 const notes=el('div',undefined,'field full'),label=el('label','Why? Add any useful wording, missed nuance, or verbosity you noticed.'),area=el('textarea');area.id=`${scenario.id}-notes`;area.maxLength=2000;area.value=row.notes;label.htmlFor=area.id;area.addEventListener('input',()=>{row.notes=area.value;saved=false;updateCompletion();});notes.append(label,area);fields.append(notes);evaluation.append(fields);const actions=el('div',undefined,'actions');for(const [text,next] of [['Previous scenario',index-1],['Next scenario',index+1]]){const button=el('button',text);button.disabled=next<0||next>=6;button.addEventListener('click',()=>{index=next;render();});actions.append(button);}evaluation.append(actions);root.append(evaluation);updateCompletion();
}
let productPreference='',reason='';
function updateCompletion(){
 footer.replaceChildren();const completed=[...responses.values()].filter(complete).length;footer.append(el('p',`${completed} of 6 scenario evaluations complete.`,'muted'));const finish=el('section',undefined,'evaluation');finish.append(el('h2','Product preference'),el('p','Choose after comparing the scenarios. This records your preference; it does not change the normal app.'));const fields=el('div',undefined,'fields');field(fields,'Which product direction do you prefer?',['Keep AI Review coaching','Replace Review AI with deterministic coaching questions','Remove Review coaching entirely and keep only evidence/reflection'],productPreference,value=>{productPreference=value;saved=false;},'product-preference');const group=el('div',undefined,'field'),label=el('label','Reason for your product preference'),text=el('textarea');label.htmlFor='product-reason';text.id='product-reason';text.maxLength=4000;text.value=reason;text.addEventListener('input',()=>{reason=text.value;saved=false;button.disabled=completed!==6||!productPreference||!reason.trim();});group.append(label,text);fields.append(group);finish.append(fields);const status=el('p',saved?'Evaluation saved. Return to Codex and reply “evaluated.”':'Answers are saved to local QA evidence only when you submit.','muted');status.setAttribute('role','status');const button=el('button','Save my evaluation','primary');button.disabled=completed!==6||!productPreference||!reason.trim();button.addEventListener('click',async()=>{button.disabled=true;try{const r=await fetch('/evaluation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({experimentId:experiment.experimentId,responses:experiment.scenarios.map(s=>responses.get(s.id)),productPreference,reason})});if(!r.ok)throw new Error();saved=true;status.textContent='Evaluation saved. Return to Codex and reply “evaluated.”';}catch{status.textContent='Evaluation could not be saved. Your answers remain here; try again.';button.disabled=false;}});finish.append(button,status);footer.append(finish);
}
fetch('/comparison.json').then(r=>{if(!r.ok)throw new Error();return r.json();}).then(value=>{experiment=value;render();}).catch(()=>root.replaceChildren(el('p','The frozen comparison could not be loaded.','error')));
